### ISSUE TITLE
Website "403 Forbidden" Error

### ISSUE THREAD

**Issue by markus2330** [Betterbird/thunderbird-patches#100]
When visiting https://www.betterbird.eu/downloads/index.php with Firefox ESR when clicking one of the folders without JavaScript turned on, e.g. on "LinuxArchive" I land on:

https://www.betterbird.eu/downloads/LinuxArchive/

where I get:

```
Forbidden

You don't have permission to access this resource.
Apache Server at www.betterbird.eu Port 443
```

Allowing JavaScript for betterbird.eu works but is there a specific reason why you don't allow Apache to list the files in the folders?

**Comment by Betterbird** [comment]
Well, the download page is run via https://www.betterbird.eu/downloads/index.php which is an adaption of https://github.com/halgatewood/file-directory-list.

Trying to open https://www.betterbird.eu/downloads/LinuxArchive/ directly gives a 403. "Apache to list the files in the folders" is not a function of Apache to our knowledge, at least on the provider we use. To list fines in the directory, you need a PHP file that does the job. We don't want to provide such a script for all the subdirectories of our downloads.

You know that you can download the installers directly via:
https://www.betterbird.eu/downloads/get.php?os=win&lang=en-US&version=release
https://www.betterbird.eu/downloads/get.php?os=linux&lang=en-US&version=release
etc.
