### ISSUE TITLE
Support Winget for Windows update management

### ISSUE THREAD

**Issue by Betterbird** [Betterbird/thunderbird-patches#101]
As per:
https://www.thunderbird-mail.de/forum/thread/90865-betterbird-regelm%C3%A4%C3%9Fig-per-winget-bereitstellen/?postID=506981#post506981

https://winget.run/

**Comment by neiaberau** [comment]
hm, ich sehe betterbid da schon, wie auch immer das passiert ist

C:\>winget search betterbird
Name       Id                    Version      Source
-----------------------------------------------------
Betterbird Betterbird.Betterbird 102.5.0-bb24 winget
.

**Comment by neiaberau** [comment]
https://github.com/microsoft/winget-pkgs/commit/ba6d7b346b3c398160b3bc153130671246c6b3f8

**Comment by Betterbird** [comment]
Thanks, @borque, please get in touch if you have questions.

**Comment by borque** [comment]
Hello @Betterbird !
I just created winget-manifests for 102.5.1-bb25 and as long as I have time I can continue to try to keep the winget-manifests updated.
There is one thing that the translators could do: the localizations of wingets manifests contain a field called " ShortDescription: ".
For de-DE and en-US I used the folowing description:
en-US: Betterbird is a fork of Mozilla Thunderbird with additional features, patches and bugfixes.
de-DE: Betterbird ist ein Fork of Mozilla Thunderbird, der zusaetzliche Features, Patches und Bugfixes enthaelt.

If the translators could provide these in their native languages I could enhance the manifests with the texts.Please let me also know, iIf you have other suggestions for the texts I wrote.

**Comment by Betterbird** [comment]
Hi there, thanks for your effort. I suggest these texts:
en-US: Betterbird is a fork of Mozilla Thunderbird with additional features and bugfixes.
de-DE: Betterbird ist eine Fork of Mozilla Thunderbird, die zusätzliche Features und Bugfixes enthält.

Remarks: Mentioning patches is not useful for the user. Everything is done via additional patches. The gender of "Fork" in German is unclear. IMHO it should be "die" (feminine) since it's derived from "die Gabel".

Which other languages do you need?
es: Betterbird es una bifurcación de Mozilla Thunderbird con funciones y correcciones de errores adicionales.
fr: Betterbird est un fork de Mozilla Thunderbird avec des fonctionnalités et des corrections de bogues supplémentaires.
it: Betterbird è un fork di Mozilla Thunderbird con funzioni e correzioni di bug aggiuntive.
nl: Betterbird is een afsplitsing van Mozilla Thunderbird met extra functies en bugfixes.

We don't speak Japanese or Chines and online translation can't be trusted 100%.

**Comment by borque** [comment]
Hello @Betterbird !
I think it's a good idea to remove the "patches" and I will change this in the next release. 

Concerning "fork" nearly all German publications I have read use the male form speaking of "der fork" when using it for software and not meals, perhaps because the authors are thinking of the more common German termn "der Zweig" instead of the literal translation "die Gabel". To avoid confusion (indeed I never thougt of the gender of a software fork befor your remark)  I propose to use "Ist ein Zweig" oder "Ist eine Abspaltung"?

Concerning the other translations: My opinion on online translations is precisely the same as yours. Therfor I thought it might be a good idea to ask the translaters of Betterbird for help! Are the texts provided above machine translated, or can I use these in a future release?

**Comment by Betterbird** [comment]
Hello, well, [here](https://www.btc-echo.de/academy/bibliothek/was-ist-eine-fork/) they use "eine Fork". I thought the rule is to take the article of the translated German word. A fork is not a branch, and "Abspaltung" sounds like a (malevolent) splinter group. You can do whatever you deem fit since the winget stuff is your work.

As for the translations: I'm actually doing German, French and Spanish myself, that is use Google/DeepL and correct the result, and no, my proposal is **not** exactly what online translations give. The all translate "additional (features and bugfixes)" as "(additional features) and bugfixes", for example French gives: "Betterbird est un fork de Mozilla Thunderbird avec des fonctionnalités supplémentaires et des corrections de bogues", which is not what I have. The same wrong grouping happens in Spanish, Italian and Portuguese.

Dutch, Italian and Portuguese are also taken from there, but they sound about right. I can't harass the translators for every single phrase.

---

Coming back to "die/der Fork": Here's an anecdote. I spend 16 outside Germany, and when I returned, I was amazed at how much bad German had grown in the meantime. mostly for technology terms. I don't even want to mention "das Handy", there is also "der Newsletter", getreu übersetzt von "das Rundschreiben", "die Firewall", getreu übersetzt von "der Schutzwall" (oops, "die Brandmauer"), "das Blog" (although Duden also admits "der Blog").
