### ISSUE TITLE
Betterbird ignoring "Message Archives" setting

### ISSUE THREAD

**Issue by d5ve** [Betterbird/thunderbird-patches#102]
Thank you for Betterbird!

I'm using Betterbird 102.5.0-bb24 (15 November 2022) on MacOS Monterey (M1)

Betterbird seems to be ignoring my chosen "Message Archives" folder setting.

I have used a custom archive location, `Archive/YYYY`, rather than the default, pluralised `Archives/YYYY` for the past few years with Thunderbird.

I recently switched to Betterbird, but it doesn't seem to be honouring my "Message Archive" settings.

I chose "Other" for the Message Archive, then browsed to the `Archive` folder in my account. I also selected `Yearly archived folders`

![betterbird-folder-bug](https://user-images.githubusercontent.com/379960/203460987-736a6d98-0c88-4d52-9a07-09264cd283ad.png)

However, when I archive messages, they currently all end up in `Archives/2022`, rather the the desired `Archive/2022`

**Comment by Betterbird** [comment]
I can't reproduce this, at least on Windows. I configured what you described and this is the correct result:
![image](https://user-images.githubusercontent.com/86832723/203493055-6da25f80-ba9b-4f85-bc1d-73eef7285325.png)
(I've just archived some return receipts for testing purposes.)
Maybe you can select the archive folder again and see whether it works then. Also, you can check the relevant preference, search for `archive_folder`, in my case I have: `mail.identity.id17.archive_folder	mailbox://betterbird%40betterbird.eu@XXXserver.YY/Archive`.

Also, there are no differences between TB and BB in the area, so if it doesn't work, it's very likely a bug in TB.

**Comment by Betterbird** [comment]
I've now also tried on a Mac, where I have this pref value: `mail.identity.id1.archive_folder	mailbox://nobody@Local%20Folders/ArchiveXX`. It also works there.

That said, I checked Bugzilla and found this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1606621, especially the last comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1606621#c25

So maybe this is an IMAP issue? Is this an IMAP account? And the archive is kept in an IMAP folder? When the problem happens, what is the value of the corresponding preference?

**Comment by d5ve** [comment]
This is great info thanks!

On my mac laptop, the settings panel UI (see screenshot in issue description) is showing a custom location `Archive` (singular), but the Advanced Setting (`about:config`) is showing `mail.identity.id1.archive_folder=imap://me%40example.com@mailserver.com/Archives` (plural)

I'll try setting the value directly in the advanced settings and see it that helps.

Perhaps somewhere under the hood there is some lazy code just checking "does the string start with archive?" and assuming it's the default!

The same setup does work correctly on my linux box. Maybe the case-insensitive filesystem on macos?

**Comment by Betterbird** [comment]
Not sure what the issue was here exactly. BB has no changes wrt. archive handling. Feel free to reopen if think there's something actionable here.
