### ISSUE TITLE
Session only restores tabs not stand-alone message windows (TB bug 737887)

### ISSUE THREAD

**Issue by Tragen** [Betterbird/thunderbird-patches#105]
This bug is since forever in TB.
https://bugzilla.mozilla.org/show_bug.cgi?id=408338
https://bugzilla.mozilla.org/show_bug.cgi?id=737887

It's a very annoying bug which I think should be fixed in BB as the TB devs obviously don't care about it, but it helps a lot.
I don't install updates and reboot as often needed because I have so many open windows in TB which I need to process.

Thanks for BB :)

**Comment by Betterbird** [comment]
Thanks for the report, we'll take a look. Strangely bug [408338](https://bugzilla.mozilla.org/show_bug.cgi?id=408338) is marked FIXED and a patch with r+ was indeed landed in [comment #33](https://bugzilla.mozilla.org/show_bug.cgi?id=408338#c33).

So what exactly doesn't work? This is what I see after a restart:
![image](https://user-images.githubusercontent.com/86832723/204126622-495b5a10-392f-4224-b0bb-3010ccf1162f.png)
All the tabs that were open are open again.

And bug [737887](https://bugzilla.mozilla.org/show_bug.cgi?id=737887) is about stand-alone messages, that's not likely to be fixed.

**Comment by Tragen** [comment]
The tabs are still opened, yes, but not the other opened emails in separate windows.

**Comment by Betterbird** [comment]
Sorry, not likely to address this since we're not friends of stand-alone windows.

**Comment by Tragen** [comment]
I'm sad to hear that.
You cannot do everything only with tabs. If you need to have 2 or 3 different emails open because they are about the same case and the information you need is in the different windows, you can see it at once, Now you need to switch tabs which is not user friendly.
Perhaps you can think about it.
