### ISSUE TITLE
RSS-Feed from follow.it won't be synced

### ISSUE THREAD

**Issue by Siggi0904** [Betterbird/thunderbird-patches#106]
Hello,

I added a rss feed from feedburner alternative https://follow.it.
After I added it to thunderbird, it won't be updated anymore.
Only deleting and re adding helps for updating.

Does this feed works with betterbird?

**Comment by Betterbird** [comment]
What is the exact feed URL? https://follow.it is not a valid URL, see:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffollow.it

**Comment by Siggi0904** [comment]
for me, I'm using: https://follow.it/der-postillon-abo?user=mario_siegmann but it's registred to my own e-mail.
After you read it, please delete it from this post.

**Comment by Betterbird** [comment]
You can always e-mail such details to our support. I've added the feed to my setup, the last post is "Sonntagsfrage: Was sagen Sie dazu, dass Deutschland heute gegen Spanien verliert?" from 10:41. Let's see whether it updates. If not, you should file a bug for TB in Bugzilla.

**Comment by Betterbird** [comment]
Just now:
![image](https://user-images.githubusercontent.com/86832723/204237166-770fa8e2-bac9-4fad-b08b-842464425fd5.png)

**Comment by Betterbird** [comment]
This feed is not very active, nothing new for the last 7 days, "Newsticker (1881)" of 28th November is still on the top.
