### ISSUE TITLE
version 102.7.0 breaks exchange OAuth2

### ISSUE THREAD

**Issue by BishopWolf** [Betterbird/thunderbird-patches#112]
BetterBird in current version 102.7.0 does indeed ship with this problem

https://bugs.archlinux.org/task/77208
https://blog.thunderbird.net/2023/01/important-message-for-microsoft-office-365-enterprise-users/

Please abstain to publish version 102.7.0 (just skip it), or add some patch to it

**Comment by Betterbird** [comment]
We have added a patch to it:
https://github.com/Betterbird/thunderbird-patches/commit/5b946e123f153f9e2637f0ede65ffc87897c4bad
In fact, the same code that TB has tested, see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1810760#c7

The latest "replacement" build of 19th January should work. Which build ID are you using?

**Comment by Betterbird** [comment]
Does that "replacement" version not work?

**Comment by BishopWolf** [comment]
> Does that "replacement" version not work?

Sorry, It is not working for me. I can't still connect to my work exchange server.
`Authentication failure connecting to server outlook.office365.com`

![imagen](https://user-images.githubusercontent.com/11816952/213935968-48fcfe57-8b2c-46f6-b0b6-8cfb1d98695b.png)
![imagen](https://user-images.githubusercontent.com/11816952/213936009-627b1a11-4d77-4297-9adb-7fba425e4b20.png)

**Comment by Betterbird** [comment]
Sadly there were three builds for 102.7.0-bb28, so without the build ID which you find in "Help > More Troubleshooting Information" we can't tell which build you are using. That said, the fix shipped in the latest build of 19th January, which is also in the AUR and the FLatPak. Things should be working as they include the fix other users have confirmed working in TB:
https://bugzilla.mozilla.org/show_bug.cgi?id=1810760#c7

However, there were general changes which are described here:
https://thunderbird.topicbox.com/groups/enterprise/T262ef074c0833a12-Mb7dd2995cbea31000255ac10

**Comment by BishopWolf** [comment]
Nombre 	Betterbird
Versión 	102.7.0-bb28
ID de Build 	20230119120106
ID de distribución 	
Agente de usuario 	Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Thunderbird/102.7.0
SO 	Linux 6.1.5-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Jan 12 15:19:12 UTC 2023

**Comment by Betterbird** [comment]
OK, recent enough. And the article I posted doesn't help. And downgrade to 102.6.1 helps?

**Comment by BishopWolf** [comment]
> OK, recent enough. And the article I posted doesn't help. And downgrade to 102.6.1 helps?

102.6.1 Works perfectly

**Comment by Betterbird** [comment]
I've checked the version, it has the fix that TB developed. Can you try the build mentioned here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1810760#c4?

https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/XeTLt6FkQaiBK_-Mez5e-A/runs/0/artifacts/public/build/target.tar.bz2

**Comment by BishopWolf** [comment]
I have tried twice, that binary segfault in my system. I will stay in 102.6.1 for a while

**Comment by Betterbird** [comment]
Sigh. OK, here is 102.7.0-bb28, but instead with the "reduced fix" which be originally shipped, with the full fix that will go out in TB 102.7.1 next week. It should make any difference, but please try:
https://www.betterbird.eu/downloads/LinuxArchive/betterbird-102.7.0-bb28-full-oauth2-fix.en-US.linux-x86_64.tar.bz2

If this doesn't work, like I assume, please provide the content of the error console (Tools > Developer Tools > Error Console).

**Comment by Betterbird** [comment]
We have more reports that the BB 102.7.0-bb28 versions don't work for some MS OAuth2 user. We'll look into it.

**Comment by BishopWolf** [comment]
The reduced fix does not work, it still says authentication failure, several messages in console

```
NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIRequest.name] OAuth2.jsm:168
    onStateChange resource:///modules/OAuth2.jsm:168
```

```
XHRPOSThttps://login.microsoftonline.com/common/oauth2/v2.0/token
[HTTP/1.1 400 Bad Request 1362ms]

	
POST
	https://login.microsoftonline.com/common/oauth2/v2.0/token
Estado
400
Bad Request
VersiónHTTP/1.1
Transferido1,35 KB (tamaño 556 B)
Política de referenciastrict-origin-when-cross-origin

    	
    Access-Control-Allow-Methods
    	POST, OPTIONS
    Access-Control-Allow-Origin
    	*
    Access-Control-Expose-Headers
    	Content-Length,Content-Encoding,x-ms-request-id
    Cache-Control
    	no-store, no-cache
    Content-Length
    	556
    Content-Type
    	application/json; charset=utf-8
    Date
    	Mon, 23 Jan 2023 22:06:27 GMT
    Expires
    	-1
    P3P
    	CP="DSP CUR OTPi IND OTRi ONL FIN"
    Pragma
    	no-cache
    Set-Cookie
    	fpc=AhN1L1RaJYJJqtqiUbh1cUgQaf9UAgAAAJ37YNsOAAAA; expires=Wed, 22-Feb-2023 22:06:27 GMT; path=/; secure; HttpOnly; SameSite=None
    Set-Cookie
    	x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
    Strict-Transport-Security
    	max-age=31536000; includeSubDomains
    X-Content-Type-Options
    	nosniff
    x-ms-ests-server
    	2.1.14526.4 - NEULR2 ProdSlices
    x-ms-request-id
    	0bb1c459-8cbe-4729-87da-25e5f79e0300
    X-XSS-Protection
    	0
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3
    Connection
    	keep-alive
    Content-Length
    	951
    Content-Type
    	application/x-www-form-urlencoded;charset=UTF-8
    Cookie
    	fpc=AhN1L1RaJYJJqtqiUbh1cUgQaf9UAQAAAJ37YNsOAAAA; ESTSSSOTILES=1; AADSSOTILES=1; brcap=0; wlidperf=FR=L&ST=1666100185013; x-ms-gateway-slice=estsfd; stsservicecookie=estsfd
    Host
    	login.microsoftonline.com
    Origin
    	null
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	cross-site
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Betterbird/102.7.0
```

**Comment by Betterbird** [comment]
> The reduced fix does not work, it still says authentication failure, several messages in console.

You meant to say: The **full** fix from
https://www.betterbird.eu/downloads/LinuxArchive/betterbird-102.7.0-bb28-full-oauth2-fix.en-US.linux-x86_64.tar.bz2
?

It's surprising to see
```
    Sec-Fetch-Mode
    	cors
```
in the log, when the program explicitly sendas `no-cors`, see here:
https://github.com/Betterbird/thunderbird-patches/blob/acede87b8d7b3f354df538f831abb1f69118d99d/102/bugs/1810760-fix-oauth2-ms.patch#L20

Is there any chance that the code you're running doesn't reflect the latest build? In this case, it's advisable to start with `-purge-caches` or or clear the startup cache via "Help > More Troubleshooting Information".

**Comment by Betterbird** [comment]
Please try:
https://www.betterbird.eu/downloads/LinuxArchive/betterbird-102.7.1-bb29-preview.en-US.linux-x86_64.tar.bz2

This is based on TB 102.7.1 which will ship today and contains the "official" fix for the problem. We checked the XHR and `Sec-Fetch-Mode` was `no-cors`.

**Comment by Betterbird** [comment]
Please try:
Linux: https://www.betterbird.eu/downloads/get.php?os=linux&lang=en-US&version=latest
Windows: https://www.betterbird.eu/downloads/get.php?os=win&lang=en-US&version=latest

**Comment by Betterbird** [comment]
@BishopWolf: When you find the time, please try the build from the previous comment. We've had reports that it semi-works, the setup goes through but then this error comes up:
Configuration could not be verified. If your username and password are correct, it’s likely that the server administrator has disabled the selected configuration for your account. Try selecting another protocol.

Not sure whether after that you can still accept the account.

**Comment by BishopWolf** [comment]
I haven't had the time to make the tests, maybe this weekend.

**Comment by Betterbird** [comment]
No problem. In the meantime the TB team have created their own solution:
https://www.betterbird.eu/downloads/LinuxArchive/betterbird-102.7.1-bb29-preview2.en-US.linux-x86_64.tar.bz2

You can compare to:
https://www.betterbird.eu/downloads/LinuxArchive/betterbird-102.7.1-bb29-preview.en-US.linux-x86_64.tar.bz2

**Comment by BishopWolf** [comment]
Last version of thunderbird is working ok. I will try the latest of betterbird.

**Comment by Betterbird** [comment]
I'm not sure which version of TB you're referring to. The issue certainly isn't fixed in 102.7.0.

**Comment by BishopWolf** [comment]
> I'm not sure which version of TB you're referring to. The issue certainly isn't fixed in 102.7.0.

Nombre 	Thunderbird
Versión 	102.7.0
ID de compilación 	20230128121018
ID de distribución 	Manjaro
Agente de usuario 	Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Thunderbird/102.7.0
OS 	Linux 6.1.8-2-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Jan 25 05:25:38 UTC 2023

I am getting no errors in my exchange account

**Comment by BishopWolf** [comment]
Using now Betterbird version 102.7.1. Simply better.
Build details: os=Linux, locale=es-AR, version=102.7.1, buildid=2023-01-31 17:39:19.
Everything is working OK
Thanks

**Comment by Betterbird** [comment]
Thanks for the confirmation.
