### ISSUE TITLE
Feature Request: Loading of compressed .eml files

### ISSUE THREAD

**Issue by dsl101** [Betterbird/thunderbird-patches#114]
I use GMVault to back up a gmail account, resulting in just over 100,000 files. They are all `.eml.gz`, and it would be fantastic to be able to load these directly rather than having to individually uncompress them. Any chance BB could support this?

**Comment by Betterbird** [comment]
Anything can be added given the right motivation/funding :wink: - But talking seriously, I don't see this implemented.

You can script the decompression of multiple files and then `cat` all the .eml files together into an mbox file, maybe adding a From header before each messages. TB/BB will happily open the mbox if it's done correctly. Or maybe even easier if you use maildir.

Other then that, maybe a job for https://addons.thunderbird.net/en-GB/thunderbird/addon/importexporttools-ng/.

**Comment by dsl101** [comment]
Fair enough. Using it on Windows, so options for scripting are less simple...

**Comment by Betterbird** [comment]
Well, install some Unix tools, there are plenty around. Then something like:
1. `ls *.gz > import.bat`
2. Use `sed` to change `mail.eml` to `cat mail.eml > mbox ` on each line. Depending on whether the .eml files already have a From header you need to `echo "From - Thu Jan 26 17:50:06 2023"` before, so something like `mail.eml` becomes: `echo "From - Thu Jan 26 17:50:06 2023" > mbox && cat mail.eml > mbox`
3. move the mbox to Local Folders.

Overall maybe two hours work.

**Comment by dsl101** [comment]
Thanks—uploading to a backup gmail account now, so if that works, all good. Will bookmark this for when that all goes wrong :).
