### ISSUE TITLE
Portable Launcher (register default E-mail program)

### ISSUE THREAD

**Issue by dtoxic47** [Betterbird/thunderbird-patches#115]
Could we get support for to register Betterbird portable with Portable Registrator https://github.com/SiL3NC3/PortableRegistrator

As it stands now if your register Betterbird launcher as default email client in windows and try to click on a mailto link then Betterbird tries to launch again,instead it should open email compose window if Betterbird is already running

This is working fine with Thunderbird portable,this might also something to do with the portable launcher *.ini settings (not sure about that thou)

**Comment by Betterbird** [comment]
Can you find someone to work on this, we're happy to accept any patches.

**Comment by dtoxic47** [comment]
No,not really i just discovered betterbird a day ago and wanted to replace thunderbird but that option to click on mail links is needed for me,i am no coder i just thought id post here what i think is lacking or could be made better

**Comment by Betterbird** [comment]
Should be fixed via https://github.com/Betterbird/thunderbird-patches/commit/e5dd5e94a47b0d7210b9f820f62bcb63496ae433.
We'll ship the new launcher in 102.7.1 in the next few days. In the meantime, you can download it from
https://github.com/Betterbird/thunderbird-patches/raw/main/BetterbirdLauncher/BetterbirdLauncher.exe
for testing.

**Comment by dtoxic47** [comment]
thank you!

**Comment by Betterbird** [comment]
Working?

**Comment by dtoxic47** [comment]
will let you know tomorrow since i am away from my pc

**Comment by dtoxic47** [comment]
Managed to do a quick test...works like a charm! thank you will let you know if any problems arise,but i think we are good!
