### ISSUE TITLE
Folder Unsubscribe

### ISSUE THREAD

**Issue by dtoxic47** [Betterbird/thunderbird-patches#116]
I cannot unsubscribe from a IMAP folder (Archive) i uncheck the folder but it always comes back

The best i can explain it is written all here by some other users https://bugzilla.mozilla.org/show_bug.cgi?id=1773798

this is the webmail portal i connect to https://webmax.ctelekom.me/SOGo/

and here is the error in the console and the code utils-message.js:2:1 moz-extension://161efed6-1bd6-4f56-9591-d0d1db08d7ce/scripts/utils-message.js

<details><summary>Error</summary>class NoKeyIdError extends Error {};
class NoMessageError extends Error {};

let messagePartReturner = MessagePart => {
	if(MessagePart){
		return MessagePart;
	}
	throw new NoMessageError;
};

async function getMessage(id){
	return browser.messages.get(id).then(messagePartReturner);
}

async function getMessageFull(id){
	return browser.messages.getFull(id).then(messagePartReturner);
}

async function getMessageKeyId(id) {
	let partsParser = parts => {
		// if(parts.headers['x-qnote-text']){
		// 	let qtext = parts.headers['x-qnote-text'][0];
		// 	utf8decode(qtext);
		// }

		if(!parts.headers || !parts.headers['message-id'] || !parts.headers['message-id'].length){
			return false;
		}

		let id = parts.headers['message-id'][0];

		if((id[0] == '<') && (id[id.length - 1] == '>')){
			return id.substring(1, id.length - 1);
		} else {
			return id;
		}
	};

	return getMessage(id).then(parts => {
		if(parts.headerMessageId){
			return parts.headerMessageId
		} else {
			return getMessageFull(id).then(parts => {
				let mid = partsParser(parts);

				if(mid){
					return mid;
				} else {
					throw new NoKeyIdError;
				}
			});
		}
	});
}

async function createNoteForMessage(id) {
	return getMessageKeyId(id).then(keyId => {
		let note = createNote(keyId);

		note.addListener("afterupdate", (n, action) => {
			QDEB&&console.debug("afterupdate", action);
			if(Prefs.useTag){
				tagMessage(id, Prefs.tagName, action === "save");
			}

			mpUpdateForMessage(id);
		});

		return note;
	});
}

async function loadNoteForMessage(id) {
	return createNoteForMessage(id).then(note => {
		return note.load().then(() => note);
	});
}

async function deleteNoteForMessage(id){
	return createNoteForMessage(id).then(note => {
		return note.delete().then(() => note);
	});
}

async function saveNoteForMessage(id, data){
	return loadNoteForMessage(id).then(note => {
		note.set(data);
		return note.save();
	});
}

async function saveNoteForMessageIfNotExists(id, data){
	return loadNoteForMessage(id).then(note => {
		if(!note.exists){
			note.set(data);
			return note.save();
		}
	});
}

async function tagMessage(id, tagName, toTag = true) {
	return getMessage(id).then(message => {
		QDEB&&console.debug(`tagMessage(id:${id}, tagName:${tagName}, toTag:${toTag})`);
		let tags = message.tags;

		if(toTag){
			if(!message.tags.includes(tagName)){
				tags.push(tagName);
			}
		} else {
			tags = tags.filter(item => item !== tagName);
		}

		return browser.messages.update(message.id, {
			tags: tags
		});
	});
}

async function getDisplayedMessageForTab(tab) {
	return browser.messageDisplay.getDisplayedMessage(getTabId(tab)).then(messagePartReturner);
}

async function ifNoteForMessageExists(id) {
	return new Promise((resolve, reject) => {
		loadNoteForMessage(id).then(note => {
			if(note.exists){
				resolve(note);
			} else {
				reject();
			}
		});
	});
}

Ill assume that this is maybe also locked on the server's side? but it does not make any sense that one can not unsubscribe from a folder from a mail client

**Comment by Betterbird** [comment]
Look, there are 14.000+ Thunderbird errors which we can't fix as part of the Betterbird project. If something annoys you in particular, drop our support a line. We've taken note of the "Yahoo can't unsubscribe bug". If this error is reported for TB, no need to have another ticket here.

The error you've mentioned above is from an add-on, based on the code you've quoted, some add-on that adds notes to IMAP messages or folders. Again, we won't fix this as part of BB. Please contact the add-on author.

And finally, we don't know who is behind WebMax, looks like some subsidiary of the German Telekom. In any case, we don't have an account there. I suggest to subscribe on the bug and mention your problem with your provider.

**Comment by dtoxic47** [comment]
ok thx

**Comment by Betterbird** [comment]
We found and fixed an issue that the tree selection doesn't update when using the Subscribe/Unsubscribe buttons:
https://github.com/Betterbird/thunderbird-patches/commit/a4dc9cf29272e77b9a517b1dc52d0fd3cd38dc83

However, the issue not being able to unsubscribe from Yahoo is different and should be looked at by the TB team. If they don't look at it, we'll have a look. However, Yahoo is just about the worst mail provider, so no one will bend backwards to fix stuff related to them. Who's behind the WebMax crowd?

**Comment by dtoxic47** [comment]
I don't know Germany maybe,ill try and send an email to them see if maybe it;s locked on their side or something,because on outlook.live it works with no problems, will let you know what i find

**Comment by Betterbird** [comment]
In our opinion, Yahoo & friends are totally hopeless, see [here](https://wiki.mozilla.org/User:Jorgk/8-bit_bytes_and_e-mail_corruption_at_Verizon,_Yahoo,_etc.).

**Comment by dtoxic47** [comment]
So i got a response,they unfortunately do not allow unsubscribing from particular folders,what is even more strange is that the folder "Archive" is present in Betterbird but is not present when i access it with web a web browser,further more i used a small utility to check the sizes of the imap folders "IMAPSize_037" and the folder is present and when trying to delete it it always comes back...so i guess this is a dead end,ill try and find some extension or a solution to just hide it from view.

**Comment by Betterbird** [comment]
As I wrote two comments up, Yahoo is pretty hopeless. I read https://bugzilla.mozilla.org/show_bug.cgi?id=1773798#c6 with the conclusion that you can't unsubscribe from folders in Yahoo. Archives are a different story, TB/BB creates the folder by default if so configured in the Account Settings in the section "Message Archived". Try unchecking the box "Keep message archives in" and deleting the folder.

**Comment by dtoxic47** [comment]
Nope does not work,as this is not a "Archive-s" folder it's "Archive"....the first one gets deleted this one does not,it's like a  ghost folder that you cant un-subscribe nor delete,there is a error when trying to right click in the error console and no delete option is displayed

**Comment by Betterbird** [comment]
Maybe you didn't try hard enough. I set my Archives to a local folder:
![image](https://user-images.githubusercontent.com/86832723/216690200-a5f13126-6e43-48b2-8caa-bd39bb616fa9.png)
then deleted the folder from Yahoo:
![image](https://user-images.githubusercontent.com/86832723/216690324-3766f3c1-737e-49a1-80f7-6ce55ac4a6fa.png)
If you disable archives altogether and then clear the Archives flag with this add-on https://addons.thunderbird.net/en-GB/thunderbird/addon/folderflags/, you can also delete the local archives folder.

I guess just unchecking the archiving option, then clearing the Archives flag on the IMAP folder would also have allowed you to delete the IMAP Archives folder without switching to a local folder first. In any case, the Archive(s) folder can be removed.

**Comment by dtoxic47** [comment]
I tried everything that comes to mind + with this addon i can delete it,but as soon i exit and start betterbird again it gets recreated,this is some stupid stuff on the server side nothing i can do about it i guess

**Comment by Betterbird** [comment]
Well, with the add-on I can take it from here:
![image](https://user-images.githubusercontent.com/86832723/216699941-72ac1552-3e99-48f9-8ffc-180937c2faa7.png)
to here:
![image](https://user-images.githubusercontent.com/86832723/216700158-f3e23daf-9fc4-422c-b684-1c792e6fe52d.png)
And emptying the trash gets rid of it. But when I restart, it comes back and it never goes from the subscribe dialogue:
![image](https://user-images.githubusercontent.com/86832723/216700886-69e32ae1-3525-452a-8556-ddadb82dc6a4.png)

Use a better provider :wink:

**Comment by dtoxic47** [comment]
Yeap for me it subscribes automatically for some reason,anyway we lost enough time on this damn thing :)
