### ISSUE TITLE
Request: i386 version

### ISSUE THREAD

**Issue by superlinuxero** [Betterbird/thunderbird-patches#117]
Hi there and thanks for such an improvement over TB.

I've been using Betterbird for more than a month after so many more months of frustration using TB. However, my work laptop, an ancient but venerable 2006 Thinkpad can't run amd64 code. Is there any chance I could find somewhere an i386 compilation of Betterbird? I've tried searching for compilation instructions that would work on i386 but I haven't found anything, not even sure it will compile.

Thanks so much in advance.

**Comment by Betterbird** [comment]
Thanks for getting in touch. There are no 32bit builds and there won't be. The build instruction can be found here. They should work for 32bit builds:
https://github.com/Betterbird/thunderbird-patches/blob/main/README.md#building-betterbird

Of couse you'd have to adapt the mozconfig:
https://github.com/Betterbird/thunderbird-patches/blob/a4dc9cf29272e77b9a517b1dc52d0fd3cd38dc83/102/mozconfig#L3
