### ISSUE TITLE
Calendar event reminder window cannot be dismissed

### ISSUE THREAD

**Issue by pongraczi** [Betterbird/thunderbird-patches#120]
## Symptom
* I got a calendar reminder as a small window, snooze/dismiss buttons and link to details. Screenshots later.
* When I try to hide/mute/acknowledge this notification by hitting the dismiss or dismiss all buttons, nothing happens.
* Ok, I just close the window by hitting the X of the window (close window), it closes.
* In some minutes the reminder appears again with a nice sound effect, and the loop restarts again: dismiss does not work, close, appears again, close, appears again....
* 2nd day in a row, even the event is overdue (it's 8th of Feb, the event was on 7th of Feb).

## System
* It is a calendar event from a remote caldav server: contact's birthday, show reminder enabled, no additional notification exists. (screenshot below).
* Betterbird versions: 102.7.0-bb28 and 102.7.1-bb29
* Linux version (tar.gz).

### Reminder window  

![Kijelölés_246](https://user-images.githubusercontent.com/5891983/217512770-f9a645e3-84cf-44f2-b7d2-201963c3c85a.png)

### Calendar setup

![Kijelölés_247](https://user-images.githubusercontent.com/5891983/217513609-e863e397-ce65-44d1-8e3e-59ff792f8ff6.png)

Any idea? Thanks.

**Comment by Betterbird** [comment]
Certainly not a BB issue, we have no modifications wrt. TB in Calendar.

Is there a TB bug for this? Have you tried in TB? Have you read our bug filing rules here?
https://github.com/Betterbird/thunderbird-patches#bug-reporting--support

Likely an issue with an add-on or CalDAV provider. You're using any add-ons. I vaguely remember that TbSync caused this behaviour for me a while ago. In any case, not enough information here to act on the report. Anything in the error console? Tools > Developer Tools > Error Console.

**Comment by pongraczi** [comment]
Thank you for the hint, it seems the error console holds useful information.  

Anyway, sorry, of course I did not read the details of the bug-reporting--support, my bad.

**Comment by pongraczi** [comment]
Just for the record, seems here is the exact same problem, at least since 2016 it exists:  
https://bugs.launchpad.net/thunderbird/+bug/1846423  
https://cardbook.icu/forum/forums/topic/birthday-reminder-problem/  
https://help.nextcloud.com/t/cant-reset-birthday-reminder-after-migration-in-thunderbird/3455

**Comment by Betterbird** [comment]
Look, we're happy to help, but we can't fix all 14.000+ TB bugs as part of the project. I can't read through the three references in a hurry now. The question is: Is there a reliably reproducible test case reported in the TB bug in their Bugzilla? For me in my daily usage, events can of course be dismissed.

Or is that related to a "birthday reminder" (I've never heard of it). What is that, how is that produced? Via Cardbook? I have a separate calender for birthdays (events recurring every year) and yes, I dismiss the reminders with no problem.

**Comment by pongraczi** [comment]
Sorry, **you have nothing to do with this anymore**, I just put some links to the original bug for those, who are interesting or found this ticket. For reference only.  

Just leave it as is, this is one of the bugs TB has and never will be solved.  

Frankly, why Evolution has no port to windows? :)))))))))

**Comment by Betterbird** [comment]
Can we a bit more constructive than "one of the bugs TB has and never will be solved".

To solve any bug, you need to reproduce it. I can't reproduce it so far. So if you like, provide the information necessary to reproduce it. Or if this bug has been reported here https://bugzilla.mozilla.org/, please provide the reference.

Looking at https://bugs.launchpad.net/thunderbird/+bug/1846423, this seems to be related with an invalid duration, like `TRIGGER;VALUE=DURATION:-PT30M`, also seen here:
https://help.nextcloud.com/t/cant-reset-birthday-reminder-after-migration-in-thunderbird/3455/6
`TRIGGER;VALUE=DURATION:PT0S`.

There are a few bugs in Bugzilla related to this area, see:
https://bugzilla.mozilla.org/buglist.cgi?quicksearch=dismiss+reminder
https://bugzilla.mozilla.org/buglist.cgi?quicksearch=dismiss+event

Most notably: https://bugzilla.mozilla.org/show_bug.cgi?id=1625122

**Comment by chymian** [comment]
@Betterbird 
sry to dig up that old issue, but it's not fix and drives users away, so you might be interested in it.

Maybe this helps with reproduction:
just  installed a fresh copy of debian testing/trixie.
Plasma/wayland (5.27.11, QT, 5.15.13)
betterbird: 115.14.0-bb31 (64-Bit) as flatpack.
connected it to my nexctloud and voila,
after activating calendars, these __immutable reminders__ pop up and are so annoying, that I have to look for another solution for the moment.

never the less, guys, I like your approach very much and I encourage you to fully support linux, i.e. debs and appimages.
IMHO  betterbird could be the looong missed version of a usable MailClient for all OSes - that what TB missed/stopped to be.
and i think, the linux-community is waiting for a product like that, and will probably chime in with a lot of support, if you position it right. at the moment nearly nobody in Linux-Community have heard from it.
let me know, if you need further testing…

**Comment by Betterbird** [comment]
> debs and appimages

Issue #80 and issue #38.

>  at the moment nearly nobody in Linux-Community have heard from it

Judging by the downloads and support queries, that appears to be an underestimation.

As for the original issue, "calendar event reminder window cannot be dismissed", or "immutable reminders", you would need to present a reproducible case. It's certainly not true that this issue occurs with all CalDAV calendars.

**Comment by scrutinizer80** [comment]
It happens to me using iCloud calendar on Thunderbird 128.6.0esr

**Comment by zefilipe** [comment]
Hi,

I'm using BetterBird 128.7.0esr-bb22 (64-bit) in Windows 11
I had installed provider for for google calendar 128.5.2

NS_ERROR_NOT_IMPLEMENTED: [xpconnect wrapped (nsIClassInfo, calIItemBase, calIEvent, calIInternalShallowCopy)] [CalCachedCalendar.sys.mjs:770](resource:///modules/CalCachedCalendar.sys.mjs)
Calendar: [calGoogleCalendar] Modifying item Tomar injeção  failed:2147500033: Item type not supported [gdataCalendar.sys.mjs:582:13](resource://gdata-provider/legacy/modules/gdataCalendar.sys.mjs?version=128.5.1)
NS_ERROR_NOT_IMPLEMENTED: [xpconnect wrapped (nsIClassInfo, calIItemBase, calIEvent, calIInternalShallowCopy)] [CalCachedCalendar.sys.mjs:770](resource:///modules/CalCachedCalendar.sys.mjs)
Calendar: [calGoogleCalendar] Modifying item Tomar injeção  failed:2147500033: Item type not supported [gdataCalendar.sys.mjs:582:13](resource://gdata-provider/legacy/modules/gdataCalendar.sys.mjs?version=128.5.1)
NS_ERROR_NOT_IMPLEMENTED: [xpconnect wrapped (nsIClassInfo, calIItemBase, calIEvent, calIInternalShallowCopy)] [CalCachedCalendar.sys.mjs:770](resource:///modules/CalCachedCalendar.sys.mjs)

And snooze / dismiss don't work !
Regards

**Comment by Betterbird** [comment]
gdataCalendar.sys.mjs is not Thunderbird or Betterbird code, it comes from this add-on:
https://addons.thunderbird.net/en-GB/thunderbird/addon/provider-for-google-calendar/

Please file your issue here: https://github.com/kewisch/gdata-provider/issues, wait there is already an issue:
https://github.com/kewisch/gdata-provider/issues/900

**Comment by Betterbird** [comment]
Another user got rid of the (unnecessary) add-on and connected the Google calendar natively. It's working now for that user.

**Comment by zefilipe** [comment]
Good Morning,

Today when i started BetterBird, google calendars its now back available with update  of gdata-provider to version 128.5.4 it works again ... !

If it continue not working in next days  maybe i will create new profile, but google calendars sync again, and dont need do this (create new profile)

Thanks, 
Regards

**Comment by NerioAlvaro** [comment]
What worked to me was change the whole birthday calendar to Read-Only

**Comment by loqzer** [comment]
I'm having the same issue with no add-on or anything changed, a fresh installation of betterbird with the only thing I did is log into Google Mail. As soon as the calender synchronizes, the notification window appears. If I try to dismiss the reminders, the error appears:

![Image](https://github.com/user-attachments/assets/b1c54d06-0b83-475c-a7d8-412d41d0bf9b)

**Comment by Betterbird** [comment]
> A bit more of research lead me to a workaround which is disabling reminder for missed appointments in the calendar options.

Nice! There is a long discussion of making that the default:
https://thunderbird.topicbox.com/groups/planning/T22a9802df20fa357-Mb35a59ccf966a845714e6782
