### ISSUE TITLE
Advertise beign able to use BB in parralel with TP on the front page, to improve adoption.

### ISSUE THREAD

**Issue by navid-zamani** [Betterbird/thunderbird-patches#122]
This is not strictly an issue with the code base itself, but I hope it fits here anyway. Also, it’s a quick and easy thing. :)

I don’t know what you guys think, but one of the main issues with switching to BB, for me, was the hassle of possibly “not being able to go back”. As in: I assumed an irreversible “profile import” or the like, like most people likely do.
But then I read on the support page, that one can even have *both* installed at the same time, using the same profile! Which *changed everything*.
It means I can try out BB with zero hassle, and go back if I don’t like it (haha, as if that’s ever going to happen :D), or even compare between both. *Which takes away almost all the hurdles of installing it* and trying it out (and obviously staying with it).

So, thinking about adoption numbers, this is the first and easiest thing one could change, to improve adoption:
Highlight on the front page “Can be tried out in parallel, using the same Thunderbird profile”.

Since I am poor, I can’t offer money, so I’m trying to give back with what I’m good at: Useful ideas. :)
So I hope this is useful to you (and will boost adoption numbers, especially now, that Thunderbird announced focusing on “modernizing” itself (read: follow the same degenerating iPath towards “function follows (utterly flat) form” instead of being a reliable work horse.)

**Comment by navid-zamani** [comment]
Also, I saw some people on Heise complain that it does that, purely because it never said that and they didn’t trust it (probably because they assumed one might not be able to go back).

When they would have liked it, if it was stated as the feature that it is (in a way that they saw it right away).

**Comment by Betterbird** [comment]
Done. Check the website now, please make sure to refresh/reload the pages so the anchor works.

**Comment by navid-zamani** [comment]
Awesome! You’re the best!

**Comment by Betterbird** [comment]
Glad you like it. On second thought we've changed "best of all" to "easy adoption". Easy adoption is nice, but likely not the best of our features.

**Comment by navid-zamani** [comment]
Yes. :))
