### ISSUE TITLE
Rspamd Adding Heavy Spam Symbol to Mail Sent via Betterbird

### ISSUE THREAD

**Issue by georglauterbach** [Betterbird/thunderbird-patches#125]
This is, strictly speaking, not a bug. When sending mail via Betterbird, Rspamd will add the symbold `FORGED_MUA_MOZILLA_MAIL_MSGID_UNKNOWN` with a (pretty hefty) weight of `2.5`. This is presumably because the headers cannot be properly identified. For comparison the headers from the MUA as I received them:

**Betterbird**

```txt
Received: from [X.X.X.X] (X.X.X.X) by
 SOME.MAIL.SERVER (172.26.35.115) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.1.2507.21; Sun, 19 Feb 2023 14:16:24 +0100
Content-Type: multipart/alternative;
	boundary="------------7Lt0Yki5vy0UI5zsbAWrNRBL"
Message-ID: <a8cb0a41-d65a-204d-54b5-2ff676189523@MAIL.SERVER>
Date: Sun, 19 Feb 2023 14:16:24 +0100
MIME-Version: 1.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101
 Betterbird/102.7.0
```

**Thunderbird**

```txt
Received: from [X.X.X.X] (X.X.X.X) by
 SOME.MAIL.SERVER (172.26.35.115) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.1.2507.21; Sun, 19 Feb 2023 14:37:41 +0100
Content-Type: multipart/alternative;
	boundary="------------tHk5tUhO0r7fpCPkQJRXlEC0"
Message-ID: <721db70c-b435-bc88-4367-b5412dfce91c@MAIL.SERVER>
Date: Sun, 19 Feb 2023 14:37:41 +0100
MIME-Version: 1.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101
 Thunderbird/102.7.1
```

This is roughly the point inside the Rspamd code where the rule is applied: <https://github.com/rspamd/rspamd/blob/2f0d146b19db2d60b512855e8999dc2bcab22734/rules/regexp/headers.lua#L439-L462>

@vstakhov I am not 100% sure whether the issue really is located in the code. Could you help us a bit? Maybe we can provide a patch to support Betterbird in the future?

**Comment by Betterbird** [comment]
Why don't you talk to the maintainers of rspamd?

Looks like all you need to change is this line:
```
local user_agent_thunderbird	= 'User-Agent=/^\\s*(Thunderbird|Mozilla Thunderbird|Mozilla\\/.*Gecko\\/.*(Thunderbird|Icedove)\\/)/H'
```
Add Betterbird like Icedove was added:
```
local user_agent_thunderbird	= 'User-Agent=/^\\s*(Thunderbird|Mozilla Thunderbird|Mozilla\\/.*Gecko\\/.*(Thunderbird|Betterbird|Icedove)\\/)/H'
```

**Comment by Betterbird** [comment]
Sorry, we were a little brief this morning. Thanks for the report, it's important that mail sent with BB isn't classified as SPAM. We were going to offer to send a PR to https://github.com/rspamd/rspamd, but you were faster. So thanks again!

**Comment by georglauterbach** [comment]
> it's important that mail sent with BB isn't classified as SPAM.

That's one of the reasons I opened an issue here, and because of the possibility there actually was a bug introduced by BB :)

> We were going to offer to send a PR to https://github.com/rspamd/rspamd, but you were faster. So thanks again!

When an issue is closed, at least when I do, I assume the discussion is over, hence I went ahead and quickly provided a PR to Rspamd, which wasn't a big deal either :)

---

The initial response was, although straight to the point, missing out on clarifying whether this may actually be something related to BB; in that regard it was not too kind either.

---

But the matter should be resolved now and all is well - thank you all for proving us with this peace of improved software ❤️

**Comment by Betterbird** [comment]
Thanks again. Let's hope rspamd deploy this quickly. According to https://rspamd.com/ the last release was in Nov. 2022.

**Comment by georglauterbach** [comment]
A maintainer from [`docker-mailsever/docker-mailserver`](https://github.com/docker-mailserver/docker-mailserver/) (where I come from as well) has opened an issue about using GitHub's CI. This may delay the next release, but I am not 100% sure (see [this ticket](https://github.com/rspamd/rspamd/issues/4390)); it should make subsequent releases easier though.
