### ISSUE TITLE
Message filters not running automatically for Inbox (v102.8.0-bb30)

### ISSUE THREAD

**Issue by csmosx** [Betterbird/thunderbird-patches#126]
Message filters not running automatically for Inbox.
They can be run manually.

I see a filter-specific bug was [fixed upstream in v102.7.2](https://bugzilla.mozilla.org/show_bug.cgi?id=1806245).

But it seems BB still has this problem?

**Comment by Betterbird** [comment]
The upstream bug you're quoting is about a crash. BB has no issues running filters on the inbox, we use this functionality on a daily basis.

If filters don't run for you, at a first step, repair your inbox and make sure filters are correctly configured. There is also filter logging and other logging to track down filter issues. A look into the error console also doesn't go astray.

In general, please don't file support requests as issues. There are published ways to reach our support.
