### ISSUE TITLE
[FR] Copy to clipboard event fields

### ISSUE THREAD

**Issue by 875d** [Betterbird/thunderbird-patches#127]
I request the ability to copy to clipboard the field of an events, like the "location" field

**Comment by Betterbird** [comment]
Can you please clarify? From where do you want to copy? The reminder?
![image](https://user-images.githubusercontent.com/86832723/223099989-b052656b-8378-4aa3-bd1c-b0b609f96943.png)
Yes, the location is clickable but you can't copy it. If you click "Details", you get to edit the event.

**Comment by Betterbird** [comment]
Sorry, no further information received, I'm closing this now. Feel free to reopen with more information.
