### ISSUE TITLE
[agenda's reminder] I have double reminder shown for every agenda alert activated

### ISSUE THREAD

**Issue by CapitainFlam** [Betterbird/thunderbird-patches#128]
## BB is the best
Hi there! 
As explained in a previous post, as soon as I tried BB, loved it. Thanks for the good work (again).
It's not an issue, but it's a good start. 

# TL;DR: 
I have double reminder shown for every agenda alert activated, and dismissing one of them dismiss both of the reminders. I would like to have only one! 😅

# The bug(s) (in detail)
A picture worth a thousand words...
![image](https://user-images.githubusercontent.com/31761317/224573968-e1f3175a-158a-401a-b6f4-d2efe71527eb.png)
**As you can see, every alert I have in agenda's reminder is doubled.** 
Of course, I don't know why, and it's not a wanted behaviour.

## How to reproduce
Honestly, I don't know. Just have a Gmail account with events and reminders activated?

## "_OK morron, what did you try before disturbing us?_"
Well...
* "_Did you try TB?_" - Yes, I tryed TB. There is no automatic connection to Gmail agenda. And I didn't tryed an external addon, 'coz i belive that it's neither a TB or a BB addon the problem (as it's BB build in!)
* "_Did you activate 'debug mode', switching off all extensions?_" - Yes. No change. 
* "_Did you clean up the "starting cache' (button available in the debug info')_" - Yes. No change.
* "_Did you try to find it on internet? GIYF! / RTFM!_"  - Yes. Not found.
* "_Did you bribe the developers?_" - No, I respectfully paid them a coffee with a wire. But yes, I bribed them saying BB is the best. 
* "_Do you know that it will not help you to bribe them?_" - Technically, I said I didn't bribe them. But anyway, devs have a sense of humor !
* "_Did you even include the debug details?_" - Yes, it's in attachment. 
* "_Did you tried everything?_" - Almost. [Help me Obi Wan](https://www.youtube.com/watch?v=5cc_h5Ghuj4)
* "_Can't you live with it, [live and let die!?](https://www.youtube.com/watch?v=6D9vAItORgE)_" - I could. [But I will only if devs says so](https://sleepinggeeks.com/2016/01/04/aim-for-the-moon-land-amongst-the-stars/).

(after reading the debug file)
* "_Why the F do you have 10 agendas connected to your Gmail account?_" - Well, aside the fact that it's not your business (except if it's a root cause of the issue), I track family members, activities and jobs in different calendars, allowing instant color sorting by color in everyday use. 
* "_Why did you [redacted] some agenda names?_" - Copy past previous answer. Names and family are not public information. 

## debug extraction: 
[debug details.odt](https://github.com/Betterbird/thunderbird-patches/files/10952160/debug.details.odt)

below is the agenda's debug table:
(see attachment for full report)

Nom | Valeur
-- | --
Nom |  
Type | caldav
Désactivé |  
Nom 				d’utilisateur |  
URI |  
Intervalle 				d’actualisation |  
En lecture 				seule | false
Supprimer 				les alarmes |  
Cache activé |  
Identité 				iMIP | id1
iMIP 				
désactivé |  
Compte iMIP |  
Identifiant 				de l’organisateur |  
Forcer la 				planification des messages |  
Alarmes 				contextuelles prises en charge |  
Alarmes sur 				invitation prises en charge |  
Alarmes 				maximales par évènement |  
Pièce 				jointe prise en charge |  
Catégories 				maximales |  
État de 				confidentialité pris en charge |  
Priorité 				prise en charge |  
Évènement 				pris en charge | true
Tâche prise 				en charge | false
Heure locale 				prise en charge |  
UTC/GMT pris 				en charge |  
Programmation 				automatique prise en charge | true

# "_A last word ?_" 
Thanks for reading.

**Comment by Betterbird** [comment]
> "Did you try TB?" - Yes, I tryed TB. There is no automatic connection to Gmail agenda.

Well, there are absolutely no changes between BB and TB as far as calendar/Google calendar/CalDAV is concerned. None whatsoever.

So what you're seeing is an upstream Thunderbird bug. If you have tried TB, you haven't tried hard enough. There are these bugs for "doubled up reminders":
https://bugzilla.mozilla.org/show_bug.cgi?id=802577
https://bugzilla.mozilla.org/show_bug.cgi?id=805776

Are these recurring events? We also see two reminders for the previous-last recurrence and the last recurrence of locally stored recurring events. We never looked into it. Our team has close to o knowledge about "calendar stuff" 😢.

P.S.: I appreciate your humorous long report, but short and precise would be more efficient.

**Comment by CapitainFlam** [comment]
LOL, I don't know what to say, I don't have any reminder showing on TB actually ! I'll try switching profile.
Thanks for the information. I'll live with that and wait for debug :)
...And I'll (try to) be more efficient next time! 🤞

**Comment by Betterbird** [comment]
Well, it would be good to know what the problem was: Subscribed to a calender twice, any of the two bugs quoted above describe the problem? If everyone using TB got two reminders every time, I think the problem would be more widely known.

**Comment by CapitainFlam** [comment]
###...Scratching my head... /me: confused 😕 EDIT: /me: absolutely confused 😵

It's definitively the first bug: https://bugzilla.mozilla.org/show_bug.cgi?id=802577, 
'coz second bug is caused by a "duplicate event in a second agenda". And I don't duplicate them. 

The catch is that, even if I had the bug since first day, **I don't have it now. I mean, right now, since last restart.** I had it few seconds ago. I don't understand. 

###What did I do before change ?
I controlled (again!) everything in accounts (but didn't change anything)... 
I controlled everything in calendar parameters (but didn't change anything)... 
I closed and reopened BB, going in Agenda tab to look at it. 
I created the test event. 
And it's OK.
I am really puzzled by this issue. I had it for several days, and now i report it, it's gone. 

**Oh wait !
...Nevermind, it came back.** 
**The reminder was OK, then it ADDED both duplicated AFTER 5 minutes.** 

![image](https://user-images.githubusercontent.com/31761317/224686429-60232ec0-0449-4637-bcda-73b97a6064f5.png)

and here is my agenda: no duplicate or whatsoever. 
![image](https://user-images.githubusercontent.com/31761317/224686947-36cccb31-0d7b-41e7-951b-35ee8f14e4f0.png)

It's seems like it's loading a first time the calendar with associated reminder... Then reload it, and trigger reminder again. 

##Analysis:
it is NOT caused by a recurring event, as both are triggered, one is recurring (each week), this other is stand-alone 
It is NOT caused by Gmail agenda only, because "Test" was created in BB, not in Gmail... 

...**But it could be caused by the _synchronization_ with the Gmail agenda ?** (it would explain the delay ? And as I clicked directly in the AGENDA tab, and created the event 'TEST', it may have not finished synchronization ? Thus, on the next sync, it loaded in Gmail agenda, and duplicated the reminder ?)

below showing that TEST created in BB has been sync with Gmail agenda

![image](https://user-images.githubusercontent.com/31761317/224688369-c3202885-9c9b-4f67-9b88-2fb4e3349dc3.png)

🤯

**It doesn't make _any_ sense**, and I can understand that you just put it aside. It's OK to have no knowledge in calendar stuff 😁

If you want to investigate, tell me what you want me to do.
I have a meeting in a few minutes, so I can't investigate further right now, but I'll do what you request if needed.

**Comment by Betterbird** [comment]
Well, the best would be to:
Start **Thunderbird** on a new profile (start with `-p`). Connect the Google calendar somehow, then reproduce the problem. Create a new bug in Bugzilla for Thunderbird with minimal details.

I don't understand "local event" but synchronised with Google. That makes two, no? When you create an event, you decide which calendar it goes into:
![image](https://user-images.githubusercontent.com/86832723/224692327-22298f56-6295-4ec3-b00f-b4d7d2d1a208.png)
So if you put it into a CalDAV/Google calendar, that's where it's stored.

**Comment by CapitainFlam** [comment]
OK I'll try on a fresh install of TB...

And for the "local event", I have badly explained my idea, 
_It's the same event, but it has to be asynchronously synchronized between local and cloud._ 

it's based on the analysis that 
A/ I created it 'locally' in BB, 
B/ the synchronization with Gmail server / Gmail agenda, via CalDAV is asynchronous (as I remember and as I read) (for detail see https://fr.wikipedia.org/wiki/CalDAV and https://www.rfc-editor.org/rfc/rfc4791#section-8.2)
C/ The issue could be caused by the synchronization between 'local data in cache' and 'server data'

**Comment by Betterbird** [comment]
OK, so all you have is a standard CalDAV calendar, apparently with additional storage in local cache via this option:
![image](https://user-images.githubusercontent.com/86832723/224834781-7a82bb0a-2939-47fe-b07c-01f2f32a2977.png)
You create events in the local client, and they are of course stored on the server and in local storage.

I think a lot of people use it like this and don't have your problem. That turns it into a support problem. As was said, please try on a new profile in TB and BB to see whether it's reproducible.
