### ISSUE TITLE
Dark UI: automatically convert light message content to dark (TB bug 1715361)

### ISSUE THREAD

**Issue by theincogtion** [Betterbird/thunderbird-patches#129]
Betterbird Version: 102.8.0-bb30

Linux Mint
OS and Betterbird are in Dark Mode.
Nevertheless the message content of mails are with white background:
![grafik](https://user-images.githubusercontent.com/10852327/225070202-b38f49b1-ec73-449a-a52c-3ee53f29ba2c.png)

![grafik](https://user-images.githubusercontent.com/10852327/225071149-a963aa1a-1797-4562-a0d7-0fc1a4581127.png)

This happens with unformatted messages and html ones.

**Comment by Betterbird** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1715361

Please don't file BB issues for long-standing upstream bugs or enhancement requests.

**Comment by Betterbird** [comment]
Looking at https://bugzilla.mozilla.org/show_bug.cgi?id=1715361 a little closer, it turns out that a lot of work was done by the TB team already and then the process stalled in Feb. 2022 although technical and product manager both wanted that implemented for version 102.

We'll see whether we can get something implemented.

**Comment by Betterbird** [comment]
Why don't you install this add-on in the meantime?
https://addons.thunderbird.net/en-GB/thunderbird/addon/darkreader/

**Comment by Betterbird** [comment]
No "home-grown" solution will ever be as good at this add-on developed by a very active big community:
https://github.com/darkreader/darkreader
Sadly the TB/BB version:
https://addons.thunderbird.net/en-US/thunderbird/addon/darkreader/
is much older than the FF version:
https://addons.mozilla.org/en-US/firefox/addon/darkreader/
We'll try talking to them to provide more up-to-date TB/BB versions (or find a way to provide it ourselves).

**Comment by Betterbird** [comment]
For your convenience, we've built the latest version 4.9.62 of Dark Reader and uploaded it here:
https://www.betterbird.eu/downloads/DarkReader/darkreader-thunderbird-4.9.62.xpi
