### ISSUE TITLE
Multi-line usability issues for new users

### ISSUE THREAD

**Issue by narFnarF** [Betterbird/thunderbird-patches#130]
I recently installed Betterbird specifically for the functionality of being able to see the subject on a second line. However, Betterbird doesn't make it easy to access this feature.

# Problem 1:
The setting is hidden in a sub-sub menu. (Menu button > View > Layout > Multi-line View
![Screenshot from 2023-03-19 15-01-37](https://user-images.githubusercontent.com/3538115/226201046-6774be74-3fb2-4ec0-883a-a11f8430de90.png)

## Proposed solution:
Add these options in the column dropdown:
![Screenshot from 2023-03-19 15-13-22](https://user-images.githubusercontent.com/3538115/226203427-25ca069f-6da9-4db1-a254-9bb9a86536e8.png)

These could also be added in the Settings screen, which is where I went looking the first time.

# Problem 2:
It's unclear what the difference is between "_Multi-line view on all folders_" and "_Multi-line view via subject column_"

## Proposed solution
I don't have a solution to propose because I still don't understand the difference between these 2 options. If you could explain me, I could try to provide an alternative that would be clearer.

**Comment by Betterbird** [comment]
See https://www.betterbird.eu/expert-tips/ - Quote:

Many people have asked us to finally implement a [multi-line view](https://www.betterbird.eu/media/img/multiline-view.png), so we're happy to announce that this is now included in Betterbird. There are three options:

1. View > Layout > Multi-line View On All Folders: Once you enable this option, all folders will show in multi-line view. This switches the subject column off for all folders which are displayed while the option is in effect.
2. View > Layout > Multi-line View Via Subject Column: With this option, to switch on multi-line view for a folder, deselect the subject column for the particular folder in the column picker of the message list/thread pane. Selecting the subject column again switches off multi-line view for the folder.
3. View > Layout > No Multi-line View: No folder will show in multi-line view. This switches the subject column on for all folders which are displayed while the option is in effect, hence undoing any individual settings made with the second option.

**Comment by narFnarF** [comment]
I understand better the difference between these options. That being said, I still believe the problems I've raised are still valid and should be addressed to help new users. New users won't dive into a documentation named "Expert tips" 😅
