### ISSUE TITLE
Introduce preference to configure to which custom-column second line in multi-line view is aligned

### ISSUE THREAD

**Issue by narFnarF** [Betterbird/thunderbird-patches#131]
When the Thunderbird Conversation extention ([link](https://addons.thunderbird.net/fr/thunderbird/addon/gmail-conversation-view/)) is installed, multi-line view moved the subject far to the right

![Screenshot from 2023-03-19 15-11-41](https://user-images.githubusercontent.com/3538115/226203447-7e8ba9d5-7da5-4824-ac60-4b7cd2d28386.png)

This seems to be because Betterbird attach the subject to the Date column specifically.

Suggestion: Always put the subject line aligned to the left instead

**Comment by Betterbird** [comment]
> This seems to be because Betterbird attach the subject to the Date column specifically.

No. We attach to the left-most column in this set:
https://github.com/Betterbird/thunderbird-patches/blob/df119c0f2f08e6d66648a705777ba123239b6f4b/102/features/04-feature-multiline-tree.patch#L660
From/Recipient/Correspondents/Date/Received.

Sadly we can't attach to any custom-column an add-on may add. It would be possible to add an preference where you can configure a column name to attach to. With the right motivation, we may be able to develop this.

**Comment by Betterbird** [comment]
The cheaper option would be just to add the `betweenCol` used by the Conversations extension into the list.

**Comment by Betterbird** [comment]
Fixed the "cheap" way via https://github.com/Betterbird/thunderbird-patches/commit/b62b4d94a03ff5a840925828b93b4720c41b99c0.
