### ISSUE TITLE
Implement loading of extensions from betterbird/extensions

### ISSUE THREAD

**Issue by Betterbird** [Betterbird/thunderbird-patches#132]
Implement extension loading from extensions directory (not distribution/extensions). First we need to investigate how this is done in the official Ubuntu build via ppa:mozillateam/ppa:
![image](https://user-images.githubusercontent.com/86832723/226333590-7d6197fc-0a24-4fa5-aa8e-e35fdf684456.png)

I hope @mfschumann or @ricotz can help here. @mfschumann pointed me to
https://sources.debian.org/patches/thunderbird/1:102.9.0-1/prefs/Don-t-auto-disable-extensions-in-system-directories.patch/
but setting pref extensions.autoDisableScopes doesn't appear to help. I noted that pref value is 0 from TB 78 from Ubuntu.

**Comment by mfschumann** [comment]
I think the relevant parts must be in the [Debian patch set](https://sources.debian.org/patches/thunderbird/1:102.8.0-1/) already, because Debian install lang packs into /usr/lib/thunderbird/extensions, just as Ubuntu.

**Comment by mfschumann** [comment]
I've done a test on Debian Testing (TB 102.8.0):
- When installing TB from the Debian repos, `extensions.autoDisableScopes` is set to 3 (as per the patch linked above). Installing a language pack makes the corresponding XPI file appear in `/usr/lib/thunderbird/extensions`, and TB shows it as enabled in the list of addons.
- When setting `extensions.autoDisableScopes` to 15 (the BB and upstream TB default), installed language packs still appear in the list of addons, but they are shown as disabled and cannot be used.

That means the pref is involved in making system extensions work, but might not be the only thing that has to be adapted.

**Comment by Betterbird** [comment]
Thanks for testing. Yes, the pref `extensions.autoDisableScopes` is not the only part of the game. I set it to 0 in BB and nothing got loaded from the `extensions` directory I created next to the executable (I don't want to say "install folder").

What puzzles me is that `extensions` is not a folder that is usually searched for extensions. Also, I remember the days when Calendar/Lightning was a "distribution extension". That caused a who lot of strive. If there is such a thing as a "system extension", Lightning could have used it. Or maybe, it's only for Linux.

I guess, unless @ricotz gets back to us, we'll need to read through:
https://bugzilla.mozilla.org/show_bug.cgi?id=412446
https://bugzilla.mozilla.org/show_bug.cgi?id=311008
https://searchfox.org/mozilla-central/rev/d2786d9a6af7507bc3443023f0495b36b7e84c2d/toolkit/xre/nsXREDirProvider.cpp#402
https://searchfox.org/mozilla-central/rev/d2786d9a6af7507bc3443023f0495b36b7e84c2d/toolkit/xre/nsXREDirProvider.cpp#1303

It's this, isn't it?
https://searchfox.org/mozilla-central/rev/d2786d9a6af7507bc3443023f0495b36b7e84c2d/toolkit/moz.configure#3117
`set_define("ENABLE_SYSTEM_EXTENSION_DIRS", True, when="--enable-system-extension-dirs")`

**Comment by Betterbird** [comment]
Done some more reading: `--allow-addon-sideload` (setting `AppConstants.MOZ_ALLOW_ADDON_SIDELOAD`) will be it, as seen here:
https://hg.mozilla.org/mozilla-central/rev/1ac4b6bdcbb2#l1.10
That changed removed sideloading from the application directory when `AppConstants.MOZ_ALLOW_ADDON_SIDELOAD` was **not** set. So it is should still be possible to set this via:
https://searchfox.org/mozilla-central/rev/d00845a44a8d1bf3f472ff36fd3f22a03af30a76/toolkit/moz.configure#1714
`set_config("MOZ_ALLOW_ADDON_SIDELOAD", True, when="--allow-addon-sideload")`

**Comment by Betterbird** [comment]
First part of the fix here: https://github.com/Betterbird/thunderbird-patches/commit/b1dacfc382c3c3946e456ea30f45085787dcbc0c. Now we also need to set the `extensions.autoDisableScopes` pref. It's a toss up whether to do this, since BB itself doesn't take advance of "application extensions". Interested users could switch the pref themselves.

**Comment by mfschumann** [comment]
If it's really only `/usr/lib/betterbird/extensions` that is searched for extensions the feature is pretty irrelevant for the average user: `/usr/lib` is supposed to be managed by some sort of package manager. A use case I can think of is language packs that are packaged separately from betterbird (just like debian does for thunderbird) and get installed there. On the other hand, if the feature is only relevant to package maintainers, they can as well use the appropriate build options when building betterbird in the packaging process. 

Btw, what was the use case of the guy writing you about this issue in the first place?

For the flatpak I am considering to turn the language packs from distribution extensions into application extensions. @Betterbird Do you see any downsides of this approach? 

The advantage I see is that the choice and versions of installed lang packs are solely managed by flatpak. With the current approach it is difficult to get back a language pack that has previously been uninstalled by the user.

**Comment by Betterbird** [comment]
> Btw, what was the use case of the guy writing you about this issue in the first place?

Good question. He went silent after I fixed it for him. I assumed he was in some sort of IT consulting business (based on his e-mail address) and thought he might be setting up some machines for company use for multiple users. He explicitly mentioned doing this stuff on the Debian/Ubuntu version of TB.

> Do you see any downsides of this approach?

We'll so far we don't set the `extensions.autoDisableScopes` pref yet and I'm not sure we will. Any argument in favour or against it? Distribution extensions are a constant hassle, I wrote earlier on that Lightning shouldn't have used them. Surely Debian/Ubuntu don't use distribution extensions for language packs.

**Comment by mfschumann** [comment]
I have successfully tested sideloading a dummy extension in the flatpak version [here](https://github.com/flathub/eu.betterbird.Betterbird/pull/70) and plan on switching the langpacks from being installed as distribution extensions to being installed as application extensions with the next BB release (if everything behaves as expected when testing the changes). That means I will then set `extensions.autoDisableScopes` to `3` in the `default-preferences.js` I was already shipping in the flatpak.

> We'll so far we don't set the `extensions.autoDisableScopes` pref yet and I'm not sure we will. Any argument in favour or against it? 

I think either way it is easy enough for the sysadmin or the maintainer of a BB package to set the pref on their own if they want to use addon sideloading. Maybe you want to document somewhere that there is this alternative to using distribution extensions?

**Comment by Betterbird** [comment]
Like this https://www.betterbird.eu/releasenotes/ (reload page) or more explicitly? Sideloading is phased out by Mozilla, so I don't want to advertise this too widely.

**Comment by mfschumann** [comment]
> Like this https://www.betterbird.eu/releasenotes/ (reload page) or more explicitly? Sideloading is phased out by Mozilla, so I don't want to advertise this too widely.

Looks fine to me, thanks.

**Comment by Betterbird** [comment]
> Any argument in favour or against it?

The application add-on in betterbird/extensions will override/overwrite the en old one that was installed into the user's profile via the distribution extension mechanism before?

**Comment by mfschumann** [comment]
I've done some testing with quite inconclusive results so far: https://github.com/flathub/eu.betterbird.Betterbird/pull/70#issuecomment-1483813249
