### ISSUE TITLE
will not recognize Thuderbird's address book

### ISSUE THREAD

**Issue by JimFlasch** [Betterbird/thunderbird-patches#134]
Why does Betterbird not recognize Thunderbird's address book right off the bat? I had to export it from Thunderbird to a CSV file and then import it into Betterbird to use it, which was quite annoying.

**Comment by Betterbird** [comment]
Please don't file support requests as GitHub issues. Contact our support team instead.

Of course BB recognises TB's address book, it all depends on whether and how you copied/imported the profile or whether you're sharing the profile with TB.
