### ISSUE TITLE
Build error: mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.h:103:28: error: expected class name public nsIMultilineTreeView

### ISSUE THREAD

**Issue by artist-linux** [Betterbird/thunderbird-patches#135]
Since about 3 days building on an Artix Linux derivative OS no longer works:

```
 7:04.11 comm/mailnews/base/src
 7:19.21    Compiling gkrust v0.1.0 (/build/betterbird/src/mozilla-esr102/toolkit/library/rust)
 7:31.70 In file included from /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.cpp:10:
 7:31.70 /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.h:103:28: error: expected class name
 7:31.70                     public nsIMultilineTreeView,
 7:31.70                            ^
 7:31.70 /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.h:112:3: error: 'GetRowCount' marked 'override' but does not override any member functions
 7:31.70   NS_DECL_NSITREEVIEW
 7:31.70   ^
 7:31.70 /build/betterbird/src/mozilla-esr102/obj-x86_64-pc-linux-gnu/dist/include/nsITreeView.h:142:14: note: expanded from macro 'NS_DECL_NSITREEVIEW'
 7:31.70   NS_IMETHOD GetRowCount(int32_t *aRowCount) override; \
 7:31.70              ^
 7:31.70 In file included from /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.cpp:10:
 7:31.70 /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.h:112:3: error: 'GetSelection' marked 'override' but does not override any member functions
 7:31.70 /build/betterbird/src/mozilla-esr102/obj-x86_64-pc-linux-gnu/dist/include/nsITreeView.h:143:14: note: expanded from macro 'NS_DECL_NSITREEVIEW'
 7:31.70   NS_IMETHOD GetSelection(nsITreeSelection **aSelection) override; \
 7:31.70              ^
 7:31.70 In file included from /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.cpp:10:
 7:31.70 /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.h:112:3: error: 'SetSelection' marked 'override' but does not override any member functions
 7:31.70 /build/betterbird/src/mozilla-esr102/obj-x86_64-pc-linux-gnu/dist/include/nsITreeView.h:144:14: note: expanded from macro 'NS_DECL_NSITREEVIEW'
 7:31.70   NS_IMETHOD SetSelection(nsITreeSelection *aSelection) override; \
 7:31.70              ^
 7:31.70 In file included from /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.cpp:10:
 7:31.70 /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.h:112:3: error: 'GetRowProperties' marked 'override' but does not override any member functions
 7:31.70 /build/betterbird/src/mozilla-esr102/obj-x86_64-pc-linux-gnu/dist/include/nsITreeView.h:145:14: note: expanded from macro 'NS_DECL_NSITREEVIEW'
 7:31.70   NS_IMETHOD GetRowProperties(int32_t index, nsAString& _retval) override; \
```

Things tried so far:
- use previous rust version
- use mk_add_options MOZ_MAKE_FLAGS="-j1" in mozconfig - the buildserver has 32GB internal memory
- chroot is always clean
- use another build server, also with 32GB

Maybe this is related to an upstream change.
Any pointer on how to fix this is welcome.

**Comment by Betterbird** [comment]
Which version are you building? We've built 102.9.1-bb32 successfully using our build script a week ago (29th March 2023). Which mozilla-esr102 and comm-esr102 versions are building on, the ones from 102.sh? Which revision of this repo are you using? Which build script are you using?

Looks like your source is not correctly set up. If `nsIMultilineTreeView` is not a known class (very first error), then you haven't applied 04-feature-multiline-tree-m-c.patch. It's downhill from there.

**Comment by artist-linux** [comment]
Tried building from:
- latest commits, e0d163ea094a72548730aa964902b3d515614ade and before that from 702adb4dfd01d782457e8ac2970e7bf6cfc0e9eb
- MOZILLA_REV=e26ff04290d095dac006a3710b07077ee5d20f31
- COMM_REV=a8965ef0b30705f497df3df718db60d9dc2c304f

I indeed removed all 04-feature* patches, but only for the last run.
The last build that succeeded was on Mar 30 13:51 for betterbird-102.9.1 so probably from 093685292c44b63e9cfd32d3219e75a83690db9d or 4fd3232cd2584392989bf11d446b52a8e360d1a1

I tried a new build, without removing any patches, from 093685292c44b63e9cfd32d3219e75a83690db9d and this errors out with:

...
applying 03-feature-biff-server.patch
applying 04-feature-multiline-tree.patch
applying 04-feature-multiline-tree-allow-grouping.patch
applying 04-feature-multiline-tree-allow-threading.patch
applying 04-feature-multiline-tree-dummy-rows-css.patch
applying 04-feature-multiline-tree-all-off.patch
applying 05-feature-default-buttons.patch
...
 2:08.10 In file included from /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.cpp:10:
 2:08.10 /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.h:103:28: error: expected class name
 2:08.10                     public nsIMultilineTreeView,
 2:08.10                            ^
 2:08.11 /build/betterbird/src/mozilla-esr102/comm/mailnews/base/src/nsMsgDBView.h:112:3: error: 'GetRowCount' marked 'override' but does not override any member functions
 2:08.11   NS_DECL_NSITREEVIEW
...

**Comment by Betterbird** [comment]
As I said, you likely didn't apply the 04-feature-multiline-tree-m-c.patch patch to the mozilla-esr102 repo.

**Comment by artist-linux** [comment]
Thank you for your response. I have no doubt you are right about that, so I tried to find out why the patch is not being applied.
The output shows the patches from the 'series' file are applied.
The output also shows the patches from the 'series-M-C' but NOT that these are applied.
Is that related to below line: 1252 abort: 00manifest@c1f78e57c2d0d58de9e0e957d221d1d278a31803: no node ?

...
   1250 =======================================================
   1251 Pushing all patches
   1252 abort: 00manifest@c1f78e57c2d0d58de9e0e957d221d1d278a31803: no node
   1253 08-branding-m-c.patch
   1254 09-branding-m-c.patch
   1255 1563452-serialise-shouldnt-break-attributes-m-c.patch
   1256 04-feature-multiline-tree-m-c.patch
   1257 04-feature-multiline-tree-allow-grouping-m-c.patch
   1258 04-feature-multiline-tree-allow-threading-m-c.patch
   1259 04-feature-multiline-tree-all-off-m-c.patch
   1260 04-misc-missing-fluent-strings-m-c.patch
   1261 06-misc-no-quirks-mode-message-m-c.patch
   1262 07-misc-details-notification-incompatible-link-m-c.patch
   1263 08-misc-disable-TB-langpacks-m-c.patch
   1264 359303-dont-replace-NBSP-m-c.patch
   1265 532712-insert-NBSP-m-c.patch
   1266 1783001-dont-close-spellcheck-menu-m-c.patch
   1267 1783001-dont-close-spellcheck-menu-2-m-c.patch
   1268 1799093-fix-cropping-in-tree-view-m-c.patch
   1269 1777788-fix-dialog-resizing-m-c.patch
   1270 backout-bug-1730429-lost-style-m-c.patch
   1271 1812386-optimise-FindURLStart-End-Moz-m-c.patch
   1272 1812386-limit-look-ahead-m-c.patch
   1273 16-feature-limit-plaintext-URL-ScanTXT-m-c.patch
   1274 1820504-optimise-grapheme-m-c.patch
   1275 (working directory not at a head)
   1276 applying 01-branding.patch
   1277 applying 02-branding.patch
   1278 applying 03-branding.patch
   1279 applying 03-branding-mac.patch
   1280 applying 04-branding.patch
   1281 applying 05-branding.patch
...

**Comment by Betterbird** [comment]
Hmm, looks like you're using out build.sh script. That also does a `hg qser` command, so you can see which patches are applied, they are in colour which is lost when pasting here.

That abort line doesn't look good. Try replacing the mozilla-esr120 repo or do a `hg verify`.

BTW, the rust version is defined in the 102.sh file, this is the version that needs to be used.

I'm closing this now, feel free to comment further.

**Comment by artist-linux** [comment]
I tried a build for a slightly newer commit of the mozilla-esr102 repo, and this completed without problem. I tried once more with en even newer commit and this also completed ok.
So the issue is clearly upstream as the original problem reproduced on 2 servers in complete different networks and even countries.
Thank you for helping pin-point the cause.

**Comment by Betterbird** [comment]
This is really weird. 102.sh says to use e26ff04290d095dac006a3710b07077ee5d20f31 which is TB is using:
https://hg.mozilla.org/releases/comm-esr102/rev/1a13e13d67c8755210e07171506a0b407a4836f9 <-- specified here
https://hg.mozilla.org/releases/mozilla-esr102/rev/e26ff04290d095dac006a3710b07077ee5d20f31 <-- here it is.
