### ISSUE TITLE
Spell checker marks everything red

### ISSUE THREAD

**Issue by Code-TT** [Betterbird/thunderbird-patches#137]
Every time I reply to an email, the spell checker marks everything in red. When I open the spell checker, I see that only English is enabled, but German is not. So I have to activate German, but unfortunately this value is not saved. With the next email I have to activate it manually again - very annoying. Please fix that.

![betterbird](https://user-images.githubusercontent.com/37022171/229782898-e3e17c17-18d6-4e33-9c05-cea584488f62.png)

**Comment by Betterbird** [comment]
Please don't file support requests as bugs. You need to enable the German dictionary here, then everything works:

![image](https://user-images.githubusercontent.com/86832723/229785432-778fda4c-49a1-4950-a421-8865ed21d64f.png)

![image](https://user-images.githubusercontent.com/86832723/229785560-9d8d5692-70ad-4327-8273-4c8e48e77c2e.png)
