### ISSUE TITLE
Change unread email background and colour

### ISSUE THREAD

**Issue by shadyslim2018** [Betterbird/thunderbird-patches#139]
I have adjusted the UI font in Manjaro to bold, as it improves readability for my deteriorating eyesight. However, this has resulted in the unread and old emails appearing nearly identical. I am wondering if there is a way to customise the appearance of unread emails, such as adjusting the background colour or font colour?

**Comment by Betterbird** [comment]
Please don't file support requests as GitHub tickets.

Anything is configurable using userChrome.css. We supply a sample file here: https://www.betterbird.eu/expert-tips/userChrome.css

Something like this might be helpful:

```
#threadTree treechildren::-moz-tree-row(unread) {
  color: colour-of-your-choice !important;
  background-color: colour-of-your-choice !important;
}
```
Please understand that we can't give support for users wishing to configure the product individually.
