### ISSUE TITLE
[Feature request] Autostart minimize to systray

### ISSUE THREAD

**Issue by Bjoern-B** [Betterbird/thunderbird-patches#140]
Would it be possible to add an option to have Betterbird start minimized to the systray instead of having it launch in fullscreen and having to close it everytime on boot.

**Comment by Betterbird** [comment]
For which platform? Windows has "minimise to tray", on Linux we still don't have it, see Issue #111.

What do you mean by "close it every time on boot"? Do you have BB as a startup program?

**Comment by Bjoern-B** [comment]
Yes sorry for windows, exactly i have Betterbird as a startup program and everytime i boot windows it then opens but it would be nice if it would just open to the system tray directly so that i still get the notifications while im on my machine but just dont have to close it every time.

**Comment by Betterbird** [comment]
OK. Do you know the `mail.biff.show_tray_icon_always`? That always shows the icon in the system tray, regardless of whether there is new mail or not. Would be handy in your case to know whether BB is running.

As for the "start minimised", we could investigate an and another option. Any incentive you can offer?

Checking Bugzilla for existing bugs, I found:
https://bugzilla.mozilla.org/show_bug.cgi?id=1679702
https://bugzilla.mozilla.org/show_bug.cgi?id=1816256

**Comment by Betterbird** [comment]
Looks doable. `window.minimize()` minimises the window, that call must be placed at the right spot in the startup code, with a preference to enable it.

**Comment by Betterbird** [comment]
OK, you should get what you wanted if you set pref `mail.startupMinimized` to `true`. We can't make it 100% perfect since the window flashes up for a split-second. Try this build:
https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-102.10.0-bb33-latest-build.en-US.win64.installer.exe

**Comment by Bjoern-B** [comment]
That works great thank you

**Comment by Betterbird** [comment]
If you have a Bugzilla account, you could mention in https://bugzilla.mozilla.org/show_bug.cgi?id=1816256 that we implemented the feature.
