### ISSUE TITLE
Weird icon/shape that won't go away after launching Betterbird.

### ISSUE THREAD

**Issue by Aspredo** [Betterbird/thunderbird-patches#143]
![image](https://user-images.githubusercontent.com/131216163/232931467-36e4d49b-6fd5-4a5a-b4eb-3462d796bd8b.png)
This little icon/shape keeps appearing after launching Betterbird and I am pretty sure it is related to the "Enter New Password" button because when I press it, I don't even get the option to enter a new password for said account.

**Comment by Betterbird** [comment]
Please don't file support requests as GitHub tickets. You can reach our support via e-mail.

That said, your request lacks basic information. Which OS is this? What exactly is happening? What's an "Enter New Password" button? You mean that BB is trying to get new messages, and the dialogue Retry/Cancel/Enter New Password appears?
