### ISSUE TITLE
Console error on startup: PreferDisplayName: undefined - not a boolean

### ISSUE THREAD

**Issue by eyalroz** [Betterbird/thunderbird-patches#144]
When starting BetterBird 102.10.0-bb33 for the first time , I see:
```
NS_ERROR_NOT_AVAILABLE: PreferDisplayName: undefined - not a boolean 2 AddrBookCard.jsm:364
    getPropertyAsBool resource:///modules/AddrBookCard.jsm:364
```
and I don't see this with TB 102.10. 

... but I don't see this on second startup, so maybe the pref got set.

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1744761

**Comment by Betterbird** [comment]
It happens in TB, too, in fact since version 78, where this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1652274 was filed. They fixed it recently. Since we've survived 78, 91 and 102 with this issue, it can wait until 115. Or do you have a strong case to backport to BB 102?

**Comment by eyalroz** [comment]
No, no strong case.
