### ISSUE TITLE
'conversation-browser' has already been defined as a custom element (TB bug 1590469)

### ISSUE THREAD

**Issue by eyalroz** [Betterbird/thunderbird-patches#145]
With BetterBird 102.10.0-bb33, I get:
```
Uncaught DOMException: CustomElementRegistry.define: 'conversation-browser' has already been defined as a custom element [conversation-browser.js:907](chrome://chat/content/conversation-browser.js)
```
whenever I open a dupe review dialog with my removedupes extension. And - I definitely don't use chats or conversation browsers in it in any way.

This also happens with TB 102.10.0:
https://bugzilla.mozilla.org/show_bug.cgi?id=1590469
... not only with my extension.

**Comment by Betterbird** [comment]
Please read the BB bug filing instructions. We can't fix all 14.000+ open TB issues as part of the BB project. I've never seen or be bothered by this issue. Are there any steps to reproduce this?

**Comment by Betterbird** [comment]
@eyalroz : Are there any steps to reproduce this?

**Comment by eyalroz** [comment]
Well, I typically get it at some point while running a dupe search, but let me check this evening and see if I can't whittle this down to a simpler reproduction procedure.

**Comment by Betterbird** [comment]
Looking at https://bugzilla.mozilla.org/show_bug.cgi?id=1590469#c6:

On an installed TB/BB, can you rename omni.ja to omni.zip and unpack it. Then open chrome/messenger/content/messenger/customElements.js and add this code:

https://searchfox.org/mozilla-central/rev/8a63fc190b39ed6951abb4aef4a56487a43962bc/toolkit/content/customElements.js#14-19

If that fixes the error, we can add a patch to BB.

**Comment by eyalroz** [comment]
> Well, I typically get it at some point while running a dupe search, but let me check this evening and see if I can't whittle this down to a simpler reproduction procedure.

So, it seems my extension itself is loading `customElement.js`. I suppose at some point in became unnecessary to load it, but John Bieling's update instructions didn't mention it.

**Comment by Betterbird** [comment]
So close the ticket?

**Comment by eyalroz** [comment]
Yes; I was waiting to see whether you knew something more about this.

**Comment by Betterbird** [comment]
Well, TB can fix their own bug. They somehow started and then left it. So typical 😞
