### ISSUE TITLE
Too much console noise

### ISSUE THREAD

**Issue by eyalroz** [Betterbird/thunderbird-patches#146]
BB 102.10 bb33 has some console noise on startup. TB has its own, but not exactly the same. On my installation, BB's is:
1. 1681928635074	addons.xpi	WARN	Checking /opt/betterbird/distribution/extensions for addons
2. Found 122 public keys and 2 secret keys (2 protected, 0 unprotected) RNPLib.jsm:541:15
3. Trying to load /opt/betterbird/libotr.so OTRLib.jsm:64:11
4. Trying to load libotr.so from system's standard library locations OTRLib.jsm:64:11
5. Trying to load libotr.so.5 from system's standard library locations OTRLib.jsm:64:11
6. Successfully loaded OTR library libotr.so.5 from system's standard library locations OTRLib.jsm:72:13
7. Betterbird skipping update check, last done 19/04/2023, 21:04:52 MailGlue.jsm:760:15

About 3+4+5+6 - Why so many items for essentially one thing? Plus - it's the app's own library, not an extension, so why report trying to load it?

About 1: Why does that merit a warning? Or any notification?

About 2: Why does RNPLib need to tell me how many keys it found, unless I'm in some sort of debug mode? I don't get told how many address book entries I have, for example.

About 7: In non-debug mode, why tell me about things which the app doesn't do?

(Not including Warnings or Errors here!)

**Comment by Betterbird** [comment]
1 at a guess comes from the Mozilla platform code when it checks for add-ons. 3 to 6 are that horrible OTR stuff. You can file upstream bugs for those.

7 is deliberate.

In general, BB is a lot less noisy than TB, and yes, there are a few messages at startup.
