### ISSUE TITLE
Contact us link not working.

### ISSUE THREAD

**Issue by Aspredo** [Betterbird/thunderbird-patches#147]
I am trying to contact you guys about an issue that you told me to make a request about, but I keep getting this Java Script error when I press the contact us button on betterbird.eu.

**Comment by Betterbird** [comment]
Please stop opening new issues!

Just send an e-mail to support at the domain you quoted above.

**Comment by Aspredo** [comment]
> Please stop opening new issues!
> 
> Just send an e-mail to support at the domain you quoted above.

What domain? @betterbird.eu? What's the entire email I should be sending the email to?

**Comment by Betterbird** [comment]
Yes. Just send a message.

**Comment by Betterbird** [comment]
BTW, the contact us link works fine. There's some JavaScript behind the button to decode the e-mail address. It's not stored in cleartext on the site to avoid that Spammers pick it up.

**Comment by Aspredo** [comment]
> Yes. Just send a message.

Okay but what's the actual email to send my message to? betterbird.eu@betterbird.eu? Apologies for the confusion here, I just didn't understand what you meant when you said "Just send an e-mail to support at the domain you quoted above.".

**Comment by Betterbird** [comment]
Just send an e-mail to **support** at the domain. What is not clear about this?
