### ISSUE TITLE
Support clearing the error console, or adding some record to it, when installing an extension

### ISSUE THREAD

**Issue by eyalroz** [Betterbird/thunderbird-patches#148]
I'm an extension developer. My workflow often looks like this:

* Notice a bug
* Make a change to the extension code
* Preprocess & bundle the extension (its code is not edited in-place)
* Clear the Error Console
* Reinstall the extension
* (Possibly do something with the extension, but maybe not if the bug is visible after installation)
* Look for new records in the error console

This could be sped up in more than one way, but what I'd like to have happen is to be able to have the Error Console either cleared automagically for me before add-on installation.

**Comment by eyalroz** [comment]
On second thought, I could just file this against TB itself, so nevermind.

**Comment by eyalroz** [comment]
Yes, but I would rather not have to locate the Error Console window (not immediate if you have many windows - they all have the same icon), bring it up, click the trash, then go back to the main window to install.

... and then there's the joy of the GNOME file picker dialog in which nothing works right, especially not keeping recently-used files.

**Comment by RealRaven2000** [comment]
This should be strictly "opt-in" - and possibly reset after restarting Thunderbird. Because you have to remember that you also delete all console logs from your esteemed colleagues who may also chase after bugs in their Add-ons. Greetings from QuickFolders :)

**Comment by eyalroz** [comment]
@RealRaven2000 : Oh, certainly, I'd be fine with just an opt-in preference and no UI for this.
