### ISSUE TITLE
How to swap to Betterbird

### ISSUE THREAD

**Issue by dannypike** [Betterbird/thunderbird-patches#15]
Hi. How do I get Betterbird to use my existing profile from Thunderbird? The "import" option doesn't seem to be able to find it.

**Comment by Betterbird** [comment]
Betterbird should already use the existing profile when this profile was used by TB 91 before. Using the existing profile may not happen if you're trying to run BB on a TB 78 profile, or if you're trying to run BB, which is 64bit, on a profile created by TB 32bit.

In any case, you can start BB with the -p option (for profile manager) and select the profile you want. Or use "Help > More Troubleshooting Information", about:profiles and select the profile there.

**Comment by dannypike** [comment]
Thank you the `-p` option is exactly what I needed! Apparently, I had set up a non-default profile a while ago and forgotten about it, so BB found that and was using it rather than the right one :)
