### ISSUE TITLE
Promise in messenger.compose.saveMessage() is fullfilled too early

### ISSUE THREAD

**Issue by MyAddonsDev** [Betterbird/thunderbird-patches#150]
I am the developer of the add-on [Mail Merge](https://addons.thunderbird.net/thunderbird/addon/mail-merge/) for Thunderbird and Betterbird. A few weeks ago a user contacted me and reported an issue, which turned out to be Betterbird specific.

In the compose window, when you click the composeAction, my add-on saves the message as a draft or a template. Afterwards my add-on opens a new popup window. The new popup window should be opened in the foreground and get focused automatically. However, starting with Betterbird 102.9.0 the popup window is opened in the background and does not get focused anymore.

In fact the new popup window is opened in the foreground and focused for a very brief moment, until the "Saving Message" dialog showing "Your message has been saved." gets focused again. This ultimately results in the new popup window being displayed behind the compose window and not having focus.

Thunderbird Stable 102.10.1, Beta 113.0b5 and Daily 114.0a1 as well as Betterbird 102.8.0 are NOT affected. Betterbird 102.9.0, 102.9.1, 102.10.0 and 102.10.1 are affected.

The reasons seems to be this additional patch in Betterbird - more specifically the delayed closing of the "Saving Message" dialog in line 79: https://github.com/Betterbird/thunderbird-patches/blob/main/102/features/17-feature-improved-send-progress.patch#L79

This seems to conflict with the returned Promise in [messenger.compose.saveMessage()](https://webextension-api.thunderbird.net/en/latest/compose.html#savemessage-tabid-options), which is fullfilled too early now, i.e. before the "Saving Message" dialog is closed.

I have created and attached a simple add-on, which reproduces the issue, see: [test.zip](https://github.com/Betterbird/thunderbird-patches/files/11358929/test.zip)

**Comment by Betterbird** [comment]
Thanks for the detailed report. We could delay resolving the promise a little. However, when the promise is resolved, the message is saved, only that the window hasn't been destroyed and the progress is up for another 750ms for the user to read it. That causes a mess-up with the popup window you're launching.

Is this acceptable to you:

```
messenger.composeAction.onClicked.addListener(async (tab) => {
	await messenger.compose.saveMessage(tab.id, { mode: "draft" });
  // Wait until the compose windows is destroyed and the progress dialogue has disappeared in Betterbird.
  await new Promise(r => setTimeout(r, 1500));
	await messenger.windows.create({
		type: "popup",
		url: "popup.html",
	});
});
```

**Comment by MyAddonsDev** [comment]
Frankly, I think this issue should be fixed directly in Betterbird without the need for a change in an add-on. In Thunderbird it simply works without the need for an additional timeout - so did it in Betterbird itself until the additional patch was introduced.

The actual saving of the message and the "Saving Message" dialog belong together - at least from a usability perspective. Therefor I think the promise should only get fulfilled once both are finished, i.e. after the actual saving of the message is completed and the "Saving Message" dialog is closed.

That being said I might consider adding the timeout to workaround this issue - if there is no other way to fix the issue in Betterbird directly.

However, there is a slight problem with the additional timeout, if it is applied unconditionally for Thunderbird and Betterbird. In Thunderbird it simply delays opening the popup window for no reason, which might make the user believe - for a brief moment - that nothing is happening. I would rather avoid this and only apply the timeout, when my add-on is running on Betterbird.

Is there a way for an add-on to distinguish between Thunderbird and Betterbird via the MailExtension APIs? (Though I still think this should be fixed in Betterbird directly!)

**Comment by Betterbird** [comment]
In a WE experiment you can check `AppConstants.MOZ_APP_DISPLAYNAME_DO_NOT_USE`. We can make `browser.runtime.getBrowserInfo()` return `name=="Betterbird"` which it currently doesn't.

Let us consider the issue for a while not to deliver any quick-fix.

**Comment by Betterbird** [comment]
We found a better fix that doesn't rely on a timeout. Latest build here:
https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-102.10.1-bb34-latest-build.en-US.win64.installer.exe
This will ship in BB 102.11.0-bb35 on 9th May 2023.

Please let us know if you need a Linux "latest build" version for testing. Note that the one in the downloads area from yesterday (29th April 2023) doesn't contain the fix yet.

**Comment by MyAddonsDev** [comment]
Thank you for fixing the issue! I have just tested the "latest-build" and it works like a charm now.
