### ISSUE TITLE
policies.json has no effect

### ISSUE THREAD

**Issue by elandorr** [Betterbird/thunderbird-patches#152]
As per https://enterprise.thunderbird.net/manage-updates-policies-and-customization/managing-thunderbird-policies/customizing-thunderbird-using-policies.json

just like Firefox. Placing the file here: `/betterbird/distribution/policies.json` does nothing.

Has this been deliberately disabled?

**Comment by Betterbird** [comment]
This works fine on Windows

![image](https://user-images.githubusercontent.com/86832723/235318118-16fa5ef0-1abf-4e38-bc41-be08e551e5d0.png)

and Linux:

![image](https://user-images.githubusercontent.com/86832723/235318316-c1b66b72-56ec-48fa-9039-8049d505a35b.png)

From experience, syntax errors in the JSON file lead to the entire file being ignored.

**Comment by elandorr** [comment]
Indeed, thanks!

Sometimes trailing commas are allowed, sometimes not. That was it.

There was no error on the CLI so I thought it was turned off.

Thanks for BB! They blasted you on the HN post, but I think you're right.

**Comment by Betterbird** [comment]
> There was no error on the CLI so I thought it was turned off.

Blame that on upstream. I've been caught many times. JSON doesn't allow for trailing commas, JS does.

> They blasted you on the HN post, but I think you're right.

What's a HN post? We've collected 55K users in under two years, so we must be doing something right.

**Comment by elandorr** [comment]
> What's a HN post?

'hackernews', a popular digg clone from a 'startup incubator'. I don't read it often, but sometimes there's interesting stuff.

HN is typically frequented by well sheltered, system-compliant people, so you might save your weekend and not read it.

https://news.ycombinator.com/
https://hn.algolia.com/?q=betterbird

> we must be doing something right.

I still use CLI mail and TB legacy with minimal add-ons. Not a fan of Mozilla's constant changes killing well-working setups, but I'm giving BB a shot. You're clearly interested in it actually being used, whereas they're interested in money and buzzwords, just like ruining FF over and over. Really appreciate the effort. Plus, it has telemetry off by default, so I can hand it to regular users and they get a little less unwanted network activity.

**Comment by Betterbird** [comment]
That stuff, I've read it when it first came out. Some posters there side with our project. Sorry, I don't have time to read it, there are more important things in life. Same applies to the Reddit stuff, we even mention it on our homepage (very bottom).

That said, from: https://news.ycombinator.com/item?id=32920235:

_... because after reading that I'm not sure I want anything to do with Thunderbird any more. ... You know what that is? That's f*cking weaponized shunning. You know, like cults do._

Haha, the guy hit the nail on the head. However, I don't understand why everyone wants to discuss politics, is there no interest in software?

Here's a positive review, haha: https://news.ycombinator.com/item?id=32749193

**Comment by elandorr** [comment]
>Sorry, I don't have time to read it, there are more important things in life.

Fully agree. I saw them piling on like system-sheep and stopped.

>I don't understand why everyone wants to discuss politics, is there no interest in software?

They have to prove their allegiance to the system for social credit and a marketable 'bio'. Of course it's fake, like software. You can't open Mozilla's oh so 'libre' browser without fiddling around for hours to reach a minimum level of privacy. They actively try to prevent it. Last year they even changed an already very unknown method so it quietly pretends to work, but does not actually work. A bugtracker discussion revealed it was intentional. Their greed cost them almost all marketshare, and now they try every modern angle to stay relevant. Doesn't work anyway, Google is better at playing that game, too.

Can my mail client/browser/computer maybe only connect to where I tell it?

Even a build with tel. disabled and all settings off does not ask for the /consent/ that is such a buzzword today:

autoconfig.thunderbird.net
live.thunderbird.net
services.addons.thunderbird.net
thunderbird-settings.thunderbird.net
aus5.mozilla.org
autopush.prod.mozaws.net
classify-client.services.mozilla.com
locprod2-elb-us-west-2.prod.mozaws.net
shavar.prod.mozaws.net
Etc.pp. the list goes on, and since I last sniffed, they probably added a dozen more.

But let's not dwell on that. Thanks again for your efforts, BB is definitely the new default (non-legacy) TB!

**Comment by Betterbird** [comment]
> Last year they even changed an already very unknown method so it quietly pretends to work, but does not actually work. A bugtracker discussion revealed it was intentional.

What's that about?

**Comment by elandorr** [comment]
There was a project called 'zerofox' (or similar) with zero unwanted requests, but that stopped working, and there's no documentation from Mozilla. So I started to research.

After many hours of torturing grep with the enormous codebase, I thought it was possible to get a quiet, 'consensual' FF, but the final option did nothing. Mozilla came up with the usual bizarre logic that it would 'help' the user, if he had no control. (Not that a normal user would ever even find it, when even their own devs barely know about it.)) Would have to get the notes again to tell you the name. I ended up sniffing and blacklisting, but that's not a very usable method. And why the heck does a 'libre' tool try so hard to track infinite metadata? There are so many places this beast creates unwanted, non-consensual network connections, even their own core devs don't know them all.

_The 'libre' browser that you can't shut up._ Even ungoogled-chromium is quieter, and seems a lot more maintainable.

Imagine your `curl` started to act that way.

When someone asks on their bugzilla etc., he instantly gets beaten by a thousand sheep angry you dared to question their supreme corporation. (I stopped reporting bugs many years ago as nobody cared.)

They all want to get a little badge from Mozilla. They have a ranking system and whatnot. Besides ego, there's money involved, but I think the most part might seriously be ego. A little pat on the back from corporate is well sought-after. Although having that in your 'bio' sure is helpful for selling yourself in the future. Reminds of Microsoft's 'volunteers' who will do anything to get a badge from MS.

If it weren't for the amazing add-on devs and modders who somehow still find motivation, there would be no point using a Mozilla product. Like the bookmarks+ 'aafn' or so guy who wrote a ridiculously efficient tool with so much love for detail, it's a joy to use. He fixed things reported 15+years ago. It's just bookmarks, but it's done not for money, but for a purpose, and it's noticeable. He works around Moz obstructions.

Moz has no 'community', it's a weird corporate sham game. That became the norm in most of tech, but it's particularly odd in Moz, which keeps marketing the "we're just a bunch of happy little nerds doing this for fun", when it's hardcore business. They deal in billions of dollars, obscene manager salaries etc., there's no 'community garden project' anywhere.

With the EU/US creating ever new ways to further dystopia, it's good to know the tools you use don't cause unwanted network activity, but that's almost impossible now. We just want a tool that renders html/js/css and does nothing frickin' else. If you graph Moz's network activity, you see it's equal or more active than a retail no-settings-changed Windows 10 even. Mozilla undid everything it was loved for at the very beginning.

**Comment by Betterbird** [comment]
Wow, interesting read. I agree especially regarding the culture, community and "hardcore business".

We'd better stop this discussion here if we don't want to be reprimanded by GitHub and its sponsor 😉.

P.S.: For further greps through the Mozilla code base, use: https://searchfox.org/

**Comment by elandorr** [comment]
Thank you, that might be handy.
