### ISSUE TITLE
Crash when opening first email after long period AFK

### ISSUE THREAD

**Issue by eyalroz** [Betterbird/thunderbird-patches#153]
If I leave BB running for a long while (hours), then get back to the computer, open it, and try to read an email message by clicking it - BB crashes.

Build: 102.10.1-bb34 (64-bit)

**Comment by Betterbird** [comment]
Nice report, but sadly we can't action it. There is no crash reporting in BB, and TB itself has a few crashes.

So you can do one of two things: 1) Do the same in TB and see whether it crashes. 2) Build a debug version of BB and check where it crashes. I'm not aware of any changes we made to trigger crashes after long idle periods.

**Comment by eyalroz** [comment]
I'll try (1.) first.

**Comment by Betterbird** [comment]
Please re-open if you have more details.
