### ISSUE TITLE
Betterbird bz2 file for linux install file fails sha256 test.

### ISSUE THREAD

**Issue by JillSwift** [Betterbird/thunderbird-patches#154]
`betterbird-102.11.0-bb35.en-US.linux-x86_64.tar.bz2` fails the sha256 test. Please to fix? 

(I have cleaned out the caches and re-DLed, as well as fetching it and checking manually.)

**Comment by Betterbird** [comment]
Yes, the AUR download is currently broken since we replaced the binaries at our site with build2 and hence the checksums don't match. AUR needs to catch up.
