### ISSUE TITLE
Issue: blurry tray icon

### ISSUE THREAD

**Issue by Lungenpest** [Betterbird/thunderbird-patches#155]
System:
![grafik](https://github.com/Betterbird/thunderbird-patches/assets/64774660/3cf6d7ce-9cba-4e99-9abd-83f57769442d)

Betterbird:
![grafik](https://github.com/Betterbird/thunderbird-patches/assets/64774660/a751864d-0f18-4fcf-9c6b-c33750e81987)

Issue: blurry tray icon

![grafik](https://github.com/Betterbird/thunderbird-patches/assets/64774660/c81ee9d3-e172-42c6-80e7-90491c1eb922)

The betterbird icon is very blurry.
The taskbar has a height of 72px.
The tray icons are set to flexible size according to the height of the task bar. 

For example Steam and Telegram are also Flatpak and the tray icons are not blurry,
I think its not a problem of Flatpak.

Betterbird may have different sizes for the tray icon for better scaling?!

Its not a very important issue, but its ugly ;)

**Comment by Betterbird** [comment]
Hmm, that is very surprising. So the desktop it KDE Plasma 5.27.4. We ship the desktop icon as SVG exactly to avoid any chance of blurriness: https://github.com/Betterbird/thunderbird-patches/blob/ae237a97e30dd3f193d3942947c1c2a3e95b122f/102/features/12-feature-linux-systray-betterbird.patch#L339

So how on earth can that be blurry. It's not a problem we can fix, it's either a problem in https://github.com/AyatanaIndicators/libayatana-appindicator which we use or in KDE.

We had people try it out before we shipped it with SVG and the feedback was positive:
https://github.com/Betterbird/thunderbird-patches/issues/20#issuecomment-1384068119
https://github.com/Betterbird/thunderbird-patches/issues/20#issuecomment-1384080076

So what's special about you?

**Comment by Lungenpest** [comment]
I would say, I´m special ;)

The only thing i could imagine, is that something is with the Flatpak version wrong....


Now I tried to install Betterbird from AUR to check its not depending on Flatpak but the checksum was wrong oO

![grafik](https://github.com/Betterbird/thunderbird-patches/assets/64774660/1f516853-1998-4f7c-af86-56fe5ce9ef17)

**Comment by Betterbird** [comment]
Sigh, issue #154.

**Comment by Betterbird** [comment]
You can just download the .tar.bz2 from our site, unpack it and run it. Takes 5 minutes tops.

**Comment by Lungenpest** [comment]
Oh my gosh...

Its a Flatpak related problem...

![grafik](https://github.com/Betterbird/thunderbird-patches/assets/64774660/495652fb-57ba-4c97-b09f-46964a249d23)

**Comment by Betterbird** [comment]
Wow, I've never seen such a nice screenshot!

@mfschumann, over to you! (He's the FlatPak maintainer.)
