### ISSUE TITLE
[not a bug but illogical behavior] feeds are auto-paused on error, no warning, manual reset required

### ISSUE THREAD

**Issue by elandorr** [Betterbird/thunderbird-patches#157]
No error message/popup, it just changes the icon to an exclamation mark.

![image](https://github.com/Betterbird/thunderbird-patches/assets/56206745/13f93a78-52b7-4f06-8f16-acea477f780b)

ctrl-shift-J shows:

`feeds: downloaded: updates disabled due to error, check the url -<url>`

- you have to actively monitor the icons to catch it
  - I only have a few, but someone with let's say 10+ is not gonna check that every time.
- notifications via an add-on are useless, if it randomly pauses

It shouldn't auto-pause when a site has an error for a minute or is just plain slow. Not sure why that was deemed useful at one time.

https://bugzilla.mozilla.org/show_bug.cgi?id=1524241

They closed the ticket and that's it. You can find further details/examples on why this behavior is illogical in there. My favorite:

> I agree that there should at least be some way to disable this behavior. I have a somewhat spotty internet connection, and every time I have an outage I have to go in and restart half of my feeds. This didn't happen in Thunderbird a few years ago.

**Comment by Betterbird** [comment]
We had feedback from the person that maintained feeds code in TB a while ago. There is a pref that determines whether feeds are permanently paused after an error: rss.disable_feeds_on_update_failure.

Try setting this to false.

**Comment by elandorr** [comment]
Thanks, I'll add that to the list of mozilla-must-haves. rss2email is way more efficient, but it might help someone else.
