### ISSUE TITLE
automatic update checks are disabled via policy, BB checks anyway

### ISSUE THREAD

**Issue by elandorr** [Betterbird/thunderbird-patches#158]
The popup just showed up despite having everything under the sun turned off

**Comment by Betterbird** [comment]
Which popup? The About box?

Which policy is that? We can suppress the update check when the policy requires it.

**Comment by elandorr** [comment]
Yes, the about box with a link to the site. Not that big of a deal, but I personally have a zero-network-unless-asked policy.

```
    "AppAutoUpdate": false,
    "BackgroundAppUpdate": false,
    "DisableAppUpdate": true,
    "DisableBuiltinPDFViewer": true,
    "DisableTelemetry": true,
```

**Comment by Betterbird** [comment]
OK, if you want to suppress the check, you can set pref `betterbird.update.lastCheckTime` to 2000000000, that's 18/05/2033.

**Comment by Betterbird** [comment]
FIxed. Fix will ship in the next version.
