### ISSUE TITLE
memory usage out of control

### ISSUE THREAD

**Issue by elandorr** [Betterbird/thunderbird-patches#159]
102.11.0-bb35
Debian testing, x64, 6.2.13

Deleted a handful of mails at once and noticed lag. Checked res usage... CPU blasting and RAM++.

~800+MB used for a handful of accounts and feeds after using it for a while. All add-ons disabled, no change. Only plaintext, no HTML, no browser tabs. ~~Telemetry~~ spyware disabled, no excessive refreshing. No fancy caldav sync, nothing. It's literally a fresh copy with a bunch of accs added.

Fewer than 500 local mails, barely any on server.

Best scenario, fresh start:

betterbird-bin 450M
betterbird-bin -contentproc` 'web content' even though no web page is open with ~90M

Optimistically min. ~500M after start. And threads! 200,300,400, you name it. It uses almost as many threads as my FF with 100 tabs.

What the heck? That's worse than some electron web clients. If this is just how TB 100+ is, I have to go back.

**Comment by Betterbird** [comment]
That's all inherited from upstream TB, sadly.

**Comment by elandorr** [comment]
Tried 91.13.1-bb37, ~100M less fresh, still a lot. I don't recall my old setup snacking hundreds of MBs, the PC only had 2G total. The current one is up to 700 again without touching it.

Nothing changed functionally in 15 years, how does that make technical sense? TB ran on laptops with 1G where windows took up half of that. I don't know systems programming/deep C(PP), but I'd be curious, if you're in the mood (if not it's fine). A select few electron programs can cope with ~100 and they drag a whole chromium along.

**Comment by Betterbird** [comment]
I don't think we can action this. TB is just a balcony plastered onto Firefox which is based on the Mozilla platform. Instead of viewing web pages, it views HTML in e-mail messages (or plaintext messages turned into HTML under the cover). All the memory and thread allocation is handled by the Mozilla platform.

**Comment by elandorr** [comment]
Weird how it's worse than FF itself with plenty of tabs and a dozen add-ons. But I see.
