### ISSUE TITLE
Subject option miss from thunderbird

### ISSUE THREAD

**Issue by jaisekjames** [Betterbird/thunderbird-patches#16]
There is no option to tick subject[missing subject] in Thunderbird message list view, if we switch back from betterbird to Thunderbird
![missing subject in thunderbrid](https://user-images.githubusercontent.com/44542605/141421038-3b47f151-e922-45b2-9f8d-8ea243776727.jpg)
.

**Comment by Betterbird** [comment]
That is correct. You need to switch off the multi-line view before switching back to Thunderbird since Thunderbird doesn't offer that functionality. Sorry about the inconvenience.
