### ISSUE TITLE
Runs slow and doesnt always update emails as read

### ISSUE THREAD

**Issue by PaulMcF1987** [Betterbird/thunderbird-patches#162]
I downloaded Betterbird after being a long term Thunderbird user. I was excited to give it a shot.

First issue I noticed was that emails were very slow in coming through... I had Betterbird and Thunderbird open side by side to test and noticed that Thunderbird always received the email first, sometimes the gap was as large as 5 minutes.

The next issue I noticed was
I had read a few emails but the emails were still showing as unread. I then opened the emails and closed them again and they stayed as read.
But this is happening quite a lot.

Generally I dont double click emails to read them, I just read them in the view pane. This has always been enough to mark the emails as read but on Betterbird, I am finding that it doesnt always update the read status.

**Comment by PaulMcF1987** [comment]
Another thing I have noticed is...

The unified inbox does not behave in the same way...

You will see that in the first pic, I have selected the option that says `Inbox` and this shows me all of the emails sent to all of my email addresses without having to select each address separately.

However on the Betterbird image, the inbox tab does not show anything, I need to go into each inbox separately. I have blurred the email addresses in the image but kept the count of new emails to show that there are emails to be read.

Should this function work in the same way as it does on Thunderbird?

![image](https://github.com/Betterbird/thunderbird-patches/assets/75368133/244c4f83-bfe3-4d61-af28-8467e6207ad4)
![image](https://github.com/Betterbird/thunderbird-patches/assets/75368133/4386ae8f-3506-4c6d-aa35-8a0382d6625e)

**Comment by Betterbird** [comment]
Please don't file support requests as GitHub tickets.

BB and TB will behave identically if you run them on the same profile. You are using two profiles which are configured differently. In particular:

The interval of checking for new messages is configurable:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/0944349f-1e54-4a56-b121-b414ee38293c)

If TB checks more frequently, it will appear "faster".

The time you need to view a message for it to appear read is configurable:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/722ff97c-d64b-4b63-b94a-7935f2fc137b)

If you have a shorter time configured in TB, it will mark the messages read faster.

Lastly, check the definition of your Inbox in unified folders, by the looks of it, the inboxes of the various accounts are not part of the unified inbox in the BB profile:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/4f1f3edc-d7b4-4184-b90a-6b59b7911e41)

**Comment by PaulMcF1987** [comment]
@Betterbird Read and Display was set to Immediately, the same setting as I use on Thunderbird... will changing it to 1 second make a difference?
The message does actually set itself to `read` but when I click on a different message it reverts back to `unread`

**Comment by Betterbird** [comment]
The "immediate" setting works, too. I've never seen a read message revert back to unread.

**Comment by PaulMcF1987** [comment]
@Betterbird I will try and get a video and send it to you, its not all of the time it happens but it has seemed to happen quite a lot.

where do I find the `definition for unified inbox`?

**Comment by Betterbird** [comment]
> I will try and get a video and send it to you, its not all of the time it happens but it has seemed to happen quite a lot.

Well, we can imagine how it looks if a message pops back from read to unread. And we trust that you're not making it up. However, even seeing the effect won't let us diagnose it. If the message pops back to unread, perhaps another client sets it unread?

> where do I find the definition for unified inbox?

Right click, Properties.

**Comment by PaulMcF1987** [comment]
@Betterbird 

> perhaps another client sets it unread?
There are no other clients running that would set it back to unread. I am running Betterbird on its own with no other clients running beside it.
No one else has access to the email accounts

**Comment by PaulMcF1987** [comment]
I know you said you don't need a video, but I thought I'd provide one for you to see
I never had an issue with this happening with Thunderbird, but it is happening very regular with Betterbird

https://github.com/Betterbird/thunderbird-patches/assets/75368133/639f4c49-fcc5-4649-aea6-44e83eb74c5e

**Comment by Betterbird** [comment]
> When I right click and select properties, my pane looks different to yours as shown in the picture

You need to right-click onto the top unified folder, not the individual components.

Thanks for the video. Yes, the top message jumps back to unread. Maybe related to some SPAM processing.

There are no changes between TB and BB in this area. I suggest to run TB on your BB profile (start `thunderbird -p`) and you will see that they behave the same. Or run BB on the TB profile. That works, if both programs are at the same version 102.11.1, for example.

**Comment by PaulMcF1987** [comment]
@Betterbird 
The screenshot I added was from the top unified folder. If I select properties from one of the nested options I get a different pane with more tab options as shown in the attached pic
![image](https://github.com/Betterbird/thunderbird-patches/assets/75368133/7c135cf2-7a5d-45dd-a655-95f8db44395d)

It also does the same with mail that is not spam
BB should be running on the TB's profile as I set that up when I first ran BB, I imported everything over rather than adding all manually

**Comment by Betterbird** [comment]
> The screenshot I added was from the top unified folder.

Sorry, but that's not what happens here.
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/f57aee3f-1109-4a1a-8e3e-4869ff7ec41a)

Well, in the initial screenshot you showed TB running in dark mode, BB in light mode. That's not the same profile. Just running BB will create a new profile, importing into it is still a new profile. Unless you explicitly selected the existing TB profile for BB, you're running on a new profile. One way to select an existing profile is to start the program with `-p` to launch the profile manager.

**Comment by PaulMcF1987** [comment]
I have went to the area shown in the pic... tried setting all 3 profiles to default and it made no difference, all 3 profiles acted in the exact same manner

(I restarted BB after changing the profile)

![image](https://github.com/Betterbird/thunderbird-patches/assets/75368133/3b700e25-bdc3-474e-b3ff-0e02866d6cc4)

However, I dont see wht this would make a massive difference.

All I want is for the Inbox Unified tab to show all email, and for emails to stay read once they have been read

> Sorry, but that's not what happens here.

Well thats whats happening here as shown in the pic

![image](https://github.com/Betterbird/thunderbird-patches/assets/75368133/453538b5-60cf-4214-9f40-827163a54aac)

**Comment by PaulMcF1987** [comment]
> It really makes no sense to continue here until you run BB on the "black" profile.

As mentioned above, I have tried running BB on all 3 profiles, they all operate the exact same

Thunderbird
![image](https://github.com/Betterbird/thunderbird-patches/assets/75368133/95bc6c97-b63c-446a-868e-82e004af064d)

Betterbird
![image](https://github.com/Betterbird/thunderbird-patches/assets/75368133/659cfe27-2b42-4c9d-9954-3825f3670c80)

So from that I conclude that I am comparing apples with apples

**Comment by Betterbird** [comment]
Your pictures show that TB runs on EazyFreight and BB runs on default-default. The former displays in dark, the latter in light. As we wrote before, run any of the two programs with the `-p` switch to launch the profile manager. Alternatively, you can use the "Lauch Profile" button to start another instance on the chosen profile. That's not possible if the other program is already running on that profile.

**Comment by PaulMcF1987** [comment]
There are 2 pictures in the above message which show that both BB and TB are running on the same profile `EazyFreight`

the only time BB is running on a different profile is the pic a couple of messages above where I had changed the profile to see if it made a difference

I ran `betterbird -p` and the below pic shows what came up. I did not change anything, the `Eazy Freight Profile was selected

![image](https://github.com/Betterbird/thunderbird-patches/assets/75368133/465a9c7c-77c8-4240-8767-76ba866e3bcd)

I then ran `thunderbird -p` and the below pic shows that they are on the same profile

![image](https://github.com/Betterbird/thunderbird-patches/assets/75368133/462930fd-5307-4d07-882d-23a49e8f63c4)

**Comment by PaulMcF1987** [comment]
I uninstalled and reinstalled BB. I'll see how I get on with a fresh installation

**Comment by Betterbird** [comment]
A reinstall isn't necessary, it's essential which profile you use.

**Comment by Betterbird** [comment]
So what was the end result of all this?

**Comment by PaulMcF1987** [comment]
@Betterbird 
The issue with emails not updating as read seems to be getting worse.
I have seen emails that I have read and even replied to which are showing as unread again. It is getting frustrating as I can have 20+emails to get through in a short space of time and it knocks me off focus

**Comment by Betterbird** [comment]
As we said before, please run TB on the profile to see whether it behaves 
the same.

We can't action this since we've never experienced it; yes, we saw it in 
your video. If TB works correctly, one option is to stop using BB.

**Comment by PaulMcF1987** [comment]
@Betterbird 
As I mentioned above, I reinstalled betterbird and it is now on the same profile as thunderbird
All of the same addons etc were added automatically, If I open Thunderbird, the same tabs will be open on both. The profiles are now correctly sync'd

But the issue with the emails showing as unread seems to have got worse

**Comment by Betterbird** [comment]
If TB works better on the same profile than BB, we suggest to use TB.

> All of the same addons etc were added automatically, If I open 
> Thunderbird, the same tabs will be open on both. The profiles are now 
> correctly sync'd

We are really confused by this statement. If there is only one profile in 
use, to which profile were the add-ons added? What is "etc"? Why are you 
mentioning "the profiles" (plural) which are synced? We still haven't 
seen any evidence that the same profile is used for both programs, the 
latest screenshots showed two profiles with different themes, one light, 
one dark.

And just to repeat: The IMAP behaviour of TB and BB is exactly the same, 
so there is nothing we can think of that would cause the issue.

**Comment by Betterbird** [comment]
We'd be interested to hear whether TB behaves any better on that profile. As we understand, the problem is intermittent, but has gotten more frequent lately.

Debugging this, in TB or BB, will be difficult since we'd need direct access to the machine/setup that shows the problem. Alternatively you would have to run some IMAP logging.

**Comment by PaulMcF1987** [comment]
@Betterbird 
Back using TB with no issues

**Comment by Betterbird** [comment]
Sorry to hear that. I've you're interested in debugging this in BB, you'd need to run IMAP logging:
https://wiki.mozilla.org/MailNews:Logging#Thunderbird_Module_Names
We'd be looking for any messages where the server communicates `\seen`.
