### ISSUE TITLE
File > Exit does not close betterbird, but instead empties the trash on the highlighted mailbox

### ISSUE THREAD

**Issue by vdbhb59** [Betterbird/thunderbird-patches#165]
When I click File > Exit, betterbird instead of closing/exiting, empties the trash for the selected/highlighted/last selected email account. See snap. How and from where do I provide you the logs/debug information?
OS: Windows 11
Betterbird version: 102.12.0-bb37 (64-bit) and earlier versions.
If you need logs, please guide me how to generate them, and I can then share.
![image](https://github.com/Betterbird/thunderbird-patches/assets/60728004/34e62f57-375e-4c0f-80a0-a8c7a3091c28)

**Comment by Betterbird** [comment]
Looks like you have "Empty trash on exit" configured and that executes, 
but afterwards something prevents the program from exiting.

Is the anything in the Error Console ("Tools > Developer Tools", clear 
the console before using "File > Exit")?

Does that also happen in Safe Mode (see Help menu) or with add-ons 
disabled?

**Comment by vdbhb59** [comment]
> Looks like you have "Empty trash on exit" configured and that executes, but afterwards something prevents the program from exiting. Is the anything in the Error Console ("Tools > Developer Tools", clear the console before using "File > Exit")? Does that also happen in Safe Mode (see Help menu) or with add-ons disabled?

I had the [keepassemail](https://addons.thunderbird.net/en-US/thunderbird/addon/keepassxc-mail/) addon enabled, which was not allowing it to be closed out, as it kept on calling the keepass database file and since my db file stays locked unless needed, it was getting response as db locked. I disabled it and it closes now,  but takes between **2-3 minutes** to exit. No output on error console though post disabling the keepassmail addon upon file>exit.

**Comment by Betterbird** [comment]
2-3 minutes is still a long time for the program to close. Looks like 
some diagnostic tools need to be used to find out where the time is 
spent. The first step would be to switch on some logging:

https://wiki.mozilla.org/MailNews:Logging

What to switch on really depends on your usage, maybe IMAP to start with.

You could also uncheck the "Empty trash on exit" option to see whether 
that makes a difference.

Are you using any CalDAV calenders or anything else that is synced on 
exit?

**Comment by Betterbird** [comment]
We missed your update: If it doesn't happen in safe mode, you should 
localise the add-on that causes the delay and contact its author.

Safe Mode also resets some preferences to their default values, so it 
could also be caused by a changed pref, like some number of concurrent 
connections.

**Comment by Betterbird** [comment]
Looks like this is add-on related or related to slow network or excessive access, hence nothing we can address directly in BB. CalDAV is a different issue which seems to cause a lot of slowness. RSS feeds are likely not at fault.

We'll close the ticket, but we're happy to assist further. "Localise the add-on that causes the delay" was meant to mean "identify it", by switching the add-on back on one-by-one and checking whether the slowness returns. Of course you can also use a "bisecting" approach instead of the "one-by-one".
