### ISSUE TITLE
Autocrypt support

### ISSUE THREAD

**Issue by RasheedAZ** [Betterbird/thunderbird-patches#168]
Hi. Is it possible to support the Autocrypt standard so that open source end-to-end encrypted email is within reach of normies who can't set up, manage share and verify PGP keys manually?

https://autocrypt.org/

Delta Chat, for example, has done this and it works easily with many providers with zero setup as long as both parties are using an Autocrypt supporting client.

I know Autocrypt Level 1 is far from perfect but because of its ease-of-use, it has a million times higher chance of adoption by normies than manual pgp if clients start fully supporting it. Level 2 can always work on the remaining issues and improve...

**Comment by Betterbird** [comment]
Isn't Autocrypt already supported in TB and hence BB? I see all those 
Autocrypt headers being sent, we'll, at least for PGP encrypted e-mail. 
Is there a TB bug to support Autocrypt better?

In general, it's unlikely that we will implement additional security 
features.
