### ISSUE TITLE
Option to make "Open as list" default search view (TB bug 580252 from 2010)

### ISSUE THREAD

**Issue by mrjovanovic** [Betterbird/thunderbird-patches#169]
This is a feature request.

Thunderbird at the moment has a very complex search mechanism that is somewhat frustrating to use for those of us used to other email clients. Right now, after conducting a search, I always click "open as list". It would be great if there were an option that would skip this step and align search with practice in other email clients.

There is a bug for this in Bugzilla ([580252](https://bugzilla.mozilla.org/show_bug.cgi?id=580252)), which is thirteen years old. The comments for it are closed. I have no idea why developers are so insistent on not offering this option, but it is quite frustrating, considering that search is something I use every few minutes in the email program.

Happy to provide any additional information you might need.

**Comment by Betterbird** [comment]
We're very familiar with the issue. The last conversation we had about it was on a German forum here:
https://www.thunderbird-mail.de/forum/thread/91893-suchliste-automatisch-aufrufen/ (May 2023)
https://www.thunderbird-mail.de/forum/thread/91712-option-um-show-results-as-list-als-default-fur-suchresultate-zu-setzten/ (April 2023).

Here our answer to a support request from October 2022:

On 31 Oct 2022 10:27, Betterbird. Simply better. wrote:
> Hello,
>
> well, one of those bugs, decades old, OK, only 13 years, 50 comments, mostly arguing about why this is not done, in the end, the bug was closed for comments. No product planning, so that even minor issues would eventually get fixed. This is exactly what makes Thunderbird so toxic.
>
> The summary of the bug appears to be: After a global search (Gloda) you want the result as list and not in a faceted view, as if you had clicked "Show results as list".
>
> I've briefly looked at this[1]. Gloda was written by a semi-ingenious software engineer who later abandoned the project. To the remaining TB developers including myself, Gloda is a black box whose internals no one on the team understands; it's basically unchanged ever since the guy left. Consequently it's also not my field of expertise. It would require a significant amount of work and hence some financial incentive. All that just to save one click? The facet view does have some advantages like the statistics it shows.
>
> Sorry that I don't have a better answer.
>
> Kind regards, Jörg.
>
> [1] https://searchfox.org/comm-central/search?q=openTab&path=gloda&case=false&regexp=false
>
> One can see that a glodaFacet tab is opened, when you want a glodaList. However, trying a textual replacement at that point doesn't work, I tried. So if a punctual uneducated change (called "hack") don't yield the desired result, one needs fully understand the code.

We can have another look.

**Comment by mrjovanovic** [comment]
Thank you for this. It is very unfortunate that the Gloda stuff is so complicated. It seems to me perplexing why the faceted view was even included as a default. I can see why it seems as "saving one click", but when it's an action that is done very frequently, it becomes a barrier to using the software. I find myself logging into Outlook web just to search for things, because it's easier. :(

Would it help to set up a bounty for this? Thanks again.

**Comment by Betterbird** [comment]
Searching in TB/BB isn't ideal. I don't use global search (Gloda), I only use folder search and "quick filter" (which is the same code), Gloda is totally different. For "global" search I use `grep` on the raw mail data. The Gloda database kills itself every once in a while and its SQLite file (global-messages-db.sqlite) needs to be removed and rebuild (which isn't fun). And it grows and grows and grows, ...

By all means, set up a bounty/crowd funding. There are other requests that need funding, for example Issue #163, so good to start a test balloon.

**Comment by Betterbird** [comment]
We looked at this a little closer. So you must open the facet view before you can open the list view. If you set the new pref `gloda.list.immediate` the list will open immediately, no click required. Shipping in BB 115.0b6-bb5 in a few minutes with TB 102.13.0 to follow next week.

What's happening to the bounty/crowd funding? Right: Why pay when you can get it for free 😉.

**Comment by Betterbird** [comment]
Made it even better, pref values:
```
0 - Open facet view
1 - Open facet view and list view
2 - Open list view only (closing facet view)
```

**Comment by mrjovanovic** [comment]
Wow, you are truly amazing! A bug that's been sitting there for 13 years, and now fixed. Thank you, from the bottom of my heart!

**Comment by Betterbird** [comment]
It's a bit of a hacky fix, but sometimes that is required. You know our motto, right?
https://www.betterbird.eu/media/img/tb-bb-comparison-800px.jpg

I was in to minds how to name the pref:
`gloda.list.immediate` with values 0, 1, 2 as described above. Or `gloda.result.view` with values 1, 2, 3 for facet, both, list. But in case of "both", the list tab is focused, so is sounds more like a "list immediate" functionality.

Are you a designer? Do you have an opinion?
