### ISSUE TITLE
arch gnome default mail program

### ISSUE THREAD

**Issue by Tealk** [Betterbird/thunderbird-patches#17]
hi,

i downloaded betterbird from the website and created a desktop link in /opt and can work with it now so far. But how can I set it as a default mail program because it is not selectable in the settings.

**Comment by Betterbird** [comment]
Thanks for getting in touch. I'm afraid, the question goes beyond the scope of the project. We ship pretty much the same .tar.bz2 as Thunderbird does. How the respective distributions integrate it into their desktop/launcher is a different issue. Maybe the Arch distro offers some insights here?
https://aur.archlinux.org/packages/betterbird-bin/

**Comment by Tealk** [comment]
but as you can see the version there is outdated
`1 aur/betterbird-bin 91.3.2_bb21-1 (+1 0.68) (Out-of-date: 2021-12-04) `

**Comment by Betterbird** [comment]
Yes, outdated, but not by much. They usually pick it up quickly, they haven't caught up with the release late last Friday.
https://www.betterbird.eu/downloads/Previous%20releases/betterbird-91.3.2-bb21.en-US.linux-x86_64.tar.bz2 works.

**Comment by Tealk** [comment]
because you move the old versions into a subfolder aur can not handle it

**Comment by Betterbird** [comment]
I understand, but we can't let all old releases pile up in the same directory. For now you'd have to modify whatever is downloading it. Or ping the maintainer.

**Comment by Tealk** [comment]
maybe you and the aur creator can agree on a joint approach?

**Comment by Betterbird** [comment]
I'd love to. But I don't know the guy. I noticed that Arch picked it up. OK, I'll see whether I can get hold of him.

**Comment by Tealk** [comment]
thank you for the support
