### ISSUE TITLE
Linux Appmenu / Global Menu support  version

### ISSUE THREAD

**Issue by Kandelai** [Betterbird/thunderbird-patches#171]
I am currently an Arch Linux user using KDE desktop, and love this application. Would it be possible to create a 'betterbird-appmenu' version that supports global menus? I know XFCE and Budge DE also has the ability for global menus. It is probably the only thing keeping me from transitioning from Thunderbird to Betterbird.

**Comment by Betterbird** [comment]
We've decided against AppMenu, see Issue #32. If you want to contribute to it, we're happy to hear about it.

**Comment by Betterbird** [comment]
We'll look into it some more in Issue #297.

**Comment by Betterbird** [comment]
This was implemented in Issue #297, test build available.
