### ISSUE TITLE
Add "embossed" horizontal separator between menu bar and toolbar

### ISSUE THREAD

**Issue by eyalroz** [Betterbird/thunderbird-patches#176]
I'm using BB 115.0-bb6. I'm pleased that you switched the vertical positioning of the menu bar and the (somewhat butchered) toolbar.

What I'm missing, though, is the embossed line that separates the two. Now, I know that such a line proper was missing already in TB 102 / BB 102, but - the toolbar and menu bar had slightly different shading, so it wasn't completely horrible:

![bb_menubar](https://github.com/Betterbird/thunderbird-patches/assets/8672255/a403b3c6-4b3b-4b0d-b1f3-27e78c3911ce)

still, the people want a proper separator between the menu bar and the toolbar, looking like a groove in a surface, like we used to have:

![shot4](https://github.com/Betterbird/thunderbird-patches/assets/8672255/8c11fe8e-f4d7-4316-bcfe-bf45c8bb22ac)

**Comment by Betterbird** [comment]
Please do this with userChrome.css:
```
#toolbar-menubar:not([autohide=true]) ~ unified-toolbar #unifiedToolbar {
  border-top: 2px dotted grey;
}
```
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/67940a42-36a8-4ead-9257-641d90d1809e)

There are many CSS effects to choose from, see: https://www.w3schools.com/css/css_border.asp

Or you can style menu bar or unified toolbar with a darker background.

We're not imposing anything on the user, but it looks like the old feel of the UI won't be restored.
