### ISSUE TITLE
Restore support for forcing message charset

### ISSUE THREAD

**Issue by eyalroz** [Betterbird/thunderbird-patches#178]
With BMO [bug 1713786](https://bugzilla.mozilla.org/show_bug.cgi?id=1713786), TB stopped allowing overriding the message charset, claiming that their auto-detection is absolutely perfect and flawless.

Well, it isn't. Not to mention how a message is not necessarily limited to content in a single charset. And thus, my extension - BiDi Mail UI - is broken in its charset misdetection correction capability since TB v91. 

I am assuming that the underlying ability was not really sabotaged all the way. If that's the case - that could help my extension  fix a bunch of charset issues which currently it is not able to - and it would only be able to do that with BetterBird :-)

Caveat: The prevalence of charset issue is now relatively low, and is decreasing with time (and wider adoption of UTF charsets).

**Comment by Betterbird** [comment]
> I am assuming that the underlying ability was not really sabotaged all the way.

Sadly a wrong assumption. The so-called "mail charset" that you could set has been totally removed, all that happens now is that some "auto-detect" flag is passed down to the lower layers.

Without a huge effort that can't be reinstated.
