### ISSUE TITLE
[Suggestion] Don't hide this repo on your project page

### ISSUE THREAD

**Issue by frostworx** [Betterbird/thunderbird-patches#18]
Imho you should link to this project page directy on the front of your project page
and as well at the very top of the download page.
Imho this would look and feel far more serious.

**Comment by Betterbird** [comment]
It's been discussed to mention this GitHub repository more prominently on the project's home page at www.betterbird.eu.

We were just adding a few links, so we added this on now as well. I hope you like it. We don't consider it necessary on the downloads page which is essentially a (smart) directory listing (thanks to https://github.com/halgatewood/file-directory-list).

**Comment by frostworx** [comment]
Wow, you're fast! Thank you for accepting my suggestion! 👍

**Comment by Betterbird** [comment]
You're the second one to suggest it, plus, we were just adding some links when the request came it. Call it synchronicity.
You need to read that the tr*lls at Reddit wrote:
_Looking at their Github, they only have a bunch of patch files and miscellaneous scripts._
LOL.

**Comment by frostworx** [comment]
Those trolls are unfortunately everywhere - no nice time we live in...
I found _(and commented)_ your project on reddit as well btw, but fortunately [on a troll free sub](https://www.reddit.com/r/Boiling_Steam/comments/r8ru62/betterbird_a_finetuned_version_of_mozilla/).
I haven't tested/used your fork very much _(apart from the bit I commented)_, but thanks for your great work!
