### ISSUE TITLE
RPM/DEB packages

### ISSUE THREAD

**Issue by commandline-be** [Betterbird/thunderbird-patches#180]
Looking at the feature table i was ready to install BetterBird.
Providing RPM/DEB packages would greatly help BetterBird adoption.

Please consider having Betterbird accepted for packaging by major distros.

DEBIAN (WORLD)
UBUNTU (US)
REDHAT (US)
SUSE (EU)

**Comment by Betterbird** [comment]
Isn't this the same at issue #80? We've considered it, but we're not going to provide those packages. If the maintainers of the respective distributions what then, they can create them.

**Comment by Betterbird** [comment]
Closing this since it's already covered by issue #80.
