### ISSUE TITLE
Lack of string localization in Italian

### ISSUE THREAD

**Issue by topoldo** [Betterbird/thunderbird-patches#181]
Hi all!
I downloaded and applied the Italian language pack to Betterbird 115.0.1.
At the moment I found a string which is not translated.
If you set a "master" password, when you start Betterbird, before the main window appears, a pop-up window  appears requiring the password. As reported below, while TB translates correctly into Italian the content of this pop-up window, this does not happen in Betterbird.

Thunderbird

![Thunderbird](https://github.com/Betterbird/thunderbird-patches/assets/9356777/28d27830-d89f-4b56-b0bf-8a7be6bee033)

Betterbird

![betterbird](https://github.com/Betterbird/thunderbird-patches/assets/9356777/55b87e4c-ed3e-4305-a5ac-50babe2c2c54)

Thanks for the attention
Topoldo

**Comment by Betterbird** [comment]
If you cancel the prompt and wait for the next one, you get this:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/aa0e09fe-578e-4d6e-b7e9-2b7b411b41bf)

Still the button isn't translated.

You were using a localised version of TB, not a language pack, correct?

Please try an English version of TB with the Italian language pack, you will find the same issue. It looks like the panel launches so early that the language pack wasn't loaded/applied yet. Likely the problem won't exist when we launch a localised version of BB.

If the test with TB and Italian language pack gives the same result, please file a bug for Thunderbird.

**Comment by topoldo** [comment]
I'm giving to Betterbird an initial browse. For diferent reasons I cannot test the TB localization package, but I have no reasons for not trusting you.
Cheers,
Leopoldo aka Topoldo

**Comment by Betterbird** [comment]
Thunderbird malfunctions in the same way, this is TB with an Italian language pack:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/44487d67-43eb-4349-a673-acf8269854b4)

A fully localised version of Betterbird shows this:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/8127a69c-b63d-4d3e-b496-d405c6384451)
You can download the installer here:
https://www.betterbird.eu/downloads/115-Preview/betterbird-115.0.1-bb7.it.win64.installer.exe

Finally, we filed a bug for TB: https://bugzilla.mozilla.org/show_bug.cgi?id=1846062

If you set pref `security.prompt_for_master_password_on_startup` to false, you won't get the initial password prompt and when the prompt appears later, it should be localised.
