### ISSUE TITLE
TB icon instead of the BB one on TitleBar

### ISSUE THREAD

**Issue by topoldo** [Betterbird/thunderbird-patches#182]
Hi all!
I have the titlebar activated both in TB and in BB.
What I noticed is that the icon on BB Title bar is still the TB one as reported in the image below

![TitleBar](https://github.com/Betterbird/thunderbird-patches/assets/9356777/62d46401-3ec8-42de-a68a-9cfbbff45b3a)

Tnx
Leopoldo aka Topoldo

**Comment by Betterbird** [comment]
This is not a screenshot of Betterbird. Betterbird doesn't have the menu 
bar underneath the toolbar.

In Betterbird, you can force a different program icon as described here:
http://www.betterbird.eu/expert-tips/index.html#custom-icons

If this were happening in BB, you somehow put the TB icon into the 
location described and would have to remove it so BB's own icon is used.
