### ISSUE TITLE
message counters in status bar not refreshed upon switching between different tabs

### ISSUE THREAD

**Issue by tibitts** [Betterbird/thunderbird-patches#183]
BB 115.0.1-bb7 on Linux
I'm running BB with multiple tabs open: mail, news, chat, RSS feeds. The tab selected after starting BB is the mail tab (inbox folder). The 'Unread' and 'Total' counters in the status bar are showing correct values.
Switching to the RSS tab, the 'Unread' and 'Total' counters are not refreshed, and still show the values for Inbox. Selecting another feed, and going back to the original one will refresh the counters.
Going from the RSS tab to the news tab, the counters are not refreshed either. In fact, for news, they are not refreshed at all, even when selecting a different newsgroup. Instead the last value for the RSS feed is shown all the time in the news tab.
Going back to the mail tab, the counter can be refreshed by selecting a different folder, and then selecting the original one again.
Status bar counters in different types of tabs should be refreshed upon switching to a different tab.

**Comment by Betterbird** [comment]
Thanks for the report. We'll get it fixed in the next release.

**Comment by Betterbird** [comment]
We have a pre-release of 115.1.0-bb8 now, but only for Windows. The other platforms will have to wait until TB finalise their 115.1.0, likely on 1st of August 2023.

**Comment by tibitts** [comment]
With the pre-release of 115.1.0-bb8 on Windows the counters look good now. Thanks for the quick fix.

**Comment by Betterbird** [comment]
Thanks for testing. Since we advertise he feature on our front page, it just had to be made to work quickly. Besides, it was an easy enough fix.
