### ISSUE TITLE
BB102.14 > Import TB-Profile: Addons not imported

### ISSUE THREAD

**Issue by RalfRoemling** [Betterbird/thunderbird-patches#186]
Just stubled over BB and like it very much. When Importing the profile from TB though, the installed addons are not available in BB. Is this a bug or intended behaviour?

**Comment by Betterbird** [comment]
Please don't file support requests as GitHub tickets.

Import is defective, refer to our support page on how to do a correct 
switch.

We don't know whether import is meant to import add-ons, according to 
your description, it doesn't appear to be the case. Technically it would 
also be difficult to import add-on settings.

**Comment by RalfRoemling** [comment]
Sorry, I didn't think it to be a support-issue, but a bug, but you're right.

I don't think I'm the only one who overreads the warning. Maybe you should put it above the "Betterbird uses Thunderbird's profile directory and contained profiles for easy switching:"?
