### ISSUE TITLE
"> <" at the beginning of a line hides the rest of the message

### ISSUE THREAD

**Issue by markrousell** [Betterbird/thunderbird-patches#188]
Occurs in: Betterbird 102.14.0-bb39 (64-bit)
I have searched in Mozilla's Bugzilla but have not been able to find a matching report.

I received an email with this exact text in it:
```
> Yup, this is just a matter of altering the CSS. Take a look at the 
> <style> section and you should be able to do that.
```

Everything downwards from the line beginning with "> <style>" was hidden, including the line itself.

**Comment by markrousell** [comment]
I have tested with the same email message in Thunderbird 102.14.0 and the bug does not occur.

**Comment by Betterbird** [comment]
Please attach the message in question. We tried to construct one (attached) based on your description and it displays fine.
[github188.zip](https://github.com/Betterbird/thunderbird-patches/files/12273686/github188.zip)
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/50a37d8e-b615-4053-a140-23aa4b13e807)

**Comment by markrousell** [comment]
Whilst there is nothing terribly sensitive in it, I don't want to post a private email here in public. I'd be happy to send it to you privately though. If you'd be ok with that, let me know where you'd like me to send it.

**Comment by Betterbird** [comment]
Yes, please send it as attachment or ZIP to our support address (support @ ...).

**Comment by markrousell** [comment]
Message now sent from markr@signal100.com. It contains the actual full message and a screenshot showing how it appears in Betterbird.

**Comment by Betterbird** [comment]
Thanks for the data sample. It display fine here:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/ab00f773-5fbf-427e-bcc5-90e4b40026c9)

When you say that it works in TB, you're not running TB on the same profile or folder, right?

This looks like a typical case of inbox corruption for whatever reason. So please regenerate the message database by repairing the folder. Or for a quick check, move or copy that message to a different folder.

**Comment by markrousell** [comment]
Ah, I have found the cause: It is the 'Render Markdown Messages' add-on v1.1.0. When the add-on is enabled the message is truncated as described and when the add-on is disabled the message is shown correctly.

I'll take up the issue with the add-on author.

Apologies for troubling you with this and thank you for your very speedy response. I'll remember to disable add-ons before issuing a report next time I have a problem. :-)

**Comment by Betterbird** [comment]
Well, we've heard "works in TB, doesn't work in BB" so many times, and in 98% of cases the report was wrong, users were comparing apples with pears, that is, other profile or other circumstances.
