### ISSUE TITLE
Return-Receipt-To should not send a read receipt

### ISSUE THREAD

**Issue by M66B** [Betterbird/thunderbird-patches#19]
The *Return-Receipt-To* header represents a delivery request, not a receipt request.

**Comment by Betterbird** [comment]
This issue exists in Thunderbird, so please file a ticket at https://bugzilla.mozilla.org/. See https://www.betterbird.eu/support/

As a first step, we suggest to install the current ESR 91 version of Thunderbird in parallel and see whether the issue exists there. If so, it's a good idea to check whether a bug has been reported already at Bugzilla. If the issue only exists in Betterbird, please contact us immediately and we will endeavour to get a fix to you as soon as possible. Or you can file an issue at our Github repository. If the issue exists in Thunderbird, regardless of whether it has been reported at Bugzilla or not, you can contact us and we can check how hard it would be to fix the issue.

Additionally, this was discussed at length with the reporter in private messages. Return-Receipt-To is not meant to be transmitted to the recipient's MUA, it is sent by the senders MUA to the MTA which in turn should sent a delivery notification upon successful delivery.

Maybe the TB's strategy is that is that header ever arrives, although it shouldn't, it will be processed as Disposition-Notification-To which is used to request read receipts.
