### ISSUE TITLE
Feature request: hide to systray instead close app

### ISSUE THREAD

**Issue by Katarn** [Betterbird/thunderbird-patches#190]
Good afternoon.

It would be nice to have the option that allows when you click on the cross to close the application, instead of closing it, it minimizes to the system tray.

**Comment by Betterbird** [comment]
There's an add-on for that that work with "minimise to tray":
https://addons.thunderbird.net/en-us/thunderbird/addon/minimize-on-close/

**Comment by Katarn** [comment]
Really. Thank you.
