### ISSUE TITLE
Where's "userChrome.css" in the portable (windows) ?

### ISSUE THREAD

**Issue by shula** [Betterbird/thunderbird-patches#193]
My setup:   BetterBitd 115 (Portable), Windows 10
There's nothing "betterbird" in %AppData%, bc a portable app's data is self-contained in the app's directory.

I added "crhome" to the "Profile" dir:  `d:\programs\betterbird\profile\chrome\userChrome.css`
I retarted BBd completely,
But there's no effect on the interface.

The CSS i'm trying is:   `#mail-notification-top{ display: none; }`

ARe there other location for userChrome.css?

p.s. This is the notification I try to hide. Taking real-estate, and SUPER annoying:
![image](https://github.com/Betterbird/thunderbird-patches/assets/124651/cec38558-8daa-47b5-9348-e60c6d6364c7)

**Comment by Betterbird** [comment]
Please **DO NOT** file support queries as GitHub tickets.

userChrome.css goes into the chrome directory in your profile, also for a portable profile, You need to enable it as documented widely. for example on the second last line of https://www.betterbird.eu/expert-tips/ or in https://www.betterbird.eu/expert-tips/userChrome-115.css, 2nd line.
