### ISSUE TITLE
Create GitHub releases

### ISSUE THREAD

**Issue by SuperSandro2000** [Betterbird/thunderbird-patches#196]
I am packaging Betterbird for NixOS and creating GitHub releases would allow me to watch them and receive notifications when new release are out. Right now I need to check the tags manually, so releases are often missed or only noticed after a few days or weeks.

**Comment by Betterbird** [comment]
Hmm, can't you watch tags? Anyway, we have a mailing list notifying the people who are interested. Based on Issue #138 we had added @doronbehar to the list and he told us he's not involved any more. So please get in touch via e-mail and we'll add you. Oh, you have a published e-mail address. We'll add that. Currently we have 102.15.0-bb40 and 115.2.0-bb10 "refresh".

**Comment by SuperSandro2000** [comment]
> Hmm, can't you watch tags?

nope, github is only offering those things:

![image](https://github.com/Betterbird/thunderbird-patches/assets/7258858/1906e557-05cf-4bd1-b85b-d4f163cb8afd)

> So please get in touch via e-mail and we'll add you. Oh, you have a published e-mail address. We'll add that.

That should work, too. Thanks

**Comment by Betterbird** [comment]
I wonder how the other "packagers" follow the activities. Anyway, BB follows TB releases and they follow FF releases and they are documente here:
https://whattrainisitnow.com/calendar/ formerly at https://wiki.mozilla.org/index.php?title=Release_Management/Calendar.
As you can see, there is a release about every four weeks with 115.3 coming up on Tuesday, 26 Sept 2023. Looks like there will be a 115.2.1 on 14 Sept 2023. The 102 series already had it's last release 102.15.0 and unless some security issue comes up, there will be no 102.15.1.

Anyway, you'll be on the mailing list for any release activities. You can also add the FF .ics file to your calendar.

**Comment by SuperSandro2000** [comment]
Thanks for tall the infos.
I am not planning to follow releases that closely :)
