### ISSUE TITLE
Task Reminder Improvement

### ISSUE THREAD

**Issue by infinitelyintrigued** [Betterbird/thunderbird-patches#201]
Hi, I would like to see a couple of improvements in the task reminder dialog box.

1. Completed button. Right now, I can only postpone or dismiss. Dismissing does not change the task status to "completed." I have to switch to the task pane to set it complete. (In Outlook I can right-click the task in the reminder dialog box and change the status to "completed", but a button is better, or at least a pull-down option between Dismiss and Completed.)

2. Custom postpone time periods that are always available. I would like to be able to create "90 minutes", "next Monday", etc.

**Comment by Betterbird** [comment]
We have very little expertise in the Calendar area, so this will likely 
not be actioned.

Why don't you file an enhancement request for Thunderbird?

**Comment by infinitelyintrigued** [comment]
OK. Thank you.
