### ISSUE TITLE
Problems with the Filter Log window

### ISSUE THREAD

**Issue by kiki-ja** [Betterbird/thunderbird-patches#203]
Problems with the Filter Log window.

Bettetbird 115.2.1-b11 (64bit)
Windows 10 Pro 22H2 (64bit)

Steps to reproduce:
Click the 'Filter Log' button of the Message Filters.

Actual results:
Click the 'Filter Log' button of the Message Filters.
The log space in the Filter Log window is closed.

Expected results:
The log is displayed in the Filter Log window.

Not reproduced in Thunderbird 115.2.2 (64bit) + Windows 10 Pro 22H2 (64bit).
Is this problem a bug?

[Steps to reproduce:]
![Message Filters](https://github.com/Betterbird/thunderbird-patches/assets/80428201/127a0eab-4cf7-498b-92fc-b23d774d7ee7)

[Actual results:]
![Problem Cases](https://github.com/Betterbird/thunderbird-patches/assets/80428201/097cf890-3d08-4396-b24e-3d888d3c00ac)

[Expected results:]
![Correct Cases](https://github.com/Betterbird/thunderbird-patches/assets/80428201/0e203a82-4244-4cd4-ab25-8457dc623c06)

@kiki-ja

**Comment by Betterbird** [comment]
I don't see a problem:

![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/45502843-041e-4aa1-9579-c3fbbe67d965)

I tried a few profiles, the dialogue was always big enough to show the log content.

**Comment by Betterbird** [comment]
According to the code
https://searchfox.org/comm-esr115/rev/4ba40f4f2bff3ee4f1b33a3a9040ce7a5d6e6037/mailnews/search/content/viewLog.xhtml#16-17
the window has an initial height of 375px. Of course it will shrink if you make is smaller and that small size persists to the next opening.

So just make it big and it will stay big? What problem am I missing?

**Comment by Betterbird** [comment]
We had a lot of discussion in a newsgroup de.comm.software.mozilla.mailnews, some people had the issue, others didn't. See last article here:
http://www.al.howardknight.net/?STYPE=msgid&MSGI=%3C371a3902-8742-4068-85a8-6110c2b052de%40barghahn-online.de%3E

**Comment by Betterbird** [comment]
And TB should behave any different than BB. Does it behave differently on the same profile?

**Comment by kiki-ja** [comment]
Sorry for the late report, but with Betterbird 115.4.0-b16 this problem is no longer reproduced.
It is unclear why it has returned to normal.

Please close this issue.

@kiki-ja

**Comment by Betterbird** [comment]
Thanks for the feedback.

**Comment by fakeologist** [comment]
The log window always starts off not showing the log window.
It's not clear it needs to be expanded to show the window.
Can it not default to show the log?

**Comment by fakeologist** [comment]
![image](https://github.com/Betterbird/thunderbird-patches/assets/66537018/3d9c5fc5-8738-4569-a213-c7167154aebc)

**Comment by fakeologist** [comment]
![image](https://github.com/Betterbird/thunderbird-patches/assets/66537018/891603e7-4aff-46a1-9a3c-4cf6b315dfdb)
what it should look like on open.

**Comment by Betterbird** [comment]
Well, yes, if you read the ticket you'll see that his is not reproducible. The manual fix is to open xulstore.json in your profile in an editor and delete this entry `"chrome://messenger/content/viewLog.xhtml":{"viewLogWindow":{"width":"871","height":"841","screenX":"-258","screenY":"-30"}},`. This is a JSON file, if you don't delete it correctly and cause a JSON syntax error, you'll lose everything stored in the file, that is all UI settings, window sizes, etc.
