### ISSUE TITLE
Activation via system tray click for older systrays like trayer

### ISSUE THREAD

**Issue by Betterbird** [Betterbird/thunderbird-patches#208]
In https://github.com/AyatanaIndicators/libayatana-appindicator/pull/71#issuecomment-1741638469 it was suggested to add this code:
```
 static void
 status_icon_activate (GtkStatusIcon * icon, gpointer data)
 {
+    AppIndicator *app = APP_INDICATOR(data);
+    g_signal_emit(app, signals[ACTIVATE_EVENT], 0, 0, 0);
+
     GtkMenu * menu = app_indicator_get_menu(APP_INDICATOR(data));
     if (menu == NULL)
         return;
```
Let's see what blows up when we do.

**Comment by Betterbird** [comment]
Build with this patch:
www.betterbird.eu/downloads2/betterbird-115.3.1.en-US-bb14-additional-activation.linux-x86_64.tar.bz2

@Narthorn: No need for you to try this build since it should be the same you compiled yourself.
@dark-penguin, @Zahrun, @felixoi: could you please check the build to confirm that nothing broke? I didn't see a change in behaviour on Xfce.

[activation.patch](https://github.com/Betterbird/thunderbird-patches/files/12775338/activation.patch)

**Comment by dark-penguin** [comment]
You are not supposed to see a change - as I understand, this fixes the non-SNI behaviour.

On Mate, what blows up is it no longer processes tray icon clicks with my `enable-sni-support` fix (why?? Does this inadvertently modify the old behaviour?). However, it does process clicks _without_ that fix - both left-clicking and right-clicking the icon restore the window!

**Comment by Betterbird** [comment]
So we go with this fix and remove the `gsettings set org.mate.panel enable-sni-support true` from the documentation?

**Comment by dark-penguin** [comment]
Yes!

Oh, by the way, SNI support being broken is a user error on my part - it works just fine too. I've simply found another bug, and got confused.

**Comment by dark-penguin** [comment]
We can also add MATE tray icon support by default now if we haven't yet. It is now just as first-class as everything else.

**Comment by Betterbird** [comment]
Well, let's have the KDE and Gnome people check it first. Maybe it even works on Cinnamon now. Also, I'd need to ship the new version first.

**Comment by dark-penguin** [comment]
I did the testing - I was curious about Cinnamon, for which we don't have a "designated tester", and I already have a KDE machine ready.

On KDE, clicking the icon works the same as before.
On Cinnamon... it seems to behave the same as before: clicking the icon shows a tiny empty menu. Does not do anything about the window.

I actually don't understand what that code with an empty menu is doing. Is it a workaround for something?

Also, I believe it would be closer to "proper code" if it was either
```
  AppIndicator *app = APP_INDICATOR(data);
  g_signal_emit(app, signals[ACTIVATE_EVENT], 0, 0, 0);

- GtkMenu * menu = app_indicator_get_menu(APP_INDICATOR(data));
+ GtkMenu * menu = app_indicator_get_menu(app);
```
or
```
- AppIndicator *app = APP_INDICATOR(data);
- g_signal_emit(app, signals[ACTIVATE_EVENT], 0, 0, 0);
  g_signal_emit(APP_INDICATOR(data), signals[ACTIVATE_EVENT], 0, 0, 0);

  GtkMenu * menu = app_indicator_get_menu(APP_INDICATOR(data));
```
although I don't know enough to be sure I'm not missing anything and the second part would even work.

**Comment by Betterbird** [comment]
Huh? Look at the patch:
```
 static void
 status_icon_activate (GtkStatusIcon * icon, gpointer data)
 {
+    g_signal_emit(APP_INDICATOR(data), signals[ACTIVATE_EVENT], 0, 0, 0);
     GtkMenu * menu = app_indicator_get_menu(APP_INDICATOR(data));
     if (menu == NULL)
         return;
```
which is your "second part". `APP_INDICATOR(data)` is just a cast or some accessor.

**Comment by dark-penguin** [comment]
Oh, I did not look at the actual patch - I've only seen the proposed one. So yeah, you've already done that. :)

**Comment by Betterbird** [comment]
So this one is done.

**Comment by felixoi** [comment]
You tested GNOME already, right? Was not available the last days, sorry. The download link is not available anymore.
