### ISSUE TITLE
Deactivation the multiline Layout not working

### ISSUE THREAD

**Issue by Posi81** [Betterbird/thunderbird-patches#21]
The activation for the multiline layout works great. But the deactivation does not work. It will be still activated.

**Comment by Betterbird** [comment]
https://www.betterbird.eu/expert-tips/
To enable it, deselect the subject column in the column picker of the message list/thread pane for a particular folder. There is also a global option View > Layout > Multi-line View On All Folders. Once you enable the global option, all folders will show in multi-line view. If you disable the global option, to need to re-enable the subject column on the folders where you no longer wish to the use multi-line view.
