### ISSUE TITLE
TB 500762 - Marking parent folder read should also mark subfolders (Feature request)

### ISSUE THREAD

**Issue by spiffikins** [Betterbird/thunderbird-patches#211]
This request was made 15 years ago to Mozilla, and never implemented.
For a while we had an add-on, MarkSubfoldersRead that worked - but the add-on stopped working several years ago, with the upgrade to 68.4.1

Would really appreciate if you could consider implementing this!

**Comment by Betterbird** [comment]
This one is easier than Issue #210. Can you offer any incentive?

**Comment by spiffikins** [comment]
For my purposes, if I had this, I don't need #210 nearly as much!  

My use case is that I have dozens of nested folders, and message filters that move emails into those folders daily.  Being able to click on the top level folder, or even one a couple levels down, and say "mark subfolders read" - would save me from having to open the whole tree up, and select every folder and then say "mark folders read"

Personally I've always felt like the default behavior of "mark folder read" would be to mark EVERYTHING in the selected folder - including other folders - as read.  I don't understand the existing behavior - but I accept that at this point people are used to it so I'm on board with adding another menu option to do this, rather than changing the existing behavior of that menu option.

**Comment by christiansacks** [comment]
You can do this in thunderbird with the keyboard shortcut shift+c

Just click the parent folder first then the shortcut key and it just works.

**Comment by spiffikins** [comment]
I just tried this  - shift+C marks items in the selected folder as read, it
does nothing for any items in subfolders.

**Comment by Betterbird** [comment]
Shift+C is on the menu, it's "Mark All Read", not operating on subfolders.

**Comment by calabar77** [comment]
I fully support this request. 
Add a menu voice next to the present one to mark the folder and its subfolder as read would be perfect for me. 
I use thunderbird, but this feature would persuade me to switch to betterbird, it's lack is so uncomfortable.

**Comment by Betterbird** [comment]
> I fully support this request.

See https://github.com/Betterbird/thunderbird-patches/issues/211#issuecomment-1753475693. Can you offer an incentive and sponsor the work?

**Comment by RealRaven2000** [comment]
For what it's worth, my [Add-on QuickFolders](https://addons.thunderbird.net/thunderbird/addon/quickfolders-tabbed-folders/) supports this command:

![image](https://github.com/Betterbird/thunderbird-patches/assets/6314674/8875a871-98d9-4f64-ab61-b5285e4db5bb)

just use the navigation bar and right-click it, command should be on the top.

**Comment by spiffikins** [comment]
> > I fully support this request.
> 
> See [#211 (comment)](https://github.com/Betterbird/thunderbird-patches/issues/211#issuecomment-1753475693). Can you offer an incentive and sponsor the work?

What does sponsoring the work entail, specifically?

**Comment by Betterbird** [comment]
Hmm, I'm surprised that the term "to sponsor a bug (fix)" is hard to understand. It means to pay the developer.

**Comment by Betterbird** [comment]
From the next release you can press `Shift+"Mark Folder Read"` to mark a folder and it's sub-folders read.

<sub>Side note: If we wanted to wait for funding, we could shut down the project. The people who come and ask for enhancements usually don't pay, luckily there are other happy users who do. Let's see whether you get free treatment at your doctor or a free consultation at your lawyer next time.</sub>

**Comment by Betterbird** [comment]
@spiffikins: The very least you can do it post to https://bugzilla.mozilla.org/show_bug.cgi?id=500762 that this was implemented.
