### ISSUE TITLE
Improve install and task exiting

### ISSUE THREAD

**Issue by gunamoi1** [Betterbird/thunderbird-patches#216]
Just installed latest "betterbird-115.4.0-bb16.en-US.win64.installer.exe" on Windows 10.

1) Did not find existing Thunderbird profile.
So per FAQ page I had to find BetterBird program folder, open a cmd window, and type "betterbird -p" to let me choose the existing Thunderbird default profile.
When installing, it allows to start BetterBird app, would it be difficult if this automatically ran "betterbird -p", or maybe a checkbox on the installer so it can run "betterbird -p" if user has existing Thunderbird?

2) Couldn't switch directly back to Thunderbird, as FAQ says should be able, because Thunderbird complains Thunderbird already running.
But it was not, in fact there was a BetterBird task still in memory which I had to use task manager to End Task before I could open Thunderbird.
This appears to happen consistently, every time I open Betterbird, then close the program, a Betterbird task is left running.
Need to fix this so when program is closed all tasks are closed!!!!!
Having to manually run task manager and end Betterbird tasks every time is not good.

**Comment by Betterbird** [comment]
1. Betterbird uses the exact same profile management that Thunderbird and Firefox use. A new installation into a different location creates a new profile. Switching to an existing profile is reasonably easy, see https://www.betterbird.eu/support/index.html#switch-tb-bb.
2. Apparently the BB process doesn't close. That's called a shutdown hang and needs to be debugged. Usually there is some IMAP action that doesn't complete, like for example, cleaning out the trash on a (doubtful) Yahoo account, we had that happen ourselves. You can set pref mail.biff.show_tray_icon_always to have a permanent system tray icon and to check when the process exits.

Sorry for the bad experience, but there is nothing we will do for 1. and nothing we can do from a distance for 2. If you start TB on the profile, it will likely also hang at exit.

**Comment by gunamoi1** [comment]
Thanks for the reply.
1) There are likely to be more people switching from thunderbird to betterbird than from betterbird to thunderbird, so I just suggested adding an option to automatically run betterbird "-p" would make things easier for those users.  You will not do this, fine that is your choice.
2) When I close thunderbird, all related instances and processes disappear from the task manager, it NEVER leaves any hanging processes.  When I run betterbird on the exact same profile, it ALWAYS leaves one or more processes hanging in the task manager after it closes. Now this is a new install, so maybe there are some special betterbird options that I have not set, assuming that it would be compatible with thunderbird as advertised. Or maybe one of the add-ons that works fine on thunderbird is not compatible with betterbird. Anyway, betterbird doesn't look better at this point. You can keep the donation. I will not be keeping betterbird.

**Comment by Betterbird** [comment]
Re. 2.: TB and BB on the same profile should behave exactly the same, there are no special BB option. This is also the first time I hear about that shutdown hang. To investigate this, I'd need information of your setup. I have various profiles with POP3 and IMAP accounts, mostly using pref mail.biff.show_tray_icon_always so I can see when the last process goes away. Apart from the Yahoo "empty trash on exit" case, I've never seen a delayed exist.

As for your donation: I can refund it, but I'd need to be able to associate it with "Gunamoi Software".
