### ISSUE TITLE
GPO Settings

### ISSUE THREAD

**Issue by gotspatel** [Betterbird/thunderbird-patches#218]
Hello,

is Windows Server GPO supported for use in RDP Environment especially the below,

1. default server settings
2. default location of profile folder
3. default location of data folders
4. default Add-ons installed for all user profiles
5. default signature 
etc.

asking here as didn't find any information above the same.

TIA

**Comment by Betterbird** [comment]
Well, BB behaves the same as TB in this regard, only that we don't have an MSI or MSIX installer (yet).

Further reading on TB enterprise support here:
https://www.thunderbird.net/en-US/organizations/ (glossy)
https://enterprise.thunderbird.net/ (still glossy)
https://enterprise.thunderbird.net/deploy (getting useful)
https://enterprise.thunderbird.net/manage-updates-policies-and-customization (also useful).

Please contact our support if you're planning a wider enterprise deployment.
