### ISSUE TITLE
Tray icon on Gnome only works if used through XWayland

### ISSUE THREAD

**Issue by piekay** [Betterbird/thunderbird-patches#221]
Expected Behavior: a tray icon appears when the option: "minimize to tray" is enabled

Real-World behavior: when enabling minimize to tray on the native Wayland version it behaves like the option isn't selected and neither minimizes to tray, nor displays the tray icon. If I enable always show icon in about:config, then the icon is displayed, but the application still behaves like the option "minimize to tray" wasn't ticked 

OS: NixOS 23.05
Betterbird versions: 102.15.1 and 115.3.2 respectively
Gnome-Shell version: 44.2
 gnome-shell-extension-appindicator version: 53

**Comment by Betterbird** [comment]
Hmm, well, so if you enable "always on", the icon is displayed. Whether it will minimise depends on your desktop. Which desktop are you using? Gnome? Check the documentation:

<html><body>
<h3>System Tray support (Windows and Linux)</h3>
<p>The following is supported:</p>


OS / Desktop | System tray | System tray always | Tooltip with folder list | Minimize to tray
-- | -- | -- | -- | --
Windows | Yes | Yes | Yes | Yes
Linux / KDE | Yes | Yes | Yes | Yes
Linux / Gnome | Yes | Yes | No | Yes(*)
Linux / Cinnamon | Yes | Yes | Yes | No
Linux / Mate | Yes | Yes | Yes | Yes(**)
Linux / Xfce | Yes | Yes | Yes | Yes


<small>"Minimize to tray" on Linux from version 102.5.0 and 115.2.0. 102.5.0 only supports KDE and Gnome.</small>
<p>(*) For Gnome you need to install the "AppIndicator and KStatusNotifierItem Support" extension. Double-click to activate.<br>
(**) The Mate desktop is supported from BB 115.3.1-bb14 build after 2 October 2023.</p>
<p>Relevant preferences:</p>
<ul>
<li>System tray: <tt>mail.biff.show_tray_icon</tt> (has UI)</li>
<li>System tray always: <tt>mail.biff.show_tray_icon_always</tt> (no UI)</li>
<li>Minimize to tray: <tt>mail.minimizeToTray</tt> (has UI)</li>
<li>Linux only: <tt>mail.minimizeToTray.supportedDesktops</tt> ("kde,gnome,xfce,mate") and 
                <tt>mail.minimizeToTray.desktopsGtkWindowPresentWithTime</tt> (special activation, "mate") (no UI)</li>
<li>Start minimized: <tt>mail.startupMinimized</tt> (no UI)</li>
<li>Show new count: <tt>mail.biff.use_new_count_in_badge</tt> (has UI)</li>
<li>Only count unread message in inboxes: <tt>mail.notification.count.inbox_only</tt> (no UI)</li>
</ul>
</body>
</html>

102.15.1 has some of this support, but not all. So please test on 115.4.2.

Maybe issue #214 has some relevant information.

**Comment by mfschumann** [comment]
Are you using the flatpak version of Betterbird? If so, there is a chance that the issue will be fixed in version 115.5.1 which will be published later today.

**Comment by piekay** [comment]
this seems to be an issue with NixOS. I have used it as a side project on a Laptop, but I've switched back to my main OS where this bug doesn't occur. So I sadly can't help with testing, but since this was a niche use case in the first place I guess that this won't happen again

**Comment by 945fc41467** [comment]
Hello,

I have exactly the same behaviour. 

Ubuntu 24.04.4 LTS
Gnome 46
Wayland
Linux 6.17.0-1017-oem
Betterbird 140.10.0esr-bb21 (64 bits) (This is the last Flatpak version, and the only available if I don’t want to recompile).

**Comment by Betterbird** [comment]
You're a bit late to the party. What exactly is _"exactly the same behaviour"_?

**Comment by 945fc41467** [comment]
I mean:

> when enabling minimize to tray on the native Wayland version it behaves like the option isn't selected and neither minimizes to tray, nor displays the tray icon. If I enable always show icon in about:config, then the icon is displayed, but the application still behaves like the option "minimize to tray" wasn't ticked

If I understand well, it is supposed to work when using the minimize button from the app, with window decoration deactivated. That’s ok. But that doesn’t work. It doesn't minimize in the tray.

**Comment by Betterbird** [comment]
Did you read above?

For Gnome you need to install the "AppIndicator and KStatusNotifierItem Support" extension.

@mfschumann, does the mix reported here work for you?

**Comment by mfschumann** [comment]
On my fedora box with Gnome 49, Betterbird 140.10.0esr-bb21 in Wayland-native mode behaves as I am used to: Minimize to tray works via the app's own minimize button. It does not work through the minimize button in the system window title bar, the task bar button, or any other means.

**Comment by 945fc41467** [comment]
By default, Ubuntu install *Ubuntu AppIndicators*, its own fork of *AppIndicator and KStatusNotifierItem Support*. I tried to disabled it and to install and activate *AppIndicator and KStatusNotifierItem Support*. Doesn’t change anything.

**Comment by Betterbird** [comment]
Unfortunately we can't troubleshoot individual problems, especially not on Linux and without access to the machine. The Flatpak maintainer reported it working on Gnome 49, so that's all we can check.
