### ISSUE TITLE
Search for add-ons update not working properly on Win 7

### ISSUE THREAD

**Issue by DenB10** [Betterbird/thunderbird-patches#222]
Hi there,

I'm still on Windows 7 and one of the reasons I migrated from Thunderbird to Betterbird was that the search for add-ons updates didn't work on Thunderbird: no updates found even though I knew for a fact that there were some. On the other hand, the search for updates worked fine on Betterbird bb16.
But since bb17, when I click on the "Check for Updates" button in the add-ons manager, the search is done (possible updates are found) but the message displayed remains stuck on "Updating add-ons" and the search button is disabled (grayed out).

Please let me know if you can reproduce this behavior.
Have a nice day!

**Comment by DenB10** [comment]
Thank you very much

**Comment by Betterbird** [comment]
We'll make a "latest build" available soon.

**Comment by Betterbird** [comment]
https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.4.2-bb17-latest-build5.en-US.win64.installer.exe
Let us know if you need a Linux build. For Mac you'll need to wait for 115.5.0 next week.

**Comment by DenB10** [comment]
No need for a Linux build yet. Thanks again for your responsiveness.

**Comment by DenB10** [comment]
Thanks again, the addition of manual file sorting is much appreciated.
