### ISSUE TITLE
Option to hide the new Toolbar v115

### ISSUE THREAD

**Issue by tobip** [Betterbird/thunderbird-patches#225]
With the last update of Betterbird to v115 there is a Toolbar which is forced into view without possibility to hide.

I tried following these steps to hide it by editing the userchrome.css file:
https://support.mozilla.org/en-US/questions/1418113

Unfortunately this didn't change anything in my case, after restarting Betterbird the toolbar is still there. Am I missing something or are these css commands not working with Betterbird?

**Comment by Betterbird** [comment]
This is not a BB bug and doesn't merit a GitHub ticket. Don't file support requests as bugs.

We don't have time to read support articles with hidden solutions. We did anyway and you may be referring to this CSS:

```
#unifiedToolbar {
  visibility: collapse;
}
```
As per our support pages, there is no free support for individual configuration.

Besides, the unified toolbar is reduced in height in BB.

All that said, the CSS works, apparently you forgot to set pref toolkit.legacyUserProfileCustomizations.stylesheets. Without it, the changes in userChrome.css are not applied.
