### ISSUE TITLE
Run on startup in systray

### ISSUE THREAD

**Issue by kirawi** [Betterbird/thunderbird-patches#226]
Hello, is it possible to run Betterbird on startup in the system tray?

**Comment by Betterbird** [comment]
Set pref mail.minimizeToTray and mail.startupMinimized. Please **read the documentation** before filing a ticket.

**Comment by kirawi** [comment]
Sorry, but it's not obvious where the documentation is located. For example, it is not mentioned in your homepage nor readme.

**Comment by Betterbird** [comment]
Well, web sites are usually organised into multiple pages, not everything is on the home page. Read here: https://www.betterbird.eu/expert-tips/

<html><body>
<h3>System Tray support (Windows and Linux)</h3>
<p>The following is supported:</p>

OS / Desktop | System tray | System tray always | Tooltip with folder list | Minimize to tray
-- | -- | -- | -- | --
Windows | Yes | Yes | Yes | Yes
Linux / KDE | Yes | Yes | Yes | Yes
Linux / Gnome | Yes | Yes | No | Yes(*)
Linux / Cinnamon | Yes | Yes | Yes | No
Linux / Mate | Yes | Yes | Yes | Yes(**)
Linux / Xfce | Yes | Yes | Yes | Yes


<small>"Minimize to tray" on Linux from version 102.5.0 and 115.2.0. 102.5.0 only supports KDE and Gnome.</small>
<p>(*) For Gnome you need to install the "AppIndicator and KStatusNotifierItem Support" extension. Double-click to activate.<br>
(**) The Mate desktop is supported from BB 115.3.1-bb14 build after 2 October 2023.</p>
<p>Relevant preferences:</p>
<ul>
<li>System tray: <tt>mail.biff.show_tray_icon</tt> (has UI)</li>
<li>System tray always: <tt>mail.biff.show_tray_icon_always</tt> (no UI)</li>
<li>Minimize to tray: <tt>mail.minimizeToTray</tt> (has UI)</li>
<li>Linux only: <tt>mail.minimizeToTray.supportedDesktops</tt> ("kde,gnome,xfce,mate") and 
                <tt>mail.minimizeToTray.desktopsGtkWindowPresentWithTime</tt> (special activation, "mate") (no UI)</li>
<li>Start minimized: <tt>mail.startupMinimized</tt> (no UI)</li>
<li>Show new count: <tt>mail.biff.use_new_count_in_badge</tt> (has UI)</li>
<li>Only count unread message in inboxes: <tt>mail.notification.count.inbox_only</tt> (no UI)</li>
</ul>
</body>
</html>

**Comment by kirawi** [comment]
Websites are indeed usually split into multiple pages, however I would not have expected that page to contain documentation. The name suggests an opinionated set of suggestions related to using/configuring Betterbird (what laymen often call "power user" information). I appreciate the link and timely response, and hope to have clarified on the confusion.
