### ISSUE TITLE
Today Pane disappears at random after restart

### ISSUE THREAD

**Issue by xmaromix** [Betterbird/thunderbird-patches#228]
Didn't see this issue in Bugzilla, but randomly my upcoming events on the righthand side of the email inbox window disappears.
Using Windows 11 currently, a shared iCloud read-only calendar. 
On betterbird 115.4.2

It will open back up if I restart thunderbird.

**Comment by Betterbird** [comment]
Some clarification required here.

_"righthand side of the email inbox window"_: You mean the "Today Pane"?
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/31d7da81-79b9-4673-98a5-ae2e8107cb3a)

_"It will open back up if I restart thunderbird"_: Please explain this statement.

**Comment by Betterbird** [comment]
You keep writing "thunderbird". Is that a typo or are you reporting a bug in Thunderbird?

In any case, the today pane state is persisted in xulstore.json with this entry:
```
"today-pane-panel":{"modewidths":"210,200,200,200,200,200","collapsedinmodes":"calendar,chat,mail","width":"210"}
```
if **mail** is present, then the pane is collapsed when a 3pane (mail) tab is shown. For us it's persisted just fine, so after restarte it comes back in the previous state. It's possible that on your system something interferes with persisting the state, but we can't track this down from here.

**Comment by Betterbird** [comment]
Thanks for getting back. Looks like there's nothing we can/will action here. We can still communicate on the close ticket or even re-open it.
