### ISSUE TITLE
Enhancement: in card-view, make "Correspondent" more visually distinct from the Subject

### ISSUE THREAD

**Issue by ahydronous** [Betterbird/thunderbird-patches#232]
See Geary mail for what I mean:

![Screenshot from 2023-12-07 19-14-50](https://github.com/Betterbird/thunderbird-patches/assets/57762816/6eed0067-680d-4cbd-b6b4-f67fcf8f9ab3)

It is just a lot easier on the eyes (especially older ones!) if the sender is more visually distinct from the subject. Perhaps 1-line preview too, when supported.

Currently, Betterbird (and Thunderbird) look like this:
![Screenshot from 2023-12-07 19-23-25](https://github.com/Betterbird/thunderbird-patches/assets/57762816/90d6814b-db91-41af-bc34-df590397d69c)

**Comment by Betterbird** [comment]
You can do that in userChrome.css, for sure.

**Comment by Betterbird** [comment]
Use the inspector to find the CSS that needs changing. We did this:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/8ab4a98e-f502-4f23-b78f-4e4ed7a39a36)

Looks like you want to modify `div.thread-card-row > span.sender` and `div.thread-card-row > span.subject`.

Please get in touch with our support for help. This isn't anything we will do in the product.
