### ISSUE TITLE
Tag coloring in unread emails

### ISSUE THREAD

**Issue by PoisonFrog** [Betterbird/thunderbird-patches#233]
Since I updated to Betterbird 115.5.1 new emails that get automatically tagged by filters do not have the tag color, they have a default white color instead and only display the tag coloring after you read them. I don't know if this is the new default Thunderbird behavior or if this is a Betterbird tweak since I don't use regular Thunderbird anymore, but this made my experience using this email client way worse. Is this a bug? Is there a way to change this using the editor or is reverting to an older version the only way to fix this issue?

**Comment by Betterbird** [comment]
Sounds like Supernova bustage. Please check with TB and file a bug at https://bugzilla.mozilla.org/home. We'll take it from there,

**Comment by PoisonFrog** [comment]
> Sounds like Supernova bustage. Please check with TB and file a bug at https://bugzilla.mozilla.org/home. We'll take it from there,

[Done.](https://bugzilla.mozilla.org/show_bug.cgi?id=1869898)

**Comment by Betterbird** [comment]
Thanks. We just made a release yesterday, so this will take a week or so. In case we make a "latest build" with the fix, for which platform do you need it?

**Comment by PoisonFrog** [comment]
> Thanks. We just made a release yesterday, so this will take a week or so. In case we make a "latest build" with the fix, for which platform do you need it?

I'm using Linux. Still, you don't need to rush it. It's just a bit annoying because I'm used to color organization but I can survive some weeks without this. Thanks.

**Comment by Betterbird** [comment]
I tried it. The rule is: Move message to folder and add tag "Important". Result:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/7f27f885-8b4c-40d9-a4f8-59bc04e87ba6)

So that worked. Which are the (special) circumstances where that fails?

**Comment by PoisonFrog** [comment]
> I tried it. The rule is: Move message to folder and add tag "Important". Result: ![image](https://private-user-images.githubusercontent.com/86832723/290355036-7f27f885-8b4c-40d9-a4f8-59bc04e87ba6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTU3ODIsIm5iZiI6MTcwMjUxNTQ4MiwicGF0aCI6Ii84NjgzMjcyMy8yOTAzNTUwMzYtN2YyN2Y4ODUtOGI0Yy00MGQ5LWE0ZjgtNTliYzA0ZTg3YmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAwNTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNDg0MDgzNWQ0NjFjYTE5YWE1YzJkZGEyY2RhY2ZjNDIwYjA3MmQzOGQ3YzY3ZWY1MGRhZTMwYTIxMGM3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kGRMlrKq69jSjV97BEKEQDfvDpqjg8R3OQXG22d624)
> 
> So that worked. Which are the (special) circumstances where that fails?
> 
> We tested both POP3 and IMAP. The message was always tagged in the message list.

After reading this I was trying to figure out what was wrong with my setup and when I was about to create a new clean profile to test if it would work there it crossed my mind that it could be the theme so I switched to the official theme and it is working as expected now. I was using the Dark Night Arcturus X theme and after I updated Betterbird it messed up the theme or maybe the theme updated in the background around the same time since the development of this theme seems to be quite active and it says it was last updated on December 12, 2023 so maybe the theme update messed up things. Anyways, I'll be sticking to the default theme for now and I'll make sure to take themes into account before reporting an issue next time. Sorry and thanks for helping me solving this.
