### ISSUE TITLE
Unified Folders Mode Inbox slow to update/populate

### ISSUE THREAD

**Issue by Gittyperson** [Betterbird/thunderbird-patches#237]
Hello and thanks for your hard work.

Minor issue, started around 2-3 versions behind the current 115.5.2-bb20 (Windows 10).

Unified Folders mode/Inbox is selected at startup. During initial account checks (all IMAP), the new messages will not appear right away in the Unified Inbox list as they come from the server, but there is a delay of up to a minute. Don't know if it's waiting for all messages checks/indexing etc. to complete, or if something else is going on. Clicking on a single account Inbox and then back to Unified, will usually make the messages appear immediately.

Tried clearing cache and deleting Mail/smart mailboxes folder. Couldn't find something in Bugzilla.

**Comment by Betterbird** [comment]
You should enable online search in the properties of the unified folder. We've recently dropped the default to off a while ago. Reason: for some servers, it became to slow, the app hung and users didn't know where to disable this option. Once you set it, the option will stick:

![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/dd0eb465-e702-45bf-8209-88d3b5f800cd)

**Comment by Gittyperson** [comment]
Thank you. I did miss that, although I am not sure it's the cause. The new messages will just not appear, even though the notification for them has come and gone, so they are already properly downloaded. Click anywhere else then back to Unified Inbox and they will appear instantly.

**Comment by Betterbird** [comment]
I tested it, it works here:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/54258c92-7857-41de-927b-c2f2dd5785ec)
I was in a non-inbox folder when sending the message. When the message arrived, the biff indicator showed immediately on inbox and unified inbox and clicking onto the unified inbox, the message was there.

When in the unified inbox, newly arrive messages show up immediately. I can't detect any malfunction.

If it's also not working in TB, please file an issue at https://bugzilla.mozilla.org/. Apart from the different default value which comes into effect when first creating the unified folder on a new profile (and of course also when you delete "smart mailboxes"), BB has no changes in the area.

**Comment by Betterbird** [comment]
Hmm, I wrote: _When in the unified inbox, newly arrive messages show up immediately. I can't detect any malfunction._

Now I did this: Select the unified folder as startup folder, so it will come up at start. From a different profile, sent a message there. Started BB. It opens to the unified inbox and the message is received into it.

If you have exact steps to reproduce your problem, please send them to our support. This is not the place to handle support cases. If new messages didn't show up in the unified inbox as they should, at a guess, we'd have more cases than just this one here. Also, "started 2-3 versions" ago is not helpful reporting. The TB folks also make changes to the 115 code-base, so if something fails, it needs to be reported immediately.

**Comment by Betterbird** [comment]
In general, IMAP comes with (too) many parameters: There are IMAP servers from different "manufacturers" which all may behave differently, there a a heap of different IMAP settings, there can be network issues, etc. That's why you need to try the scenario with TB and if it reproduces there, file a bug with the TB project. They will likely ask you to provide IMAP logs, etc. The scope of our project is not to troubleshoot all TB problems and fix their 15.000+ bugs.
