### ISSUE TITLE
Logo should be smaller in About screen

### ISSUE THREAD

**Issue by aaronliu0130** [Betterbird/thunderbird-patches#241]
Most important issue ever, I know
![image](https://github.com/Betterbird/thunderbird-patches/assets/11874211/3a99e292-d6d0-4e86-86cc-17a7cccf63f7)
The logo in "About Betterbird" takes up the entire window, which just looks weird. Shouldn't there be a little bit of padding above and below the logo to make it have the same height as the text?

**Comment by Betterbird** [comment]
Bigger is better.

**Comment by aaronliu0130** [comment]
How so? It takes up the entire window, making it feel claustrophobic. There's a reason so many sites use padding

**Comment by aaronliu0130** [comment]
Would a screenshot of the things surrounding the about window help understand this?
