### ISSUE TITLE
Upstream bug 1872789: Calender only searches back one year

### ISSUE THREAD

**Issue by Betterbird** [Betterbird/thunderbird-patches#251]
https://bugzilla.mozilla.org/show_bug.cgi?id=1872789
regressed here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1844408

https://www.reddit.com/r/Betterbird/comments/198p0x4/how_can_i_return_this_important_calendar_feature/

Will become relevant for BB 128.

**Comment by Mobilize1696** [comment]
Thank you for logging! I don't know when you plan to release 128 beta. 
When should I look back for an update?

**Comment by Betterbird** [comment]
BB 128 beta comes in May or June 2024.

**Comment by Mobilize1696** [comment]
OH great! 
Apologies, but I cant' find downloads for current BB betas, only the stable versions. Could you please provide a link?

**Comment by Betterbird** [comment]
Generally there are no betas. We'll do a BB 128 beta in May or June 2025.

**Comment by Mobilize1696** [comment]
> BB 128 beta comes in May or June 2024.

Oh, was 2024 a typo then?

**Comment by Betterbird** [comment]
No, 2025 was the typo. The next ESR 128 comes in June/July 2024 and the beta a month before.

**Comment by Mobilize1696** [comment]
Awesome! Look forward to updating then.

**Comment by Betterbird** [comment]
Maybe the TB folks are going to implemente something in https://bugzilla.mozilla.org/show_bug.cgi?id=1855900

**Comment by Mobilize1696** [comment]
> Maybe the TB folks are going to implemente something in https://bugzilla.mozilla.org/show_bug.cgi?id=1855900

Thanks! 
After looking at it, it seems just as old and inactive as mine. Is there a reason you believe this one will lead to an implementation from them?

**Comment by Betterbird** [comment]
We'll see, if not, we'll do something.

**Comment by Mobilize1696** [comment]
It's a month before the BB 128 ESR. Is there an update on either your implementation or TB's?

**Comment by Mobilize1696** [comment]
Okay, since October is still quite awhile away,
      do you think there is still a likelihood that despite the other
      bugs, TB might also fix the calendar issue by then?
    
        - Thanks
      
    On 01/06/24 08:49:45, Betterbird wrote:
    
    
      
      Thanks for the reminder. As expected, the TB folks
        haven't done anything. We'll fix it for 128.
      
        It's a month before the BB 128 ESR.
      
      Well, the official release date is the 9th of July
        2024. I doubt that it will be released then, since due to a
        broken backend, 128 is unusable:
      Folder corruption since version 122: https://bugzilla.mozilla.org/show_bug.cgi?id=1890230
        Folder compact broken since version 122: https://bugzilla.mozilla.org/show_bug.cgi?id=1878541.
      Our best estimate is that 128.3 in October may be
        usable.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2143347282",
"url": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2143347282",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Betterbird** [comment]
Unlikely.

**Comment by Mobilize1696** [comment]
Okay, thank you for taking this on then!
    
    On 01/06/2024 21:21, Betterbird wrote:
    
    
      
      Unlikely.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2143573887",
"url": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2143573887",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Betterbird** [comment]
Looks like the TB folks are fixing this in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1855900 now.

**Comment by Mobilize1696** [comment]
Thanks for updating! To me, it just looks like someone keeps starting a repeat bug every few months. 
I can't see anyone saying they will actually fix it. 
But I replied to promote it since my bug was marked as a dupe.

**Comment by Betterbird** [comment]
Don't worry, you will get something workable. The new bug has a fix 
attached which is waiting for review. If that's not enough, we'll improve 
it.

**Comment by Mobilize1696** [comment]
Okay, I'm not understanding the programming lingo on there. When should I check in? Or will you update like before?

**Comment by Betterbird** [comment]
If you are Sanded7279 on BMO, you will get updates on the bug. If two 
years back is not enough, we can increase that value. Surely 100 years 
ago you wouldn't have had any appointments (unless you're the Flying 
Dutchman).

**Comment by Mobilize1696** [comment]
I have important dates for memories including
      medical records that go back 40+ years that I've entered into my
      calendars.
      I need the whole history to be accessible as it was before the
      feature was removed.
      
      Okay, please keep me updated if you find a significant
    development or workaround.
    
    
        - Thanks
      
    On 06/06/24 15:16:27, Betterbird wrote:
    
    
      
      If you are Sanded7279 on BMO, you will get updates on the bug. If
      two 
      years back is not enough, we can increase that value. Surely 100
      years 
      ago you wouldn't have had any appointments (unless you're the
      Flying 
      Dutchman).
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2152656034",
"url": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2152656034",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Betterbird** [comment]
If the TB folks stick with the 2-year limit, we'll likely increase to 100 years. Let's assume that no one gets older than 110 years and that in the first 10 years they don't book any appointements.

If you have such important calendar content, please make sure it's duly exported and backed up.

**Comment by Mobilize1696** [comment]
Thank you, I really appreciate you.

**Comment by Betterbird** [comment]
Good Lord, https://bugzilla.mozilla.org/show_bug.cgi?id=1855900 stalled 😢

**Comment by Betterbird** [comment]
We looked at the fix in the bug and it looks good to us, We'll ship it in the next 128 build.

Note that TB's technical director got it wrong, see:
https://phabricator.services.mozilla.com/D212771

Quote: _This is a feature that has been broken since 115 and we didn't get many duplicates._

That's wrong. This feature has worked from day one until it was removed here https://bugzilla.mozilla.org/show_bug.cgi?id=1844408 in version 118. So it clearly worked in 115.

**Comment by Mobilize1696** [comment]
Hi! Thanks for update. I'm confused. 
      Is there simultaneous development by both apps to fix this bug for
      version 128? 
      
      And TB: https://phabricator.services.mozilla.com/D212771:
      
      "This is a
      feature that has been broken since 115 and we didn't get many
      duplicates.
      We're gonna start a complete calendar rebuild around September
      so it's not worth trying quickly fix a niche feature that was
      removed due to multiple issues.
      Let's defer this to after ESR."
    
        - Thanks
      
    On 12/07/2024 22:55, Betterbird wrote:
    
    
      
      We looked at the fix in the bug and it looks good to
        us, We'll ship it in the next 128 build.
      Note that TB's technical director got it wrong, see:
        https://phabricator.services.mozilla.com/D212771
      Quote: This is a feature that has been broken
          since 115 and we didn't get many duplicates.
      That's wrong. This feature has worked from day one
        until it was removed here https://bugzilla.mozilla.org/show_bug.cgi?id=1844408
        in version 118. So it clearly worked in 115.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2226404771",
"url": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2226404771",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Betterbird** [comment]
Yes. One TB developer suggested a solution, two others rejected it with the following arguments:
1. WRONG: The feature has been broken already in 115 (like for more than a year) and no on complained.
2. BAD ARGUMENT: Calendar will be overhauled in September (2024?).
3. Technical nits.

Since the TB folks are usually not sticking to their self-declared aims, maybe users will see the feature restored at some stage in 2025 or 2026, or not at all. Hard to predict.

**Comment by Mobilize1696** [comment]
Ah, okay, they're just quack quack quacking
      themselves up and down into the ground over and over, so now
      you've decided to actually soar up into the clouds, because you're
      tryin' to be the Better bird! Got it! 
      
    
    On 13/07/2024 07:11, Betterbird wrote:
    
    
      
      Yes. One TB developer suggested a solution, two
        others rejected it with the following arguments:
      
        WRONG: The feature has been broken already in 115 (like for
          more than a year) and no on complained.
        BAD ARGUMENT: Calendar will be overhauled in September
          (2024?).
        Technical nits.
      
      Since the TB folks are usually not sticking to their
        self-declared aims, maybe users will see the feature restored at
        some stage in 2025 or 2026, or not at all. Hard to predict.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2226790797",
"url": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2226790797",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Betterbird** [comment]
Done. Will ship in the next 128 release, likely in 7-10 days.

**Comment by Mobilize1696** [comment]
Muchos Gracias!
    
      On 13/07/2024 20:34, Betterbird wrote:
    
    
      
      Done. Will ship in the next 128 release, likely in
        7-10 days.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2227061433",
"url": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2227061433",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Betterbird** [comment]
If you're on Windows and want to try it: https://www.betterbird.eu/downloads/get.php?os=win&lang=en-US&version=future

**Comment by Mobilize1696** [comment]
Thanks but I need a different version, I can't
      fine this 128 version in portable and with GB language.
    
        
        
      
    On 15/07/2024 11:45, Betterbird wrote:
    
    
      
      If you're on Windows and want to try it: https://www.betterbird.eu/downloads/get.php?os=win&lang=en-US&version=future
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2228205477",
"url": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2228205477",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Betterbird** [comment]
Those versions are coming in a month or so.

**Comment by Mobilize1696** [comment]
Hi! Whilst waiting for portable version of
      betterbird 128, I was notified that an addon was made to show "all
      events" which the German developer said is limited to 50years. 
      I've tried it on TB 128.01 portable and can confirm that it actually searches up to 50 years ago in the past
      and 50 years in future.
    Link below:
https://connect.mozilla.org/t5/discussions/calendar-search-function-in-nebula/td-p/63744
    
        - Thanks
      
    
    
    On 15/07/2024 20:53, Betterbird wrote:
    
    
      
      Those versions are coming in a month or so.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2229268768",
"url": "https://github.com/Betterbird/thunderbird-patches/issues/251#issuecomment-2229268768",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Betterbird** [comment]
Next we will need an add-on to send mail :cry:

BTW, to make a portable, just grab any portable version, extract it. Then get the 128 Windows installer (.exe), open with 7Zip and replace the "core" folder in your portable version with the "core" folder in the installer.
