### ISSUE TITLE
UI glitch on Windows 7

### ISSUE THREAD

**Issue by sergeevabc** [Betterbird/thunderbird-patches#254]
Windows 7 x64 with Basic theme, Betterbird 115.6.1 portable.
Cannot use the app because some UI glitch is present upon launch.

![2024-0117-1944 betterbird 115 ui bug](https://github.com/Betterbird/thunderbird-patches/assets/373718/9dd95fad-b913-47d0-bc50-415eeeaef8f7)

**Comment by Betterbird** [comment]
You need to set up an account or copy or import a profile. You closed the 
account setup and are left with an empty screen.

**Comment by sergeevabc** [comment]
I want to use Calendar (Lightning) without setting up an email account. It is difficult to use Betterbird in the mentioned capacity because of the skewed interface and, for example, the inability to close the first tab 'Loading…'.

![2024-0119-0533 betterbird lightning](https://github.com/Betterbird/thunderbird-patches/assets/373718/09ed5e29-c102-4c1c-b283-e3cae6eb2b93)

For a counter example, look at the polished interface of Sunbird, abandoned years ago.

![2024-0119-0538 sunbird](https://github.com/Betterbird/thunderbird-patches/assets/373718/9aede437-5f96-4975-9f1a-9d209d4e79da)

**Comment by Betterbird** [comment]
Yes, the "Loading ..." is a little ugly, we'll see whether we can improve that. We suggest to add an empty "Blogs & News Feeds" account, so it looks like this:

![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/7ae1c9f7-615a-4a24-8e09-c613a0058522)

Yes, you can't close the first tab.

**Comment by Betterbird** [comment]
OK, "Loading..." will no longer be displayed. Shipping in BB 115.7.0-bb23 next week.
