### ISSUE TITLE
Betterbird flatpak fails to start

### ISSUE THREAD

**Issue by sho-87** [Betterbird/thunderbird-patches#257]
I installed Betterbird the other day as a flatpak. I got everything set up and working fine. At some point I was changing some settings (I think it was related to the minimize to tray option) and Betterbird crashed.

From that point on, I have been unable to start Betterbird. Every time I try I get:

![image](https://github.com/Betterbird/thunderbird-patches/assets/5199715/d939833b-37f8-4727-95c6-638798412475)

Things I have tried:

- Uninstall flatpak, delete everything Betterbird related in `~/.var/app/`, reinstall flatpak.
- Running `flatpak run eu.betterbird.Betterbird` gives the same dialog box, with some printout (something nvidia/wayland related?):
```
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: ManageChildProcess failed
 (t=5.27879) [GFX1-]: glxtest: ManageChildProcess failed

Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: ManageChildProcess failed
 (t=5.27879) |[1][GFX1-]: No GPUs detected via PCI
 (t=5.27883) [GFX1-]: No GPUs detected via PCI
```
- Following the advice [here](https://github.com/Betterbird/thunderbird-patches/issues/80) and [here](https://github.com/flathub/eu.betterbird.Betterbird?#migration-from-pre-exisiting-thunderbird-flatpak-installations), I figured I could try a profile migration to bootstrap things. I installed thunderbird (flatpak), set everything up, copied `~/.var/app/org.mozilla.Thunderbird/.thunderbird` to `~/.var/app/eu.betterbird.Betterbird/.thunderbird`. However, running `flatpak run eu.betterbird.Betterbird -P` gives the same dialog box error
- I had a previous btrfs snapshot from before the dialog started showing up. Restoring the snapshot doesnt seem to fix anything

I'm confused about why this error would still be showing up after removing Betterbird from my system. Why would the lack of a profile carry over between installs like that?

fyi:
this is on Nobara/Fedora39, running KDE Plasma wayland

**Comment by Betterbird** [comment]
Sorry, this may seem harsh, but we can't action this, especially since it was working fine until "some settings" were changed.

This is a support case and not a fault we can address in the software. "Your Betterbird profile cannot be loaded" is clearly a sign of an inaccesible profile in `~/.thunderbird` or wherever FlatPak stores the profile. I'm not even sure, `-p` works in the FlatPak context.

Maybe the FlatPak maintainer can assist you. @mfschumann, any comments?

**Comment by Betterbird** [comment]
> I'm not even sure, `-p` works in the FlatPak context.

It might try to access the profiles in `~/.thunderbird` where FlatPak doesn't store the profiles (I believe).

**Comment by mfschumann** [comment]
Are you running the flatpak with default permissions or have you given BB access to your home directory (using flatseal or via `flatpak override`)?

With default permissions, the profile must be in `~/.var/app/eu.betterbird.Betterbird/.thunderbird`, whereas it must be in `~/.thunderbird` when BB has access to your home directory.

**Comment by sho-87** [comment]
ah good to know. didnt know it looked in a different place depending on permissions. all works now
