### ISSUE TITLE
Strange behaviour with Master Password on Startup of Betterbird

### ISSUE THREAD

**Issue by uDEV2019** [Betterbird/thunderbird-patches#26]
When launching Betterbird with master password set, Betterbird ask for the master password.
If i don't enter the password and press cancel, Betterbird launches and gives me a decent view to all accounts, emails (except the crypted once) and i also can go into the settings of Betterbird and make changes to them.

The only thing what isn't possible then, is to check for new mails (pop3 and imap) and sending of emails.

I don't know if this happens in Thunderbird too. Made a short google search and didn't found something about this.
What i know for sure is, that this is not as it must be.

**Comment by Betterbird** [comment]
Same in Thunderbird, please file a bug at https://bugzilla.mozilla.org. As per Betterbird's support pages, sadly we can't fix all 14.000+ bugs TB has. The master password basically protects the passwords for IMAP, POP3, SMTP access and keys to decrypt messages. All else is not protected. I mean, you can read/edit all the files in the profile with a text editor.

Some people advise against using a master password and using disk encryption instead.

**Comment by Betterbird** [comment]
On could of course close the session of the master password isn't entered correctly. But that doesn't offer any real protection. Whoever has access to the computer, so they can start TB/BB, also has access to the underlying files in the profile where unencrypted messages are stored in text files. BTW, people with access to the machine can also install a keylogger and break any password. At best, the master password protects server access and PGP keys.
