### ISSUE TITLE
Feature request: colour the message objects or the background of the row in the list instead of the first column only.

### ISSUE THREAD

**Issue by ElimGarak72** [Betterbird/thunderbird-patches#261]
Hello!
Right now, if I set a colour to an account, the background of first column in the list is filled with it.
I think it would be more readable if the characters of the line where in that colour. Or the whole row background was filled.
I know that it can be done using tags and filters, but it would be nice to see it integrated in Betterbird. 
Thank you!

**Comment by Betterbird** [comment]
We're deliberately only colouring the background of the first column for two reasons:
1. We don't want to flood the entire folder list with colour
2. We don't want to conflict with tags, themes, people's userChrome (striping and all sorts of funny things), etc.

Let's see whether the request gains more traction (of funding). We could do a preference to enable full row colour.

**Comment by Betterbird** [comment]
You can switch on "full row color/colour" with pref `mail.threadpane.full_row_color` in the next release.
