### ISSUE TITLE
Feature request: Option to launch Betterbird at Windows startup

### ISSUE THREAD

**Issue by ElimGarak72** [Betterbird/thunderbird-patches#262]
Hello!
It would be nice to have an option to launch Betterbird at Windows startup (choosing to have it fullscreen or minimized).

Thank you!

**Comment by Betterbird** [comment]
There is an option to start minimised, see "expert tips" page on the 
website.

"Start at Windows start" you need to do yourself, via Windows scheduler, 
startup folder or registry.

**Comment by Betterbird** [comment]
The Windows task scheduler is possibly best, it allows for a certain delay after start.

https://www.betterbird.eu/expert-tips/ has:

Relevant preferences:
System tray: mail.biff.show_tray_icon (has UI)
System tray always: mail.biff.show_tray_icon_always (no UI)
Minimize to tray: mail.minimizeToTray (has UI)
Linux only: mail.minimizeToTray.supportedDesktops ("kde,gnome,xfce,mate") and mail.minimizeToTray.desktopsGtkWindowPresentWithTime (special activation, "mate") (no UI)
**Start minimized: mail.startupMinimized (no UI)**
Show new count: mail.biff.use_new_count_in_badge (has UI)
Only count unread message in inboxes: mail.notification.count.inbox_only (no UI)
