### ISSUE TITLE
flatpak version makes firefox light instead of opening config dir

### ISSUE THREAD

**Issue by moritz-t-w** [Betterbird/thunderbird-patches#263]
Steps:
1. Click on the three horizontal lines in the top bar
2. Click on `Help`
![Screenshot](https://github.com/Betterbird/thunderbird-patches/assets/90388353/cdcf0e73-21dc-4abd-9860-4c1a9924f87f)
3. Click on `Troubleshooting Information`
![Screenshot](https://github.com/Betterbird/thunderbird-patches/assets/90388353/b9ee900e-1611-4a82-8cc0-99bcfd47b47a)
4. Spam click `Open Directory` under "Profile Directory"
<video src="https://github.com/Betterbird/thunderbird-patches/assets/90388353/029741e6-de39-4295-90b2-4a017198aea2">https://github.com/Betterbird/thunderbird-patches/assets/90388353/029741e6-de39-4295-90b2-4a017198aea2</video>

Firefox goes into light mode, even if dark mode is explicitly selected.
It seems to reset itself as soon as it's somehow reloaded, as you can see in the video

This happens on arch with the GNOME shell with the combination of pacman firefox and:
- [x] Flatpak betterbird
- [ ] Flatpak thunderbird
- [ ] Pacman thunderbird
- [ ] AUR betterbird (flagged `Out-of-date: 2024-01-29`)

**Comment by Betterbird** [comment]
Sorry, but certainly not a Betterbird "the application" issue. Looks like some weird interaction of packages/processes(???) on Linux.

You can file FlatPak issue at the BB FlatPak repo: https://github.com/flathub/eu.betterbird.Betterbird/

Does it happen with "Flatpak thunderbird"?

**Comment by moritz-t-w** [comment]
> Does it happen with "Flatpak thunderbird"?

No, as you can see in the checkbox list above it happens only with flatpak betterbird.

**Comment by Betterbird** [comment]
Thanks for the clarification.
