### ISSUE TITLE
[Feature request] Attachment list above for new email

### ISSUE THREAD

**Issue by tomas-chrastina** [Betterbird/thunderbird-patches#264]
I have configured Betterbird to display attachments above the message.
This works great for list and even specific message detail.

A bit of a problem is that it does not apply for new message window.
It is confusing when attachments' position is not consistent across the whole application -> it is hard to get use to it.

So it would be nice to also adjust display of attachments while editing message. If current behavior works for some users (to prioritize Formatting bar etc.), please consider adding separate option for this case.

Thank you in advance for considering this.

Version: Betterbird 115.7.0-bb23 (64 bit)
OS: Windows 10 / Xubnuntu 22.04.3 (Flatpak)

To avoid some side effects while testing, I have created new profile and set only an option to _Display attachment list above message_.

**Comment by Betterbird** [comment]
This is already implemented. There is an option in the Compose settings 
to display the attachments in the compose window above the message body 
where they were in TB a few versions back.

**Comment by tomas-chrastina** [comment]
Oh, I am sorry. Somehow I missed this one :X. Thank you for this!

To make it even better, I would welcome an option to have the same visual that is used in display mode or edit mode when bar is located at the bottom.
But it is in the "nice to have" category, and really a matter of taste.

Thank you for your efforts!
