### ISSUE TITLE
English (en-GB) Language Pack 

### ISSUE THREAD

**Issue by TheMetMan** [Betterbird/thunderbird-patches#267]
Betterbird version 115.7.0-bb23 (64-bit)
Gentoo Linux up to date
The English (en-GB) Language Pack cannot be installed because it is not compatible  with Betterbird version 115.7.0.

Oh Dear! I do hate US English!

Will this be fixed? If so when?

**Comment by Betterbird** [comment]
Get the BB en-GB language pack: https://www.betterbird.eu/downloads/get.php?os=all&lang=en-GB&version=release

Check the downloads page: https://www.betterbird.eu/downloads/

**Comment by TheMetMan** [comment]
Great! thanks

**Comment by TheBaggBoy** [comment]
Where does the language pack go?

**Comment by Betterbird** [comment]
Install like an extension, then add language in settings.
