### ISSUE TITLE
I would like to adopt Bug 1747360 (next build)

### ISSUE THREAD

**Issue by kiki-ja** [Betterbird/thunderbird-patches#27]
I would like the following fixed in Thunderbird 97.0 Beta2 to be adopted in the next build.

1747360 - [91.4.1] Attachments with extensions not registered in MIME type cannot be opened in Thunderbird Ver91.4.1
https://bugzilla.mozilla.org/show_bug.cgi?id=1747360

**Comment by Betterbird** [comment]
Looking at the bug, this will ship in TB 91.6.0 in about two weeks time anyway, hence also in BB. I took note of the bug to include it should TB not ship it. If you had contacted us four days ago, we could have included it in BB 91.5.1, too late now.

**Comment by Betterbird** [comment]
TB 91.6.0 didn't take it, but I have:
https://github.com/Betterbird/thunderbird-patches/blob/main/91/bugs/1747360-attach-with-unknown-MIME.patch
https://github.com/Betterbird/thunderbird-patches/blob/a1184bda0cb7a9b5ede2defa32304b078e6c97d7/91/series#L37
