### ISSUE TITLE
Replaced icons

### ISSUE THREAD

**Issue by t0msk** [Betterbird/thunderbird-patches#270]
Hello, I dont know here to ask so I ask here,

icons are located in `betterbird/chrome/icons/default/default.svg and betterbird/chrome/icons/default/newmail.svg`, I changed it, several days ago I updated betterbird and icons were replaced to original state, so it looks like that new version will replace custom icons, so I wonder if there is any solution to keep custom icons during update :)

Thank you

**Comment by Betterbird** [comment]
The quick answer is: Use Windows ;-)

On Windows, the icons are resources within the executable, and the icons 
in the directory you mentioned are not replaced upon update. They 
override the ones in the binary.

On Linux, the icons are installed each time. We suggest you use a script 
that puts the icons you want back. Not ideal, but also not a big overhead 
every 2 or 4 weeks.

**Comment by t0msk** [comment]
"use Windows" is no go :D but thanks, I will create some script for it :)
