### ISSUE TITLE
[Suggestion] set layout to show new mail at the top

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [Betterbird/thunderbird-patches#271]
I like seeing my mail from newest at the top to oldest at the bottom. There seems to be no way to set the layout like this.

**Comment by asdsadsaasd12312132** [comment]
I'm blind. I found it.

**Comment by Betterbird** [comment]
You can set pref `mailnews.default_sort_order` to `2` to get "descending" for all new folders by default:
https://searchfox.org/comm-esr115/rev/50fb88d0210042cc01e558a7f15cbdd0e72fb9c7/mailnews/mailnews.js#86-94
