### ISSUE TITLE
[Bug] Email alerts don't match 1 second setting

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [Betterbird/thunderbird-patches#272]
I have my email alert duration set to 1 second. The notification is lasting much longer than this.

**Comment by Betterbird** [comment]
You didn't mention whether you're using system alerts (on Windows, Linux or Mac?) or the "inbuild" alert.

The latter is launched here ...
https://searchfox.org/comm-esr115/rev/50fb88d0210042cc01e558a7f15cbdd0e72fb9c7/mailnews/base/src/MailNotificationManager.jsm#409
and pulled down here:
https://searchfox.org/comm-esr115/rev/50fb88d0210042cc01e558a7f15cbdd0e72fb9c7/mailnews/base/content/newmailalert.js#76,81,88

Fading in/out takes its time. If you set pref `ui.prefersReducedMotion` to 1, there is no fading and it's really displayed for 1 second.

BTW, you didn't follow the bug submission guidelines. Try it in TB first, then file a bug at TB's Bugzilla. We're not here to fix all 15.000+ TB bugs. But anyway, it works as designed.

**Comment by asdsadsaasd12312132** [comment]
I'm using the inbuilt alert.

**Comment by Betterbird** [comment]
Our comment referred to the inbuilt alert and you can reduce the display time by disabling the animation (fade in/out).

**Comment by asdsadsaasd12312132** [comment]
How do I disable the animation? I can't find it under incoming mail.

**Comment by Betterbird** [comment]
Please read https://github.com/Betterbird/thunderbird-patches/issues/272#issuecomment-1961679155.
