### ISSUE TITLE
Crashes at message load after long idle time

### ISSUE THREAD

**Issue by eyalroz** [Betterbird/thunderbird-patches#275]
I'm using 115.8.1-bb25 (64-bit) on Devuan GNU/Linux excalibur, with Cinnamon DE.

For the last couple of weeks (or so), I've been experiencing almost-certain crashes in the following scenario:

* App is running
* A long idle period (hours)
* Loading a message after the idle period (I think always the first one, but maybe sometimes the second one? Not sure)

I've experienced similar crashes, very infrequently, before, but now it's maybe half the times this scenario occurs, which is basically daily.

**Comment by Betterbird** [comment]
It sounds like Issue #266. What happens if you set these prefs to false:
mail.biff.show_tray_icon, mail.biff.show_tray_icon_always, mail.minimizeToTray ?

**Comment by eyalroz** [comment]
@Betterbird : I'll set these to false for a few days and see what happens.

**Comment by Betterbird** [comment]
Same issue as Issue #153, right? We never got to the bottom of this one. There were a few crash stories, all related to the system tray. The reports were that if people got back to the program after a while, reading a message and hence updating the system tray icon tooltip, it crashed. This happened on Gnome, but we can't rule out that Cinnamon is also affected.

**Comment by eyalroz** [comment]
Whoops... I'd forgotten I'd filed that one. I guess sometimes a few mysterious reports add up into something actionable. Will put a calendar reminder to report about the experiment results in a few days.

**Comment by beeburrt** [comment]
I'm getting crashes too. It happens only after I first start Betterbird after a boot/reboot. I'm not using the system tray feature. 

![system_details](https://github.com/Betterbird/thunderbird-patches/assets/162539390/827c726d-1536-4fb9-abcd-7b32469e3202)

![betterbird](https://github.com/Betterbird/thunderbird-patches/assets/162539390/5d356924-dd37-4b03-a80b-597bd383a7d3)

**Comment by Betterbird** [comment]
> It happens only after I first start Betterbird after a boot/reboot. I'm not using the system tray feature.

Hmm, and TB doesn't crash? Have you switched these prefs off? mail.biff.show_tray_icon, mail.biff.show_tray_icon_always?

Fedora, Gnome and Wayland are really not the most stable combination. TB has crashes, too.

**Comment by beeburrt** [comment]
Thunderbird doesn't crash.

mail.biff.show_alert -- false
mail.biff.show_tray_icon -- false
mail.biff.show_tray_icon_always -- false
mail.minimizeToTray -- false

I installed the eu.betterbird.Betterbird.Debug but I'm sorta lost as to what to do next in order to attach gdb. Do I need to launch Betterbird from gdb before crash?

**Comment by Betterbird** [comment]
The FlatPak maintainer once pointed me to this article:
https://blogs.gnome.org/mclasen/2017/01/20/debugging-a-flatpak-application/

**Comment by mfschumann** [comment]
@beeburrt You can either
1. run Betterbird from gdb, then trigger the crash:
```
flatpak run --devel --command=sh eu.betterbird.Betterbird
gdb /app/lib/betterbird/betterbird
(gdb) run
```
2. or inspect previous crashes:
```
coredumpctl
flatpak-coredumpctl -m <PID from coredumpctl output> eu.betterbird.Betterbird
```

In both cases you should end up with a `gdb` prompt at the point where the crash occurred. From there you can save the C++ and the JS traces to a file by running:

```
(gdb) set logging file trace.txt
(gdb) set logging enabled on
(gdb) bt
(gdb) print DumpJSStack()
```

**Comment by beeburrt** [comment]
when I run:

    flatpak run --devel --command=sh eu.betterbird.Betterbird

I get the cool betterbird prompt that looks like:

    [📦 eu.betterbird.Betterbird ~]$

and then, after a few seconds, I get thrown back to my prompt, which I then have to `reset` to get back to normal

And when I run:

    flatpak-coredumpctl -m 3627 eu.betterbird.Betterbird

I got:

```
Executable /usr/libexec/xdg-desktop-portal doesn't seem to be a flatpaked application.
Running: `"flatpak" "run" "--filesystem=home" "--filesystem=/tmp" "--command=gdb" "--devel" "eu.betterbird.Betterbird" "/usr/libexec/xdg-desktop-portal" "/tmp/tmpb2zscnka"`
```

...then gdb downloading more stuff... and then:


```
Downloading executable for /usr/lib64/liblzma.so.5.4.4                          
[###                                                                         ]Traceback (most recent call last):
  File "/usr/bin/flatpak-coredumpctl", line 83, in <module>
    coredumper.run()
  File "/usr/bin/flatpak-coredumpctl", line 58, in run
    subprocess.check_call(flatpak_command)
  File "/usr/lib64/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['flatpak', 'run', '--filesystem=home', '--filesystem=/tmp', '--command=gdb', '--devel', 'eu.betterbird.Betterbird', '/usr/libexec/xdg-desktop-portal', '/tmp/tmpb2zscnka']' returned non-zero exit status 137.
```

<details><summary>
From running <code>sudo journalctl -r</code>:
</summary><pre>
Apr 14 14:53:15 fedora betterbird-bin[7580]: Failed to load module "pk-gtk-module"
Apr 14 14:53:15 fedora betterbird-bin[7580]: Failed to load module "canberra-gtk-module"
Apr 14 14:53:15 fedora betterbird-bin[7580]: Failed to load module "pk-gtk-module"
Apr 14 14:53:15 fedora betterbird-bin[7580]: Failed to load module "canberra-gtk-module"
Apr 14 14:53:15 fedora systemd[3191]: Started app-flatpak-eu.betterbird.Betterbird-7557.scope.
Apr 14 14:53:15 fedora systemd[3191]: Started app-gnome-eu.betterbird.Betterbird-7557.scope - Application launched by gnome-shell.
Apr 14 14:45:56 fedora abrt-notification[7240]: [🡕] Process 5997 (flatpak-coredumpctl) of user 1000 encountered an uncaught subprocess.CalledProcessError exception
Apr 14 14:45:56 fedora abrt-applet[3814]: g_app_info_should_show: assertion 'G_IS_APP_INFO (appinfo)' failed
Apr 14 14:45:56 fedora abrt-server[7229]: Deleting problem directory Python3-2024-04-14-14:45:55-7195 (dup of Python3-2024-04-14-14:25:56-5997)
Apr 14 14:45:55 fedora python3[7195]: detected unhandled Python exception in '/usr/bin/flatpak-coredumpctl'
Apr 14 14:45:45 fedora systemd[3191]: Started app-flatpak-eu.betterbird.Betterbird-7197.scope.
Apr 14 14:44:47 fedora systemd[3191]: Started vte-spawn-64ded488-b41f-4d52-8db2-db65744082db.scope - VTE child process 7139 launched by gnome-terminal-server process 7120.
Apr 14 14:44:47 fedora gnome-shell[3465]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Apr 14 14:44:47 fedora gnome-terminal-[7120]: Failed to load module "pk-gtk-module"
Apr 14 14:44:47 fedora systemd[3191]: Started gnome-terminal-server.service - GNOME Terminal Server.
Apr 14 14:44:47 fedora systemd[3191]: Starting gnome-terminal-server.service - GNOME Terminal Server...
Apr 14 14:44:47 fedora systemd[3191]: Started app-gnome-org.gnome.Terminal-7112.scope - Application launched by gnome-shell.
Apr 14 14:44:43 fedora systemd[3191]: gnome-terminal-server.service: Consumed 40.401s CPU time.
Apr 14 14:44:43 fedora systemd[3191]: vte-spawn-8c10acbd-1e92-462b-8dc7-6c85ec0366ab.scope: Consumed 26.703s CPU time.
Apr 14 14:44:00 fedora abrt-notification[7074]: [🡕] Process 5997 (flatpak-coredumpctl) of user 1000 encountered an uncaught subprocess.CalledProcessError exception
Apr 14 14:44:00 fedora abrt-applet[3814]: g_app_info_should_show: assertion 'G_IS_APP_INFO (appinfo)' failed
Apr 14 14:44:00 fedora abrt-server[7063]: Deleting problem directory Python3-2024-04-14-14:44:00-7029 (dup of Python3-2024-04-14-14:25:56-5997)
Apr 14 14:44:00 fedora python3[7029]: detected unhandled Python exception in '/usr/bin/flatpak-coredumpctl'
Apr 14 14:43:50 fedora systemd[3191]: Started app-flatpak-eu.betterbird.Betterbird-7031.scope.
</pre>
</details>

I realize this isn't really a betterbird issue at this point and I appreciate y'all, thanks.

**Comment by eyalroz** [comment]
> @Betterbird : I'll set these to false for a few days and see what happens, but the second two were already false.

I think this took care of the crash issue for me.
