### ISSUE TITLE
I can't find out how to donate

### ISSUE THREAD

**Issue by terminal-root** [Betterbird/thunderbird-patches#276]
The [donate page](https://www.betterbird.eu/donate/index.html) directs me to a nonfunctional `contact us` link if I'd like to donate using something other than PayPal.

The link currently is `javascript:linkTo_UnCryptMailto('nbjmup;jogpAcfuufscjse/fv', 'Request donation information');`

**Comment by Betterbird** [comment]
The link works if you have JavaScript enabled and your browser redirects mailto: links to your mail client. Tested in FF, Chrome and Edge triggering BB.

If all this fails, you can use `info` at the projects domain as the e-mail address.

**Comment by terminal-root** [comment]
Odd, I do have JavaScript enabled, but I am on Mullvad Browser. So, it definitely could be some security measure causing it. Ah, Brave allows it. Yeah MVB blocks out-of-app interaction by default I think. Though, when I allow the link to open in a another app, it doesn't do anything. I have my default mail handler set to Betterbird.

I'll use that address. Thank you!
