### ISSUE TITLE
Message header font css doesn't effect changes

### ISSUE THREAD

**Issue by PaduaPlay** [Betterbird/thunderbird-patches#277]
/* Tweaks to header pane */
.message-header-label {
  color: red ! important;
  font-weight: bold ! important;
}

This is from https://www.betterbird.eu/expert-tips/userChrome.css and doesn't effect any changes to the message header.

Is there any change to the message header element name or syntax for this?

**Comment by Betterbird** [comment]
In general, for 115 you should be looking at https://www.betterbird.eu/expert-tips/userChrome-115.css. However, this still works:
```
/* Tweaks to header pane */
.message-header-label {
  color: red ! important;
  font-weight: bold ! important;
}
```
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/e3fa6101-3e42-44af-9d32-ec68e3357413)

Have you enabled pref `toolkit.legacyUserProfileCustomizations.stylesheets` ?

In general, please don't file support requests as GitHub tickets.

**Comment by PaduaPlay** [comment]
Thanks very much for the response. 

Posted here because the example css did not work and thought that perhaps with the new rev the element name had changed.  Apologies if it was not the forum protocol. Noted about not posting support questions as 'issues' on GitHub and will do. 

Just started using Betterbird 115.8.1-bb25 and toolkit.legacyUserProfileCustomizations.stylesheets is already set to true.

/* Tweaks to header pane */
.message-header-label {
  color: red ! important;
  font-weight: bold ! important;
}

(which is the same in https://www.betterbird.eu/expert-tips/userChrome-115.css and https://www.betterbird.eu/expert-tips/userChrome.css), does not change anything in the message headers shown on the message pane.

Of course, this is just a minor tweaking preference, so don't wish take up valuable dev time.

Thanks again.
![messageheader](https://github.com/Betterbird/thunderbird-patches/assets/57243140/77c218c6-594b-4916-91cb-44787ad43a14)

**Comment by Betterbird** [comment]
> ... does not change anything in the message headers shown on the message pane.

It does. However, in your screenshot we don't see the "normal" Betterbird (or Thunderbird) message header. Headers are uppercase, there is no `folder:` header, and the icons shown don't belong to BB/TB. This comes from the Conversations add-on. Clearly the CSS aimed at changing the BB/TB headers won't have an effect on the stuff the add-on displays.

You need to use the inspector (Tools > Developer Tools > Developer Toolbox) to analyse the CSS you want to change. We find Conversations quite invasive, so we installed it on a test profile. The headers are displayed when you click the (i) icon. The inspector shows this:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/dbb96112-bac8-4505-a9df-55578f462f06)

So maybe this CSS will work:
```
/* Tweaks Conversations headers */
.detailsLine {
  color: red ! important;
  font-weight: bold ! important;
}
```

**Comment by PaduaPlay** [comment]
I very much appreciate your taking the time.  

The .message-header-label tweak does not even after disabling the 'Conversations' add on (which I have found very useful to link messages in various folders) and restarting Betterbird.

**Comment by Betterbird** [comment]
> The .message-header-label tweak does not work even after disabling the 'Conversations' add on

I think discussing proven facts (see comment https://github.com/Betterbird/thunderbird-patches/issues/277#issuecomment-1988050847) doesn't get us anywhere.

You're correct that the suggestion for `.detailsLine` doesn't work for Conversations, although the add-on defines this:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/b05ef984-17fd-4bde-84bd-775a1300e377)

For some reason the CSS in userChrome.css doesn't take effect.

**Comment by Alfred-Peters** [comment]
I hope I can clear this up: You're both absolutely right. 😉

Whether the foo rule works depends on the option:
`Headerpane -> [More] -> Customize... -> [ ] Hide labels column`

If it is switched on, there is no `.message-header-label` - but then there is a `.row-heading`. Therefore, this one should work:
```css
.message-header-label, .row-heading {
  color: red ! important;
  font-weight: bold ! important;
}
```

**Comment by Betterbird** [comment]
Thanks, Alfred. Well, if there is no label, then there's nothing to colour. Any idea why the CSS for "Conversations" doesn't take effect?

**Comment by Alfred-Peters** [comment]
You mean the add-on?
Yes, that's a nasty trick. The Conversation header pane is not the right header pane. The AddOn completely recreates it. And it does so in the body!  And this means that the `detailsLine` rule must be included in userContent.css.

**Comment by Betterbird** [comment]
Ouch!!

**Comment by PaduaPlay** [comment]
Thanks for the clarifications, @Alfred-Peters . 
They work. 
The usercontent.css tweak suggested to make this work with the 'Conversations' addon works as well. Glad that this works, since it is a useful addon.

A WYSIWIG UI customization or css generating tool would be a, very nice to have, companion app, and, so too would be a forum, for BetterBird, in English.

**Comment by Betterbird** [comment]
Well, there is https://www.reddit.com/r/Betterbird/.

**Comment by PaduaPlay** [comment]
> Well, there is https://www.reddit.com/r/Betterbird/.

True that, with 89 members.. 

A wysiwig customization + css generating tool (perhaps even an AI tool to generate the css from a wysiwig UI) would catapult BB and its inspiration into a different value bracket.

Of course, BB and Thunderbird are good as they are 👍(thanks to the devs) and sort of slowly getting the idea of switching from Thunderbird 60.x, as the main email client, after many years of parallelly trying the various iterations of Thunderbird, since the 60.x version.

Thanks also for the detailed responses here in this discussion board.
