### ISSUE TITLE
feature request: add ability to disable selected mail accounts

### ISSUE THREAD

**Issue by mehlian** [Betterbird/thunderbird-patches#278]
As in the title, please add a new option to disable the selected email account. 
This option should be available by pressing RMB on a given email address.
![obraz](https://github.com/Betterbird/thunderbird-patches/assets/31826615/27afb53a-12dd-410a-8f9b-cba65e9660e1)

Reason:
sometimes for some reason we lose access to a given email account (e.g. the administrator took away our access to it or we lost access to it for some time). In such a case, when trying to check for new emails for other account, a message will pop up informing about failed login or other errors related to problematic email account.

However, I would like to maintain this account on the list (along with local versions of emails) and get rid of this error when using other emails.

Disabling the option 'check new emails' in the 'Server Settings' section for this account does not solve the problems - error messages still appear.

Disabled email accounts could appear as gray text and should be treated as an archive for which new emails are not checked.

**Comment by Betterbird** [comment]
This has been requested for TB in 2011: https://bugzilla.mozilla.org/show_bug.cgi?id=689067, there are also a few duplicates.

**Comment by just37** [comment]
How much would this feature cost, I might be willing to fund it.

**Comment by Betterbird** [comment]
The cost depends on various things: How long does it take an engineer to implement, and what is the remuneration of such an engineer. If you want a checkbox in the UI "disable account", this needs to be translated and the translation shipped in 13 locales we currently support. If it's only done with a (hidden) preference, like `mail.serverNN.disabled`. it's less effort.

Best not discuss $$ figures publicly, so please get in touch directly.

**Comment by Betterbird** [comment]
Lastest build:
https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.11.0-bb28-latest-build5.en-US.win64.installer.exe

**Comment by Betterbird** [comment]
This has been fully implemented with UI in BB 128. It's working in BB 115 by setting the prefs.
![image](https://github.com/user-attachments/assets/22478b6e-5498-4a77-8f50-9205a464d6dd)
