### ISSUE TITLE
Stop annoying pop-ups that lose keyboard focus

### ISSUE THREAD

**Issue by ferrieux** [Betterbird/thunderbird-patches#280]
Hello,

Since version 115, many background tasks that formerly were only mentioned in the status line, now post a pop-up window saying something of groundbreaking importance like "Fetching e-mail" or "Retrieving certificates".

This is really annoying, as the result is losing keyboard focus. You end up losing several sentences of text in the currently composed message.

Could someone roll back this "innovation" ? Or is there some config variable to disable it ?

Thanks in advance,

-Alex

**Comment by ferrieux** [comment]
The text is approximative, and the presence of the pop-up is fleeting (but enough to lose the focus).
I cannot seem to reproduce right now, presumably this is linked to some network delay or packet loss on the IMAP or LDAP paths.
I will arrange for a screencast then extract the specific frames showing the pop-ups, when I am able to reproduce.

One thing though: if you abstract away the exact contents of these pop-ups, do you have in mind a situation where the code could decide to show them based on some timing issue ? In other software, it is not uncommon to see a "stuck eventloop watchdog", that would kick in if the main thread has not polled for events for X milliseconds or so.

**Comment by ferrieux** [comment]
Update: I have a repro now :)

I've done a screencast and extracted the frame:

![popup](https://github.com/Betterbird/thunderbird-patches/assets/614725/2f1155e2-90e0-4f8d-a093-7453d0635487)

This window pops up roughly 5 seconds after a "Reply To All" on a message with 4 recipients. Interestingly, I have disabled encryption and signature by default.

For some reason, this is "sticky" in that the certificates never end up being downloaded (possibly due to an LDAP misconfiguration here, but that's another story).

**Comment by ferrieux** [comment]
Well, stealing the focus may depend on the window manager and its configuration (focus-follow-mouse, click-to-focus, etc).
However, changing this just because of an unwanted behavior of an isolated application, be it the e-mail client, is not an option.
So, Betterbird should not make any assumption on the focus policy, and just refrain from posting pop-ups.

Note: I am aware of the temptation to use pop-ups *with a Cancel button*, when the associated asynchronous task may be cancelled. However, there are other options: (1) a dedicated menu entry or submenu in the top menubar; (2) forget about cancelling, just like for "Compact folders" which is not cancellable.

**Comment by Betterbird** [comment]
Please report your concerns in an upstream ticket at https://bugzilla.mozilla.org/.

**Comment by Betterbird** [comment]
Actually, the same pop-up appears in 102.

**Comment by ferrieux** [comment]
Possibly, I typically don't upgrade unless pushed by bugfixes :)

On a side note: kudos for the principle of Betterbird. Focusing on stability instead of featurism is really refreshing in this day and age.

**Comment by Betterbird** [comment]
We have a few features :wink: - https://www.betterbird.eu/#featuretable
