### ISSUE TITLE
Undo subthreading

### ISSUE THREAD

**Issue by aaronliu0130** [Betterbird/thunderbird-patches#281]
Forgive me if I'm dumb, but there seems to be no current way to drag a subthread out of a thread to become its own root. In this week, I have, on two occasions, accidentally dragged a message into another message while, uh, playing with my mouse 🤫A way to implement an undoing would be support for message reordering, something like a horizontal bar that appears when a drag a message between messages and lets you drop it there.

**Comment by Betterbird** [comment]
It appears that you haven't read the release notes referring to the section https://www.betterbird.eu/expert-tips/index.html#rethreading.
Both Ctrl+t, Ctrl+z or Ctrl+t, Ctrl+x work.

**Comment by aaronliu0130** [comment]
It would still be a bit helpful to have a graphical way of outhreading a messages. I clearly don't the shortcut enough, and I come back to this issue every once in a while to find the link to the shortcut.

**Comment by Betterbird** [comment]
The developer suggested to add "Unthread Message" and "Restore original threading" to the context menu. That's more work for localisation. Maybe we'll do it for 128 in due course.
