### ISSUE TITLE
Can't apply column view settings to unified folders

### ISSUE THREAD

**Issue by Cwpute** [Betterbird/thunderbird-patches#282]
I have several email accounts and have chosen to see them in a unified view, but i can't find a way to propagate the colum settings i use for my other folders to the unified view for any of my email folders...
If it allows you to propagate these settings to any folder, it should allow you to do so to unified folders as well, shouldn't it ?

Not sure if this is a bug, but if not, then consider this a feature suggestion :)

**Comment by Betterbird** [comment]
Since any unified/search/virtual folder can be made up of many folders with conflicting settings, we see no way to propagate column settings from member folders to the unified folder. Sure, you can program a lot of stuff, like apply member settings if they are all the same or "similar", or come up with some other approach to unify disjoint column setting of the members, but there is little gain to be had.

We're not even sure that this is a desirable feature for many users.

**Comment by Cwpute** [comment]
I'm a bit confused about why you're talking of "similar" settings, "other approach" and if-conditions for applying them or not... i'm not talking about folder settings, but the way they are displayed. I must not have been precise enough.
I thought this might have been a bug (or rather an oversight) from Thunderbird dev team, because you can propagate column appearance to any folder of your liking, and their children-folder if you so desired to, except for the Unified Folders view.

I am talking about the way columns are displayed to the user for each folder. I have found a pleasant way to display my columns and want all my columns in Betterbird to look like this. This can be done folder view by folder view in the (big) column options list, at its very bottom, by selecting the folders you want to apply this view to. But in this list, you cannot find the Unified Folders, preventing you from propagating this way of displaying columns to it.
What i am asking for is that i am able to copy the way the columns are displayed using that menu, and apply this column appearance to the Unified Folders view. Not necessarily to its children, which i have already set! But to the Unified Folders view itself.

Is that such a controversial option to consider or such an ordeal that this request gets immediately dismissed ?

**Comment by Betterbird** [comment]
Oh, now the penny dropped. You want your unified folders to appear here:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/74775407-4545-495e-8056-1e8254448f07)

So basically you just want the smart folders to appear in the folder list that opens. Doable.

**Comment by Cwpute** [comment]
Yes, exactly :)

**Comment by sharpjs** [comment]
Even an "All folders" option in that menu would work.

**Comment by vix1000** [comment]
Yes, please add this feature for a global/default option: "Apply columns to ALL Folders (and ALL Children)"

Tweeking Config Editor > "mailnews.database.global.views.global.columns" does not work

**Comment by Betterbird** [comment]
The mentioned pref `mailnews.database.global.views.global.columns` applies to synthetic Gloda views.

BTW, the TB folks have implemented an option to globally apply some view properties (not columns) to all folders, see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1829737

**Comment by vix1000** [comment]
Thanks for link. I was aware of the threading solution. I am really looking/hoping for a column solution.
What is Gloda  ?

**Comment by Betterbird** [comment]
Global Database, activated via:
![Image](https://github.com/user-attachments/assets/967b12ee-9556-4efa-bd3d-876b659cf9c7)

I don't use it. Further reading: https://support.mozilla.org/en-US/kb/global-search

You can find more information via https://www.google.com.au/search?q=gloda+mozilla, there used to be even "design" documents. Gloda is mostly unmaintained and bug aren't fixed.
