### ISSUE TITLE
How about a cleaner icon?

### ISSUE THREAD

**Issue by ronso0** [Betterbird/thunderbird-patches#286]
![Screenshot_2024-04-09_12-54-58](https://github.com/Betterbird/thunderbird-patches/assets/5934199/38c6c204-8527-4535-bdcb-fa6d84123604)
Just an idea, if contributions in that regard are welcome let me know : )
(actually I just removed the circular back path. My window switcher uses PNGs so I had to regenerate them from the clean SVG)

**Comment by Betterbird** [comment]
I'm not sure what you're saying. The artwork we ship is fine, in both SVG and PNG on all three supported platforms. If you tweak stuff yourself, it's up to you to make it nice. In general, the logo is part of the registered trademark, so it won't change.

**Comment by ronso0** [comment]
> In general, the logo is part of the registered trademark, so it won't change.

Alright, wasn't aware of that. So no logo tweaks accepted. Thank you!
