### ISSUE TITLE
build error for Betterbird 128

### ISSUE THREAD

**Issue by artix-arist** [Betterbird/thunderbird-patches#287]
Maybe it's too early to build Betterbird v128 from source but this is the error that occurs then:

 4:57.28 /build/betterbird/src/mozilla-central/comm/mailnews/compose/src/nsMsgCompose.cpp:248:21: error: non-const lvalue reference to type 'nsAString' (aka 'nsTSubstring<char16_t>') cannot bind to a value of unrelated type 'nsAutoCString' (aka 'nsTAutoStringN<char, AutoStringDefaultStorageSize>')
 4:57.28   248 |     anchor->GetHref(objURL);

Maybe this is related to 12+13-feature-linux-systray-incl-minimise.patch ?

Thx for looking into this.

**Comment by Betterbird** [comment]
Too early, we haven't compiled it yet, we're still adjusting patches for 128, well, currently at 126.

Looks like a simple compile error, looks like something like this is needed:
https://hg.mozilla.org/comm-central/rev/a25bf321fdd3e4e8179fba4d147716b36f599099#l1.12

**Comment by Betterbird** [comment]
We've built it now on Windows with `./build.sh 128`. This is of course a build based on TB **126**. On Windows it starts, but there are various issues we need to address (like no mail displayed).

It's possible that it doesn't compile on Linux. We have a contributor who will build on Linux "soon" and we'll let you know when it's ready.
