### ISSUE TITLE
[EnhancementReq] Ignore diacritics in Quick Filter

### ISSUE THREAD

**Issue by Hakun1n** [Betterbird/thunderbird-patches#289]
Hi,

Is there any way to make a switch for QuickSearch to **ignore diacritics**?
I could even live with a manually configurable replacement table (like ... consider "č" as "c", etc...).

This is one of the most-annoying thing in Thunderbird for me. My native language has a lot of diacritics and since the SMS era it is quite common that people are not using diacritics in informal emails/messages (it used to be cheaper as we had char-limits :p). Especially for people in IT and/or for those for which English (or other lang) is the daily driver. But the other half is using diacritics fully.

Quick-filter is absolute blast when i KNOW that i recently got certain email (eg. i saw it on my cell, but want to reply on PC). So i just open Thunder/Better-bird, click to QuickFilter, type the word and ... nothing ... (maybe i did a typo? second attempt!) ... nada .. then i realize that the freaking word has a "ž" in it, so i either have to switch keyboard and quick-search for third time OR i have to use the global-search (which is an overkill for such case BUT it actually ignores diacritics). Worst-case is if the word has multiple letters with diacritics but the sender forgets one ... then it is a guess-game till i give up and use the global search.

There is a related ancient bug-report in bugzilla - [506064](https://bugzilla.mozilla.org/show_bug.cgi?id=506064) closed as duplicate to even more ancient [284856](https://bugzilla.mozilla.org/show_bug.cgi?id=284856) (19 years)

Note: I tried the [Expression Search - NG](https://addons.thunderbird.net/en-us/thunderbird/addon/expression-search-ng/) which allows using "g <text>" to invoke global search but it is clunky, it has annoying history overlay and the fact a prefix is required voids the "Quick" meaning.

Thank you in advance for at least reading this :)

**Comment by Betterbird** [comment]
How about using regular folder search together with regular expression matching?
Matches "xx.yy" will match "xxayy" and "xxäyy".

Otherwise we'd have to implement some very expensive diacritics matching. That said, if you search in this page in Firefox, both ä and a will match the a's on the page. We'd have so see how this is done and whether it can be adapted to BB.

Would you like to fund the enhancement?

**Comment by Betterbird** [comment]
Looks like the Mozilla "find in page" happens here:
https://searchfox.org/mozilla-central/rev/863aef60f9fa1536884252ad90cad1d8ee9d8a41/toolkit/components/find/nsFind.cpp#585
Look for `mMatchDiacritics` in that code. That can't be used for quick filter.

ICU string search could be used for string search ignoring diacritic:
https://unicode-org.github.io/icu/userguide/collation/string-search.html

This would need to be plugged in here into `nsMsgSearchTerm::MatchString()`:
https://searchfox.org/comm-central/rev/c3c7f562cb0e1d0b409c81e9f3cbf46f10f73c02/mailnews/search/src/nsMsgSearchTerm.cpp#976

Looks the TB folks track it in https://bugzilla.mozilla.org/show_bug.cgi?id=1839085.

**Comment by Betterbird** [comment]
> I can drop you an email if you wish.

Yes, please.

**Comment by Betterbird** [comment]
https://github.com/Betterbird/thunderbird-patches/commit/f6b606f43a2de2e62044c7e20b9016d85029cdfb

**Comment by Hakun1n** [comment]
> [f6b606f](https://github.com/Betterbird/thunderbird-patches/commit/f6b606f43a2de2e62044c7e20b9016d85029cdfb) [0d1d3ce](https://github.com/Betterbird/thunderbird-patches/commit/0d1d3ce6d7f4aba273fe38047addc4a6d4de163d)

That was super fast. I've checked the version 115.10.0-bb27 but sadly I am not able to make it work. Quick filter of `zadost` does not find `žádost` nor `žadost`. Do i need to "enable" the feature somewhere?

Checking [this line](https://github.com/Betterbird/thunderbird-patches/commit/f6b606f43a2de2e62044c7e20b9016d85029cdfb#diff-47b001e715c35fbef3dcb36c8d41d11d5ca9e73c2f658a8a63ad563ee0956b7bR16) it already contains `ž` so that should not be an issue. On the other side there are some characters (from my lang) which are missing -> `čČřŘďĎťŤňŇÝůŮ`

Oh and the email has been sent.

**Comment by Betterbird** [comment]
Since it was requested after the 115.10.0 release, it's not in that release. Please try:
https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.10.0-bb27-latest-build1.en-US.win64.installer.exe

The second changeset is relevant since there we switched the processing to ICU to cover all possible accents, see:
https://en.wikipedia.org/wiki/Diacritic#Languages_with_letters_containing_diacritics

**Comment by Hakun1n** [comment]
Oh, silly me. I missed the disclaimer on the Release Notes page. I've now updated to the latest build and it works like a charm. You made my day, thanks !
