### ISSUE TITLE
BB & TB 115.10.0 crash with Yahoo account(s) "Empty Trash" option checked

### ISSUE THREAD

**Issue by topoldo** [Betterbird/thunderbird-patches#291]
As it was reported here:
https://www.reddit.com/r/Thunderbird/comments/1c35vvd/thunderbird_not_closing_in_task_manager_in_115100/
Thunderbird 115.10.0 and also Betterbird 115.10.0-bb27 (the second one tested by myself), don't close correctly if:
- A Yahoo account is present in the TB/BB profile
- Yahoo account has the "Empty trash" option checked
If this option is uncheck, then everyting is OK.
No problem with BB versions < 115.10.0 and also TB < 115.10.0 as reported in the link above.

Regards,
Leopoldo Saggin aka Topoldo

**Comment by Betterbird** [comment]
We backed out out the offender in https://github.com/Betterbird/thunderbird-patches/commit/c60309f9cf8fc2b6dc4eac0fda40ec7a5adb3514, so please try this build:

https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.10.0-bb27-hotfix.en-US.win64.installer.exe

**Comment by topoldo** [comment]
Hi!
I tested the hotfix build using the checkbox on all these accounts:
- Gmail
- Microsoft (@outlook.com)
- Yahoo
The patch seems to work fine.
There is only a little delay in closing the prg.
Of course I cannot say if there are downsides.

Many tnx for the fast feedback.
Regards,
Leopoldo Saggin aka Topoldo
