### ISSUE TITLE
Crash a short time after being opened

### ISSUE THREAD

**Issue by stemy2** [Betterbird/thunderbird-patches#293]
Hello,

For some reason, i'm unable to keep Betterbird opened longer than a couple of minutes or even seconds sometimes, it crash itself at every attempt. And launch it with the console don't give me any clue, there's no sign of any error right before the crash, as you can see below:

```
stem@stem-kubuntu:~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=betterbird --file-forwarding eu.betterbird.Betterbird @@u %u @@
Betterbird: Detected desktop environment kde.

stem@stem-kubuntu:~$
```

OS: Kubuntu 23.10
GPU: Nvidia 1050 Ti (driver: nvidia-535)

**Comment by Betterbird** [comment]
Please follow the FltPak debugging instructions given here:
https://github.com/Betterbird/thunderbird-patches/issues/275#issuecomment-2054176541

**Comment by stemy2** [comment]
None of the debugging instructions are working for me.

```
stem@stem-kubuntu:~$ flatpak run --devel --command=sh eu.betterbird.Betterbird
error: runtime/org.freedesktop.Sdk/x86_64/23.08 not installed
stem@stem-kubuntu:~$
```

```
stem@stem-kubuntu:~$ coredumpctl
No coredumps found.
stem@stem-kubuntu:~$
```

**Comment by RedSnt** [comment]
I'm hoping this will fix the problem I'm having as the flatpak version of betterbird will sometimes not launch, and other times just close out of nowhere.
