### ISSUE TITLE
Crash on compose new message 115.10.0-bb27 

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Betterbird/thunderbird-patches#296]
Reproducible crash:

1. Open new message
2. paste recipient E-Mail address into To: via CTRL+V

115.10.0-bb27 (64-Bit) Windows
```

Pfad der fehlerhaften Anwendung:	C:\Program Files\Betterbird\betterbird.exe

Problemsignatur
Problemereignisame:	APPCRASH
Anwendungsname:	betterbird.exe
Anwendungsversion:	115.10.0.0
Anwendungszeitstempel:	661fab6c
Fehlermodulname:	olmapi32.dll
Fehlermodulversion:	16.0.17425.20124
Fehlermodulzeitstempel:	65fe5890
Ausnahmecode:	c0000005
Ausnahmeoffset:	00000000000454b8

```
no extension enabled

**Comment by Betterbird** [comment]
No crash here. What is olmapi32.dll? Looks like some Outlook MAPI DLL. Not present on my system although I have Outlook 365 installed. Why does that even get triggered? Something wrong going on on your system. Looks like a support case at best.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> What is olmapi32.dll? Looks like some Outlook MAPI DLL.

I checked and found the Microsoft Office component DLL Module is loaded into Betterbird.exe from “C:\Program Files\Microsoft Office\root\Office16\OLMAPI32.DLL” which is installed alongside on the same OS.

**Comment by Betterbird** [comment]
Strange. It's possible that olmapi32.dll gets loaded via mapi32.dll, but only when you do a MAPI operation, like sending a message via an attachment from the desktop/a folder, or from another program, like Word or LO Writer. It doesn't seem plausible that this should interfere with pasting recipients.

https://www.google.com.au/search?q=olmapi32.dll+crash+thunderbird
gives a lot of crashes related to that DLL.
