### ISSUE TITLE
Not possible to pin betterbird to KDE taskbar

### ISSUE THREAD

**Issue by IrregularLogic** [Betterbird/thunderbird-patches#298]
As betterbird currently does not seem to come as a debian package management *.deb file it is required to uncompress betterbird archive folder first and move it to a location from where to start binary file named "betterbird".

Currently when i want to run betterbird I have to browse to its folder and doubleklick its start file. For convenience, I would like to shortcut starting betterbird by placing the app (pin to) onto KDE taskbar. This is normally done either by chosing the app in kde start menu (which does not work as debian package management does not know it is "installed", therefore no app entry is available in KDE) or by running the app, right-clicking onto its icon in taskbar and then selecting entry "pin to taskbar". Then starting betterbird would require single click only, just as with all my most often used applications.

Unfortunately, betterbird does not show this entry, so it is not possible to pin it to taskbar.

Can you please update betterbird metadata etc. or whatever it takes to have betterbird show an entry for pinning to taskbar?

BTW thunderbird has this entry, so betterbird here is a worsebird, lol.

Thanks a lot.

**Comment by Betterbird** [comment]
> Unfortunately, betterbird does not show this entry, so it is not 
> possible to pin it to taskbar.

Are you sure this isn't also a "KDE thing" when the app is installed via 
a .deb package? We have no knowledge of KDE, we have a .desktop file in 
our repo that you can adjust to your/KDE needs, that's all.

Please do your own research and let us know. You can also file a ticket 
on KDE's Bugzilla or ask on one of their mailing lists.

**Comment by Betterbird** [comment]
It works fine if you use a desktop file. Please inspect
[xx](https://github.com/Betterbird/thunderbird-patches/blob/8c6d9032ad318a80f23a521d91f0fa6d5d5532ee/install-on-linux/install-betterbird.sh#L62)
to see how it's done.

Some screenshots:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/0fd3d727-a71a-4f91-a52d-ae9345cfb703)

![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/5f04d1e7-b400-42eb-a684-89b7af8ed834)
