### ISSUE TITLE
Sender/Receiver mail addresses filled in wrong in the Mail Composition window 

### ISSUE THREAD

**Issue by teymuri** [Betterbird/thunderbird-patches#299]
When ever I click on the reply button, I have to manually select the correct sender and receiver addresses from the drop-down menu of my email-accounts. I would expect that the compose-message window automatically detects the address of the sender-account and the address to whom I am replying (the receiver). If this already can be set, then I am sorry for opening this issue, and would appreciate pointing me out to the write setup.

Greetings

**Comment by Betterbird** [comment]
This seems like a support issue, not a software bug.

Of course reply works, the recipient (you) becomes the sender and the sender becomes the recipient. There are a lot of variations, lie "Reply All" or when the "Reply-To" header is used or when replying to a mailing list post. All this works and is covered by automatic tests so it doesn't silently break.

If the reply function doesn't work, something is misconfigured, you're using some rogue add-on or there is a special case.
