### ISSUE TITLE
Question: Thunderbird folder compatible with Betterbird?

### ISSUE THREAD

**Issue by boschkundendienst** [Betterbird/thunderbird-patches#30]
Hi, just a simple question.

I am currently on Thunderbird 91.6.0 (64-Bit) on Linux.
I just openend ProfileManager with betterbird and switched to my Thunderbird profile.

Just wanted to make sure that this is perfect compatible or not, is it? Can I switch back (I hope I must not) at any time?

Kind regards

Peter

**Comment by Betterbird** [comment]
It is almost perfectly compatible ;-) - If you switch to the multi-line view, that is, the subject column is removed and the subject is placed as a second row, then switching back to TB you won't have a subject and no way to get it back. So before switching back to TB, re-establish the subject if you switched to multi-line view.

There have been reports on missing header pane toolbar buttons, if that happens to you, see the section "What's the story with the header pane buttons?" at https://www.betterbird.eu/support/.
