### ISSUE TITLE
Messages no longer show headers (all folders, both INBOX and SENT).

### ISSUE THREAD

**Issue by rickst29** [Betterbird/thunderbird-patches#301]
'Inbox' messages no longer show any header information. (When displayed in a new tab, or a new window, or within the message area of the 'classic' 3-panel layout. 'View Message Source' shows that all messages were delivered to the Client with full and correct header information. 

I added the 'FolderFlags' add-on, and verified that my INBOX folder has only the "Inbox" flag marked. The The problem is not present within current Thunderbird, but has possibly been 'exposed' by a change within my ISP's 'folder layout' for my email account (IMAP):  All other folders (Drafts, Sent, Archive, Junk, Spam, Trash) are now configured as subfolders INBOX.

I don't know if that 'subfolders' arrangement has always been like that, or is a new change at the ISP. Each subfolder is associated with only the single and correct 'flag' for its type, and they operate correctly.

**Comment by Betterbird** [comment]
You accidentally collapsed the header area using the respective splitter. 
Drag the splitter down to make the headers visible again.

**Comment by rickst29** [comment]
I'm an idiot. THANK YOU !

**Comment by Betterbird** [comment]
Well, it would be best not to file support cases as GitHub tickets.
