### ISSUE TITLE
Host Betterbird repository at Codeberg or Forgejo

### ISSUE THREAD

**Issue by Francewhoa** [Betterbird/thunderbird-patches#302]
## Suggestion

For a stronger security, stronger privacy, and for using a repository software that better match Betterbird's values, I suggest two actions:
___1. Use the fully Libre Source (Open Source) and free https://codeberg.org or https://forgejo.org as PRIMARY code repository
___2. Use the Secret Source (Proprietary) Microsoft's GitHub as SECONDARY code repository. In other words, an automated mirror of Codeberg or Forgejo primary repository above.

Both me and the Ubertus.Org team would be happy, as volunteer, to contribute testing and documentation, if needed. I am an end-user. Not a developer. I do not have a financial conflict of interest with Codeberg or Forgejo. I am just a happy end user.

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

Below is the same as above. But with details for those interested in those. Including my review of Forgejo.

## Strength

• Forgejo visual design and workflow are similar to Github. Which make migration and initial learning curve much easier.
• Quick and easy start with the free and Libre Source (Open Source) at https://codeberg.org Which is a SaaS powered by Forgejo. Alternatively, the free and Libre Source (Open Source) Forgejo can be self-hosted per documentation at https://forgejo.org
• Drop-in replacement for Gitea
• Libre Source (Open Source). If you are not familiar with "Libre Source", it means this software has both stronger security & stronger privacy. Because its code is publicly available for review and contributions at https://codeberg.org/forgejo/forgejo
• Attractive MIT license. This means the software code is owned and supported by a friendly not-for-profit community. Instead of a for-profit corporation. https://forgejo.org/imprint/ In comparison, Github, GitLab, Gitea are owned by for-profit corporation.
• Federated
• API
• Kanban board
• Dark theme
• For those not familiar with the challenge with Gitea is that, starting in October 2022, without knowledge or approval of the community, a for-profit company took over the Gitea community domains and trademark. Big mistake. Since then, most of the Gitea community left to Forgejo.org.
___• What the Gitea community needed was to continue for a not-for profit organization to be the owner of its infrastructure and direction. Such as, but not limited to, its domains, trademark.
___• Obviously what would have resolved this challenge above was for the main developer and maintainer to simply create a for-profit organization. With its own domains and trademark. Without interfering in any ways to the already existing not-for-profit community organization.
___• Before leaving, the Gitea community communicated their needs to the Gitea main developer and maintainer. Which ignored them, then declined their suggestion.
___• The risk with for-profit company is that, usually, they value money above people. So in the future, it is very high risk that Gitea will introduce lock-ins to monetize. Functionalities available only if you pay. And increasingly make decision without involving the community or just ignore it. Why. Simply because legally speaking, for-profit organization communicate a clear intent that they value money above people. Above you ;)

___• "In October 2022 the domains and trademark of Gitea were transferred to a for-profit company without knowledge or approval of the community. Despite writing an open letter, the takeover was later confirmed." Source at:

______• https://gitea-open-letter.coding.social

______• https://archive.ph/T573R#selection-83.0-99.83

______• In other words, this challenge above could have been resolved with two organizations. A not-for-profit and a for-profit. Each with its own domains and trademarks. Unfortunately, the maintainer declined this. Took over the not-for-profit community. As a result, most of the Gitea community left to Forgejo.

___• To resolve this challenge, I suggest to migrating to any alternative to your liking which is owned by a NOT-for-profit organization. The keyword here is "NOT-for-profit". Because NOT-for-profit value people above money. In comparison, https://forgejo.org is owned by its community :) In other words, owned and controlled by YOU.

___• "Forgejo was created in 2022 because we think that the project should be owned by an independent community. If you second that, then Forgejo is for you! Our promise: Independent Free/Libre Software forever!" Source:

______• https://codeberg.org/Forgejo/forgejo

______• https://archive.ph/UZx6n

___• One of many examples of people who migrated AWAY from Gitea is Codeberg. Since December 2022, Codeberg is now powered by Forgejo. Codeberg host over 50,000 projects and 40,000 users.

___• Codeberg wrote: "Codeberg needs to run on a Free Software codebase maintained by trustworthy people. And the Gitea community deserves to be in control of the project when they generously volunteer their time. It must not be the company accepting the community. It must be the community generously accepting the company, and Gitea Ltd should be thankful for this, instead of trying to dictate how governance shall work in the future. Luckily Codeberg is in a unique position to reconnect the Gitea community in one place, independent and out of control of Gitea Ltd. And so we did." "Codeberg will use Forgejo instead of Gitea starting with version 1.18.0" Source:

______• https://blog.codeberg.org/codeberg-launches-forgejo.html

______• https://archive.ph/qcva1

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

## Challenge

• Very basic time tracking, email notification on events, and Kanban board. In the future those popular features will likely grow. But for now there are very basic.

___• Time trackings do not yet have reporting features. This is essential for Product/Project Managers services.

___• Email notifications include only "Email on mention", "Enable", or fully "Disable Email Notification", and other options need to be enable for EACH user.

___• Kanban board can not easily be filtered to reduce the clutter. Which is challenging for large team.

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

Show Your Support:

• If you enjoy this application, show your support to the authors & contributors with:

___• Community support with tickets at https://codeberg.org/forgejo/forgejo/issues

___• Report bugs at https://codeberg.org/forgejo/forgejo/issues

___• Contribute documentation at https://forgejo.org/docs/latest

___• Patch at https://codeberg.org/forgejo/forgejo

**Comment by Betterbird** [comment]
Thanks for the suggestion and the offer.

Betterbird is a soft fork of Thunderbird, we only have to host modifications to the underlying TB/Mozilla software in a form of patches. Any repository can be used for this purpose. Currently we host 15 MB in 824 files. Git and GitHub seem to be used pretty frequently, GitHub also offers the advantage of GitHub actions which we may start using in due course, see PR #173. Right now, we don't have plans to move the repository. Given more resources, we'd rather progress with GitHub action, for example for Issue #88.

The repository of the patches has nothing to do with the security or the privacy the software offers.
