### ISSUE TITLE
Feature request: Encrypted email messages should be stored decrypted in the local folders

### ISSUE THREAD

**Issue by Katarn** [Betterbird/thunderbird-patches#304]
Hello. This feature would be very useful. It hasn't been implemented in the original Thunderbird for 20 years.

https://bugzilla.mozilla.org/show_bug.cgi?id=280588

**Comment by Betterbird** [comment]
TB/BB can decrypt messages to a folder, but it's a manual action. There is no automatism in decrypting when storing a message in a local folder. For legal purposes, many user need to keep the original message for some years, so decrypting it and replacing it with the decrypted version is not an option.

Implementing "Filter action decrypt" (https://bugzilla.mozilla.org/show_bug.cgi?id=1627962) would be more appropriate.

The original idea of decrypting automatically when storing in a local folder could be done in an add-on. You can contact us if you'd like to fund this work.

**Comment by Katarn** [comment]
I prefer the idea of ​​having two settings:

- When receiving a letter, create a decrypted copy.
- - When creating a decrypted copy, delete the original.

Of course, if the mail was received via IMAP, it should be saved in the same IMAP. Is it possible to do this in an add-on?

> TB/BB can decrypt messages to a folder, but it's a manual action.

I didn't find such an option. The only thing I found was enabling the ability to search for encrypted messages.

**Comment by Betterbird** [comment]
It's on the context menu:

![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/3633d21d-652a-4165-86dc-b4cae4747741)

**Comment by Katarn** [comment]
Thank you! This functionality will be quite enough for me.
