### ISSUE TITLE
MS Outlook invitations menu vanished from 115.11.0-bb28.en-US.win64

### ISSUE THREAD

**Issue by Piotr-Fr** [Betterbird/thunderbird-patches#306]
After the update from 115.10 to 115.11.0-bb28.en-US.win64
there is no possibility to react to MS Outlook invitations coming in:

![image](https://github.com/Betterbird/thunderbird-patches/assets/82875426/ab1d22fa-101e-468f-8ea7-efe96b14d25a)

All in red circle is missing.

I have reinstalled 115.10, and all works.

Unfortunately, no Thunderbird install, cannot confirm in regard to TB.

It is rather an important issue as work related.

**Comment by Betterbird** [comment]
Seems to work here in 115.11.0:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/ad38d627-f596-482f-851a-ccf7826e5d07)

Also, there were no changes to anything Calandar-related between 115.10.0 and 115.11.0. There must be some problem at your end.

**Comment by Piotr-Fr** [comment]
Hi, just FYI, I downgraded to 115.10.0, and now upgraded to 115.12.0-bb29,

all works now.
Solved.
