### ISSUE TITLE
The app stays open in the panel when minimized to try

### ISSUE THREAD

**Issue by KarkanAlzwayed** [Betterbird/thunderbird-patches#307]
I just started noticing this issue recently. Usually, when I minimize the app, it actually does minimize to the tray (I do have the option to minimize to the tray checked), meaning it looks like it is "closed" and wouldn't show the little preview window when I hover over the app icon in the panel. Not the case anymore, the app continues to stay open to where a little preview shows in the panel when I hover over the icon. See attached screenshot
 
![Screenshot_20240604_112044](https://github.com/Betterbird/thunderbird-patches/assets/49320606/8c1af8e8-a6a7-47ba-8ecd-502059ee68a2)

**Comment by Betterbird** [comment]
That's KDE, right? You're using Wayland? What has changed from the last 
point in time when it worked?

Linux is a nightmare to support. That said, it seemed to work OK on KDE, 
so it's really up to you to find out what broke it.

**Comment by KarkanAlzwayed** [comment]
That is KDE Plasma, correct. And, yes, I'm using wayland. I'm not sure what broke it to be honest. Before, when I minimize the app, it acts like it completely closed, so when I hover over the icon while it is minimized, I don't see that little preview window. Now I see it. I use thunderbird on my Windows install and minimizing the app makes it act like it was closed and hovering over the icon in the taskbar doesn't show the preview.

**Comment by Betterbird** [comment]
Wayland never worked, see Issue #279.
