### ISSUE TITLE
documentation request: how to install betterbird

### ISSUE THREAD

**Issue by sysdbugfactory** [Betterbird/thunderbird-patches#309]
I recently found out the existence of betterbird. 

it seems to be the software I need to fix issue, I have been encountering with thunderbird which imho are mostly mismanagement from mozilla.

but I am unable to give betterbird a try for lack of documentation explaining how to install it, in my case for debian linux.

**Comment by Betterbird** [comment]
> it seems to be the software I need to fix issue, I have been encountering with thunderbird which imho are mostly mismanagement from mozilla.

Correct.

There is Issue #80 on file.

Linux users can use FlatPak, or there is [this](https://aur.archlinux.org/packages?O=0&SeB=nd&K=betterbird&outdated=&SB=p&SO=d&PP=50&submit=Go) for Arch.

There's also an install script:
https://github.com/Betterbird/thunderbird-patches/tree/main/install-on-linux

We don't have any other plans.
