### ISSUE TITLE
notification 'no secret key' for OpenPGP encrypted message showing up twice

### ISSUE THREAD

**Issue by tibitts** [Betterbird/thunderbird-patches#31]
When attempting to open an OpenPGP encrypted message which has not been encrypted to any of my keys, a red banner 'The secret key ... is not available' pops up in the header pane. That's fine, however, the banner is shown twice.

<img width="828" alt="secret_key_not_available" src="https://user-images.githubusercontent.com/30876012/153613683-bdb7483c-2ef7-4794-b9bd-10a18aff469a.png">

Even though this is a cosmetic issue and does not impact functionality, it still looks odd. It happens with both, BB 91.6.0, and TB 91.6.0.
I believe this did not happen in TB prior to v91.6.0, so this could be a regression in TB, but I'm not exactly sure.

**Comment by Betterbird** [comment]
Hmm, we were working on BB on isssue #29 yesterday and saw this red banner once, on the other hand, at least on one profile we saw the "this was broken by Exchange" four times.

Please check whether the "double red" effect is present in TB and then file a bug at BMO. There were only tow changes in PGP between 91.5.1 and 91.6.0 in TB:

**Comment by tibitts** [comment]
new BMO bug 
https://bugzilla.mozilla.org/show_bug.cgi?id=1755039

**Comment by Betterbird** [comment]
Thanks, I don't think we need to track this twice. We might advance the TB fix when available or provide one ourselves if we can reproduce it.
