### ISSUE TITLE
suggestion: debian repository to distribute betterbird

### ISSUE THREAD

**Issue by sysdbugfactory** [Betterbird/thunderbird-patches#310]
debian user eager to replace thunderbird with betterbird here.

betterbird is unavailable from the official debian repositories.

I could not find betterbird packaged for debian on the official website.

no debian repository is almost the same as unable to install on debian. I think I do not have to explain why software living outside the debian way of managing software (apt) it out of scope for the vast majority of debian user, but feel free to ask if you need me to explain why.

it seems to me that betterbird should offer a debian repo to allow debian users to install and use it.

**Comment by Betterbird** [comment]
Seems like the same as Issue #309 or Issue #80.

**Comment by sysdbugfactory** [comment]
sorry for the noise, my search for existing report failed to return this.

sadly if there is no plan for betterbird to meet the basic minimal standard of linux software distribution then even if it would have fit the use case and a possible solution, I will have to pass.

I have been plagued by the various mozilla mismanagement of feature removal, broken UI changes and disregarding users' need and feedback, but it costs less to deal with that nonsense than having to manage a single piece of software out of the standard software distribution.

I manage about a dozen debian installations for people who struggle with using computers. I provide them with technical support on my free time at no charge. there is no way they will be able to maintain and update any software that's outside apt, and I do not have time to manually deal with this, let alone times 12.

Imho linux users should never use flatpak, this format is wrong and bad. For this kind of software packaging, appimage is the way to go. but this kind of packaging is out of question for my use case anyways.

AUR distribution would fit my use case, but switching distros to an AUR compatible one is not an option. these users need a stable OS over being closer to the egde.

I guess this means I'm locked out of betterbird due to the lack of availability of an appropriate distribution mechanism. which in turns prevent betterbird from reaching user who would benefit from it.

do you know why betterbird was rejected from inclusion in debian repositories ?  

can you explain why the betterbird team does not offer a debian/ubuntu repository ? 
the only explanation in issue #80 is "because thunderbird does not either", and this answer seems to run the opposite way of what this project does.

**Comment by Betterbird** [comment]
> do you know why betterbird was rejected from inclusion in debian 
> repositories ?

As far as I know, they never paid attention to it. No rejection. You can 
lobby it. We're happy to cooperate as we do with Arch and FlatPak.

> can you explain why the betterbird team does not offer a debian/ubuntu 
> repository ?

We started as Windows project. Supporting Linux is our biggest headache 
and least bang for the buck.

The 1% of Linux users on their bazillion configurations make 80% of the 
noise. No offence intended, just facts. For testing along we need to look 
at four DEs (KDE, Gnome, Mate, Xfce) and then there are still issues on 
Wayland. A nightmare.

**Comment by sysdbugfactory** [comment]
I just looked and unless I missed something it seems betterbird never bothered to request to be packaged in debian.

from I gather from a quick read of linux users discussion about betterbird, most do not even know it exists as it is not part of the standard way of software distribution, in comparison similar soft fork of mozilla products to work around mozilla mismanagement such as waterfox and librewolf are known and popular and are available from extra repositories.
among those who discover betterbird some are wary of giving it a try due to the use of flatpak and the lack of appimage, or simply because they never heard of it before and it lacks a way of installing it. 

it is a kind of snake biting its own tail situation. which contribute to why you have so little linux users, and why you have to deal with that much support request. 

not that linux users would be a large proportion of the user base but it should be a few times bigger. having a larger linux user base and visibility also means that you will have more linux people helping each other for support and asking in their communities first instead of coming upstream. with enough users you should also find people willing to do some testing for you.

no offence taken, fragmentation in the linux world is indeed a known drawback which can be a hurdle to supporting the various linux. but here it is not a matter of providing support to users or dealing with the various desktop environments but a matter of software distribution. 

past the initial setup, build a deb for distribution through a repository can be fully automated. so it adds little overhead.
various tools and documentation exists to ease the setup process for each distribution system. 

alternatively you could also make use of solutions such as [open build service](https://openbuildservice.org/) to build for differents distros from a single place. you do not even have to manage the tool yourself as opensuse has a public instance for this purpose: https://build.opensuse.org/

**Comment by Betterbird** [comment]
Thank you for your deliberations. I mostly agree. However, BB is FOSS, if someone is interested to take they matter further, we're happy to cooperate.

**Comment by sysdbugfactory** [comment]
well I just did what I could.

if you ever find yourself wanting to reach the linux user base, you know what to do and how to set it up with relative ease so it would be automated.

but you should not expect end users to do this for you as the harsh reality is that it is typically a part that falls on the devs shoulders, or project packager when there is one.

I as a end user, will simply pass on betterbird despite it being a good fit for my use case because it is not properly packaged and distributed.

thanks for your time and keep up the good work with betterbird, it seems to be a useful and needed piece of software.

**Comment by shuvashish76** [comment]
> can you explain why the betterbird team does not offer a debian/ubuntu repository ?

According to repology https://repology.org/project/betterbird/versions it's available in Pacstall : _Pacstall is the AUR Ubuntu wishes it had. It takes the concept of the AUR and puts a spin on it, making it easier to install programs without scouring github repos and the likes. See the [Pacstall](https://pacstall.dev/) project for more information._
@sysdbugfactory The package looks bit outdated contact the respective [package maintainer](https://github.com/pacstall/pacstall-programs/issues). I'm not a debian/ubuntu user.

```bash
pacstall -I betterbird-bin
```

---

> or this kind of software packaging, appimage is the way to go

Besides that as mentioned in #38 also available as _Unofficial_ AppImage format

- Install via [AppMan](https://github.com/ivan-hc/AppMan) (rootless)
  ```bash
  appman -i betterbird
  ```
- Install via [AM](https://github.com/ivan-hc/AM)
  ```bash
  am -i betterbird
  ```

**Comment by Betterbird** [comment]
Note https://github.com/Betterbird/thunderbird-patches/issues/80#issuecomment-3442970427

Debian packages are now available.
