### ISSUE TITLE
Close to tray?

### ISSUE THREAD

**Issue by iamstonecutter** [Betterbird/thunderbird-patches#311]
I'm thankful for the minimize to tray, but why is there to close to tray? Would be great if this feature is added.

**Comment by Betterbird** [comment]
Where is it? Here: https://github.com/Betterbird/thunderbird-patches/issues/244#issuecomment-1873557127

**Comment by Betterbird** [comment]
> Can anything be done about this?

Read the documentation? https://www.betterbird.eu/expert-tips/

Relevant preferences:

    System tray: mail.biff.show_tray_icon (has UI)
    System tray always: mail.biff.show_tray_icon_always (no UI)
    Minimize to tray: mail.minimizeToTray (has UI)
    Linux only: mail.minimizeToTray.supportedDesktops ("kde,gnome,xfce,mate") and mail.minimizeToTray.desktopsGtkWindowPresentWithTime (special activation, "mate") (no UI)
    Start minimized: mail.startupMinimized (no UI)
    Windows only: Show count in taskbar badge: mail.biff.show_badge (has UI)
    Show new count: mail.biff.use_new_count_in_badge (has UI)
    Only count unread message in inboxes: mail.notification.count.inbox_only (no UI)
