### ISSUE TITLE
Feature request: PST file viewer and more

### ISSUE THREAD

**Issue by Torinde** [Betterbird/thunderbird-patches#312]
Ability to work with PST files from Outlook:
- [ ] view/browse inside 
- [ ] edit
- [ ] import from PST
- [ ] export to PST

That will make possible various interoperability/replacement use cases.

**Comment by Betterbird** [comment]
You're looking for a PST tool kit. Maybe that's available commercially. 
Another way to work with PST files, is to install Outlook.

Besides, PST is a proprietary format and at times it seems that even 
Microsoft don't understand their own format (see the errors scanpst used 
to produce (haven't run it in ages)).

This will certainly not be implemented.
