### ISSUE TITLE
Feature request: Systray to provide cascading folders browse funtion

### ISSUE THREAD

**Issue by Torinde** [Betterbird/thunderbird-patches#313]
I'm using the Windows desktop toolbar for "browsable folders with cascading levels" - a place on the taskbar from where I can browse the whole computer (preferably starting from Desktop/User folder - showing This PC, Control Panel, OneDrive(s), Sharepoint(s), Network, Recycle Bin, Libraries, User folder, etc.) only with moving the mouse (without clicking) - cascading further inside (including in ZIP files), then right-clicking and/or dragging files/folders, copy/cut/paste/delete/rename, etc.

Add item/icon implementing the ">>" symbol functionality from the Win10 desktop toolbar somewhere in the left-click menu of the tray icon (similarly to [TrayToolbar](https://github.com/rojarsmith/TrayToolbar))

See [screenshot](https://www.eightforums.com/threads/i-dont-miss-start-menu-at-all-heres-why.5442/):
![Browsable cascading folders](https://user-images.githubusercontent.com/97228894/154351043-acb0eec3-fb8c-4b62-af71-4af88fa376e6.png)

Related: https://github.com/microsoft/PowerToys/issues/16404

**Comment by Betterbird** [comment]
Not planned, sorry. Would be hell to implement on other platforms.

Check these add-on for fast folder access:
https://www.betterbird.eu/addons/index.html#QFM-Classic
https://addons.thunderbird.net/en-GB/thunderbird/addon/quickfolders-tabbed-folders/
