### ISSUE TITLE
The bottom part of the 'About Betterbird' Window is cut off

### ISSUE THREAD

**Issue by kiki-ja** [Betterbird/thunderbird-patches#315]
The bottom of the 'About Betterbird' window is cut off and the text is not visible.
Please see the screenshot.
Is this a problem in my environment?

![About Betterbird 102-115](https://github.com/Betterbird/thunderbird-patches/assets/80428201/ece67c70-9558-4d0a-89a0-8088e0376548)

---

I modified it by adding the following two lines to 'aboutDialog.css'.
```
#leftBox {
  background-image: url("chrome://branding/content/about-logo.svg");
  background-repeat: no-repeat;
  /* min-width and min-height create room for the logo */
  min-width: 210px;
  min-height: 210px;
 + margin-top: 20px; /* add */
 + margin-bottom: 20px; /* add */
  margin-inline-start: 30px;
}
```
Below is a screenshot of the results.

![About Betterbird +20px](https://github.com/Betterbird/thunderbird-patches/assets/80428201/a0c452ea-77f1-4dec-84cd-13009eb3c46d)

![Betterbird について +20px](https://github.com/Betterbird/thunderbird-patches/assets/80428201/37c183c0-c20e-49e7-9b82-237d46c77077)

@kiki-ja

**Comment by Betterbird** [comment]
Hmm, works for me:

Windows:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/d23853f4-0bff-49bd-b4fe-c238dc0a5ed5)

Linux:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/04cb857c-f05e-4313-aa47-f6748653a1b2)

Why doesn't it fit for you? Looks like the logo is too small. I can add the margin, it was requested here: Issue #241

**Comment by Betterbird** [comment]
Does it work with 10px margin instead of 20px? How about increasing min-height?

**Comment by kiki-ja** [comment]
I saw your screenshot and it turns out that it seems to be a problem with my system font.

>Why doesn't it fit for you? Looks like the logo is too small.

On my Windows 10 PC I have changed the system font and size so the font is probably a bit large for the logo.
This is probably why the logo appears small in terms of balance.
This may be the reason why the bottom row of text is two lines long and cut off from the window.

My system font:
'BIZ UDGothic font family'
https://learn.microsoft.com/en-us/typography/font-list/biz-udgothic

>I can add the margin, it was requested here: Issue #241

Seems like a problem with my font.
But it is strange because in Thunderbird it is not a problem.(?????)
If it is not a problem in other users' environments, then there is no need to add margins.

>Does it work with 10px margin instead of 20px?

10px margin would work, but a 20px margin was best.

margin 10px case:
![About Betterbird +10px](https://github.com/Betterbird/thunderbird-patches/assets/80428201/654be19d-c6cc-43d8-94e7-d62826e9cb83)
![Betterbird について +10px](https://github.com/Betterbird/thunderbird-patches/assets/80428201/70eb6779-97f8-4a90-9b2a-ec2f0f6fab45)

>How about increasing min-height?

I tried it, but up the min-height did not make the desired change.

------
So I will deal with this by customizing it with CSS.

userChrome.css:
~~~
#leftBox {
  margin-top: 20px !important;
  margin-bottom: 20px !important;
}
~~~

Thank you very much.

@kiki-ja

**Comment by Betterbird** [comment]
Thanks for the details, we'll consider adding 15px margin since something similar was requested in Issue #241.

**Comment by Betterbird** [comment]
How does this issue look in BB 128? We've never addressed it :cry:

**Comment by kiki-ja** [comment]
Betterbird 128.5.0esr en-US version has no problem.
But in Betterbird 128.5.0esr ja version it looks like this.
I have added top and bottom margins.

![bb128 5 0-AboutWindow](https://github.com/user-attachments/assets/c422d73c-6e32-4037-9001-62cda2040108)

[userChrome.css]
#leftBox {
  margin-top: 15px !important;
  margin-bottom: 20px !important; /* or 15px */
}

If you want the bottom line to be one line, add the following

[userChrome.css]
#rightBox {
min-width: 230px !important; /* 230px should be changed according to your environment */
}

I don't know because I haven't tried it in other language versions, but I feel it is better to add a top and bottom margin because I guess that there could be a case where the bottom line is broken off.

@kiki-ja

**Comment by Betterbird** [comment]
OK, we'll add the 15px top and bottom margin to finally close the issue. Thanks for your advice.

**Comment by Betterbird** [comment]
OK, I added 15px margin to the leftBox. The rightBox had 20px margin, we needed to increase that so text and image line up vertically centred. Of course that brings the text further down and may defy the purpose altogether.

**Comment by Betterbird** [comment]
Is this better in 128.5.2 now?

**Comment by kiki-ja** [comment]
128.5.2 bb19 64bit
Windows 10 Pro 22H2 64bit

About Betterbird (ja version) window is good.
See screenshot.

![128 5 2 about betterbird ja](https://github.com/user-attachments/assets/8f066102-beb7-4ccb-9b3a-62f1de6a3a85)

-------------------------

[Ref]
I have made the following customization to make the bottom line of text a single line.

[userChrome.css]
```
#aboutDialogContainer {
  width: 680px !important;
}
```

![128 5 2 about betterbird ja my custom](https://github.com/user-attachments/assets/c3874edc-dfb4-48cc-941d-ba3fcc6d7308)

@kiki-ja

**Comment by Betterbird** [comment]
OK, thanks for testing. I actually looked at it with a Japanese language pack and the font was way smaller.

**Comment by kiki-ja** [comment]
>I actually looked at it with a Japanese language pack and the font was way smaller.

That seems to be normal.

In my case, as I mentioned earlier, I have changed the OS system font.
Also, its font size is increased by 1 - 2pt.
So I have customized it a little.

I would be happy if you could use this as reference information for the Japanese version.

@kiki-ja

**Comment by Betterbird** [comment]
> I would be happy if you could use this as reference information for the Japanese version.

I'm not sure what you want me to do. Everything should be fine now for the Japanese version.
