### ISSUE TITLE
Feature request: displaying RSS feed child folders content at the parent level

### ISSUE THREAD

**Issue by VladimirMarkelov** [Betterbird/thunderbird-patches#317]
I do not know whether it is possible to implement in BetterBird and how hard it is. So, I do not expect it is added to BetterBird any time soon. I saw that feature in "TheBat!" and I liked it.

Feature: BetterBird shows the total number of unread RSS messages of all children if a folder is folded. That is helpful. Is it possible to show RSS messages from all folder's children when I select a folder RSS folder? At this moment, BetterBird shows nothing in message list pane in this case. You have to select a certain RSS feed to show its list of messages.  Important thing: it should work only for RSS feeds. For regular email folders the feature seems harmful.

My use case: I create an RSS folder "Software", then I added 10-15 RSS feeds related to various applications (e.g, "DoubleCommander", "Vim Tricks" etc). I also add a few more RSS folders about other subjects, each of them contains 2-10 RSS feeds. If I unfold all folders, the treeview looks cluttered - too many feeds in the screen and I have to scroll the treeview up and down all the time. If I fold all RSS folders, I lose a way to read new RSS message in a convenient way - I have to unfold the parent folder, read new ones, and than fold the folder back.

Thank you for the BetterBird!

Edit: I checked TB bugzilla, in the list of feature requests I did not find a similar one.

**Comment by Betterbird** [comment]
> Important thing: it should work only for RSS feeds. For regular email folders the feature seems harmful.

In the folder tree, all folders are usually treated the same. A feed folder is just a folder whose content is populated by one or more feeds.

As for the feature: Can you please submit some screenshots including a mock-up or an annotated one where you want the additional count to appear.

**Comment by VladimirMarkelov** [comment]
if all folders are equal, I think, my request is better to be closed. Anyway, here are screenshots to demonstrate what I'm talking about.

BetterBird: I've created RSS folder "Software" and added an RSS feed. If I select the folder "Software", the list of message is empty in spite of "The Bat" feed has 1 message:

![image](https://github.com/Betterbird/thunderbird-patches/assets/1577186/92d2d730-49f6-49f5-b6a7-6a5c83407114)

Then I've created a folder "Software" in TheBat! and added a few RSS feeds to it. When I select folder "Software", I can see in the message list RSS messages from all feeds of the folder:

![image](https://github.com/Betterbird/thunderbird-patches/assets/1577186/71d44feb-f462-4b0e-b709-b492ca4a89a0)

So, in TheBat! if a folder has a lot of feeds, I can fold the folder and keep the mail box treeview short and tidy. At the same time I can read all RSS messages without unfolding the folder "Software". It seems handy to me.

**Comment by VladimirMarkelov** [comment]
Extra comment: you can see in my TheBat! screenshot two grayed RSS feeds. It means that I disabled automatic updating them. Disabling RSS feeds is also can be handy in case (it is case of "gHacks" one in the picture) when RSS feed is dead, but you want to keep some useful messages from it or in case of you want to keep the messages but you do not want to follow the feed any longer (as in FLTK case above - FLTK feeds is alive but I stopped following FLTK project closely, so I do not need any new from it at this moment).

**Comment by Betterbird** [comment]
Thanks for the clarification. You have two options:

1. Move all the feed subscriptions into the single folder Software folder (drag and drop in subscribe dialog); move all the messages there too.
2. Create a virtual folder to unite all the feed folders of Software.

If you do solution one, it should look like this:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/1a6c5f63-c5c0-4295-8d11-4989a26b1477)

Looks like the overall folder shouldn't show the icon of one of its feeds. We'll look into it.

**Comment by VladimirMarkelov** [comment]
I have never used virtual folders, so I missed this way to do what I need. Thanks a lot for the tips!

**Comment by Betterbird** [comment]
You can put a virtual folder "SoftwareV" into the feeds account and unite all the subscription folders.
