### ISSUE TITLE
Send icp or similar messages to listeners/daemons so shell scripts can be run from Thunderbird

### ISSUE THREAD

**Issue by borjasanlei** [Betterbird/thunderbird-patches#318]
This is more of a question than a feature request.

### Context
I want to be able to execute shell scripts in my Linux system from Thunderbird events like key presses. Since running arbitrary code from the email client might be dangerous, I'd think about the ability to send some events to a listener so scripts can be executed. The events should be able to carry data like the MessageID to be used as parameters in the script.

### Example use case
I use the MessageID to follow particular messages. I use some extension to manually copy the ID to my task manager. Then I open back the email in Thunderbird directly.

This process might be quite automatizable if I was able to send the MessageID to custom scripts in my system, thus, making the client fully connected to other processes without manual intervention.

Is it possible through any coding/extension?

**Comment by Betterbird** [comment]
> Is it possible through any coding/extension?

What is this issue about? Some software fault? Doesn't look that way.

If you write an "privileged" add-on (so-called WebExtension Experiment), that add-on, just like the host application Thunderbird or Betterbird would have full access to your system, unless you're running FlatPak where the app is sandboxed.
