### ISSUE TITLE
Sorting E-Mails by date does not sort related E-Mails

### ISSUE THREAD

**Issue by Bluejanis** [Betterbird/thunderbird-patches#319]
First, I prefer to sort all emails descending by date. I usually have to sort each folder once individually. (I think there is a Firefox setting for all folders, but it is not applied. I still have to check that function in Betterbird.)

I still experience two bugs when sorting emails descending by date:

1. Sorting regular E-Mails works fine, but once there are related E-Mails they are bunked together and the sorting is not applied anymore. For example, these E-mails are all ordered incorrectly (still ascending by date):
![Email1](https://github.com/Betterbird/thunderbird-patches/assets/10140165/d39db47f-434d-4589-b2a2-666adca981e7)

2. Also, when I close the view of the related E-Mails, it sorts the E-Mail in the correct spot, but shows the wrong date. It does not show the date of the e-mail, but instead shows the date of the first related e-mail.
For example, this shows the date from an E-Mail from 2022:
![Email2](https://github.com/Betterbird/thunderbird-patches/assets/10140165/87b17448-6b75-4748-95b3-67999df4b442)
To me, it is very confusing, that old emails are preferred over new emails.

Both issues exist in Thunderbird, and are also still present in Betterbird.

**Comment by Bluejanis** [comment]
I am also wondering, how the system decides whether emails are related or not. Because it also does it for unrelated emails (but same sender) for me.

**Comment by Betterbird** [comment]
This is how threading works. Threads are sorted by the date of the last message in the thread, but if the thread is collapsed, the first message in the thread shows. It's been like this for well over 20 years. For improvements, see Issue #160 and Issue #245.

If you're wondering, you can contact our support, no need to file a bug. Messages are related via the Message-ID:, References: and In-Reply-To: headers. Please inspect the message source.

**Comment by Bluejanis** [comment]
It definitely felt like a bug, since the sorting is partly not applied when clicking on the sort row.

And honestly, just because it was always done like that, is not a good argument!

**Comment by Betterbird** [comment]
Meanwhile we implemented reversed sorting, check the release notes. You might want to try that.

**Comment by Bluejanis** [comment]
Thanks for implementing it now! Seems like people have been asking for it for 16 years!

Maybe you want to consider changing this issue from not planned, to solved now?

So according to the [release notes](https://www.betterbird.eu/releasenotes/) you have to enable a `pref ``mailnews.reversed_threading`.
I will post back, once I figured out how to do that.

**Comment by Bluejanis** [comment]
ChatGpt for the rescue 😄 

> Steps to Enable a Preference in Betterbird:
> 
>     Open Betterbird: Launch the Betterbird email client.
> 
>     Access Configuration Editor:
>         In the menu, click on Tools > Settings (or Preferences, depending on your OS).
>         In the left sidebar, scroll down and select General.
>         Scroll all the way to the bottom of the General settings page and click on the Config Editor button under the Advanced Configuration section.
> 
>     Proceed with Caution: A warning message will appear saying "Changing these advanced settings can be harmful to the stability, security, and performance of this application." Click Accept the Risk and Continue to proceed.
> 
>     Search for the Preference:
>         In the Config Editor, there is a search bar at the top.
>         Type the name of the preference you want to enable (e.g., mailnews.some.pref).
> 
>     Enable or Modify the Preference:
>         If the preference exists, you’ll see it in the list below. Double-click on the preference to change its value.
>             For boolean (true/false) preferences, double-clicking will toggle between true and false.
>             For numeric or string preferences, double-click and input the desired value.
> 
>     Restart Betterbird: Some preferences may require restarting Betterbird to take effect. Close and reopen the application to apply the changes.

**Comment by Betterbird** [comment]
Reversed threading was implemented in Issue #160.
