### ISSUE TITLE
[Linux] Request support for AppMenu

### ISSUE THREAD

**Issue by Janvitus** [Betterbird/thunderbird-patches#32]
Hello,
it's possible to add support of libappmenu to betterbird like the patches included in firefox-appmenu and thunderbird-appmenu?

https://aur.archlinux.org/packages/firefox-appmenu
https://aur.archlinux.org/packages/thunderbird-appmenu

Thanks for your time.

**Comment by Betterbird** [comment]
What is libappmenu, what is it used for and which advantage does integration with FF/TB/BB have?

**Comment by Janvitus** [comment]
https://packages.ubuntu.com/search?keywords=appmenu&searchon=names&suite=all&section=all

Ii's a library for appllication menu's on the panel desktop's (mate, xfce, kde plasma, etc)

Example: http://www.webupd8.org/2017/02/alternative-global-menu-for-mate-and.html

**Comment by Betterbird** [comment]
Looks like it "detaches" the application's main menu to the top of the screen, like on macOS. @Posi81, what do you think of this? Personally I'm no a great friend of that Mac-UI.

**Comment by Janvitus** [comment]
> Looks like it "detaches" the application's main menu to the top of the screen, like on macOS. @Posi81, what do you think of this? Personally I'm no a great friend of that Mac-UI.

On mid/mid-low screen (13" or less), like my ultrabook, appmenu gains some space for displaying the desktop and applications.

**Comment by Posi81** [comment]
@Betterbird Sorry for the late reply.
So I'm personally not a big fan of it either. But I'd like to take a closer look.

**Comment by Betterbird** [comment]
We'll look into it some more in Issue #297.

**Comment by Betterbird** [comment]
This was implemented in Issue #297, test build available.
