### ISSUE TITLE
Clipboard data crashes Betterbird

### ISSUE THREAD

**Issue by mehlian** [Betterbird/thunderbird-patches#320]
Version: Betterbird 115.6.0-bb21 (64-bit)
OS: Windows 10

Steps to reproduce:
1. Go to this website: https://streamable.com/uvlx0k
2. RMB on video and select 'Copy Video URL' option
3. Open Betterbird and click on 'Write' button to open new message window
4. Paste data from clipboard to mail content section (using RMB and selecting 'Paste' option)
5. New message window hangs
6. Click with mouse pointer on 'To', 'Subject', and content sections
7. Betterbird closes.

'Paste Without Formating' works.

**Comment by Betterbird** [comment]
The HTML you're pasting is:
```
<html><body>
<!--StartFragment--><div style="position: absolute; user-select: text; top: -1000px; left: -1000px;">https://streamable.com/uvlx0k</div><!--EndFragment-->
</body>
</html>
```
You can see this in a 3rd party app, like FreeClipViewer or after pasting using ThunderHTMLedit in the compose window:
```
  <body style="padding-bottom: 1px;">
    <div style="position: absolute; user-select: text; top: -1000px; left: -1000px;">https://streamable.com/uvlx0k</div>
    <p></p>
  </body>
```

So basically due to the off-screen absolute placement you don't see anything. But there is no hang and no crash. Tested with BB 115.13.0-bb30.

If you can reproduce the crash on the current version, please get back to us. If you can reproduce the crash in Thunderbird, please file a ticket in their bug tracker Bugzilla. They have better crash diagnosis than we do.

Further reading: https://bugzilla.mozilla.org/show_bug.cgi?id=1276391

**Comment by mehlian** [comment]
The problem still occurs in the latest Betterbird and Thunderbird. I have submitted a crash report in Thunderbird.

**Comment by Betterbird** [comment]
What's the crash ID? You can get it from "Help > Troubleshooting Information". Did you file a bug at bugzilla.mozilla.org quoting that crash ID? If not, you should.

**Comment by mehlian** [comment]
here's my crash:
https://crash-stats.mozilla.org/report/index/f422d38a-5b74-4080-8eb7-f492a0240710#tab-details

Similar bug was already posted on bugzilla.

**Comment by Betterbird** [comment]
You mean https://bugzilla.mozilla.org/show_bug.cgi?id=1793909? Then I suggest to post your "steps to reproduce" into the ticket, they may be grateful to get a way to reproduce it. That said, just repeating the steps from your first comment **does not reproduce** the issue for me.

Also I just noticed that the result seems to depend on which browser you use for https://streamable.com/uvlx0k. In my experiments above I used Firefox. But if I use Chrome, the HTML pasted is much different:
```
<html>
<body>
<!--StartFragment--><span style="color: rgb(0, 0, 0); font-family: __Manrope_6fe9f1, __Manrope_Fallback_6fe9f1; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">https://streamable.com/uvlx0k</span><!--EndFragment-->
</body>
</html>
```
There is no absolute placement, it's mostly CSS and the net text is `https://streamable.com/uvlx0k`, not even as a link.

**Comment by mehlian** [comment]
I provided a repro in the crash window for Thunderbird.
Here is repo for Betterbird in video form.

https://github.com/Betterbird/thunderbird-patches/assets/31826615/b918859f-49f8-44e8-95e4-0c1c901e2705

**Comment by Betterbird** [comment]
Hmm, you're clicking into the addressing fields. That's all I see.

**Comment by mehlian** [comment]
and mail content section in the end

**Comment by Betterbird** [comment]
> and mail content section in the end

???

**Comment by mehlian** [comment]
> > and mail content section in the end
> 
> ???

I mean the area where I paste the contents of the clipboard (the place where you enter the email content).

> I don't understand: "I provided a repro in the crash window for Thunderbird." Where did you provide it? Nothing has changed in https://bugzilla.mozilla.org/show_bug.cgi?id=1793909

When Thunderbird crashes, new popup window appears with section where you can provide details for developers. I believe this section is only visible for Mozilla programmers.

I believe that sending an error using this mechanism should be enough for programmers to see the cause of the error and fix it (+ my reproduction steps). If this is not the case, then they should remove this mechanism from Thunderbird.

**Comment by Betterbird** [comment]
Your comments about what TB should or shouldn't do don't help us here.

If you want your problem to advance:
1. Paste the fresh crash IDs into a comment at https://bugzilla.mozilla.org/show_bug.cgi?id=1793909
2. Paste the instructions how to reproduce the crash into the same bug report.

If you don't do that, no one will look at the issue.

**Comment by Betterbird** [comment]
We've posted your information to the relevant upstream bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1793909#c5

**Comment by Betterbird** [comment]
Can you please create a Bugzilla account and follow the ticket, we don't want to play secretary here. The Mozilla devs answered:

_The crash (both this crash report and all others with the same signature that I've looked at) seems to be in IME-related code. Can you check with the user what IME and language they use, and if they can still reproduce it with the keyboard set to US English?_

I'm sure you know what IME is? It's about entering, for example, Chinese or Japanese on a "normal" keyboard.
