### ISSUE TITLE
Account colors not displaying in card view anymore

### ISSUE THREAD

**Issue by Ph15** [Betterbird/thunderbird-patches#321]
Hello Betterbird team!
I've been a very happy Betterbird user so far, and have especially liked the account color feature. Thank you for the work you have accomplished!

Account colors have worked as a charm until a few days ago. For some reason (Fedora update?), I can't see them in card view anymore, but can still see them in table view.

Do you have any clue what might be going on?

I'm running on Fedora 40 with Gnome. 
Betterbird is under latest version 115.13.0-bb30.

Many thanks for your help!
— Phil

**Comment by Betterbird** [comment]
Works fine here, this is with pref mail.threadpane.full_row_color set to true.
![image](https://github.com/user-attachments/assets/9e3e2b74-e485-4074-b1b1-bd3064978afc)

With the pref set to it's default value, it looks like this:
![image](https://github.com/user-attachments/assets/19fae2c2-479e-4800-ab98-66ad6d2b8ab4)

That was testes on Windows, if you insist, we can test it on Linux later.

Which version worked for you last? 115.12.0-bb29? There was really very little change to the new version, nothing in this area.

**Comment by Ph15** [comment]
Hi there!
Thank you for your prompt answer!
I changed the settings but it didn't help. So I thought the problem might come from elsewhere... And it was!
The theme I was using (Dark Arcturus) was apparently overriding this setting. With another theme, it works perfectly well.
Thank you!

**Comment by Betterbird** [comment]
Forgot to say: Meanwhile we've also tested successfully on Linux.
