### ISSUE TITLE
Feature Request - Maildir++ support

### ISSUE THREAD

**Issue by thx1111** [Betterbird/thunderbird-patches#325]
Just that - Maildir++ support.  Best as I can tell, Gnome Evolution Mail is the only working alternative now.  Thunderbird itself just warns that Maildir support is broken - and I don't know if it even tries to support Maildir++.

**Comment by Betterbird** [comment]
Sorry, to big of a change we can handle with a soft fork. We're mostly doing tuning, not redesigning the base product.
