### ISSUE TITLE
How to add custom type for email in Personal Address Book

### ISSUE THREAD

**Issue by fknemi** [Betterbird/thunderbird-patches#327]
## Personal Address Book
In Personal Address Book when adding a contact in email address it shows selection for type of email such as Work, Home, None.
How can i add custom type at that place...

![image](https://github.com/user-attachments/assets/96a90a2b-32e0-4858-aabd-4d4c80647d79)
![image](https://github.com/user-attachments/assets/4e823c8a-0bd8-4191-8f3f-38f10832fb16)

**Comment by Betterbird** [comment]
Apparently you can't.

**Comment by Betterbird** [comment]
Code references:
https://searchfox.org/comm-central/rev/a8f106bd47f2256ec40a6eab8bc4bd1b7e600bb1/mail/locales/en-US/messenger/addressbook/vcard.ftl#12-22

See `vcard-entry-type-custom`. That is not referenced anywhere other where it's defined:
https://searchfox.org/comm-central/search?q=vcard-entry-type-custom&path=&case=false&regexp=false

Looks like an upstream Thunderbird bug or omission. Please file a ticket at https://bugzilla.mozilla.org/.
