### ISSUE TITLE
Feature request: make emptying the trash bin more convenient

### ISSUE THREAD

**Issue by VladimirMarkelov** [Betterbird/thunderbird-patches#329]
It may be applied to any frequent operation, but emptying the trash bin bugs me the most. I guess, emptying is the most used operation on the trash bin in Betterbird 😄 Every few days I decide that I do not need any email in my trash bin any longer I want to empty it. But every time, after opening the context menu, I waste time to find the line "Empty Trash" in the context menu - it is written in the same font as the rest items, and it is hiding somewhere in the middle of the menu. I have to read the context menu items one by one until I stumble upon the required one.

Ways that can improve the situation (maybe it increases usability only for a few people but here I am mentioning all ideas I am able to generate):

1. Add an icon to the most used operations in the context menu. The trouble is that "the most used" may differ for various people.
2. A new option to empty the trash automatically at some time interval. It does not help me as I empty the bin at arbitrary intervals only when I am confident that everything in the trash is already useless to me. So, I would keep the option disabled and it solves nothing to me.
3. Add a button to a panel that shows information about the selected folder (in my example I painted "Empty" button right after the number of messages, but I did this only to minimize the size of screenshot - the button can be at the right side where the button "Message list display options" is):

![image](https://github.com/user-attachments/assets/1dda242b-73a7-40cb-9148-2a239251d045)

**Comment by Betterbird** [comment]
Not planned, sorry. You can modify the context menu already with userChrome.css, see here for example:

![image](https://github.com/user-attachments/assets/97378f2b-039c-4e35-bf8a-3e9393345da9)

This is the CSS that does it:
```
#mailContext-delete {
  color: red !important;
}

#mailContext-delete::before {
  content: url("chrome://messenger/skin/icons/new/compact/warning.svg") !important;
  -moz-context-properties: fill, stroke, fill-opacity;
  margin-right: -16px;
  fill: yellow;
  stroke: red;
}
```

That needs to be adjusted, of course.

**Comment by Betterbird** [comment]
![image](https://github.com/user-attachments/assets/90cba410-43a7-47bf-a917-1cbff5d2e9bc)

```
#folderPaneContext-emptyTrash {
  color: red !important;
}

#folderPaneContext-emptyTrash::before {
  content: url("chrome://messenger/skin/icons/new/compact/trash.svg") !important;
  -moz-context-properties: fill, stroke, fill-opacity;
  margin-right: -16px;
  fill: yellow;
  stroke: red;
}
```

**Comment by VladimirMarkelov** [comment]
I forgot that Betterbird is as customizable as Firefox and I can use `userChrome.css` to do it myself. The last your message is what I wanted.

Thank you a lot!
