### ISSUE TITLE
Systray on Linux / Notifications for new messages

### ISSUE THREAD

**Issue by sbadux** [Betterbird/thunderbird-patches#33]
Hello,
IMHO one of the main features Thunderbird lacks is the message notifications, at least in Linux. The users receive a notification of a new message only if Thunderbird is opened. This is the same behavior of BetterBird.

I'm not an heavy email user so I don't need to keep Thunderbird/BetterBird always running, but I would like to get notified if a new email is received. (E.g. Geary doesn't need to be opened to notify the new messages.)

I don't know if this can be easily implemented or not, but it would be great.

**Comment by Betterbird** [comment]
Fixed in issue #20 and will ship in 102.7.0 next week.
