### ISSUE TITLE
betterbird change language to francais automatically

### ISSUE THREAD

**Issue by 3xploiton3** [Betterbird/thunderbird-patches#332]
my default language is english, i never change language setting
this day i check betterbird change language to france,  before this happen i remove windows defender AV, i have no idea if this relate
https://github.com/ionuttbara/windows-defender-remover

![image](https://github.com/user-attachments/assets/8e30eab2-ce5d-4be0-bb4f-568c9c270810)

**Comment by 3xploiton3** [comment]
![image](https://github.com/user-attachments/assets/ae07b9a6-66ce-4e54-83ec-53e97b0672e4)

**Comment by Betterbird** [comment]
Is this Windows? Which installer did you use? Seems like you installed the French version.

**Comment by 3xploiton3** [comment]
> Is this Windows? Which installer did you use? Seems like you installed the French version.

daily command update using
winget upgrade --all

OS: Windows 11 22h2

**Comment by Betterbird** [comment]
Not our issue then, the winget people messed something up. We filed an issue there:

https://github.com/microsoft/winget-pkgs/issues/166835

**Comment by Betterbird** [comment]
Apparently winget fixed the issue.
