### ISSUE TITLE
Build Betterbird 128

### ISSUE THREAD

**Issue by depeo** [Betterbird/thunderbird-patches#335]
Hello,

I tried to build on ArchLinux Betterbird 128, I followed the instructions in the readme, and when running build.sh 128 I get this errror:
(I read that the imap bug only affects 32bit systems so i thought it was ok to test it out)
```
 0:06.59 checking for the wasm C compiler... /usr/bin/clang
 0:06.60 checking whether the wasm C compiler can be used... yes
 0:06.60 checking the wasm C compiler version... 18.1.8
 0:06.62 checking the wasm C compiler works... yes
 0:06.63 checking the wasm C compiler can find wasi headers...
 0:06.64 DEBUG: Creating `/tmp/conftest.pn_ec91s.c` with content:
 0:06.64 DEBUG: | #include <string.h>
 0:06.64 DEBUG: | int
 0:06.64 DEBUG: | main(void)
 0:06.64 DEBUG: | {
 0:06.64 DEBUG: |
 0:06.64 DEBUG: |   ;
 0:06.64 DEBUG: |   return 0;
 0:06.64 DEBUG: | }
 0:06.64 DEBUG: Executing: `/usr/bin/clang -std=gnu99 --target=wasm32-wasi /tmp/conftest.pn_ec91s.c -c`
 0:06.64 DEBUG: The command returned non-zero exit status 1.
 0:06.64 DEBUG: Its error output was:
 0:06.64 DEBUG: | /tmp/conftest.pn_ec91s.c:1:10: fatal error: 'string.h' file not found
 0:06.64 DEBUG: |     1 | #include <string.h>
 0:06.64 DEBUG: |       |          ^~~~~~~~~~
 0:06.64 DEBUG: | 1 error generated.
 0:06.64 ERROR: Cannot find wasi headers or problem with the wasm compiler. Please fix the problem. Or build with --without-wasm-sandboxed-libraries.
 ```
 
How can I fix that? I tried to install extra/wasi-libc++ but that didn't fix it.
Also, should it really use "--target=wasm**32**-wasi" on a 64bit system?

Thanks!!

**Comment by Betterbird** [comment]
Why are you building it when you can download it?
https://www.betterbird.eu/downloads/128-Preview/betterbird-128.1.0esr-bb6-build7.en-US.linux-x86_64.tar.bz2

If you ran `./build.sh 128` then there shouldn't be a problem, that's what we do. The mozconfig you get switches off wasm:
https://github.com/Betterbird/thunderbird-patches/blob/df651170a58648937b0f3288c21625d5f7e3d2fb/128/mozconfig-Linux#L6

Other than that, we can't tell what's going on with your system, perhaps your Arch is too modern. Feel free to continue the dialogue here, but we're not going to action this.

**Comment by depeo** [comment]
Oh Thanks for the quick reply, I only saw Windows on the betterbird.eu website.

**Comment by Betterbird** [comment]
> (I read that the imap bug only affects 32bit systems so i thought it was ok to test it out)

That is not correct. The IMAP corruption affects all systems, so we're in no rush to ship broken software were some users need to repair their IMAP mailboxes three times a week. The support forums are full of "e-mail not displayed correctly" reports. If you have information that is affects 32bit systems only, we're very interested.

The horrendous bug where large mailboxes were truncated to 4 GB only affected 32bit systems.

References:
IMAP: https://bugzilla.mozilla.org/show_bug.cgi?id=1890230
Dataloss 32bit: https://bugzilla.mozilla.org/show_bug.cgi?id=1911076
