### ISSUE TITLE
Betterbird 128 installer Mac (x86)

### ISSUE THREAD

**Issue by RobertvanderHulst** [Betterbird/thunderbird-patches#338]
I would like to start testing / working with Betterbird 128 on my x86 Mac.
There is only an Arm64 installer for Mac.
Are you planning the x86 installer too, or is there a technical problem preventing this?

Robert

**Comment by Betterbird** [comment]
It will be available in the next 24 hours.

**Comment by Betterbird** [comment]
You can download it now.

**Comment by RobertvanderHulst** [comment]
Thanks!
