### ISSUE TITLE
Post the changes and features you added somewhere

### ISSUE THREAD

**Issue by PoisonFrog** [Betterbird/thunderbird-patches#34]
I'm very excited by this project since there are many issues with Thunderbird right now that Mozilla devs don't fix, but I can't find anywhere a list of improvements made by Betterbird.

**Comment by PoisonFrog** [comment]
Nevermind. I finally found a feature table.

**Comment by Betterbird** [comment]
More precise information in the release notes https://www.betterbird.eu/releasenotes/ which state the exact differences for every release.
