### ISSUE TITLE
Feature request Make Title of 'Message List' clickable (Inbox)

### ISSUE THREAD

**Issue by dbojan** [Betterbird/thunderbird-patches#340]
I like to hide folder view.
I would like to be able to click on 'Inbox' in Message list title bar, and to display folders (Inbox, sent ...) so I can select current folder.
Menu that shows would look like folders view, till you click on the folder you want. After that you would be in selected folder, and menu would be hidden back.

Example is with 'stacked' view.
Screenshot of the part of BB is attached

Thanks

![inbox](https://github.com/user-attachments/assets/371cb32c-6d35-4ad9-b0de-21f59e644e37)

**Comment by Betterbird** [comment]
Use the "location" widget in the Unified toolbar, here shown when add-on QFM Classic
https://www.betterbird.eu/addons/index.html#QFM-Classic
is installed, but it works without the add-on.

![image](https://github.com/user-attachments/assets/71aa31f7-7260-4c1e-8dc3-16ad1b2a946c)
