### ISSUE TITLE
Bad sort order when showing list after global search

### ISSUE THREAD

**Issue by tag6** [Betterbird/thunderbird-patches#342]
Since it was implemented by jorgk3 I'm glad that
gloda.list.immediate set to 2
works fine opening directly the list when using the Global Search Ctrl-K.

Since 2-3 versions of Betterbird the list opens with the oldest results as first, sorted by date ascending. This is not what I want. The best option would be that it remembers the setting which was last used, I guess. Or at least sort descending, so that the newest results get shown. I'm quite sure it was one of these ways before.

The version I'm currently using is Betterbird 115.15.0-bb32 (64-Bit) Linux 64 Bit German.

I'm not sure if the issue is related to the gloda.list.immediate, but I don't use Thunderbird and don't want to start it (it will be 128 installed on Ubuntu 24.04 automatically I'm quite sure).

**Comment by Betterbird** [comment]
The order used in a new view of any kind is determined by pref mailnews.default_sort_order.
1 = ascending, 2 = descending. So please set that pref to 2.

**Comment by Betterbird** [comment]
> (It is unclear why the sort order was fine some versions ago, but I'll ignore that)

Only you can tell since this hasn't changed in ages. However, the default value of the pref has changed to 2 in TB 120. So if you had value 2, then ran a later version of TB/BB on the profile, then went back to 115, it would have dropped back to 1.
