### ISSUE TITLE
Wrong url on winget

### ISSUE THREAD

**Issue by globdug** [Betterbird/thunderbird-patches#343]
Hello,
winget url is wrong: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.15.0-bb32.it.win64.installer.exe

The updated one https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.15.0-bb32-build2.it.win64.installer.exe, right?

![immagine](https://github.com/user-attachments/assets/c4ef2f5d-d21d-4fbe-9164-16f94574cd67)

**Comment by Betterbird** [comment]
Yes, sadly we had to replace the original build with "build2". Looks like the winget people didn't follow this.
Please download the installer directly: https://www.betterbird.eu/downloads/get.php?os=win&lang=it&version=release

You can also file an issue at winget, like these:
https://github.com/microsoft/winget-pkgs/issues/166835
https://github.com/microsoft/winget-pkgs/issues/161274
