### ISSUE TITLE
Activity Manager flashes constantly when synchroniing folders

### ISSUE THREAD

**Issue by andrewbernard** [Betterbird/thunderbird-patches#344]
Since the Activity Manager pane is unique to Betterbird, this is worth reporting. When setting up, I have many thousands of mails to download in several accounts and I would like to see the progress, but Activity Manager is unusable due to the update flashing.

**Comment by Betterbird** [comment]
The Activity Manager exists in Thunderbird. The difference between TB and BB is that BB opens it in a tab instead of a (small) window. It's unclear what you mean by "update flashing". Can you post a screenshot or video?

**Comment by andrewbernard** [comment]
Yes, but Activity Manager in a tab is Betterbird only is it not?

I don't know how to make screen videos, sorry. As it is working the whole tab flashes, that is what I meant, Windows 11 Insider Prevfiew.

**Comment by Betterbird** [comment]
What is flashing, the tab title or the tab content?

**Comment by andrewbernard** [comment]
Tab content.

Windows 11 Insider Preview.

**Comment by Betterbird** [comment]
Are you using BB 115 or 128? Without seeing it, it will be impossible to fix. Does TB have the same issue?

**Comment by andrewbernard** [comment]
115. TB has a separate window for Activity manager, not a tab, and it does not show this behaviour.

**Comment by andrewbernard** [comment]
I guess you are going tohave to see it to address it, so clearly you don't see it so we may as well drop the matter. Unless there is a way to get dbug logs from the application on my computer.

**Comment by Betterbird** [comment]
I've started with the Activity Manager tab open, no flickering. Clearly, there is activity going on. 

Is it better when you switch this off:
![image](https://github.com/user-attachments/assets/6980e1c6-9a4f-440d-8644-799f4d879990)

**Comment by andrewbernard** [comment]
One final comment and then we can leave it. It happens when downloading 10,000 messages and more when setting up a connection to large existing mail account.
