### ISSUE TITLE
Feature Request: "Grouped By" w/o needing to sort 

### ISSUE THREAD

**Issue by viking2** [Betterbird/thunderbird-patches#347]
Currently I need to sort by a column to be able to group by that column.

I would like an option to be able to group by a column w/o also being required to sort by that column (That is how it woks in Outlook).

See example & discussion here: https://forums.mozillazine.org/viewtopic.php?t=3125138

**Comment by Betterbird** [comment]
What is asked for here is "threaded" (by subject/conversation) and in the thread, sorted by date descending. That's called reversed threading which is available in BB: https://www.betterbird.eu/media/img/reversed-threading.png

**Comment by viking2** [comment]
Threads are for subjects. I am not grouping by subject, but by Tag. 

I would like to group by Tag but **only** sort by date.
In other words, I want the Tags grouped and the Tag group with the latest Date show up on top.
This is how it works in Outlook.

See example & discussion here: https://forums.mozillazine.org/viewtopic.php?t=3125138

**Comment by Betterbird** [comment]
Maybe read what you wrote (quote):

I am grouping by subject and therefore need to sort by subject. My secondary sort is by date. In this case, messages are first sorted by subject and then by date within each subject. That is correct, but not what I want.
I want this:

Subject2
message (9/23/24)
message (8/05/24)

Subject3
message (9/20/24)
message (8/25/24)

Subject1
message (9/15/24)
message (8/10/24)

**Comment by viking2** [comment]
Yes, you are correct. My bad.
Threading by subject is the way to go in this case. However, for some reason the subjects were not threaded. Messages have the exact same subject line but they are not grouped together for unknown reason.
That is why I grouped by subject instead. **Not sure how to troubleshoot this?**

**In other cases**, I would like to group by Tag and only sort by date
In other words, I want the Tags grouped and the Tag group with the latest Date to show up on top.

**Comment by Betterbird** [comment]
Well, threading is different than grouping by subject. In a thread, you can change the subject, and two distinct threads can have the same subject. That's why grouping by subject doesn't make a whole lot of sense.

**Comment by viking2** [comment]
OK. I updated my post on the Thunderbird forum (https://forums.mozillazine.org/viewtopic.php?p=14985197#p14985197)
I am not sure why I can't reproduce what I get in Outlook in BetterBird. 

The goal is to "group" the conversations (Outlook terminology) and then sort them by date.

**Comment by Betterbird** [comment]
> The goal is to "group" the conversations (Outlook terminology) and then sort them by date.

The TB folks are working on a conversation view, which also includes sent messages (replies). The closest you get to this is threaded, which is why the forced threading onto everyone. Reverse threading makes it even closer.

Sorry, no can do right now.

**Comment by viking2** [comment]
Maybe an addon such as this one https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/ would work in the meantime to reproduce my Outlook results?

**Comment by Betterbird** [comment]
Yes, the very invasive "Conversations" add-on delivers something like OL's view.

**Comment by viking2** [comment]
I think that my edit may have crossed your response.

I tried the addon, but it made no difference. The subjects are still not grouped together (I have an Email list discussing various topics but the messages of each topic are not grouped like in Outlook)
