### ISSUE TITLE
Activate button in notification not doing anything

### ISSUE THREAD

**Issue by lsdijk** [Betterbird/thunderbird-patches#349]
This is happening with Betterbird 115.16.0-bb33 under Slackware64 15.0 in an Xfce 4.16 desktop environment.

When an email is received Betterbird generates a notification that shows up at the top right corner of my desktop. In this notification there is a button labeled Activate.

In previous versions of Betterbird  when clicking on that button Betterbird would automatically go to the newly-received email, display its contents in the email display area in Betterbird, and mark the message as read. With the Betterbird version above when clicking on that button nothing happens. The thing is, the version of Thunderbird that I still have in that same Slackware system (115.15.0) still works as expected in this respect, while configured exactly the same way as Betterbird when it comes to notifications.

This started happening very recently, maybe as recently as the most recent Betterbird update.

**Comment by Betterbird** [comment]
Linux is a total pain with its bazillion variations. Works fine on our Xfce with 115.16.0. Sorry, you need to work out yourself what's happening on your machine.

**Comment by lsdijk** [comment]
Well, the good news is that it is not a Betterbird problem. The bad news is that it is the interaction between KDE Connect in my new Android 14 phone and KDE Connect in my desktop: when either is not running the problem that I described does not rear its ugly head.
