### ISSUE TITLE
Compress dialogue needs to stop asking.

### ISSUE THREAD

**Issue by jakimfett** [Betterbird/thunderbird-patches#350]
When checking mail manually and at seemingly random times, a dialogue asking if I'd like to compress my message storage interrupts whatever I'm doing.

<img width="552" alt="Screenshot 2024-10-09 at 10 49 47" src="https://github.com/user-attachments/assets/90744ece-186a-4728-9e13-d555454aeb53">

**This dialogue needs a "no, and stop asking" option.**

<img width="449" alt="Screenshot 2024-10-09 at 11 02 06" src="https://github.com/user-attachments/assets/3272fdd2-7972-4a2d-86b2-4c85f6ef85b0">
I have disabled compression in my settings, and I do not want the app constantly second-guessing that decision. 

Betterbird should fix this because this is not good consent, and Thunderbird doesn't prioritize this sort of thing.

**Comment by Betterbird** [comment]
Compaction and its pesky dialogue seems to be an evergreen issue in TB. But you can switch it off, no? I never see the dialogue with this setting:
![image](https://github.com/user-attachments/assets/03854aa1-73f1-42a0-82c4-f7ab8b09d5a0)

**Comment by jakimfett** [comment]
Thanks for the response, @Betterbird ... I've updated my bug report to include that _this setting is toggled off_, and it's the lack of a way to permanently dismiss the dialogue to the negative that I am focusing on here.

**Comment by Betterbird** [comment]
We're reviewing open tickets and closing those which will likely not receive any attention.

How is this looking in BB 128? The TB folks rewrote compaction. Besides, I wasn't able to reproduce the issue in the first place, with the option turned off, I never ever see that dialogue.
