### ISSUE TITLE
Default column set for new folders or globally

### ISSUE THREAD

**Issue by nekrostr** [Betterbird/thunderbird-patches#355]
All new folders are created with a default message list column set that doesn't seem to be configurable anywhere for this specific action. 
IMO it would be more natural for each new folder that gets created to either follow the column set of its parent folder, the Inbox, or some other default definition of columns that can be customized by the user specifically for all new folders.

I tried to track down where the default column set is defined, but to no avail. I understand that when a custom folder view is applied manually, this custom column set is updated in the related MSF files (also when using the options 'Apply current view to/Apply columns to') which I think creates an unnecessary overhead, especially when updating larger archives.

Usually each user has a specific preference for the columns of the message list. So it'd be a nice feature to set it as a default somewhere, and leave that MSF config option that gets applied (^B0) for any folders that needs some very specific customization, instead of 'contaminating' all MSF files with what has to otherwise be the default for the user.

**Comment by Betterbird** [comment]
We're not planning that, see Issue #255.

**Comment by Betterbird** [comment]
There's an add-on to do this now:
https://www.ggbs.de/extensions/DefaultColumns.html
