### ISSUE TITLE
[low prior] Compress Dialogue annouce GB saved space when compress instead of MB

### ISSUE THREAD

**Issue by amseltier** [Betterbird/thunderbird-patches#356]
Since installed SUPERSTAR: Compress dialogue annouce ??? GB saved space when compress instead of ??? MB.

![Screenshot 2024-10-27 131824](https://github.com/user-attachments/assets/080934d6-9fe1-4b0c-bb5a-14b47269e797)
![Screenshot 2024-10-27 132719](https://github.com/user-attachments/assets/0c64ead5-e0b1-44a9-b098-f5cfdf9e9045)

**Comment by Betterbird** [comment]
Which version gives you the GB display? 115 or 128. 115 was called 
"Superstar", but the TB folks rewrote the compact code in 128 (which they 
call "Nebula").

**Comment by amseltier** [comment]
115.16.1-bb34 (64-Bit)

**Comment by Betterbird** [comment]
Not sure what's happening there, I've switched automatic compaction on and after a while I received:
![image](https://github.com/user-attachments/assets/7155f16d-dd6d-4c20-a3d0-a2568e77c02d)

That's in 115.

**Comment by amseltier** [comment]
No idea either. I came from 115.10... or 115.12..., updated today and started it. After, the above "Compact Folders"/"Ordner Komprimieren" window apeared as usual BUT with GB not MB.
New start of the software, same result.

Will check this the next time Betterbird ask me again for to compact folders.
It might not have any effect any other functions, I guess. So... no need for haste. :)

**Comment by Betterbird** [comment]
Have you seen this issue again? Is it present in BB 128? The TB folks rewrote compaction for 128.

**Comment by amseltier** [comment]
I am still on 115.16.1-bb34 (64-Bit) and DID NOT GET THE gigabyte MESSAGE AGAIN. 
Since the GB message only appeared while the first 2-3 starts may be there was some weird stuff cause of the 200k mails to sync?

As I wrote in caption - low priority, system works. Atm I can not replicate the message. Last ones were plausible 200-600 MB.

**Comment by Betterbird** [comment]
Thanks for the update. We won't be fixing anything in 115 any more. If it happens again in 128, we can re-open the ticket.
