### ISSUE TITLE
White background in dark theme

### ISSUE THREAD

**Issue by Li-An** [Betterbird/thunderbird-patches#359]
Hello, I discover Betterbird and I have a problem with dark themes : there is no way to show a dark background and extensions like Darko don’t work in BB. Having a white background for messages and everything else in black is terrible.

Second point : for some reason, the text is glued to the left side of the field. No padding possible and it makes things worse with dark themes.

**Comment by Betterbird** [comment]
Last we checked, [DarkReader](https://addons.thunderbird.net/en-GB/thunderbird/addon/darkreader/) worked.

The TB folks have just provided an option for dark background of messages in dark mode, currently shipping in their beta:
https://www-stage.thunderbird.net/en-US/thunderbird/133.0beta/releasenotes/

We'll evaluate this for inclusion in Betterbird.

As for your second point: which "field" are you referring to?

In general, the display is configurable with userChrome.css or userConteny.css.

**Comment by Li-An** [comment]
OK, thanks for the answer. Let’s wait for the future releases.

**Comment by Betterbird** [comment]
Try Dark Reader in the meantime.

**Comment by Li-An** [comment]
I’ve already tried it…without any effect :-(

**Comment by Betterbird** [comment]
Then you didn't try hard enough, as I wrote, it worked when I tried last. It still works:

![image](https://github.com/user-attachments/assets/97dfb751-2704-4f44-b1a7-6e31e1d15718)

**Comment by Li-An** [comment]
Well, I don’t know why it does not work fo me. I checked the options but I did not succed. Maybe something I don’t understand.

<img width="756" alt="2024-10-30_21h31_54" src="https://github.com/user-attachments/assets/6f16d817-919e-45a1-9fb3-e4a1e4428c1e">

**Comment by Betterbird** [comment]
Oh, you're using the Conversation add-on. Complain to its author.

**Comment by Li-An** [comment]
OOOOOOOOK. Thanks for the tip. I made so many different tests, I did not try to deactivate the other extensions. Thanks a lot.

**Comment by Betterbird** [comment]
Well, you know, the Conversations add-on turns TB/BB upside down. It turns chrome into content, see https://github.com/Betterbird/thunderbird-patches/issues/277#issuecomment-2002484033. Needless to say that we're not great friends of the add-on.

**Comment by Li-An** [comment]
I see…
