### ISSUE TITLE
Copying non-breaking space in plain-text composer window

### ISSUE THREAD

**Issue by pglpm** [Betterbird/thunderbird-patches#36]
Hi Betterbird team, thank you for this project full of hope! I'm trying out Betterbird hoping that some mail-composing issues for plain-text messages are solved here. Very happy to see that a couple of wrapping problems have disappeared :)

One problem still present is that non-breaking spaces (Unicode U+00A0) are replaced by normal spaces during composition of a plain-text message. This is problematic for example when writing emails that contain physics or maths text, or in languages such as French. Is there any plan to address this?

This problem seems to affect Thunderbird, Betterbird, and [Interlink](https://binaryoutcast.com/projects/interlink), but not [Claws-Mail](https://www.claws-mail.org) or Sylpheed for example.

**Comment by pglpm** [comment]
Update: Sorry, I just found out that the non-breaking spaces are actually respected – that's great!

The problem is different: if in the composer window I copy text that contains non-breaking spaces, these are somehow translated into normal spaces. Any idea why this happens? Other Unicode characters are copied correctly.

**Comment by Betterbird** [comment]
We've implemented a fix for https://bugzilla.mozilla.org/show_bug.cgi?id=359303 in https://github.com/Betterbird/thunderbird-patches/commit/ea99d04ba1eef52426636668e4ff3e2ab2c0d997. Please try the "latest build" release: https://www.betterbird.eu/downloads/

**Comment by Betterbird** [comment]
That wasn't quite right, https://github.com/Betterbird/thunderbird-patches/commit/b750ef055aac9f2ae4155d710f47e1290b88d10a fixes the issue. New build available dated 2022-03-08.

**Comment by Betterbird** [comment]
We're also addressing https://bugzilla.mozilla.org/show_bug.cgi?id=532712. Ctrl+Shift+Space will now insert a NBSP. That works well in a plaintext composition. In a HTML composition, the NBSP is inserted, but the next character typed removes it again. It works fine when inserting a NBSP between two other characters. To be continued.
