### ISSUE TITLE
Manual XPI install fails silently ; no console logs

### ISSUE THREAD

**Issue by ferrieux** [Betterbird/thunderbird-patches#360]
I'm using 115.17.0-bb35, but the issue was already there in bb24.
Currently, whenever I try to install an XPI manually, it fails silently: nothing happens in the GUI after I select Open from the file chooser.
No logs in the debug console.

An strace of the betterbird process shows no obvious syscall-level errors, nor any clear write() to a log file, while it does load the XPI and reads it entirely. Just no visible effect afterwards.

This happens with all the XPIs I have tried so far.

Please advise on enabling low-level logs of the installation process.

**Comment by ferrieux** [comment]
Sorry, this is Linux (Debian 11) - as you might guess from my mention of strace ;)
I assume something is wrong on my system or config: I don't imagine the rest of the world has had the issue and suffered in silence for months...
But to understand what's wrong, I need some verbose logging of the installation process.

**Comment by Betterbird** [comment]
And there is nothing in the Error Console (Tools >Developer Tools)? What do you mean by "debug console"?

Is this a [FlatPak](https://github.com/flathub/eu.betterbird.Betterbird/?tab=readme-ov-file#lacking-file-permissions--inconsistent-access) install or an install from the tar.bz2?

**Comment by ferrieux** [comment]
Indeed, nothing in the Error Console (that's what I meant by "debug console", sorry)
This is a tar.bz2 deployment.

**Comment by Betterbird** [comment]
Pref extensions.logging.enabled doesn't help? With that set, I get a bit of logging, but nothing really useful. I'd have to dig some more.

**Comment by ferrieux** [comment]
Thanks for the tip, didn't know. But still no sugar :(

**Comment by ferrieux** [comment]
Update: I followed the hint of the option you suggested, and generalized to the list given in [https://udn.realityripple.com/docs/Archive/Add-ons/Setting_up_extension_development_environment](here).
With that, I got *one* interesting log line when trying to install `owl.xpi`:

```shell
1730322634895	addons.xpi	INFO	Install of owl@beonex.com cancelled by user 
```
So clearly BB "thinks" I cancelled, though didn't see (let alone click or Esc) anything.

I know that many extensions start their lives with a pop-up. Could it be some issue with a pop-up that failed to materialize ?

**Comment by Betterbird** [comment]
Yes, see this code:
https://searchfox.org/mozilla-esr115/rev/fed25a325f446b0a48d2480637b9b4b688b9cd0f/toolkit/mozapps/extensions/internal/XPIInstall.jsm#1703 (and a few lines up).

So for some reason the prompt fails and that's the result.

**Comment by ferrieux** [comment]
Ha ! Thanks for the source. For some reason it's hard to land on it by naive Googling.
Starting from there, I used the js debugger to single-step through `checkPrompt`, using "step inside (F11)" to avoid missing anything.
Doing this, I pretty quickly land into `_verifyThirdPartyInstall`, and the inspection shows `lazy.WEBEXT_POSTDOWNLOAD_THIRD_PARTY` to be **false**.
As a consequence, I believe we are in the situation described by the first comment: "If we are not post-download processing, this panel was already shown"


```js
  _verifyThirdPartyInstall(browser, url, install, info, source) {
    // If we are not post-download processing, this panel was already shown.
    // Otherwise, if this is from AMO or local, bypass the prompt.
    if (
      !lazy.WEBEXT_POSTDOWNLOAD_THIRD_PARTY ||
      ["AMO", "local"].includes(source)
    ) {
      return Promise.resolve();
    }
```

**Comment by Betterbird** [comment]
This is all Mozilla platform code used in Firefox, Thunderbird and Betterbird. The TB folks and us don't have a whole lot of knowledge of it. We treat it as an "upstream toolkit". So does TB behave any differently? Does the debugger allow to change values or continue execution elsewhere? (Seems like a silly question, but since we're actually building the product, we don't use the debugger. Maybe we should.)

**Comment by ferrieux** [comment]
Yes, TB behaves normally, but the comparison is unfair as so far I didn't have the opportunity to use it with the very same profile (for fear of breaking it).  I agree I should spend some time playing with fresh profiles on both TB and BB...

In the meantime, I feel you guided me to within an Angstrom of the solution: thanks a million for that already. So, even if it is actually a TB bug in the end, I'd love to cross that last Angstrom :)

I'll try to tweak the values within the debugger and report.
In the meantime, I'm puzzled because I traced that "postdownload" to something that looks like config entry `extensions.postDownloadThirdPartyPrompt` ... which was absent from the profile ; but even after setting it to `true` ... still no effect.

**Comment by ferrieux** [comment]
Update !
Two pieces of good news:
  1. The debugger *does* allow to change values on-the-fly: just switch to console, and type the needed assignment in the JavaScript RELP loop there. The scope will be that of the current breakpoint :)
  2.  Replaying the same scenario, I found that the postdownload flag was properly set to `true` now ! 
So, now I know why it still doesn't work: it is the very next line, the test 
```js
      ["AMO", "local"].includes(source)
```
Indeed, `source` has the value "local" at that time.

Any idea why ?

**Comment by Betterbird** [comment]
It's a local (manual) install, right?

If you're afraid of running BB on the TB profile (assuming the same version), make a backup. You seem to enjoy hacking, but second-guessing someone else's code you've never seen before may not be the most productive way to solve the issue.

**Comment by ferrieux** [comment]
Yes, manual from XPI file.
I finally did what you suggest, and indeed TB behaves the same as BB on this profile, and both work properly on a fresh one.
Looks like this decades-old profile (migrated from TB to BB a few months ago) carries much cruft.
The diff with the fresh profile is daunting, as you might guess (wonder why uninstalling extensions *never* cleans up their config entries)
Anyway, sorry for bugging you with something that lies upstream. Will reopen there.

**Comment by Betterbird** [comment]
> ... upstream. Will reopen there.

They (Mozilla) won't be interested in issues related to TB which can be fixed with a new profile.

**Comment by ferrieux** [comment]
Maybe not for such a specific case, but it is directly linked with a very general issue:
There are "corners" in the configuration space that lead to unusability.
And, they can be reached *without* any manual config edits, just by migrating from TB to BB.
So, at least these corners should be either *detected* or *prevented*, don't you think ?

**Comment by Betterbird** [comment]
Sure, but you need to make the corner case reproducible: "Doesn't work on an old profile" is not an actionable report.
