### ISSUE TITLE
A popup keeps flashing about credentials

### ISSUE THREAD

**Issue by ReyVGM** [Betterbird/thunderbird-patches#363]
I don't know if this is a bug or what. 

I just installed BB a few hours ago, I added my hotmail accounts and configured everything. It was working perfectly, but now I keep getting this popup every time I click on any of my folders. 

![New Bitmap Image](https://github.com/user-attachments/assets/79066d8b-c5ea-470c-a4df-8dc53e64437b)

I don't mind if this is something BB needs to do, but is there anyway to have this happen in the background without interrupting me all the time?

Thanks!

**Comment by Betterbird** [comment]
Seems like a configuration issue. The OAuth2 credentials should be stored in the password manager and uses, when the server requests them. The account is configured with OAuth2 and the server is outlook.office365.com?

**Comment by ReyVGM** [comment]
> Seems like a configuration issue. The OAuth2 credentials should be stored in the password manager and uses, when the server requests them. The account is configured with OAuth2 and the server is outlook.office365.com?

Yep. Everything was already populated automatically when I entered my hotmail email and pass.

**Comment by Betterbird** [comment]
Possible, but which authentication method is it using and which server? It should be OAuth2 and outlook.office365.com.

Does it help to clear preferences ending in `oauth2.scope` in the config editor, of course only if the configuration is correct.

**Comment by ReyVGM** [comment]
> Possible, but which authentication method is it using and which server? It should be OAuth2 and outlook.office365.com.
> 
> Does it help to clear preferences ending in `oauth2.scope` in the config editor, of course only if the configuration is correct.

Yes, the account is configured with OAuth2 and the server is outlook.office365.com

What has helped (so far) is disabling cookies. However, the same site that suggested that, said that it will eventually ask again, so I'm not sure.

Do you think changing the option "When a server requests my personal certificate" to "select one automatically" will help getting rid of the popup?

**Comment by Betterbird** [comment]
Disabling cookies will rather make the problem worse. And it's not related to personal certificates. Which anti-virus are you using?

**Comment by ReyVGM** [comment]
> Disabling cookies will rather make the problem worse. And it's not related to personal certificates. Which anti-virus are you using?

Just the default windows one (Defender).

**Comment by ReyVGM** [comment]
Turning on cookies brought the popup back.

Let me try the oauth2.scope suggestion.

**Comment by Betterbird** [comment]
There are general OAuth2 issues in TB and hence BB. However, we haven't heard that the OAuth2 prompt comes up in every single session, it doesn't happen to us on our O365-based account.

You could try how TB 128 behaves and then TB 133 beta, their latest beta, where a lot of OAuth2 changes have been made. Those changes haven't been backported to 128. In fact, they tried, failed and reverted all the backports.

**Comment by Betterbird** [comment]
There are quite a few reports online, for example:
https://answers.microsoft.com/en-us/outlook_com/forum/all/thunderbird-v115-just-came-out-keeps-prompting-me/2e4b27c9-da60-4f09-b7a4-3f062722dfda?page=1
On the second page they suggest deleting cookies.

**Comment by ReyVGM** [comment]
Thanks for the reply. I'm not using TB or BB 128 because the site's notes say that it's kind of broken? So I used version 115 because that's the one that seems to be more stable.

Anyway, the credentials popup hasn't appeared since yesterday. If it does appear again, then I'll turn off cookies like I did before. And if _that_ causes new issues, then I'll try the newer BB128 versions then.

Thanks for all the assitance!

**Comment by Betterbird** [comment]
Right, TB/BB 128 can cause IMAP problems. It's not clear yet whether the last fixes shipped in 128.3.3 fixed the issues.
I wasn't saying to switch to 128 or TB 133 beta, you could have created a test profile.

I'm closing the ticket since I don't think we can "fix" anything here. Of course we can continue the communication here.
