### ISSUE TITLE
[REQUEST] System tray functionality enhancement 

### ISSUE THREAD

**Issue by DDjivan** [Betterbird/thunderbird-patches#366]
### Request 
- Add an option for "Hitting close button will make Betterbird move to the tray instead of closing"; 
- Keep the existing option for "Hitting minimize button will make Betterbird move to the tray" to not dissatisfy users who prefer this method; 
- Less important: Add an option for "Start to system tray when Betterbird is launched". 

### Explanation 
Most applications have a "move to tray" functionality using the close button, which aligns with user expectations. Betterbird's current behavior is an exception, which may frustrate users who use this kind of option. 

If users need to fully close Betterbird, they can still use `File > Quit` or the `CTRL+Q` shortcut. Additionally, a right-click on the Betterbird system tray icon could provide a convenient `Quit` option.

**Comment by Betterbird** [comment]
See
https://github.com/Betterbird/thunderbird-patches/issues/244#issuecomment-1873557127
And Issue #311.
