### ISSUE TITLE
thunderbirds profile folder gets deleted when purging betterbird

### ISSUE THREAD

**Issue by 1u** [Betterbird/thunderbird-patches#367]
## steps to reproduce

- installing betterbird on linux with flatpak
- importing existing profile from thunderbird by pointing to the  `foo.profile` directory (looks like it copies the folder to somewhere -> diskspace is used..)
- removing betterbird again with `flatpak uninstall --delete-data betterbird`

## bug
Problem: this results in the original profile folder is emptied  (happy i did a backup just before starting...)

## further info

You state you can switch between thunderbird and betterbird in https://www.betterbird.eu/support/

**Comment by Betterbird** [comment]
Yes, you can switch, but that page doesn't mention FlatPak which has it's own rules. It's not quite clear what you've done "pointing to the `foo.profile`. The specific FlatPak instructions are here, so please file an issue over there:
https://github.com/flathub/eu.betterbird.Betterbird/?tab=readme-ov-file#migration-from-pre-exisiting-installations

I'm CC'ing the FlatPak maintainer @mfschumann here.
