### ISSUE TITLE
The message count randomly drops in a Saved Search Folder using complex filtering

### ISSUE THREAD

**Issue by viking2** [Betterbird/thunderbird-patches#369]
I have a Saved Search Folder with 14 inboxes using complex filtering of the type discussed here (but without the last two lines): https://github.com/Betterbird/thunderbird-patches/issues/365 

I have about 24K messages in the Saved Search Folder, and several thousand messages are randomly disappearing from the message count during the day. 

For example, a few minutes ago, the count was 21,238 messages. I manually updated the Saved Search Folder and the count is now 23,836. The drop in message counts happens several times during the day and  I don't know what causes it or exactly when it happens.

I manually update the Saved Search Folder several times/day (However, it takes 4-5 min with very high CPU and makes my PC unresponsive).

This issue may be related, or even be identical, to this one: https://github.com/Betterbird/thunderbird-patches/issues/368

I am not sure how to troubleshoot this?

**Comment by Betterbird** [comment]
Does that happen if all envolved folders are IMAP? Can you supply a reproducible case? "several times/day" and "randomly" doesn't sound like something we can fix without being able to reproduce it.

**Comment by Betterbird** [comment]
Let's close this for now until we addressed #368.

**Comment by viking2** [comment]
Yes, all involved folders are IMAP. I realize that this is very difficult to fix without being reproducible.
It is difficult to supply a case with so many (private) messages. I agree to wait with this until we figure the cause of https://github.com/Betterbird/thunderbird-patches/issues/368. 
I am in the process of marking all messages (about 10K) as read. It may simplify things.
