### ISSUE TITLE
Refresh folder tree

### ISSUE THREAD

**Issue by pglpm** [Betterbird/thunderbird-patches#37]
Betterbird 91.7.0-bb28 (64-bit) on Windows 10.

This is a minor issue for me at least, but it'd be great to see it fixed sometimes in the future.

Consider an IMAP folder tree for some account. At the moment there seems to be no way to refresh it if there are any changes made to it from outside (server or some other client). The only way seems to be to quit and restart Betterbird.

In some early version of Thunderbird a refresh was possible through context-menu ("Refresh folder tree"); later I think that by closing and reopening the folder tree on the "Folders" panel achieved a refresh. But this doesn't seem to be the case in Betterbird.

**Comment by Betterbird** [comment]
What happens of you do a subscribe on the server, that should refresh the folders.

**Comment by pglpm** [comment]
I now checked, and yes this only happens with Gmail's labels, not with folders created on a mailserver.
I'm in the process of quitting Gmail for good, so this bug won't be much of an issue for me :)

**Comment by Betterbird** [comment]
Yes, I think TB needs to fix this.
