### ISSUE TITLE
Avira Antivirus puts Betterbird files into Quarantine

### ISSUE THREAD

**Issue by ThiloteE** [Betterbird/thunderbird-patches#371]
![image](https://github.com/user-attachments/assets/40b532a2-bd0b-4e1e-bb16-542c438473e6)
Betterbird continues to run, but it makes me think if this might have adverse affects on the running instance that I just failed to notice. I have files from Betterbird in the quarantine since June 2023. I do not remember, if this was the time of me installing Betterbird on this machine or not.

I assume Betterbird is not signed by Windows? So maybe it's a false positive.

It is possible to send suspicious files to Avira via this link: https://www.avira.com/de/analysis/submit. I have not done so, because I don't know what file exactly I should send.

**Comment by Betterbird** [comment]
Why do you report an Avira issue to us? Please report to them. Also read https://www.betterbird.eu/support/
Is Betterbird a virus?

Sometimes virus scanners raise an alert for the Betterbird installer or the installed executable. If you've downloaded the installer from our website, these are false alarms. You can submit alleged malicious code to a recognised online virus scanner like [VirusTotal](https://www.virustotal.com/) or [Jotti](https://virusscan.jotti.org/). We are self-signing all executables, you can [download](https://www.betterbird.eu/downloads/index.php) our certificate which you need to [install](https://www.betterbird.eu/support/certmgr.png) into "Trusted Root Certification Authorities" (check with certmgr.msc). The result looks like [this](https://www.betterbird.eu/support/uac.png). For our own use, we've excluded the Betterbird program directory and process from further scans.

Betterbird doesn't contain any more malicious code than the Thunderbird or Mozilla codebase, but we admit that we haven't inspected the millions of lines of upstream code. The binaries we distribute are built from open source code and you can build the package yourself using the instruction on the [Github repository](https://github.com/Betterbird).
