### ISSUE TITLE
Question: color for folders and account

### ISSUE THREAD

**Issue by topoldo** [Betterbird/thunderbird-patches#373]
Hi all!
Herein I report a **question** not a bug about BB/TB.
BB at first (and now also TB) have the possibility to set a color for each account.
The main reason I would like to take advantage from this opportunity is to be sure to send an email from the appropriate account.
So until today I used the addon [BorderColorsD](https://addons.thunderbird.net/en-us/thunderbird/addon/bordercolors-d/).
Now I tried to use this new setting also in BB, so I went to AccountSettings -> Color and I got what it is reported in the image below, ie:
a) all the folders of an account were colored
b) the field "From:" of the composition message has the background color which is the same of the account which was used for the composition.

![Actual](https://github.com/user-attachments/assets/896801ea-b7e4-4834-a8e1-6cec4b402c25)

Now the question(s):
1. Is it possible to have a situation like it is reported in the image below with regard to Microsof account?
    I did not find any way to get it or something like it!
3. What is the effect to set  to **true** the preference **mail.threadpane.full_row_color**?
I tried to set it but I didn't see any change (maybe because my accounts/folders/view were set in such a way that they could not show any difference.

![Wanted](https://github.com/user-attachments/assets/25e2cfc0-94d7-42be-9820-909b055eeff1)

TIA for any clue on this subject

Best regards,
Leopodo aka Topoldo

**Comment by Betterbird** [comment]
> Herein I report a question not a bug about BB/TB.

For questions and support, please use the support e-mail.

> BB at first (and now also TB) have the possibility to set a color for each account.

TB's implementation is total shambles. It gives you the coloured dot when composing and it gives you a coloured account icon in the folder tree. No colouring of the folder tree, no colouring of the thread tree/message list, the bug where they wanted to implement this has been forgotten: https://bugzilla.mozilla.org/show_bug.cgi?id=1882368

For the questions:

You want a coloured header, maybe that's doable with userChrome.css. The BB implementation colours the entire part of the tree belonging to the account.

mail.threadpane.full_row_color does this:
![image](https://github.com/user-attachments/assets/0c3f882b-9ea1-4ef3-a7c7-b759b0c24a09)
but of course only in virtual folders based on multiple accounts.
