### ISSUE TITLE
Thunderbird icon instead of Betterbird one

### ISSUE THREAD

**Issue by topoldo** [Betterbird/thunderbird-patches#375]
Hi all.
My OS system: Windows11 24H2
My Betterbird version: 128.5.0esr-bb18 (64 bit)

If I go to:
Tools > Developer Tools > Addons Debug
I have a new tab whose aspect is reported in the image below, which still contains a TB icon which I emphasized inside a red rectangle

![Senza titolo](https://github.com/user-attachments/assets/c2c3e478-141d-4406-96f4-e9d0ce634f7a)

Yours sincerely,
L. Saggin aka Topoldoo

**Comment by Betterbird** [comment]
Thanks for the report, we need to override this:
https://searchfox.org/comm-central/search?q=aboutdebugging-firefox-logo&path=&case=false&regexp=false

We'll fix it in the next version, the normal user wouldn't notice it, so it's more cosmetic.

**Comment by topoldo** [comment]
> We'll fix it in the next version, the normal user wouldn't notice it, so it's more cosmetic.

Of course!
I pointed out it just because I wanted to make Betterbird a ...better Betterbird ;-)

**Comment by Betterbird** [comment]
Fixed:
![image](https://github.com/user-attachments/assets/19f455a6-69df-481e-8f9a-eb52a1ae7e3b)
