### ISSUE TITLE
[Faceted Search]: Option to make "Open as List" view the default view

### ISSUE THREAD

**Issue by nietsmmar** [Betterbird/thunderbird-patches#381]
I always click `Show results as list` after searching for something. The default search UX is not helping me most times. It would be really really nice if there could be a setting to make the list-view default when searching.

Since waiting for this feature request to be implemented for years I thought that maybe the Betterbird team is more interested in this.

This feature request was filed 14 years ago at [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=580252)  with bug number `580252`.

**Comment by Betterbird** [comment]
Please check the features **before** requesting new ones.

https://www.betterbird.eu/#featuretable
Global search results can open to list view - Yes!

https://www.betterbird.eu/expert-tips/
gloda.list.immediate	Gloda search results: 0: Facet view, 1: Facet view and list view, 2: List view only.

https://www.betterbird.eu/releasenotes/
NEW - New preference gloda.list.immediate to show the search result as list immediately without having to click "Show results as list". Values: 0: Facet view, 1: Facet view and list view, 2: List view only. - Bug 580252
