### ISSUE TITLE
Start page will not display a local html page.

### ISSUE THREAD

**Issue by ChooChooAl** [Betterbird/thunderbird-patches#382]
In settings you can pick something for your start page.
In Thunderbird I can specify file:///home/alan/.thunderbird/GoHome/index.html
and it works.
But putting /home/alan/.thunderbird/GoHome/index-BB.html or
file:///home/alan/.thunderbird/GoHome/index-BB.html doesn't work.

And yes, I've checked.  Putting that link in Firefox's URL bar brings up what I want. 
I'm running Thunderbird 128.5.2esr, and Betterbird in flatpak  128.5.2esr-bb19 (64-bit)
On Linux Mint 22

**Comment by Betterbird** [comment]
It works, tried on Windows with: file:///D:/Desktop/sig.html

For FlatPak it's likely a sandboxing issue. (If we had a dollar every time we get a bug reported on that, we'd sit under a palm tree on the Bahamas.)

https://github.com/flathub/eu.betterbird.Betterbird/?tab=readme-ov-file#lacking-file-permissions--inconsistent-access

**Comment by ChooChooAl** [comment]
Thanks.  Then I'll install the normal download version.  
It's probably what most people are using anyway.

**Comment by Betterbird** [comment]
Well, some distros like Mint install BB via FlatPak in their software manager. That give it good exposure, sadly with some FlatPak-inherent problems. Check out the install script:

https://github.com/Betterbird/thunderbird-patches/tree/main/install-on-linux
