### ISSUE TITLE
Run of spaces N long changed to N-1 non-breaking spaces and a space

### ISSUE THREAD

**Issue by RalphCorderoy** [Betterbird/thunderbird-patches#386]
When configured to send a plain-text email, Betterbird (and Thunderbird) replace a run of N spaces where N>1 with N-1 non-breaking spaces, U+00A0, followed by a space. This is often visible to me, a non-*bird user, when plain-text emails arrive from Betterbird where the author follows the 'two spaces at the end of a sentence' convention: `The start.  The end.` becomes `The start.  The end.` where the inter-sentence gap is U+00A0, U+0020.

This 'A0+20' is an unusual convention and interferes with Unix text processing which expects only spaces there, with non-breaking spaces used for keeping words together, e.g. `25th Dec`. For example, when replying, editing the draft in vi(1), and cutting down the quoted text, the normal sentence-movement commands like `)` don't see the end of the sentence.

My guess is Betterbird's email-composition box is always fancy-formatting behind the scenes even if the email is in plain-text mode at that point, and that some historical aim was for a run of spaces used to indent and align to persist into a HTML rendering for a text/html email. A text/plain email writer can enter an explicit non-breaking space when required.

**Comment by Betterbird** [comment]
Your description isn't 100% accurate.

In a plaintext composition, no NBSP is inserted. However, it you compose in HTML and that's "downgraded" to plaintext upon sending, then the NBSP that was inserted into the HTML composition is maintained. I've just tested it.

Overall, that's the behaviour of the underlying Mozilla platform code, the editor and the serialiser. We won't action this.

**Comment by RalphCorderoy** [comment]
Thanks for your time and prompt response.

So I should explain to *bird users that there's a difference between 'Send plain text messages', which downgrades to plain text on sending, and 'Completely plain email', and that the latter needs to be used if they want their 'two space' typing to be sent verbatim?

- https://kb.mozillazine.org/Plain_text_e-mail_-_Thunderbird#Send_plain_text_messages
- https://kb.mozillazine.org/Plain_text_e-mail_-_Thunderbird#Completely_plain_email

**Comment by Betterbird** [comment]
That sounds about right.

People who want to send plaintext usually switch off HTLM composition in the Account Settings.
