### ISSUE TITLE
EN-US language pack XPI

### ISSUE THREAD

**Issue by ethanblock** [Betterbird/thunderbird-patches#387]
When I installed Betterbird off flathub, it defaulted to EN-GB for the language pack. I would like to change it to EN-US, but the XPI isn't published on the Betterbird website. Please add. Thank you.

**Comment by Betterbird** [comment]
Please don't file support requests or FlatPak issues in this repository. FlatPak issues should be filed at:
https://github.com/flathub/eu.betterbird.Betterbird/

That said, as I understand it, FlatPak ships with all available language packs integrated into the product, so all of them arrive pre-installed. It's just a matter of selecting the desired language in the settings.
