### ISSUE TITLE
Copy account to clipboard

### ISSUE THREAD

**Issue by SamHobbsOrg** [Betterbird/thunderbird-patches#388]
This is a suggestion (feature request).

I could really use a context menu item to copy the account (such as whoever@example.com) to the clipboard. Currently I can right-click an account then select settings then copy the account from there. If the context menu had an item to copy the account to the clipboard then that would be a useful feature. Definitely not a big issue either way but I assume it is very easy to do.

**Comment by Betterbird** [comment]
What do you mean by "copy the account to the clipboard". The account is a collection of data, account name, e-mail, server settings, etc. What do you want copied?

**Comment by SamHobbsOrg** [comment]
I think the obvious is what I mean. I am not sure what terminology to use, I wanted to avoid someone complaining if my terminology is not their terminology.

In _Settings_ it is called _Account Name_. I gave the example whoever@example.com; I just want the text `whoever@example.com` to be put into the clipboard.

**Comment by Betterbird** [comment]
The account name is at the top, the e-mail address is below. There is no need for a context menu to select and copy a text input field, especially given that there are at least two relevant fields.

**Comment by SamHobbsOrg** [comment]
I probably mean email address. I am saying it would be a convenience, for use in other applications. I often need to provide my email address for a variety of purposes. It would be convenient to be able to copy the email address more conveniently.

**Comment by Betterbird** [comment]
Hmm, the emphasis is on "other applications". Usually you write to someone and that transmits your e-mail address.

I don't know what "other applications" you're referring to. If it's about filling in some data on the web, the browser's "auto fill" should take care. Besides, for new registrations you need to copy/paste other data. I don't see a point in adding a context menu to the account manager just to have a convenient way to copy the e-mail address from. Especially in Betterbird, where additional UI strings cause a lot of extra work.

**Comment by SamHobbsOrg** [comment]
I am not asking for anything that only has value for me. I think however this would have value for many. If I am wrong then it should be ignored.

You say _additional UI strings cause a lot of extra work_ and that is a good reason to not do it.

I cannot think of many of the times that I could have used the feature but currently one example is the UPS website. UPS is a shipper. I must type in my email address each time I sign in. Unlike most websites, my browser does not fill in the user name and the website does not offer the option to fill it in for me.

**Comment by RealRaven2000** [comment]
> I cannot think of many of the times that I could have used the feature but currently one example is the UPS website. UPS is a shipper. I must type in my email address each time I sign in. Unlike most websites, my browser does not fill in the user name and the website does not offer the option to fill it in for me.

you haven't even specified from where exactly you want to have the

>   context menu item to copy the account 

In the address book? in an email / thread list? in the header area above the mail preview? That one already exists, if you right-click any sender, you can select "copy email address":

![image](https://github.com/user-attachments/assets/fad72ad8-2f51-45ee-8f4d-fdb5751341e6)

and if you haven't got an email from UPS, where would you look it up in Betterbird? Would you search for an email from UPS first, or would you open address book and hope to find it there?

**Comment by RealRaven2000** [comment]
> This is a suggestion (feature request).
> 
> I could really use a context menu item to copy the account (such as [whoever@example.com](mailto:whoever@example.com)) to the clipboard. Currently I can right-click an account then select settings then copy the account from there. If the context menu had an item to copy the account to the clipboard then that would be a useful feature. Definitely not a big issue either way but I assume it is very easy to do.

ok, I reread the original request. You mean on the account nodes in the thread list. Sounds a little cluttery to me, but it would be very easy for a mail extension to implement. unfortunately I do not have bandwidth for this, but maybe check out the thunderbird forums and suggest it there.

**Comment by SamHobbsOrg** [comment]
An extension seems a reasonable solution.
