### ISSUE TITLE
xdg_activation_v1 protocol for outbound requests

### ISSUE THREAD

**Issue by ethanblock** [Betterbird/thunderbird-patches#389]
When I click on an http link  in betterbird, it opens a new tab in my browser (Vivaldi) without brining my browser window to the foreground. I'm not sure what is happening because mailto links do open a betterbird compose window in the foreground and non-betterbird apps with xdg_activation_v1 implementation open Vivaldi in the foreground. I am running betterbird in Wayland.

Betterbird UA: Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Thunderbird/128.5.2
Vivaldi UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

**Comment by Betterbird** [comment]
There are to many variations on Linux, besides, this looks like a Vivaldi 
issue. IIRC, there were Vivaldi activation issue in the past, I'd have to 
find the reference. You're better off asking in a Vivaldi forum.

If it's not a Vivaldi issue, it will be a Mozilla issue and TB will 
behave the same.

We won't action this.
