### ISSUE TITLE
Markdown support in betterbird?

### ISSUE THREAD

**Issue by deknos** [Betterbird/thunderbird-patches#39]
Hello,
i suppose that is too much to ask, but i wanted to know if it was possible to include markdown rendering in emails? there's even an RFC for that: https://datatracker.ietf.org/doc/html/rfc7763

**Comment by Betterbird** [comment]
Nothing new under the sun, https://bugzilla.mozilla.org/show_bug.cgi?id=1280912

Yes, it's a big ask. Personally I don't see how this can be useful since you can already edit the e-mail as HTML. Transmitting markdown isn't feasible since no other client will support it.
