### ISSUE TITLE
[Request] macOS prebuilts

### ISSUE THREAD

**Issue by thefiredragon** [Betterbird/thunderbird-patches#43]
Dear all, could you also support macOS builds of your betterbird project? 
When no I would try to build it
best Regards

**Comment by Betterbird** [comment]
We have no Mac hardware and won't provide a version for Mac. Some other people were interested in building it on Mac, so here are some hints:
- You may be able to adapt the Linux Ansible build, https://github.com/4ch1m/ansible-betterbird
- Likely that Ansible build doesn't cover the build pre-requisites for Mac (XCode?, etc.)
- Likely that the build will need some tweaks like here: https://github.com/Betterbird/thunderbird-patches/blob/main/91/branding/05-branding.patch
- The code has never been tested on Mac, so it's likely that some stuff doesn't work
- Localisation in its current form won't work on Mac, we basically repackage the installer files on Windows with Windows scripts.

**Comment by Betterbird** [comment]
We've done some tinkering ourselves with this result: https://github.com/Betterbird/thunderbird-patches/commit/780fabdfabe2d3c68d6fec51f8dade397d5b697a.

We'll see whether that gets it built.

**Comment by Betterbird** [comment]
OK, with the latest commit https://github.com/Betterbird/thunderbird-patches/commit/37910dec57b90303e6f51ce514c0f79297379e6b we managed to build Betterbird on Mac, albeit without icons (.icns file). We'll add this soon and then we'll see whether we can get it packaged (mach package).

How are you going?

**Comment by Betterbird** [comment]
There is a Mac build now: https://www.betterbird.eu/downloads/ - MacDiskImage. Built on an Intel Mac under macOS 12 "Monterey". No idea on which Macs this will run.

**Comment by thefiredragon** [comment]
Thank you very much, it's working on my intel mac :)

**Comment by thefiredragon** [comment]
And I love yet the multiline view, I can't understand why thunderbird this after so many years do not implement

**Comment by Betterbird** [comment]
Hmm, well, my wife went BB with multiline, looked good on her screen. I'm still grappling with it, I don't know I like it that much. You can customise that a lot, see https://www.betterbird.eu/expert-tips/userChrome-ol.css or https://www.thunderbird-mail.de/forum/thread/88749-css-anweisungen-nicht-gefunden/ (in German). I'm using:
```
treechildren::-moz-tree-cell-text(multiline, untagged) {
  color: rgb(0, 114, 198) !important;
}
treechildren::-moz-tree-cell-text(multiline, colspan, untagged) {
  color: black !important;
}

treechildren::-moz-tree-cell-text(multiline, colspan) {
  font-style: normal !important;
}

treechildren::-moz-tree-row(multiline, unread) {
  border-left: 2px solid rgb(0, 114, 198) !important;
  background-color: rgba(0, 114, 198, 0.03) !important;
}

:root[uidensity="compact"] treechildren::-moz-tree-row(multiline) {
  margin-top: -1px !important;
  height: 2.4rem !important;
}
:root[uidensity="compact"] treechildren::-moz-tree-colspan {
  margin-top: 1.2rem !important;
}
:root[uidensity="compact"] treechildren::-moz-tree-cell(multiline) {
  min-height: 1.2rem !important;
  height: 1.2rem !important;
}
```

I tried it on a VM with 10.15 and it worked there, too. Delivering in a language other than English will be tricky:

https://sourceforge.net/p/sevenzip/feature-requests/1559/
