### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by fredtempez** [Betterbird/thunderbird-patches#44]
Hi,
Thanks for this great update of Thunderbird. How do I install translation file (french.cmd) in binary versions ?
Thanks for your support.

**Comment by Betterbird** [comment]
There seems to be a misunderstanding. fr.cmd is a script we use for localisation into French. You can't use it unless you compile/build Betterbird yourself. We ship localised binaries, see here: https://www.betterbird.eu/downloads/index.php
Windows: https://www.betterbird.eu/downloads/get.php?os=win&lang=fr&version=release
Linux: https://www.betterbird.eu/downloads/get.php?os=linux&lang=fr&version=release
