### ISSUE TITLE
Subject column missing after testing Betterbird and switching back to Thunderbird

### ISSUE THREAD

**Issue by captainawol** [Betterbird/thunderbird-patches#45]
Windows 10, Betterbird 91.8.0, Thunderbird 91.8.0.
I don't know that this is a bug, but I wanted to give Betterbird a try and since it said it is 100% compatible with Thunderbird I directed it to my current profile. It looks fabulous and I am very impressed, but have not yet 100% decided to switch permanently, so I switched back to Thunderbird and the subject column is no longer there and it doesn't appear that it can be turned back on easily. I will rebuild my profile if I have to, just thought I would put a note here to bring it to the developers attention. (perhaps it is already mentioned somewhere, admittedly I didn't read all the wiki and release notes prior to trying Betterbird) 
Anyway excellent project!!

**Comment by captainawol** [comment]
Was able to fix it by switching of multiline in Betterbird and repairing the folder prior to switching back to Thunderbird.

**Comment by Betterbird** [comment]
We've added this to https://www.betterbird.eu/support/

When the multi-line view has been used in Betterbird, you need to switch the Subject column on again in the column picker before switching back to Thunderbird.

What do you mean by "repair". There's nothing broken.
