### ISSUE TITLE
Mehrzeilen-Ansicht für alle Ordner - Multi-row view for all folders

### ISSUE THREAD

**Issue by Doelli** [Betterbird/thunderbird-patches#47]
The Betterbird Setting "Mehrzeilen-Ansicht für alle Ordner" (Multi-row view for all folders) cannot be undone.

**Comment by Betterbird** [comment]
Please read the documentation:
https://www.betterbird.eu/expert-tips/

Once you enable the global option, all folders will show in multi-line view. If you disable the global option, you still need to re-enable the subject column on the folders where you no longer wish to the use multi-line view.
