### ISSUE TITLE
Doesnt open mailto links

### ISSUE THREAD

**Issue by firefoxlover** [Betterbird/thunderbird-patches#49]
This is pretty weird. The app works perfectly, although I pretty much only use it for the layout.

It doesnt open mailto links though, when clicking on an email adress it opens the window, but not the message compose window so I have to copy paste it manually. 

This is not because I havent set it as standard app, I have.

I am on Linux
Operating System: Kubuntu 21.10
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-39-generic (64-bit)
Graphics Platform: X11

**Comment by Betterbird** [comment]
Hello, did you read the bug reporting guidelines before filing this issue? We're pretty sure the bug exists in TB under the same "registration circumstances". OS integration is always a terrible thing to get right. There are plenty of mailto bugs in TB (https://mzl.la/3Meb6Nh), but none report what you're reporting here. https://bugzilla.mozilla.org/show_bug.cgi?id=1755576 is interesting, but that's for Windows. On Windows, clicking on the link in
<html><body><a href="mailto:betterbird@betterbird.eu">Send mail to betterbird@betterbird.eu</a></body></html>
opens a compose window, but not a main window.

Anyway, please test this in TB and file a bug at BMO. Linux is not our main platform, so we have no means to reproduce this. If you let us know how to set the default application on Mint with Xfce, we can try it.

@posi81, does this work for you?

**Comment by Posi81** [comment]
For me works perfectly.
My system:
OS: Arch Linux
DE: KDE 5.93.0 / Plasma 5.24.4
WM: KWin (X11)
Kernel: x86_64 Linux 5.17.3-zen1-1-zen
Qt Version: Qt 5.15.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 11.2.0) on "xcb"

**Comment by Posi81** [comment]
@firefoxlover ..... can you try this code in your console and show me the output?
`xdg-mime query default 'x-scheme-handler/mailto'`

**Comment by Betterbird** [comment]
No feedback in three weeks. Feel free to reopen with more information.

**Comment by Betterbird** [comment]
With a correct betterbird.desktop in `/usr/share/applications/` and registering it with `xdg-mime default betterbird.desktop x-scheme-handler/mailto` will work.

**Comment by LeoniePhiline** [comment]
In my system the KDE Plasma mailto default application did not change anything. I had to select betterbird as mailto handler within the Firefox settings. It seems like Firefox simply ignored the system handler.

**Comment by Betterbird** [comment]
Well, the Xfce defaults application doesn't work for me to set BB as default mailto: application, but running the commands from my last comment works. Long live Linux!

**Comment by rs-gh-asdf** [comment]
Hello,

For people finding this in the future, if you are using the Flatpak-provided version, at least on Ubuntu, then your .desktop file is located at:

```
/var/lib/flatpak/app/eu.betterbird.Betterbird/x86_64/stable/${REALLY_LONG_STRING}/export/share/applications/eu.betterbird.Betterbird.desktop
```

And you can set Betterbird to be your default mailto opener with:

```
xdg-mime default eu.betterbird.Betterbird.desktop x-scheme-handler/mailto
```
