### ISSUE TITLE
XDG Base Dir Spec

### ISSUE THREAD

**Issue by DC7IA** [Betterbird/thunderbird-patches#51]
Everybody likes standards in software, right?

So why not follow the XDG Base Directory Specification?

details: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Meaning Betterbird should look for (and place) its configuration files by default under a directory in `/home/$user/` instead of using its own path. Usually this is `.config`, but this path should be derived from variables, as it can differ.

This leads to a less cluttered home directory.

It also allows syncing the settings between devices using for example Syncthing. Right now syncing would lead to inconsitent data as the directory conatins more than just the settings.

Thunderbird bug: https://bugzilla.mozilla.org/show_bug.cgi?id=735285

That one has been open for 8 years. There's a good chance they would just take up a patch and include it.

**Comment by Betterbird** [comment]
We do what Thunderbird does to remain compatible and be able to switch profiles easily. TB does what the Mozilla platform code does, ie. Firefox. It's spelled out here: https://bugzilla.mozilla.org/show_bug.cgi?id=735285#c7
Sorry, but we won't deviate from that, particularly not on a (much-loved yet) minority desktop platform. It's perfectly good on Windows.

**Comment by Damglador** [comment]
So there's no chance it'll be implemented even as an option (for example, if .local/share/thunderbird exists, use it instead of .thunderbird) until it'll get implemented upstream? Even if someone makes a PR?

**Comment by Betterbird** [comment]
Well, 90% of support queries are related to profile issues. We'd rather not interfere with Mozilla's profile storage to satisfy a minority of users on a 2% platform. We **may** consider it if it's an "easy" change.
