### ISSUE TITLE
[Linux] Action buttons missing in mail view.

### ISSUE THREAD

**Issue by PoisonFrog** [Betterbird/thunderbird-patches#53]
When I click a mail in Betterbird the action buttons that usually stay on the top do not appear.
Thunderbird:
![Thunderbird](https://i.imgur.com/i1Oed2d.png)

Betterbird:
![Betterbird](https://i.imgur.com/uhkPLYS.png)

Buttons are not invisible, they are not there at all. Is it a bug? It shows in Thunderbird but not in Betterbird and configurations should be the same across clients.

**Comment by Betterbird** [comment]
Please read the support page: https://www.betterbird.eu/support/

What's the story with the header pane buttons?

By popular demand, Betterbird has restored the [header pane button customisation](https://www.betterbird.eu/media/img/header-customisation.png). We've received reports that all header pane buttons had disappeared (like "configured away") for a few users. To restore the buttons, start Betterbird in so-called Troubleshoot Mode (Help > Troubleshoot Mode) and when Betterbird restarts, select "Reset toolbars and controls".

Also note that the add-on "Message Header Toolbar Customize" is not working in Betterbird.
