### ISSUE TITLE
build.sh builds Firefox and not Betterbird?

### ISSUE THREAD

**Issue by idslnx** [Betterbird/thunderbird-patches#59]
Hi,

Maybe I am doing something wrong, but when trying to build from source by running build.sh this builds Firefox and not Betterbird.

File https://github.com/Betterbird/thunderbird-patches/blob/main/build/build.sh contains:
./mach --no-interactive bootstrap --application-choice "Firefox for Desktop"

This is from mozilla-esr91/python/mozboot/mozboot/bootstrap.py which contains no reference to Betterbird.

Should mozilla-esr91/comm/python/rocboot/bin/bootstrap.py be used somehow, as this does refer to Betterbird?

If anymore info is needed please let me know.

Regards,
Ids

**Comment by Betterbird** [comment]
`./mach --no-interactive bootstrap --application-choice "Firefox for Desktop"` is correct, it does the bootstrap for the desktop builds of Firefox, Thunderbird and Betterbird.

I've used `build.sh 91` on a rented Linux cloud server with no issue, I'm also using it on Windows, and it has also been tested on Mac. Some contributors are also using it on am Amazon ARM64 instance.

Which platform are you on?

If this is building FIrefox, then there is something wrong with your mozconfig file. Without mozconfig file, Firefox will be built by default.

**Comment by idslnx** [comment]
Thanks for the clarification.
I'll see if I can fix the issue.

**Comment by Betterbird** [comment]
There really shouldn't be any issue. If you clone the repo into your build directory as described in README.md, everything will work. The mozconfig is provided in the repo and copied by the build script, so Firefox will not be built but instead BB.

**Comment by Betterbird** [comment]
We found the issue a while ago. `./mach bootstrap` supersedes the mozconfig file. We've since fixed it by changing the order of the build.
