### ISSUE TITLE
Boolean filter logic: Adding simple term after group leads to simple term receiving unrelated preceding group operator instead of operator of own group

### ISSUE THREAD

**Issue by ThiloteE** [Betterbird/thunderbird-patches#60]
Related and follow-up issue to #35

How to reproduce:
1. Create new filter; Do this:
![grafik](https://user-images.githubusercontent.com/73715071/171840558-6e9cf50c-e4b8-4ca3-b69a-98bb8709604f.png)
2. Very Important: To create the "match any" rule one has to use the top right button. It cannot be reproduced with sub-level button! See here:
   ![grafik](https://user-images.githubusercontent.com/73715071/171842401-4979c9e4-2835-4615-aea9-b10f1db678d6.png)

3. Click on "ok"
4. Open the filter again with "edit"
5. See this:
   ![grafik](https://user-images.githubusercontent.com/73715071/171841673-f70f4fb3-8825-4afd-bc88-71db3c855230.png)

Explanation:

This might actually be correct logic and behavour, but the UI is misleading. It makes it look as if the "match any" rule is a sub-group of the "match all" rule, whereas it actually is NOT. It operates on the same level and hierarchy, if I got this right.

**Comment by ThiloteE** [comment]
For illustration: There is no conversion of the filterrules anymore, when adding another rule into the "match all". Like this:

![grafik](https://user-images.githubusercontent.com/73715071/171844038-ebcc65c3-3e0b-4ce4-b7f5-4eb6e3e89432.png)

But how can I as user see if the "match any" rule is a top-level group or a subgroup?

This is relevant if I want to create something like this:

`a` and (`b` or `c` or ... `n`), which is equivalent to (`a` and b) or (`a` and `c`) or (`a` and `...`) or (`a` and `n`). In that case, I don't want it to automatically be transformed to match any.

**Comment by Betterbird** [comment]
> But how can I as user see if the "match any" rule is a top-level group or a subgroup?

I don't understand the question. The indentation shows the level. Altogether, the UI was lifted from Mac's search, see here: https://bugzilla.mozilla.org/show_bug.cgi?id=297852#c65, and generally Mac offers a (semi-)decent UI.

https://user-images.githubusercontent.com/73715071/171844038-ebcc65c3-3e0b-4ce4-b7f5-4eb6e3e89432.png shows a [date && to && (to || to)]

**Comment by ThiloteE** [comment]
Ah sorry.

Betterbird version 91.9.1-bb32 (64-bit) Linux

Maybe you already fixed it.

Here the filter AFTER the conversion:

```
name="test after conversion"
enabled="no"
type="17"
action="Mark read"
condition="AND (to,is,test@test.de) AND (to,is,test3@test.de) OR (to,is,test3@test.de)"
```

Ok, guess what there was another condition to be able to reproduce:

1. One has to create a "new filterrule" first before clicking the top-level group button.

See video:

https://user-images.githubusercontent.com/73715071/171859130-3175f554-83cc-4318-a73a-3d8f3620d0b0.mp4

**Comment by ThiloteE** [comment]
The questions are this: Should there be a conversion if these specific conditions are at play? If yes, how to make it so that users will not get confused, because as a matter of fact: The indentation does NOT show the difference (yet). I have two filters that apparently look the same, but one will be converted and the other one will not be converted.

**Comment by Betterbird** [comment]
Thanks for the video. It clearly shows a user error. You are creating an empty group which will not be saved. The last two conditions are not part of the preceding group header. Compare your construct
![image](https://user-images.githubusercontent.com/86832723/171915051-4e87599e-6fb9-4581-8db1-bc1db6bed671.png)

to what you intended to do:
![image](https://user-images.githubusercontent.com/86832723/171914979-17d89dbf-4062-46ca-8a6b-375ee36057dc.png)

I don't know what you mean by "conversion", there is no conversion, but, as you saw, empty groups aren't stored. That's no surprise since only search terms are stored, the grouping is stored by storing the grouping information in the first and last search term. If the group is empty, this can't be done and the group is lost.

`condition="AND (to,is,test@test.de) AND (to,is,test3@test.de) OR (to,is,test3@test.de)"` is a very surprising result and looks invalid, at least it's nothing TB or BB would create. There are people who edited msgFilterRules.dat to achieve some sort of AND/OR combination.

If you can give the exact steps of how to get into this situation, we can investigate this further. 

When we create an empty group, the content of msgFilterRules.dat looks like this:
`condition="AND (subject,contains,a) AND (subject,contains,b) AND (subject,contains,c)"`, that is, no mixed operators.

**Comment by ThiloteE** [comment]
You are right. Now I see the indentation. Good! Thank you for pointing that out. My bad.
I also now understand what you mean when yo say an "empty group" gets deleted and I understand the logic behind it. Thanks for pointing that out as well.


To answer your questions:

1. There is no other steps than shown in the video. These are the steps. It was a completely new filter. No manual editing in filter rules. It is all created from what I did in the UI. Just do what I do in the video, then check the msgFilterRules.dat. Please ignore the msgFilterRules.dat I showed you in the above comment (`condition="AND (to,is,test@test.de) AND (to,is,test3@test.de) OR (to,is,test3@test.de)"`) if you think this is not possible. I only used the UI in Betterbird, so I am not sure how it came to be...

2. With conversion I mean: The "match all" gets converted to "match any". I would argue, the conversion to "match any" is counterintuitive. It should stay "match all", since that is the thing I clicked.

**Comment by Betterbird** [comment]
The video shows:
`+` at top
`+()` at top
Switch empty group to "Any"
`+` at top.
Fill in details for the two simple conditions
Add another simple condition at bottom and add details.
![image](https://user-images.githubusercontent.com/86832723/171987482-0638f0a0-34bd-4697-8e7b-92e3e39a96f7.png)

Save and edit again: Result the empty group is lost:
![image](https://user-images.githubusercontent.com/86832723/171987499-4fc1a425-6b0a-418f-9580-206c6da247eb.png)
but the top condition now comes back with "Any" and msgFilterRules.dat contains `condition="AND (subject,contains,a) AND (subject,contains,b) OR (subject,contains,c)"`.
OK, that's a bug. We'll address that, but not on the weekend 😉

**Comment by ThiloteE** [comment]
Thank you :-)

By the way, overall I am very happy with the complex filter rules implementation! Took me a little bit of trial and error to get used to it, but at the end of the day, it is a huuuuuge improvement :)

One success-story I can already tell: I was able to get rid of 5 old filters that all moved mails to a single folder and replaced them with a single filter that contained some complex rules. Out of 5 make 1 :) Nice!

I will do some more testing the coming weeks/months and will report back eventually with the results and give examples of what worked really well for me and what not. I am especially curious if some other bugs that are in bugzilla, can still be reproduced with Betterbirds implementation.

**Comment by Betterbird** [comment]
Not related to empty groups, anything appended after a group can potentially get the wrong operator ☹️

**Comment by Betterbird** [comment]
Fixed by https://github.com/Betterbird/thunderbird-patches/commit/d1de264fd433f3da591bd4602d51be5d1724131a.
Please try https://www.betterbird.eu/downloads/get.php?os=win&lang=en-US&version=latest

**Comment by Betterbird** [comment]
@RealRaven2000: Please note that there was a significant logic error here which could have led to invalid rules.

**Comment by ThiloteE** [comment]
Alright, will try. I am on Linux though, and my current machine does not have enough ram to compile from source, so I will just wait until it reaches the official download page, unless you give me another link for Linux :D

**Comment by Betterbird** [comment]
Difficult issue. We build Linux on both cloud servers and project owned build machines. 91.10.0 was built on the "throw away" cloud setup, that means we can't just redo the build with a small additional fix as we can do for Windows.

**Comment by ThiloteE** [comment]
Got it. I have time; Will wait for the new version :)

**Comment by Betterbird** [comment]
We've made a build for you: https://www.betterbird.eu/downloads/get.php?os=linux&lang=en-US&version=latest

**Comment by Betterbird** [comment]
@ThiloteE : Did you have time to test this?

**Comment by ThiloteE** [comment]
I just did some tests and as far as I can see, at least with top-level groups it seems to work! :-)

I found some other weird behaviour with second or third level groups, but I will create a separate issue with video for this in the evening.

**Comment by Betterbird** [comment]
We love videos :wink:

**Comment by RealRaven2000** [comment]
I wonder if it would be possible to clarify the UI, by showing the nesting levels in the following way:

![image](https://user-images.githubusercontent.com/6314674/228517250-2b54cde2-a939-45b4-9bd1-c43551524d76.png)

that would be awesome and would help a lot in avoiding user errors like the one described in the video.

**Comment by Betterbird** [comment]
Patches and funding welcome 😏 - Likely you can do something in the CSS used for indentation:
https://github.com/Betterbird/thunderbird-patches/blob/093685292c44b63e9cfd32d3219e75a83690db9d/102/bugs/297852-grouping-search-term.patch#L1850
You could try in the inspector and submit the changed CSS.

**Comment by ThiloteE** [comment]
I would suggest to open a new issue for this. Thank you :-)

**Comment by RealRaven2000** [comment]
> Patches and funding welcome 😏 - Likely you can do something in the CSS used for indentation:
> 
> https://github.com/Betterbird/thunderbird-patches/blob/093685292c44b63e9cfd32d3219e75a83690db9d/102/bugs/297852-grouping-search-term.patch#L1850
> 
> You could try in the inspector and submit the changed CSS.

If it is welcome, I might have a go at it. As soon as I get time I will do that and open a new issue. There may be a little Javascript necessary unless there is a way to write a `:last-row-in-group` selector :) I haven't looked at the markup, but `:last-child` might even work depending on the markup.

**Comment by Betterbird** [comment]
With very simple CSS you can achieve this:
![image](https://user-images.githubusercontent.com/86832723/228799718-43e546eb-86c5-4258-9db8-6e5b85bf3877.png)
That's
```
margin-inline-start: 35px;
border-left: 1px solid blue;
padding-inline-start: 5px;
```
instead if the original `padding-inline-start: 40px;`.

What you've drawn up is more like a tree structure, and that won't be easy to do.
