### ISSUE TITLE
Bad TLS: Betterbird no longer connects to Proton Bridge

### ISSUE THREAD

**Issue by IngwiePhoenix** [Betterbird/thunderbird-patches#65]
Hello!

I decided to use Betterbird because of the vertical column layout which I prefer a lot. However, it seems to have forgotten how to talk to the Proton Mail Bridge.

This issue does not exist within Thunderbird itself.

Basically, within the Proton Mail Bridge logs, I can see this message:

```
cannot upgrade connection: remote error: tls: bad certificate  protocol=IMAP
```

I have tried removing all certificates by Proton AG to force a new "Trust this server" dialog, but to no avail. I also tried to re-add the `cert.pem` manually (`...}AppData\Roaming\protonmail\bridge\cert.pem`) but I still get the same error.

I can connect with Thunderbird just fine, but Betterbird seems to have some issue connecting.

My version is currently 91.12.0-bb35 (64-bit)

Anything I can do to fix this error? Thanks!

**Comment by Betterbird** [comment]
Hmm, I've heard about the "Proton Bridge" doing damage in general. Certificates are handled in Mozilla platform code, there is nothing specific to TB or BB, in particular, there are no differences between TB and BB in this area. It's possible that the bridge setup is geared towards TB and doesn't work with BB. Hard to imagine since we even use Thunderbird in the user agent string.

Try running TB on the BB profile and vice versa to see what combination works.

**Comment by Betterbird** [comment]
Thanks for the comment. The claim that TB worked and BB didn't hinted at some incorrect configuration.

Closing this now as per @xet7'a suggestion. @IngwiePhoenix, do you still have issues?

**Comment by Betterbird** [comment]
Didn't you say it worked? Can you provide more details about the failure.

**Comment by xet7** [comment]
Yes, it did work, but not anymore, now I have problem both with Thunderbird and Betterbird, both with STARTTLS and without, it does not accept password. Maybe I messed up my computer, I try reinstall Ubuntu 22.10 and newest software versions.

![better2](https://user-images.githubusercontent.com/15545/207873258-71bfe374-6385-4404-9e6a-ddfc4573936d.png)

![better1](https://user-images.githubusercontent.com/15545/207873263-c5740f20-e7c1-44fa-8db3-b9ea19d91f3d.png)

**Comment by xet7** [comment]
Hi,
I installed newest Protonmail Bridge, Thunderbird and Betterbird.

Sending email via Protonmail bridge works on both Thunderbird and Betterbird, when not using any encryption between email client and Protonmail Bridge.

This issue can be closed.

**Comment by xet7** [comment]
This is using my paid Protonmail account with custom domain, works:

## IMAP

![betterbird-imap](https://user-images.githubusercontent.com/15545/208236914-e3e1a57a-b8e2-4c59-aa0f-66474516bcf5.png)

## SMTP

![betterbird-smtp](https://user-images.githubusercontent.com/15545/208236922-b8139c67-69e4-4b0a-bc9b-4c35c0cca618.png)

**Comment by Betterbird** [comment]
Thanks for the update.
