### ISSUE TITLE
Add metadata for Linux distribution

### ISSUE THREAD

**Issue by mfschumann** [Betterbird/thunderbird-patches#68]
I suggest adding the following metadata to this repository that is required for distributing Betterbird under Linux:

- a .desktop file (description of menu entries)
- an .appdata.xml file (contains a description of the software that can be shown in software stores)
- program icons

Including this data here will help those creating packages for Linux from Betterbird/Thunderbird source code.

If you agree to include these files in this repo, I can create a PR with a suggestion from the work done for distribution as flatpak (c.f. #7).

**Comment by Betterbird** [comment]
[eu.betterbird.Betterbird.appdata.xml.txt](https://github.com/Betterbird/thunderbird-patches/files/9438805/eu.betterbird.Betterbird.appdata.xml.txt)

What's a desktop file? Something like https://bug296568.bmoattachments.org/attachment.cgi?id=185295.
Or this: https://bugzilla.mozilla.org/show_bug.cgi?id=1637575
So:
```
[Desktop Entry]
Encoding=UTF-8
Name=Betterbird
GenericName=Mail, news, chat, feeds and calendar client
Comment=Mail client supporting mail, news, chat, feeds and calendar
Exec=betterbird
Icon=betterbird . ???
Terminal=false
Type=Application
Categories=Application;Network;WebBrowser; ???
MimeType=message/rfc822:x-scheme-handler/mailto:text/calendar:text/vcard:text/x-vcard
StartupNotify=True
```

As for the icons, what would you like? SVG? PNG? Size?
We have plenty of that:
https://www.betterbird.eu/betterbird.svg
https://www.betterbird.eu/media/img/betterbird-256.png

**Comment by Betterbird** [comment]
Added some here:
https://github.com/Betterbird/thunderbird-patches/commit/56b349ab663b76905c318819b8a0fd79f2e28fda
Will add .desktop once the ??? are clarified, equally, some icons.

**Comment by Betterbird** [comment]
Please note https://github.com/Betterbird/thunderbird-patches/commit/7612242e621ab97e3fa5aa696a60317c7fb69479 which improves the screenshots.

**Comment by Betterbird** [comment]
We're done here, right. Further tweaks can be done via more pull requests.
