### ISSUE TITLE
Betterbird flatpak listing on Flathub.org

### ISSUE THREAD

**Issue by ovari** [Betterbird/thunderbird-patches#7]
Can [Betterbird](https://flathub.org/apps/search/betterbird) please be added to [Flathub](https://flathub.org/home)?

Can the [Thunderbird flathub repository](https://github.com/flathub/org.mozilla.Thunderbird) help?

@Erick555 could you kindly assist?

Thank you

**Comment by ovari** [comment]
@4ch1m can [ansible-betterbird](https://github.com/4ch1m/ansible-betterbird) be used as a fully automated build script for [Betterbird](https://betterbird.eu/) using Ansible into the [Flathub app store](https://flathub.org/home) whenever there is a new [Betterbird release](https://betterbird.eu/releasenotes/index.html)?

Thank you

**Comment by 4ch1m** [comment]
[ansible-betterbird](https://github.com/4ch1m/ansible-betterbird) automatically ...
* installs all dependencies for a local build of Thunderbird/Betterbird (Mercurial, Python, etc.)
* does all the necessary configuration (mozconfig)
* pulls the original sources of Thunderbird
* pulls all the latest Betterbird patches from this repository
* applies all Betterbird patches
* executes the build
* generates the release package (*.tar.bz2).

Creating (and publishing) a Flatpack would be another task; probably for another (Ansible) script which could utilize [ansible-betterbird](https://github.com/4ch1m/ansible-betterbird) for the actual build process.

**Comment by Erick555** [comment]
I think you can't currently publish to flathub from external CI without special approval (which only mozilla got for publishing firefox). You could publish *.tar.bz2 somewhere then point to it from flathub which will make flatpak out of it.

**Comment by ovari** [comment]
Thank you @Erick555 for your information.

Currently there is a *.tar.bz2 file at https://www.betterbird.eu/downloads/index.php. The file is https://www.betterbird.eu/downloads/betterbird-91.1.1-bb14.en-US.linux-x86_64.tar.bz2

Can Betterbird be listed on Flathub now?

Thank you

**Comment by Betterbird** [comment]
Well, that build was more like a one-off for testing purposes. Apparently there is still a naming issue (thunderbird vs. betterbird).

**Comment by Betterbird** [comment]
We're publishing .tag.gz now for English and German for every release, https://www.betterbird.eu/downloads/, also see the requirements here: https://www.betterbird.eu/system-requirements/.
So maybe @Erick555 can move this forward now.

**Comment by Erick555** [comment]
I don't use this app and I don't have interest in publishing it on flathub. I've only offered some guidance.

**Comment by thomasphansen** [comment]
Hi there! :)
Just found this documentation, which can probably help:
https://github.com/flathub/flathub/wiki/App-Submission
https://docs.flatpak.org/en/latest/publishing.html
Looking forward to see Betterbird at flathub! :)

**Comment by vasyugan** [comment]
hey, just pinging you, I was just going to write a feature request for a flatpak, I see it is already there, but the process seems to be stalled.

**Comment by Betterbird** [comment]
So reading https://github.com/flathub/flathub/wiki/App-Submission:
 4. Add your app’s manifest to the branch, commit it and push the commit

What is that manifest and can someone locate the equivalent for Thunderbird? Looks like the TB repo is here:
https://github.com/flathub/org.mozilla.Thunderbird

**Comment by Erick555** [comment]
It's possible to build it from scratch or use pre-build binaries. I guess flathub reviewers would prefer the former although if you have your own CI setup already then you may convince them for the latter.

The manifest is something like [this](https://github.com/flathub/org.mozilla.Thunderbird/blob/master/org.mozilla.Thunderbird.json). This file declares all remote sources and tells how to build them (or copy/install if they are in binary form).

**Comment by vasyugan** [comment]
> What is that manifest and can someone locate the equivalent for Thunderbird? Looks like the TB repo is here: https://github.com/flathub/org.mozilla.Thunderbird
 
I guess it makes sense to look at a manifest file for a package using pre-built binaries, [such as Skype](https://github.com/flathub/com.skype.Client/blob/master/com.skype.Client.json).

**Comment by mfschumann** [comment]
I have modified the Thunderbird manifest to create a flatpak package from the pre-built binaries of Betterbird: https://github.com/mfschumann/betterbird-flatpak

@Betterbird The project license for Thunderbird is stated as MPL-2.0. Does this apply for Betterbird, too? 

The next step towards a listing on Flathub is to open a pull request against the flathub repo, adding the manifest. Once the pull request has completed, a new repository will be created hosting the Betterbird manifest. On everey push to that repo (e.g. on every release of a new Betterbird version), a new flatpak package will be built. 

@Betterbird Do you want to create the pull request against the flathub repo? Like that you would get write access to the manifest repo and would be able to integrate updating the manifest into the Betterbird release workflow. If you want me to help with anything, just let me know.

**Comment by Betterbird** [comment]
Thanks for that.
Yes, the license is MPL-2.0 only with a slight modification related to attribution, see: https://github.com/Betterbird/thunderbird-patches/blob/main/LICENSE. For the purposed of distribution it's MPL-2.0.

Briefly looking at https://github.com/mfschumann/betterbird-flatpak, the screenshots show Thunderbird.

If at all possible, for now we don't want to get involved in maintaining any Linux distribution. For example, we found a volunteer that maintains the Arch packages.

**Comment by ovari** [comment]
Thank you @mfschumann.

Should the https://github.com/mfschumann/betterbird-flatpak#readme also be updated? For example, from

> [Thunderbird](https://www.thunderbird.net/) for [Flatpak](https://flatpak.org/) installation instructions are available by [clicking here to visit the Thunderbird app page on Flathub](https://flathub.org/apps/details/org.mozilla.Thunderbird).

to

> [Betterbird](https://betterbird.eu/) for [Flatpak](https://flatpak.org/) installation instructions are available by [clicking here to visit the Betterbird app page on Flathub](https://flathub.org/apps/details/eu.Betterbird).

**Comment by mfschumann** [comment]
@ovari Yes, absolutely. Also, the screenshots should be updated to actually show Betterbird. I just did the bare minimum to succesfully make the flatpak package yet. Feel free to make these adaptions and create a pull request.

**Comment by ovari** [comment]
https://github.com/mfschumann/betterbird-flatpak/pull/1

**Comment by ovari** [comment]
Can the screenshots just be removed or the following be initially used?
* https://betterbird.eu/betterbird.svg
* https://betterbird.eu/media/img/tb-bb-comparison-800px.jpg

At least until someone provides Betterbird screenshots?

**Comment by Betterbird** [comment]
Please don't use the "propaganda" cartoon. It can't be so hard to start BB and take a screenshot. If necessary, even I can do it under Linux. The "windows badge" is for Windows, it doesn't apply to Linux.

**Comment by Betterbird** [comment]
![dark](https://user-images.githubusercontent.com/86832723/186654701-7f69bfc1-3c6e-48c1-b8d1-af78e5a35d35.png)
![light](https://user-images.githubusercontent.com/86832723/186654740-81ec642c-8272-409c-be1b-107585b0183b.png)

**Comment by ovari** [comment]
> ![dark](https://user-images.githubusercontent.com/86832723/186654701-7f69bfc1-3c6e-48c1-b8d1-af78e5a35d35.png) ![light](https://user-images.githubusercontent.com/86832723/186654740-81ec642c-8272-409c-be1b-107585b0183b.png)

Should those images be added to:
* https://betterbird.eu/
* https://github.com/Betterbird/thunderbird-patches/

**Comment by Betterbird** [comment]
This is now tracked elsewhere: https://github.com/flathub/eu.betterbird.Betterbird

**Comment by mfschumann** [comment]
🎉 Betterbird has been released on flathub!

The flathub web page does not seem to show it just yet, but installing via `flatpak install eu.betterbird.Betterbird` or using Gnome Software works.

**Comment by ovari** [comment]
Flathub now shows Betterbird:
* https://flathub.org/apps/details/eu.betterbird.Betterbird
* https://flathub.org/apps/search/betterbird
* https://flathub.org/apps/search/thunderbird
* https://flathub.org/apps/collection/new

**Comment by Betterbird** [comment]
So now we wait until people complain that it's only in English and that there are no language packs 😉

**Comment by vasyugan** [comment]
> So now we wait until people complain that it's only in English and that there are no language packs wink

That's kind of an issue, and one that doesn't occur with the Thunderbird flatpak. In both thunderbird and firefox you can switch the language and it will, as it seems, download the missing localisation files.

**Comment by mfschumann** [comment]
We are already working on localization: https://github.com/flathub/eu.betterbird.Betterbird/issues/4
