### ISSUE TITLE
Importing Thunderbird profile does not work

### ISSUE THREAD

**Issue by Karmalakas** [Betterbird/thunderbird-patches#72]
Windows 10
Thunderbitd v102.2.1
Betterbird v102.2.1-bb15

Selected `Tools > Import... > Import from another Thunderbird installation`
Tried at first to leave detected default profile, got an error:
> Import failed unexpectedly, more information may be available in the Error Console

Same if I manually select default profile
Same happens if I select only 2 of 4 - Accounts and Messages

Error console output (expanded seemingly useful rows):
![image](https://user-images.githubusercontent.com/3602819/188491378-1c1e68f8-1c67-491d-af0f-a3ab84c5c6cc.png)

Checked if profile folder is really the one and it was

Tried exporting from TB to ZIP and then import to BB - exact same issue
![image](https://user-images.githubusercontent.com/3602819/188492608-aaff06cc-3e6b-44da-a3a8-693ee7a2c32c.png)

ZIP file - ~1.3GB

**Comment by Betterbird** [comment]
In general, you can run BB directly on the TB profile and no import is needed.

As we state in https://github.com/Betterbird/thunderbird-patches#bug-reporting--support, you need to see whether TB works under the same circumstances. So try to import into your target profile with TB instead of BB.

The error is a "file not found":
![image](https://user-images.githubusercontent.com/86832723/188498550-67730ac7-6ef7-4dab-9d73-3ed71317631a.png)
likely a bug in TB's import function which is new in TB/BB 102.

**Comment by Karmalakas** [comment]
> you need to see whether TB works under the same circumstances.

But I'm using TB for years now with this profile. I wouldn't want to mess it up by running an import if it fails 🙁 

---

> you can run BB directly on the TB profile and no import is needed

How do I do that? Where do I set the profile to use? Will it change anything if I switch back to TB?

**Comment by Betterbird** [comment]
I don't quite understand what you are doing. You have a profile which you were using with TB for years. OK. You exported that profile. OK. You started BB, it came up with a new profile, I suppose. You tried to import the TB profile you exported, it failed. Yes?

You can do three things:

Start TB with -p in the command line and select the second profile, the one created for BB. Then import the old profile. Our bet is that the import will fail just as it does with BB.

Or, start BB with -p and select the old profile. Nothing will mess up. See [How to switch between Thunderbird and Betterbird?](https://www.betterbird.eu/support/).

What you can also do if you want to duplicate the profile is to make a 1:1 copy of the TB profile into the folder of the BB profile.

**Comment by Karmalakas** [comment]
When I reopened BB, I noticed some inboxes half imported. How do I fix this? Just delete the folder of that profile?

Also simply selecting the same profile folder as TB uses, took all the inboxes without any issue - only needed to reenter the passwords.

I didn't try import on TB itself and probably won't in the nearest future, so closing this issue

**Comment by Betterbird** [comment]
To the delete the half-imported profile, run TTB/BB with -p (profile manager) and delete the profile. Be sure to select the option to delete the files as well.

I'm surprised you had to re-enter passwords. I occasionally switch from BB to TB and back and never had to re-enter anything. Of course, if you have a primary/master password, you need to enter it.

**Comment by Karmalakas** [comment]
It wasn't master password. I had to enter for each email account 🤷‍♂️
