### ISSUE TITLE
Betterbird icon in Gnome (42) System Overview (SUPER + S) is missing

### ISSUE THREAD

**Issue by rsramkis** [Betterbird/thunderbird-patches#74]
When pressing the SUPER key in Gnome 42 you can see all the running programs with an icon stamped at the bottom of the program. The correct stamped icon shows for Firefox\Thunderbird. But it appears to be missing for Betterbird (see photo).

The correct icon does show in the Gnome "All Applications" view  and the Gnome Dash.

![betterbird gnome show all running programs](https://user-images.githubusercontent.com/14362317/188930846-7e840b21-81e2-4a69-8d22-32153c17fea3.jpg)

I used the AUR install package:

betterbird-bin 102.2.1-1
https://aur.archlinux.org/packages/betterbird-bin

I've been looking through the Gnome Documentation to try to find out how this icon is fetched. Figure I would touch base with your team for feedback. Thank you.

**System Information:**

Kernel: 5.15.64-1-lts arch: x86_64 bits: 64 
Desktop: GNOME  v: 42.4 
Distro: EndeavourOS

**Comment by Posi81** [comment]
For me with KDE working fine

![image](https://user-images.githubusercontent.com/59346176/188950407-b4676cdf-0e46-46d5-804e-f62dbe6d4584.png)

**Comment by Betterbird** [comment]
Sorry, but we can't possibly check the 1001 Linux distros. If you care, please investigate yourself and suggest a solution.

**Comment by rsramkis** [comment]
> For me with KDE working fine
> 
> ![image](https://user-images.githubusercontent.com/59346176/188950407-b4676cdf-0e46-46d5-804e-f62dbe6d4584.png)

Thanks for sharing.  A valid test is using the same desktop of Gnome.

**Comment by rsramkis** [comment]
> Sorry, but we can't possibly check the 1001 Linux distros. If you care, please investigate yourself and suggest a solution.

We are not talking about checking Distros. If we are working cooperatively here it would be great to see if someone else using Gnome v42 Desktop is seeing the same problem with a non flatpak install.

Do you have Gnome on one of your test machines?

**Comment by Posi81** [comment]
> > For me with KDE working fine
> > ![image](https://user-images.githubusercontent.com/59346176/188950407-b4676cdf-0e46-46d5-804e-f62dbe6d4584.png)
> 
> Thanks for sharing. A valid test is using the same desktop of Gnome.

Oh really? 😉
For this i just show that KDE not have this problem.

**Comment by Betterbird** [comment]
> Do you have Gnome on one of your test machines?

No.

**Comment by Posi81** [comment]
Maybe on weekend i will make a Arch with Gnome testing mashine. After this i will reply to you

**Comment by rsramkis** [comment]
By default the icons are placed by the AUR install in the "/opt/betterbird/chrome/icons/default" directory where several resolutions are made available based on your desktop resolution.

The Desktop file used by Gnome which defines where to look for the executable and icon is in "/usr/share/applications".

Some applications (e.g. Steam) will place its application\game icons in the Home Directory "~/.local/share.icons". I did try cheating and put Betterbirds icons here. But still no luck getting them to show.

Otherwise the best option (which is already setup) is the icons are placed in the "/usr/share/icons/hicolor". This is why the Gnome Dash and All Applications show the Betterbird icon. 

![image](https://user-images.githubusercontent.com/14362317/188974948-23f474c4-5a15-4e50-80ea-b16298f6a67d.png)

I'm going to do some digging to see where Gnome is looking for the icon to show in the Show All Runnings apps view. I'll ping you once I find out.

**Comment by Posi81** [comment]
> By default the icons are placed by the AUR install in the "/opt/betterbird/chrome/icons/default" directory where several resolutions are made available based on your desktop resolution.
> 
> The Desktop file used by Gnome which defines where to look for the executable and icon is in "/usr/share/applications".
> 
> Some applications (e.g. Steam) will place its application\game icons in the Home Directory "~/.local/share.icons". I did try cheating and put Betterbirds icons here. But still no luck getting them to show.
> 
> Otherwise the best option (which is already setup) is the icons are placed in the "/usr/share/icons/hicolor". This is why the Gnome Dash and All Applications show the Betterbird icon.
> 
> ![image](https://user-images.githubusercontent.com/14362317/188975933-2676d135-f371-4256-a7ab-d051daee87a3.png)
> 
> I'm going to do some digging to see where Gnome is looking for the icon to show in the Show All Runnings apps view. I'll ping you once I find out.

KDE working the same way.

**Comment by Posi81** [comment]
> By default the icons are placed by the AUR install in the "/opt/betterbird/chrome/icons/default" directory where several resolutions are made available based on your desktop resolution.
> 
> The Desktop file used by Gnome which defines where to look for the executable and icon is in "/usr/share/applications".
> 
> Some applications (e.g. Steam) will place its application\game icons in the Home Directory "~/.local/share.icons". I did try cheating and put Betterbirds icons here. But still no luck getting them to show.
> 
> Otherwise the best option (which is already setup) is the icons are placed in the "/usr/share/icons/hicolor". This is why the Gnome Dash and All Applications show the Betterbird icon.
> 
> ![image](https://user-images.githubusercontent.com/14362317/188975933-2676d135-f371-4256-a7ab-d051daee87a3.png)
> 
> I'm going to do some digging to see where Gnome is looking for the icon to show in the Show All Runnings apps view. I'll ping you once I find out.

Did you test `sudo gtk-update-icon-cache`  ?

**Comment by rsramkis** [comment]
Can you post a screen shot showing your all running applications view in KDE? This would be good as a reference.

BTW I thought KDE also allows you to create your own desktop files with the built in desktop tools?

**Comment by rsramkis** [comment]
I'm going to look into gtk-update-icon-cache as part of my research. Keep in mind that since the icon is available for the gnome desktop Search, Dashboard and Show all Application views I am trying to target how the Show all Applications fetches the icon when the SUPER key is pressed,

Also read this as part of the GTK4 change over.
https://forum.endeavouros.com/t/gnome-42-icons-missing/28810

**Comment by Posi81** [comment]
> Can you post a screen shot showing your all running applications view in KDE? This would be good as a reference.
> 
> BTW I thought KDE also allows you to create your own desktop files with the built in desktop tools?

![image](https://user-images.githubusercontent.com/59346176/188986066-d8f99c95-8a56-4a4b-9c98-95664ffbe331.png)

**Comment by rsramkis** [comment]
I've opened a post with EndeavourOS to see if the community has suggestions on how the Gnome System Overview fetches the icon.

https://forum.endeavouros.com/t/help-needed-troubleshooting-a-missing-icons-from-gnome-42-system-overview-shortcut-super-s/31475

**Comment by rsramkis** [comment]
I notice the following about the icons. Is this something controled by the AUR deployment?

The following files do not have soft links in the hicolor theme:

/opt/betterbird/chrome/icons/default/default128.png
/opt/betterbird/chrome/icons/default/default64.png

Softlinks missing in:

/usr/share/icons/hicolor/64x64/apps/betterbird.png
/usr/share/icons/hicolor/128x128/apps/betterbird.png

**Comment by Posi81** [comment]
> I notice the following about the icons. Is this something controled by the AUR deployment?
> 
> The following files do not have soft links in the hicolor theme:
> 
> /opt/betterbird/chrome/icons/default/default128.png /opt/betterbird/chrome/icons/default/default64.png
> 
> Softlinks missing in:
> 
> /usr/share/icons/hicolor/64x64/apps/betterbird.png /usr/share/icons/hicolor/128x128/apps/betterbird.png

now added

**Comment by rsramkis** [comment]
Opened Gnome Defect to help investigate what dependency might be missing.
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5846

**Comment by rsramkis** [comment]
I checked with the Gnome project and this is what they recommended:

[Sebastian Keller](https://gitlab.gnome.org/skeller) [commented](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5846#note_1548688):

Please use https://discourse.gnome.org/ for user support. This specific issue is most likely a mismatch between the .desktop file (either the filename or the StartupWMClass) and the WM class of the window (use Alt+F2, lg, Windows) to find the WM class used by a window).



![image](https://user-images.githubusercontent.com/14362317/189243359-ef800737-91f9-4eb0-bf4c-c0fa89773522.png)

**Comment by rsramkis** [comment]
So the fix is to add the following property in the betterbird.desktop file under [Desktop Entry]:

StartupWMClass=thunderbird-default 

**Source:**
[Sebastian Keller](https://gitlab.gnome.org/skeller) [commented](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5846#note_1548717):

So the problem is exactly what I mentioned earlier, the .desktop file does not match the WM class, so gnome-shell won't be able to match the window to an application. Try renaming the .desktop file to thunderbird-default.desktop or add StartupWMClass=thunderbird-default to the [Desktop Entry] section of the .desktop file.

**Comment by Betterbird** [comment]
Well, in the .desktop file that was created for the Flatpak build has this:
https://github.com/Betterbird/thunderbird-patches/blob/497c37a256caa8271643185dd0e61658e4033a48/metadata/eu.betterbird.Betterbird.desktop#L10
A few lines up you can also see they it uses `Icon=eu.betterbird.Betterbird` which is different to
https://aur.archlinux.org/cgit/aur.git/tree/betterbird.desktop?h=betterbird-bin#n61

I suggest to add `StartupWMClass=betterbird-default` and is that doesn't work, it likely needs patching in BB itself here:
https://searchfox.org/comm-central/rev/4b737f926ea431233bf43a81f798a7c1c0b1bdec/mozilla/toolkit/mozapps/installer/linux/rpm/mozilla.desktop#15

**Comment by rsramkis** [comment]
Just to be clear, I tested the Gnome Shell suggestion of adding "StartupWMClass=thunderbird-default"  and it did work for the AUR package install.

So this change needs to be made to the  betterbird.desktop file in the source.

**Comment by Betterbird** [comment]
Sure, but in BB's desktop file we don't want a reference to TB. And the betterbird.desktop is maintained in the AUR repo unless they want to switch to https://github.com/Betterbird/thunderbird-patches/blob/main/metadata/eu.betterbird.Betterbird.desktop.

I'm sure @Posi81 is following this thread and will do the right thing in due course.

**Comment by Posi81** [comment]
I will do changes at this weekend

**Comment by Posi81** [comment]
@rsramkis please update the AUR and confirm that the changes I made are now working.

**Comment by rsramkis** [comment]
I can confirm the issue is now addressed in the AUR packaged. I have included a screen shot for the evidence.

![image](https://user-images.githubusercontent.com/14362317/189511453-48c906ed-485c-4210-bb83-8da68e11f725.png)

Suggest we close the defect as fixed.

**Comment by Betterbird** [comment]
Thanks, @Posi81 !!

**Comment by Betterbird** [comment]
@rsramkis : BB 102.3.0 switched to `StartupWMClass=betterbird`.
https://aur.archlinux.org/cgit/aur.git/tree/betterbird.desktop?h=betterbird-bin#n65

BB was compiled with this:
https://github.com/Betterbird/thunderbird-patches/blob/1a576ab764561b8201d8faf55efffaed9addb2bf/102/mozconfig-Linux#L19

Please check that it's all working now.
