### ISSUE TITLE
Consolidate StartupWMClass in .desktop file

### ISSUE THREAD

**Issue by Betterbird** [Betterbird/thunderbird-patches#75]
In the .desktop file supplied in this repo, we use:
https://github.com/Betterbird/thunderbird-patches/blob/5ada3a28bb543d662571e5d8db304b2fe32a9dd4/metadata/eu.betterbird.Betterbird.desktop#L10

To fix issue #74, the Arch .desktop file switched to this:
https://aur.archlinux.org/cgit/aur.git/commit/?h=betterbird-bin&id=525805788677e21fe90c23b3d90c368f2b6db808
but then, apparently since it didn't work, back to this:
https://aur.archlinux.org/cgit/aur.git/commit/?h=betterbird-bin&id=ef7bf56b7c4bef48daa9a7819b418f114a7cf16b
with `StartupWMClass=thunderbird-default` which was confirmed working here:
https://github.com/Betterbird/thunderbird-patches/issues/74#issuecomment-1242878685

Questions:
@mfschumann: In the flatpak you use `StartupWMClass=betterbird-default`. Does that work?
@Posi81: Wouldn't it be nicer not to reference `thunderbird` in the file?

In general, the Mozilla build system uses a variable `moz_app_remotingname` which is set to `moz_app_name` and the latter needs to remain `thunderbird` since the app name is checked in the code to distinguish between Firefox and Thunderbird, and Betterbird always needs to take the Thunderbird code path.

So shall we try setting `moz_app_remotingname` to betterbird and see what happens. References here:
https://searchfox.org/comm-central/search?q=moz_app_remotingname&path=&case=false&regexp=false

**Comment by mfschumann** [comment]
I am using the .desktop file setting `StartupWMClass=betterbird-default`, but I see the correct icons nevertheless. The `wmclass` of the running Betterbird (as reported by `lg` -> `Windows`) is `thunderbird-default`, though. So I don't really understand **why** it works for the flatpak.

**Comment by Betterbird** [comment]
Thanks for the reply. Maybe this caused https://github.com/flathub/eu.betterbird.Betterbird/issues/7?

We'll see whether we can get wmclass to show as betterbird-default in the next release.

**Comment by Posi81** [comment]
> I am using the .desktop file setting `StartupWMClass=betterbird-default`, but I see the correct icons nevertheless. The `wmclass` of the running Betterbird (as reported by `lg` -> `Windows`) is `thunderbird-default`, though. So I don't really understand **why** it works for the flatpak.

Of course it would be nicer to not reference to thunderbird in the file

**Comment by Posi81** [comment]
> Thanks for the reply. EDIT: ~Maybe this caused [flathub/eu.betterbird.Betterbird#7](https://github.com/flathub/eu.betterbird.Betterbird/issues/7)?~
> 
> EDIT: The issue was only visible on Gnome, see issue #74.
> 
> We'll see whether we can get wmclass to show as betterbird-default in the next release.

Yes it is only an issue for gnome. KDE working with the StartupWMClass=betterbird-default
So for now it will be an interim solution

**Comment by mfschumann** [comment]
Interestingly I am using gnome 42.3 on my Fedora box and it does work with `StartupWMClass=betterbird-default`, so if it works or not may depend on the version or some configuration of gnome.

**Comment by Betterbird** [comment]
Well, I'm fixing the windows class now, it's certainly taken from the config and then set here:
https://searchfox.org/comm-central/search?q=remotingname&path=.cpp&case=false&regexp=false

**Comment by mfschumann** [comment]
Even better, that should be the cleanest solution anyway.

**Comment by Betterbird** [comment]
Just for the record, I got the wmclass via `xprop WM_CLASS`. Not sure what you meant by (as reported by `lg` -> `Windows`).

**Comment by Posi81** [comment]
`xprop WM_CLASS` is in KDE / Terminal
Under GNOME you can use `ALT `+`F2` then to click on lg and after click on windows

**Comment by Betterbird** [comment]
Fixed.

Note that the wmclass is now "betterbird", not "betterbird-default". The "-default" came from this code:
https://searchfox.org/comm-central/rev/236a617d06384b08167296afffeed1ec0cda15c4/mozilla/toolkit/moz.configure#2726
where "default" is the update channel. The suffix is not necessary.

Mozilla-built Firefox as wmclass "firefox" whereas Mint/Ubuntu/whoever-built-it Firefox has wmclass "Firefox", go figure!

@Posi81 please note that the AUR .desktop file needs to be adjusted accordingly with the next release BB 102.3.0.

The Flatpak build should be OK since they are using the upstream version of the .desktop file.
