### ISSUE TITLE
cannot run Betterbird 102.2.2 with existing and same version of Thunderbird profile.

### ISSUE THREAD

**Issue by edmundlaugasson** [Betterbird/thunderbird-patches#76]
When trying to use betterbird with existing thunderbird:
![betterbird-102-2-2-does-not-run](https://user-images.githubusercontent.com/6355082/189794435-3091cc99-759f-4670-88ae-40f19a0914d3.png)

OS: EndeavourOS with KDE
Betterbird: 102.2.2

**Comment by Betterbird** [comment]
You have an incompatible Thunderbird language pack installed, please follow the instruction on the support page to remove it:
https://www.betterbird.eu/support/

From BB 102.3.0 Thunderbird language packs will be ignored and can't be installed any more to avoid problems like this.

**Comment by edmundlaugasson** [comment]
Sorry, I need my native language pack. Seems like Betterbird isn't better after all...

**Comment by Betterbird** [comment]
What you're asking for is impossible, BB can't use TB language packs since they don't contain the additional strings that BB has due to the additional functionality. You can see here that we do special processing to add the BB strings:
https://github.com/Betterbird/thunderbird-patches/tree/main/102/scripts

According to https://pontoon.mozilla.org/projects/thunderbird/, Estonian isn't even complete in Thunderbird
![image](https://user-images.githubusercontent.com/86832723/190890913-5fb4bde7-f0b5-4bc7-a0e8-1555288c96a9.png)
so we're not able to make a BB language pack for it.

**Comment by edmundlaugasson** [comment]
> What you're asking for is impossible, BB can't use TB language packs since they don't contain the additional strings that BB has due to the additional functionality. You can see here that we do special processing to add the BB strings: https://github.com/Betterbird/thunderbird-patches/tree/main/102/scripts
> 
> According to https://pontoon.mozilla.org/projects/thunderbird/, Estonian isn't even complete in Thunderbird ![image](https://user-images.githubusercontent.com/86832723/190890913-5fb4bde7-f0b5-4bc7-a0e8-1555288c96a9.png) so we're not able to make a BB language pack for it.

As you can see, Estonian language translation is near complete. Only few strings are not translated. Sorry, but using every day and haven't yet found dialog in English - all everyday usage is in Estonian. That is one main reason, why those some strings are not translated as these are not visible in most cases.
I would say, that if you claim, that Betterbird is really better, but ignoring some functionality, I mean language packs, then (with all respect) BB is not always better. I have many people, who depend on native language (mother tongue) and are not ready to use in foreign (English) language. So I can't use BB in those cases and there are lot of those. I can use in English my own but as a IT sysadmin I have to install many computers for regular users. You can use those strings from Thunderbird language pack, that exist in BB and show only them. Just make BB not to crash if it finds strings, that do not exist in BB. You can call this "Wolves eaten, sheep healthy" solution.
Don't get me wrong; I really appreciate your work. Just noted the language issue. Haven't an opportunity yet to investigate GPG-files management, that is problematic in Thunderbird, especially GPG-keys with multiple ID's.

**Comment by Betterbird** [comment]
PGP is the same in TB and BB. The improvements in BB are listed in the feature table on the home page and in the release notes.

We're a very small team, so we need to focus on the largest user groups and can't support all locales. If you have 100 users and would be willing to provide a translation of the Betterbird strings, we could discuss this further.

**Comment by edmundlaugasson** [comment]
Sounds appealing but I'm not the translator of Thunderbird. Still I believe I know that person as Estonia is a small country and IT people know each other quite often. Currently we can survive with Thunderbird, although I'm looking alternatives. The name Betterbird sounded challenging, therefore I decided to look into. Currently haven't much time to play to set up virtual machine with clean OS and test BB in live. Still I hope to find that time at some point. Anyway, thanks for quick responses and keep going!

**Comment by Betterbird** [comment]
We were referring to translating only the BB strings: https://github.com/Betterbird/thunderbird-patches/tree/main/102/scripts

**Comment by Betterbird** [comment]
We've reconsidered the issue and moved all of our BB localisation to Mozilla's new localisation system called Fluent. Missing strings will now just fall back to the base version, that is, the language the application. Missing strings will no longer prevent starting BB on a TB profile. We'll ship this in BB 102.3.1 next week.

**Comment by Betterbird** [comment]
The result is quite, well, horrible:
![image](https://user-images.githubusercontent.com/86832723/192639734-7b6d0b19-e61f-41e0-9064-48f2ece5b743.png)
The branding comes from the Thunderbird language pack and shows the "Thunderbird" string all over. What do you think?
