### ISSUE TITLE
Startup Folder menu item breaks BB when a TB language pack is installed

### ISSUE THREAD

**Issue by dillenger** [Betterbird/thunderbird-patches#78]
In this case I had the en-us language pack installed, obviously there is no Startup Folder menu item in Thunderbird language packs but they can be installed.

![Screenshot_20220917_190706](https://user-images.githubusercontent.com/571067/190869074-a0e4bb19-ea95-487d-a732-72fd92eab51a.png)

**Comment by Betterbird** [comment]
Use preview of 102.3.0, it's all fixed there.

**Comment by Betterbird** [comment]
See https://github.com/Betterbird/thunderbird-patches/issues/76#issuecomment-1260015883.
