### ISSUE TITLE
Listing of languages supported and Hungarian language support

### ISSUE THREAD

**Issue by ovari** [Betterbird/thunderbird-patches#8]
>### In which languages will Betterbird ship?
>
>Betterbird will ship in English, major European languages and Japanese. Thunderbird language packs do not work since Betterbird has additional strings. Drop us a line if your language isn't supported yet. 

https://betterbird.eu/faq/index.html

Can you please advise which languages it ships with? If not on the webpage above, on this repository's [README](https://github.com/Betterbird/thunderbird-patches#readme)?

It would be appreciated if Hungarian is supported as it currently is not.

Thank you

P.S. Thank you for fixing `Mail/message listing/thread pane needs more organization in 3 vertical pane view (column wrapping, etc)` and providing a heads-up at https://bugzilla.mozilla.org/show_bug.cgi?id=213945#c214.

**Comment by Betterbird** [comment]
Currently we're shipping in German and English (US). There is trouble with some languages, see https://github.com/Betterbird/thunderbird-patches/pull/6#issuecomment-915145981. BB uses Mozilla supplied language packs for localisation and many of these are currently broken. To support other languages, we need translations of extra strings, see examples here:
https://github.com/Betterbird/thunderbird-patches/tree/main/scripts

**Comment by ovari** [comment]
Can the `en.cmd` file be added to https://github.com/Betterbird/thunderbird-patches/tree/main/scripts so it can be copied translated? Thank you

**Comment by Betterbird** [comment]
You can start with de.cmd as a template.

**Comment by ovari** [comment]
Will this adding `hu.cmd` add Hungarian to the drop-down as shown in the image below?

![image](https://user-images.githubusercontent.com/17465872/133747682-27963984-a063-4003-86c5-ecace298578e.png)

Thank you

**Comment by Betterbird** [comment]
Sadly not. This is to install Thunderbird language packs which won't work for Betterbird since Betterbird has additional strings.

**Comment by ovari** [comment]
> Sadly not. This is to install Thunderbird language packs which won't work for Betterbird since Betterbird has additional strings.

Strange that it shows many languages, yet sadly not Hungarian.
