### ISSUE TITLE
Conversation-like thread view in inbox

### ISSUE THREAD

**Issue by mfschumann** [Betterbird/thunderbird-patches#81]
I'd like to suggest a feature that would help users keep track of their conversations directly from their inbox - one of the main features that made GMail popular, but is still missing in most open source mail clients including TB. 

There is the "[Thunderbird conversations](https://github.com/thunderbird-conversations/thunderbird-conversations)" extensions, but it has its issues and breaks on TB upgrades from time to time.

A native solution could be to extend the thread view in the inbox to a view similar to what you get when you "Open message in Conversation" by right-clicking on a message. The key difference to the status quo would be that the view includes messages from all folders (including sent mail) instead of only the inbox. Ideally the user would be able to toggle the feature (e.g. "View->Threads->Include messages from all folders").

If you consider this feature not worth the effort, there is 11 year old [TB Bug 668491](https://bugzilla.mozilla.org/show_bug.cgi?id=668491) that proposes a related enhancement (allow opening the conversation view from a collapsed thread) but should be easier to implement.

Is there any chance you could find the motivation to look into one of the two enhancements? 
Thanks btw for all the work you have put into making Thunderbird better!

**Comment by Betterbird** [comment]
Right, another feature requested for decades, issue #79 also came in today.

**Comment by Betterbird** [comment]
Is this sufficient? It fixes [TB Bug 668491](https://bugzilla.mozilla.org/show_bug.cgi?id=668491), at least as I understand the patch provided there, to enable the context menu when a collapsed thread is selected. Do you need a build? I have one for Windows and could easily do one for Linux by just applying the additional patch and not rebuilding everything from scratch. Think of your/the children, the rainforest, server power consumption, etc.

**Comment by mfschumann** [comment]
Indeed you patch fixes that 11 year old bug, and that's fantastic, thank you!

Have you had the chance to think about the other enhancement I suggested (making it possible to view conversations instead of threads in the inbox folder)? That would make the Betterbird experience perfect (at least for me personally).

**Comment by Betterbird** [comment]
Yes, I thought about it 😉. There is this add-on that does it, maybe not in the best way. I don't like to compete with add-ons.

I'd have to look into how they create the view drawing messages from various folders into a conversation view. I find the add-on way too intrusive, so I've never used it. Not a quick fix like the other one.

**Comment by Betterbird** [comment]
The TB team is working on this: https://bugzilla.mozilla.org/show_bug.cgi?id=1572000. It's unlikely that we'll address it independently.
