### ISSUE TITLE
Homebrew and Apple Silicone (M1)

### ISSUE THREAD

**Issue by rafo** [Betterbird/thunderbird-patches#88]
Nice Project! 

I finished a [Homebrew Cask](https://brew.sh/) for Betterbird but didn't push it to the Homebrew repo since there is no Apple Silicone version of BB. Are there any plans or options for a M1 build?

**Comment by Betterbird** [comment]
Not really, unless someone funds it. We're doing the Intel build on a loaned Mac book which can disappear any minute. That was initially termed "experimental", and it's not notarised either. Apparently you can get Mac M1 in the cloud. https://aws.amazon.com/ec2/instance-types/mac/.

**Comment by rafo** [comment]
Thanx for the quick reply. It would be a shame if this project for the Apple and Homebrew community failed because of this. Maybe I could help or compile it myself?

**Comment by Betterbird** [comment]
What help did you have in mind? At a guess, we should compile the binaries we distribute yourselves. You have an M1/2 machine? Did you compile there successfully?

**Comment by rafo** [comment]
I could compile it myself on a M1, but didn't try it right now. I skimmed through your build.sh and https://firefox-source-docs.mozilla.org/setup/macos_build.html, and it didn't seem too complicated, but maybe that's just naïve.

**Comment by seanbperiod** [comment]
With no updates for 7+ months - just wondering if anyone has been able to successfully build a version with native Apple Silicon support? (if so, could you post a link? 😅)

**Comment by rafo** [comment]
> Last we checked, only 2% of users were on Mac, unclear how many of those were on M1/M2.

This is sometimes a chicken-and-egg problem. 🐔 But I understand your point of view.

**Comment by Betterbird** [comment]
We will use GitHub actions soon (https://github.com/Betterbird/thunderbird-patches/pull/173). According to
https://github.com/Betterbird/thunderbird-patches/pull/173#issuecomment-1634845016
this will be supported from Q3 2023.

**Comment by Arecsu** [comment]
Seems like Github Actions can be used with m1 runners now

https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by Betterbird** [comment]
Thanks for letting us know. Sadly, building on Mac only works for the "full build from repo", not the "reduced build from source tarball" **which we prefer**, see Issue #175.

Upstream report here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1847288#c1

They did answer here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1847288#c2
_Thanks for the info. Maby you can try disabling sccache on mac?_

@sagudev could you look into it again?

**Comment by wrapper** [comment]
Just here to throw my hat in, would love to see apple silicon builds

**Comment by Betterbird** [comment]
Sure, see the comment before yours.

**Comment by shaul-pollak** [comment]
So I tried compiling on an M2 mac. In mozconfig-Mac I changed/added:
ac_add_options --target=aarch64-apple-darwin #changed
ac_add_options --host=aarch64-apple-darwin #added, not sure this is needed

Building fails with:
0:06.81 DEBUG: Executing: `/Users/<>/.mozbuild/sccache/sccache /usr/bin/clang -isysroot /Users/<>/.mozbuild/MacOSX13.3.sdk -mmacosx-version-min=11.0 -std=gnu99 --target=arm64-apple-darwin -Wl,--version`
 0:06.81 ERROR: Failed to find an adequate linker
 
 Any idea what can be done? ld does not support --version on mac

**Comment by sagudev** [comment]
We got same thing in mozjs, one solution is to set default linker to lld-classic or to clang's lld or apply this patch: https://github.com/servo/mozjs/blob/main/mozjs-sys/etc/patches/0029-fix-ld64-detection.patch

**Comment by shaul-pollak** [comment]
changed to clangd's lld. works. Thanks @sagudev

**Comment by Betterbird** [comment]
> We got same thing in mozjs, one solution is to set default linker to lld-classic or to clang's lld or apply this patch:

Has that been reported upstream at Mozilla. They build FF/TB for M1/M2, so why don't they have the issue? Or are they doing only cross-compiles for Mac on Linux?

**Comment by sagudev** [comment]
Mozilla is using their own toolchains (clang) using `mach`. I planned to upstream https://github.com/servo/mozjs/blob/main/mozjs-sys/etc/patches/0029-fix-ld64-detection.patch but I forgot. I will open bug and fix later today.

**Comment by sagudev** [comment]
Found relevant bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1871153

**Comment by Betterbird** [comment]
Thanks. Maybe we should just add the patch to the project, I guess it won't break the other builds :wink:

**Comment by Betterbird** [comment]
We did a cross-compile enabling the respective lines after this commit: https://github.com/Betterbird/thunderbird-patches/commit/be2ea886eeb8c982c59db1f271141eef5968535a

One user on [Reddit](https://www.reddit.com/r/Betterbird/comments/1dggrqs/comment/l8rmwf1/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) claims that it works, two other users report:

![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/317060a4-256b-41df-b261-0ae08a266fb0)
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/87d4ebbd-d45a-462b-a114-886819195f6c)

**Comment by Betterbird** [comment]
It can be made to work:

To "fix" the gatekeeper: `spctl --add /Applications/Betterbird.app`. Source: https://osxdaily.com/2015/07/15/add-remove-gatekeeper-app-command-line-mac-os-x/

To fix the "Betterbird is damaged": `xattr -cr /Applications/Betterbird.app`. Source: https://www.youtube.com/watch?app=desktop&v=6fqzb4qpgcs

**Comment by dstppy** [comment]
> It can be made to work:
> 
> To "fix" the gatekeeper: `spctl --add /Applications/Betterbird.app`. Source: https://osxdaily.com/2015/07/15/add-remove-gatekeeper-app-command-line-mac-os-x/
> 
> To fix the "Betterbird is damaged": `xattr -cr /Applications/Betterbird.app`. Source: https://www.youtube.com/watch?app=desktop&v=6fqzb4qpgcs

I was looking at this today; the only set flags are quarantine - are there any plans to sign BetterBird?

This was the relevant link on the topic:
https://developer.apple.com/forums/thread/128166

The attribute that is getting cleared looks like this:
`/Applications/Betterbird.app/Contents/PkgInfo: com.apple.quarantine: 0183;67d33d64;Safari;1C2C3039-E236-4A47-B6D1-6FCE0DC3E82F`

Just curious.

**Comment by Betterbird** [comment]
They are no plans to notarise BB, since it would require an expensive Apple dev subscription and additional effort.

**Comment by dstppy** [comment]
> They are no plans to notarise BB, since it would require an expensive Apple dev subscription and additional effort.

I see what's different. Sequoia changed the rules for gatekeeper. Previous versions had availability of an option to see and bypass quarantine in settings by an administrator. 

With that change we will either need to clean the flags manually as you noted or build direct from home brew. 

It's a Mac behavior that it's making it sound like it is failing a sum check and not just an "unregistered" developer. 

Thanks for responding. I understand fully now.

**Comment by dstppy** [comment]
I had to revisit this for other brew installed apps; the cleanest form of removing only the quarentine flag I distilled down to:
`find /Applications/Betterbird.app -exec xattr -d com.apple.quarantine {} +`

**Comment by Betterbird** [comment]
That is what our download page says now:
 `xattr -r -d com.apple.quarantine /Applications/Betterbird.app`

**Comment by dstppy** [comment]
Apologies; I should have rechecked before posting.
