### ISSUE TITLE
userChrome.css has no impact

### ISSUE THREAD

**Issue by vcg3rd** [Betterbird/thunderbird-patches#91]
BetterBird 102.3.2-bb19 (64-bit) on Linux 5.18.0-14parrot1-amd64

I imported from my TB default profile then copied over its userChrome.css to BB /chrome, checked toolkit.legacyUserProfileCustomizations.stylesheets (which was already toggled 'true') and restarted.  Nothing changed.  I made some major tweaks, like changing my general font size to 150%
```
/* general font size */
	treechildren{font-size:150%}
```
and restarted again.  Again, no change to the fonts.

Everything else (even my tags) imported like a charm!  What am I missing? Same userChrome that works with TB.  In the right folder. Right setting toggled.

TIA!

**Comment by Betterbird** [comment]
Thanks for getting in touch. This seems like a support request and nothing that warrants opening a bug report.

I doubt that your CSS works. If you want to experiment, try to use https://www.betterbird.eu/expert-tips/userChrome.css. There is some "crazy" stuff at the end in a comment which you could enable.

**Comment by Betterbird** [comment]
Look, we're happy to give support, preferably via e-mail and not here. 

userChrome.css works, me and many other users use it, for example to customise the multiline view. For example, users like to colour their headers, like here:
![image](https://user-images.githubusercontent.com/86832723/195426404-af3c2297-9cc0-4951-b518-2c2d23edf2e6.png)

That can be done with this CSS:
```
.message-header-label {
  color: red ! important;
  font-weight: bold ! important;
}
```

If you're saying that userChrome.css doesn't work for you, then you have misconfigured something.

I've placed `treechildren{font-size:150%}` into my userChrome.css and the effect is very visible after a restart:

![image](https://user-images.githubusercontent.com/86832723/195427145-a4d0a5d3-a4d1-4678-8b22-0831085ae6c5.png)

**Comment by vcg3rd** [comment]
Please don't think I was being snarky or petulant.  I have been a Linux user for over 20 years, but I couldn't code a simple Bash script.  I have nothing but respect for you guys!  Respect enough that if this Github page is for filing bugs I don't want to waste your time, and am sorry I did, seriously.

I am saying userChrome doesn't work for me, but it's in the right folder, the right setting is toggled, and it works in TB, so it's beyond my competence to figure out how it's misconfigured.  I had thought maybe it was a path issue because I had the unpacked BB folder in my downloads.  So I moved it to /user/home/me/.local/bin which is in my path. 

BB then acted like it had never been run on this box, and so I re-imported everything again, and userChrome.css still didn't work.  However, I had 2 new profiles in my /user/home/me/.thunderbird folder, so perhaps I am supposed to put userChrome.css in one of those.  Right now it's in /user/home/me/.local/bin/betterbird/chrome.

Anyway, thanks!  I really don't want to waste anymore of your time.

**Comment by Betterbird** [comment]
Well, it doesn't say anywhere directly that BB uses the TB profiles, that's sort of implicit in this section:

---

https://www.betterbird.eu/support/
How to switch between Thunderbird and Betterbird?
Betterbird is designed to be 100% compatible with Thunderbird of the same version. For example at time of writing you can switch between Betterbird 102.2.0-bb14 and Thunderbird 102.2.0 without problem. If Betterbird doesn't already detect your Thunderbird profile, start Betterbird with the -p option which will launch the profile manager. You can select your regular profile there. Another option is to view all profiles via Help > More Troubleshooting Information. Click on the about:profiles link which will take you to a tab where you can select a different default profile.

---

You can inspect the profiles in TB/BB: Help > Troubleshooting Information, about:profiles.

Sorry about the lost time here, but bin/betterbird/chrome was not the correct location for userChrome.css, like for TB, it goes into the profile

**Comment by Betterbird** [comment]
We've updated our "expert tips" and support pages to make things a little clearer and to avoid frustration in the future.
