### ISSUE TITLE
[Low priority] How to change (system tray) icon?

### ISSUE THREAD

**Issue by indig0F10w** [Betterbird/thunderbird-patches#92]
Greetings, Betterbird is simply better and the only issue I have with it is the red icon. It just pokes my subjective eyes with the redness and non-antialiased design. Changing the icon does not change the tray or system tray icon. Is there a way to change it? I know you had many requests to change the icon for better differentiation with Thunderbird. One solution could be dark icon for dark themed Windows/Linux.

Thank you.

**Comment by Betterbird** [comment]
See issue #83. You can customise shortcut icons on Windows, but that doesn't change the taskbar or systray. Apparently on Linux you can even achieve this. On Windows you'd need to manipulate the resources in the executable, see http://www.angusj.com/resourcehacker/.

If we change the icon to something else, people who got used to red will then complain. It's difficult to ship the product with an alternate set of icons.
