### ISSUE TITLE
[feature suggestion]  Poor man's auto-update

### ISSUE THREAD

**Issue by noyannus** [Betterbird/thunderbird-patches#94]
A feature that in intervals queries the download page for versions newer than the currently running, and alerts the user if found. That would help us to keep BB up to date.

Alternatively, or additional: offer an Email or RSS service with update notification and download links.

**Comment by Betterbird** [comment]
That already happens. BB checks at every start (see error console):
Betterbird skipping update check, last done 18/10/2022, 21:06:50
Every week it actually queries the server and pops open the "About box" if there is a new version. Users can check themselves via the "About box".

**Comment by noyannus** [comment]
Thanks. Good to know. And I'm impressed with the speedy response.

**Comment by Loping-Dinosaur** [comment]
Hi, as a follow up question: is there a way to autoupdate Betterbird? 
Windows 10 user here.

**Comment by Betterbird** [comment]
Not from within the application. But you can write a script that checks for new versions on the website.
`wget "https://www.betterbird.eu/downloads/getloc.php?os=win&lang=en-US&version=release" -O download.txt` gives you the download location of the latest version.

**Comment by tuxedotje** [comment]
> That already happens. BB checks at every start (see error console): Betterbird skipping update check, last done 18/10/2022, 21:06:50 Every week it actually queries the server and pops open the "About box" if there is a new version. Users can check themselves via the "About box".

When did this notification stop? I never get any notification, just have to try to update once in a while.  No pop up "about box" here.

**Comment by Betterbird** [comment]
I hasn't stopped. What does your error console say when you start?

**Comment by tuxedotje** [comment]
Thanks, found it. Nog on error concole. Just on the mail messages window.

Vriendelijke groeten Jaap Bosman

Sent from [Proton Mail](https://proton.me/mail/home) for Android.

-------- Original Message --------
