### ISSUE TITLE
Text-mode doesnt resize the mail window with line-breaks

### ISSUE THREAD

**Issue by firefoxlover** [Betterbird/thunderbird-patches#95]
Using the HTML or simplified HTML-mode, mails get adapted to the window size, so you dont have to scroll horizontally.

In text-only mode there are no line-breaks inserted so you have to scroll horizontally

using 102.4.1-bb22 (64-Bit) Flatpak

**Comment by Betterbird** [comment]
This is not a bug report but a support request at best.

We don't understand your request. If you start with a plaintext message, like a news message, you get this:
![image](https://user-images.githubusercontent.com/86832723/199209431-b813a8c0-05f2-4cce-b932-b7880206ba74.png)
This comes from using the vertical view layout with a narrow column on the right for message preview.

Maybe you mean that your start with a HTML message, like so:
![image](https://user-images.githubusercontent.com/86832723/199209724-f1158ab1-94f3-4577-ac9f-78234824f69c.png)
and then display it as plaintext only:
![image](https://user-images.githubusercontent.com/86832723/199209922-4a6cb1fa-3589-4fbf-845f-0f10d3f0ca74.png)

This looks pretty good to us.

If you have further problems, please send the message you think doesn't display correctly **as attachment** to our support. The only case we know of where horizontal scrolling is required is when rendering a `<html><pre>`.

You also use this CSS in your userContent.css in the chrome directory to limit the width of the display for a wide window
```
.moz-text-plain, .moz-text-flowed, .moz-text-html {
  max-width: 82ch !important;
}
```
