### ISSUE TITLE
Feature request: show unread mail count in system tray

### ISSUE THREAD

**Issue by Katarn** [Betterbird/thunderbird-patches#97]
As it was in FireTray. Below is a screenshot.

![изображение](https://user-images.githubusercontent.com/6339978/201617845-3d23a232-0049-4d91-947d-5d0c34722d39.png)

If there are no unread messages, then the standard application icon is displayed. I think quite a few people are used to this yellow box with text in the middle. Well, or make a setting so that you can change the appearance.

**Comment by Betterbird** [comment]
This is already tracked in issue #20.

**Comment by Katarn** [comment]
That issue is a request for a systray for Linux, and this issue is about displaying the number of unread emails directly in the icon. It doesn't matter where, even in Windows.

**Comment by Betterbird** [comment]
We're really disappointed that https://github.com/Betterbird/thunderbird-patches/issues/20#issuecomment-1141040721 hasn't moved at all. We'll contact the maintainer @sunweaver directly. A systray display like in Windows would be ideal.

**Comment by Katarn** [comment]
I and in Windows in the icon do not have any information about the number of unread letters. Even in Tooltip.
![изображение](https://user-images.githubusercontent.com/6339978/201632460-a326d495-f7b2-48e9-98ac-d8d84c3f3a7a.png)

**Comment by Betterbird** [comment]
Yes, it does, new mails, just now:
![image](https://user-images.githubusercontent.com/86832723/201641985-514e74e6-9eff-4d4a-9bec-bc7576f2af9e.png)
and here: https://www.betterbird.eu/media/img/windows-badge.png

**Comment by Katarn** [comment]
Actually, my request is to display the number of unread emails directly on the icon - the way thousands of FireTray users are used to it.

**Comment by Katarn** [comment]
It's clear. I just did not understand why the issue is closed with a link to this issue.
