### ISSUE TITLE
How does BB determine the location of the TB profile

### ISSUE THREAD

**Issue by dwatney** [Betterbird/thunderbird-patches#98]
I'm guessing this isn't a bug, but some configuration weirdness on my system (Linux Mint 21). The folder that BetterBird thinks is my Thunderbird profile folder doesn't exist. How does it figure this out? Knowing that, I suspect I can find and fix whatever is misleading it and be able to properly reference my TB profile.

To be specific, if I go to about:profiles in TB, the root directory of "Profile: default" is correctly identified as:
/home/marshall/.thunderbird/a2oacfs5.default

If I go to about:profiles in BB, the root directory of "Profile: default" is correctly identified as:
/home/marshall/.thunderbird/hba3elaa.default
which does not exist.

installs.ini and profiles.ini only refer to a2oacfs5.default

**Comment by Betterbird** [comment]
Please don't file support requests as issues.

We don't know what happened on your system. Profiles on Linux are stored in `~/.profiles`, you seem to have two of them `a2oacfs5.default` and `hba3elaa.default`. No idea how BB identifies the latter as the default profile it's not referenced in `profiles.ini`. We suggest to start `thunderbird -p` and `betterbird -p` and select the profile you want to start with.
